### ISSUE TITLE
Ability to convert between bibtex and biblatex formats

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#10028]
**Is your suggestion for improvement related to a problem? Please describe.**
Both formats come with some specific ways how to format things.

**Describe the solution you'd like**
Some automation conversion; like from `year` to `date` field.

Maybe, this already exists, but I didn't find it (https://discourse.jabref.org/t/convert-back-from-biblatex-to-bib/955/8 mentions something from biblatex to bibtex).

**Comment by ThiloteE** [comment]
hey claell, this can be done via the cleanup feature: https://docs.jabref.org/finding-sorting-and-cleaning-entries/cleanupentries
You can convert fields from bibtex to biblatex and also from biblatex to bibtex.

Since biblatex supports more fields than bibtex, you might encounter the situation that for some fields the conversion back to bibtex may try to put field content from two biblatex fields into a single bibtex field, which might lead to dataloss. For this reason, I would suggest to create a backup of your library before you do such conversions.

**Comment by ThiloteE** [comment]
Closing this issue, as this feature exists in JabRef already.

**Comment by claell** [comment]
Many thanks! I already thought that I just didn't find that option. I did a short web search, but it didn't show me what I looked for. Now, this issue might possibly at least help other people 🙂
