### ISSUE TITLE
Normalize names of persons breaks insitutional authors

### ISSUE THREAD

**Issue by no-preserve-root** [JabRef/jabref#10031]
### JabRef version

5.9 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new Bibliography
2. Library Properties → Save actions → Enable field formatters
3. Add Author → Normalize name of persons
4. Add entry
5. In BibTeX source, add `author = {{Company Name, LLC}},`. This is an institutional author and must be brace-protected to avoid interpretation as a name by most styles.
6. Save Library. Author is now `author = {Company Name, LLC},`. Expected behavior would be to leave the author alone; instead, the author is now parsed as a name and would be rendered as such.

**Comment by xujinming01** [comment]
JabRef 5.10--2023-09-01--779e555
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20+19

I have a similar issue, if the initial author is `author = {{Society of Automotive Engineers}}`, the first save, the author is `author = {Society of Automotive Engineers}`, the second save, the author will be `author = {of Automotive Engineers, Society}`

**Comment by praveen891** [comment]
Hi @no-preserve-root,
I have added article, in BibTeX source I have given article details as mentioned in screenshot (1). In that I have given author as author = {{Company Name, LLC}},. and it is storing author fine as Company Name, LLC.

![Screenshot (157)](https://github.com/JabRef/jabref/assets/61739983/66316dae-a8f0-44fb-b70a-5b70b4584d5b)

And now i have changed the library properties as mentioned in steps to reproduce.
then it is storing author as only company name as there in screenshot (2).

![Screenshot (158)](https://github.com/JabRef/jabref/assets/61739983/caa5592c-72b8-4e83-be15-c5f7bcde4a0c)

Could you please explain in brief about the expected behaviour. 
As per my understanding that it should take entire company name, LLC as author. Like it should behave same as it is behaving before changing the library properties as you can see in screenshot (1).

**Comment by koppor** [comment]
This is a brain teaser!

Intermediate result:

- We want to be able to parse `von Berlichingen zu Hornberg, Johann Gottfried` (`Society of Automotive Engineers` contradicts here; `of` is interpreted as `von` part)
- We want to be able to parse `{Vall{\'e}e Poussin}` (`{Company Name, LLC}` contradicts here)

**Comment by koppor** [comment]
@no-preserve-root Could you try https://builds.jabref.org/pull/11034/merge? (And share https://github.com/JabRef/jabref/wiki/GSOC-2024-ideas-list among students? 😅 - We also have https://devdocs.jabref.org/teaching.html)

**Comment by no-preserve-root** [comment]
> @no-preserve-root Could you try https://builds.jabref.org/pull/11034/merge? (And share https://github.com/JabRef/jabref/wiki/GSOC-2024-ideas-list among students? 😅 - We also have https://devdocs.jabref.org/teaching.html)

I cannot reproduce the bug with today's build, thanks for fixing!
