### ISSUE TITLE
Build error on Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [JabRef/jabref#10067]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Latest Arch Linux, bspwm windowmanager, 

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I use this build function
```
build() {
  cd ${pkgname%-git}
  [[ -d "$srcdir"/gradle ]] && install -d "$srcdir"/gradle
  export GRADLE_USER_HOME="$srcdir"/gradle
  #export DEFAULT_JVM_OPTS="-Xmx3g -Xms1g"
  
  ./gradlew --no-daemon -PprojVersion="${pkgver}" \
	    -PprojVersionInfo="${pkgver}--ArchLinux--${pkgrel}" assemble
  ./gradlew --no-daemon --no-parallel -PprojVersion="${pkgver}" \
	    -PprojVersionInfo="${pkgver}--ArchLinux--${pkgrel}" jlink 
}
```
Underlying java-environment is zulu-21

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by stefanhusmann** [comment]
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.2/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /home/haawda/paketierung/meine_Pakete/jabref-git/src/gradle/caches/jars-9/0556e97ac1fbef7591031fd1464fd59e/buildSrc.jar.
> org.gradle.api.GradleException: Failed to create Jar file /home/haawda/paketierung/meine_Pakete/jabref-git/src/gradle/caches/jars-9/0556e97ac1fbef7591031fd1464fd59e/buildSrc.jar.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 10s
3 actionable tasks: 3 up-to-date

**Comment by Siedlerchr** [comment]
You need the jdk specified here
https://github.com/JabRef/jabref/blob/ffedea2d79f66eff0cabe2a18e3d747a4bed90a3/.github/workflows/deployment.yml#L51

We use a custom version of the up coming jdk 21 which includes a patch for
jlink.
Will probably  make it in the official jdk 21


Stefan Husmann ***@***.***> schrieb am Do., 6. Juli 2023,
19:50:

**Comment by stefanhusmann** [comment]
I installed the customized version of jdk, but the error keeps the same.

**Comment by Siedlerchr** [comment]
@koppor any thing you notice that is different?

**Comment by koppor** [comment]
> Underlying java-environment is zulu-21

We need to work on this one.

According to https://docs.gradle.org/current/userguide/compatibility.html#java, Gradle does not run on Java 21. Even if using JabRef's custom JDK build, gradle does not start.

I assume, you are using JDK20 and have the other JDK installed at another location and referenced JDK21 as outlined at https://github.com/JabRef/jabref/blob/b55b94005085a071fe3f0b54562c5638b458a6ac/.github/workflows/deployment.yml#L92.

What would help me to debug is to have a `Dockerfile` mirroring the setup.

Other than that, I can only guess (with some little help from the AI, I would assume you already done these checks, but I want to be sure).

The error message suggests that Gradle failed to create the `buildSrc.jar` file. This could be due to several reasons:

1. **Permission issues**: The process may not have the required permissions to write files in the directory. You can check the permissions and if needed, change them accordingly. For instance, in Unix-like systems you can use the `chmod` command to modify permissions. 

2. **File already in use**: The Jar file that the process is trying to create might already be open or in use by another process. If this is the case, you should terminate the other process or restart your system to ensure that the file isn't in use. --> **Did you check with `ps ax` (or similar command) for running processes**

3. **Disk space**: The disk may not have enough free space to create the file. You can verify this by checking the available space on your disk.

4. **Corrupted Gradle cache**: Sometimes, Gradle's cache gets corrupted and leads to such problems. In this case, you can try to delete the cache (`~/.gradle/caches/`) and re-run the build.


Note that I removed the suggestion of the JDK version, which I already outlined above.

**Comment by Siedlerchr** [comment]
We have described the build instructions for linux in our blog post :
https://blog.jabref.org/2023/09/02/JabRef5-10/#important-build-instructions-from-source-for-linux-users
