### ISSUE TITLE
feature request: add entry based on ISSN number

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10124]
Hi

Currently we can add books based on ISBN number but it would be nice if we would also add magazines based on ISSN number

https://en.wikipedia.org/wiki/ISSN

![afbeelding](https://github.com/JabRef/jabref/assets/139498085/b59f02d4-1bb9-4e5c-940c-e27e70dfc419)

**Comment by guipmenezes** [comment]
How we can have access to that type of magazine information? I saw in ISSN Portal that they have a free tier access to view and retrieve open data about this, but I don't know how we can consume this on JabRef.

**Comment by Siedlerchr** [comment]
A first step could be to extend the DOAJ fetcher https://doaj.org/ in JabRef to extend it with a lookup for ISSN 

Otherwise we could try the German library services for magazine lookup: 
 https://zeitschriftendatenbank.de/services/schnittstellen/json-api 
https://zeitschriftendatenbank.de//api/tit.jsonld?q=iss%3D1031-2153

**Comment by guipmenezes** [comment]
> A first step could be to extend the DOAJ fetcher https://doaj.org/ in JabRef to extend it with a lookup for ISSN
> 
> Otherwise we could try the German library services for magazine lookup: https://zeitschriftendatenbank.de/services/schnittstellen/json-api https://zeitschriftendatenbank.de//api/tit.jsonld?q=iss%3D1031-2153

That's nice, I'll take a look and maybe even try to implement it.

**Comment by guipmenezes** [comment]
What I've found is that we can probably extend the DOAJ fetcher (maybe with a new Class called IssnFetcher or a new method in the DOAJFetcher) because we can use ISSN as a short field name in the search query. In this extension, it has to produce a Lucene Query for GET request. And after the 200 status, it needs to do all the parsing from JSON to our used format.
https://doaj.org/api/v3/docs#!/Search/get_api_search_articles_search_query

One thing that I was thinking about is, we are still using the v1 of DOAJ API, and it's already v3, would it be a good idea to update the API version?

**Comment by Siedlerchr** [comment]
@guipmenezes  That sounds great! Feel free to update the api version. The best approach would be to implement IdBasedFetcher

**Comment by guipmenezes** [comment]
@Siedlerchr Sounds good, I'll try it. This IdBasedFetcher interface looks like a better solution, thanks for the advice.

**Comment by Siedlerchr** [comment]
Great! If you have any questions, just ask! Also try to create a (Draft PR) soon, seeing code with context helps in case of questions. 
We also have a getting started guide https://devdocs.jabref.org/contributing.html

**Comment by guipmenezes** [comment]
Hello @Siedlerchr I didn't had time to work on this feature during the week, but now I will give it a boost. I'll create a Draft PR so you can take a look at the code and help me 😁
