### ISSUE TITLE
Importing to the correct mode when searching (BibTeX vs biblatex)

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1018]
Most (all?) of the fetchers will now produce a BibTeX entry. When importing to a BibLaTeX database, this causes some issues, see e.g. #1015. It might make sense to add some mechanism to the search interface such that the correct format is returned. For example, this can be achieved by "search formatters", which will also remove some of the need of explicit cleanup code in the fetchers as well as some of the preference settings.

**Comment by stefan-kolb** [comment]
I don't think this should be classified as a bug.
The question here is, who is responsible for outputting the correct format?
- the fetcher
- Jabref itself

I think it should be the fetcher that must be aware of what to output because he is the only one that is able to produce correct entries?!
On the other hand, this would force the fetcher to know the current mode which adds another dependency or at least a parameter to the call.

If we transform entries after fetching to the correct format this could be a hard thing.
This can only work if we always fetch Biblatex and rearrange the fields and strip unsupported fields etc.

**Comment by tobiasdiez** [comment]
Fetcher should try to fetch in BibLaTex format, but can also return BibTex format. Afterwards JabRef should always run a converter which converts to the correct mode depending on user preferences (for this a BibLaTex > BibTex converter has to be written, based on the `BiblatexCleanup`).

**Comment by Siedlerchr** [comment]
This issue is now finally closed and fixed in the latest development snapshot 


We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
