### ISSUE TITLE
web search: IEEEXplore error (network error?) 

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10260]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to web search
2. Select IEEEXplore 
3. Enter any search term e.g. "dinosaur"
4. The following error occurs

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/f0ad8666-a7bd-4a84-b136-5133d97e86e5)

Doing the same search on the website works fine...

https://ieeexplore.ieee.org/search/searchresult.jsp?newsearch=true&queryText=dinosaur

Problem present in:

JabRef 5.10--2023-08-30--c303db5
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20+19

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Works for me in 5.10

**Comment by the-dino-girl** [comment]
> Works for me in 5.10

hmm, can you test the other bugs too?
Maybe it's all the same problems fixed in 5.10?
Anyway in 5.9 many many errors when searching :(

**Comment by koppor** [comment]
The thing with fetchers is a very difficult one. Some publishers do NOT give their meta data for free. IEEE also wants money for this data (even they are a charity organization). IEEE is mostly computer science stuff. 

More technical details are available at https://devdocs.jabref.org/code-howtos/fetchers.html.

In case you need data from IEEE, you can get a key via some web form (linked in the above link).

We do check our fetchers regularly. See https://github.com/JabRef/jabref/actions/workflows/tests-fetchers.yml. We try to fix the fetchers when there is something red. Sometimes, it is too much effort to do it immediatly. For instance, we try to fix issues with writing (e.g., save in table sort order) instead of working on fetchres.

Another information: Some fetchers are not checked outmatically on the CI, because the providers block at too much usage. We did not yet contact them nor made a "proxy" concept (by offering proxy.jabref.org, which routes all requests). The only thing we can currently say: Either ask each provider for an API key - or rely on the browser plugin (https://github.com/JabRef/JabRef-Browser-Extension). OK, the browser plugin currently is also not that well maintained... We try to catch up hard.

**Comment by koppor** [comment]
I saw, we have the same issue (error `403` returned) at https://github.com/JabRef/jabref/issues/6837. Thus, I close this as duplicate. (Even though I provided more explanation text in the last comment than in 6837).

**Comment by koppor** [comment]
At https://github.com/JabRef/jabref/pull/10213, there is a proposal for better error messages. Maybe, you can think of these PR too if that helps to make the error message more clear to the user. Especially now you have a little bit more background in the problematics with the data providers
