### ISSUE TITLE
missing translation text in jabref 5.10

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10284]
The indicated part has missing translation text. Can somebody add it please?

- jabref main window

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/a68faa83-9c40-4baf-9365-23dd91609fd3)

- remove group

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/e913d0b8-1342-4b2a-b3d7-008e5b938158)

- about window

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/5958516d-7bee-4f68-b3c2-b4dca7249f43)

- preferences window

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/f9df71f5-7a4e-4271-a5d5-61a31a960c9f)

- preferences -> formatter name

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/5fbb39fb-d381-4935-8a59-f02d2ce80897)

- preferences -> custom import formats

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/a9b9249e-1d1d-4b64-ae1c-493e90e69291)

- preferences -> network

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/ab7c4efd-dd09-4999-8e20-b546bba64d37)

**Comment by Siedlerchr** [comment]
Thanks for the report! I checked the code, and it seems this is coming directly from java/JavaFX.  I experience the same when I try this on my machine.  These are standard buttons from javafx. Apparently the javafx controls do not contain any Localization at all. I checked the source code and only found these.

<img width="654" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/d0f3b2ce-06fc-4bd1-88ad-620f2ca956ba">

Sorry, we can't do anything about this :( 

PS: The whole JabRef maintainers would like to thank you for your translation effort and your cool theming.
For the moment we have paused the sync with github for a while. We will continue this once in a while so that not every new string triggers the translators and they can rather to tranlsate a couple of strings together.

**Comment by the-dino-girl** [comment]
Also "No content in table" can't be translated?

**Comment by Siedlerchr** [comment]
Yep, that also comes from javafx directly.

**Comment by the-dino-girl** [comment]
I think "general" in the tabpage can be translated? The other tabpages can...

What about the fields inside the tabpage (same for other not-shown tabpages)

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/1b49a663-6865-4bd6-9440-52ed01d8404a)

**Comment by the-dino-girl** [comment]
I found a way to remove the "No content in table" by a translated text for each language:

https://stackoverflow.com/questions/24765549/remove-the-default-no-content-in-table-text-for-empty-javafx-table

**Comment by Siedlerchr** [comment]
>I found a way to remove the "No content in table" by a translated text for each language:

Ah that is good! We can try to add this.

>What about the fields inside the tabpage (same for other not-shown tabpages) 

The fields cannot be translated. They are automatically created from the bibtex source.

**Comment by the-dino-girl** [comment]
> I think "general" in the tabpage can be translated? The other tabpages can...

and the "general" tabpage name?
