### ISSUE TITLE
new entry using ISBN is always added as "misc"

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10348]
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When I added a new entry (a book) using a ISBN using jabref 5.9, it was added as a book.

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/f80a58f3-5beb-47ec-a87c-c899dfe1e3f3)

In jabref 5.10 it's added as "misc" for each book ISBN you try to add...
It's definitely different from jabref 5.9 which I used to add many books. Never "misc" was used as type when using a ISBN.

examples of ISBN:

978-0-8229-4557-4

9780674240346

978-0-8160-5962-1

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Because of our old ISBN endpoint no longer available, we switched to a new one (based on the GVK Fetcher).
However, our existing test entries were reported back correctly with type "book". so we would need to check the code again why some ISBNs are reported back as misc. 

https://github.com/JabRef/jabref/pull/10211/files#diff-2b4f7b12839b9d7f983f456905024285786b9914417486029790d7ebd95c9edfL34-L46 

Refs https://github.com/JabRef/jabref/pull/10211

**Comment by Siedlerchr** [comment]
A fix is in the pipeline
