### ISSUE TITLE
Add a quick option to switch skins in the view options under the menu bar

### ISSUE THREAD

**Issue by ehehela** [JabRef/jabref#10417]
It is recommended to add a shortcut option to switch skins in the View menu under the menu bar. This makes it easy for people to switch skins (dark/light mode).

**Comment by u7492883** [comment]
I am interested in working on this issue. Is it free to take?

**Comment by u7452206** [comment]
hi，does anyone work on this task? if not, can I take it ?

**Comment by ThiloteE** [comment]
I apologize for the late response. I will not yet assign anybody to this issue, until a maintainer that knows more aobut coding than me can clarify.

JabRef currently only allows to change the theme via preferences in the general tab:
![image](https://github.com/JabRef/jabref/assets/73715071/ecf8624d-3099-420a-ac0f-ff3ed8282dbe)

Shortcut: ![image](https://github.com/JabRef/jabref/assets/73715071/9fcf6d38-8925-449a-9e53-c4f6c1e8f4e5). 

@calixtus, I do not know, if this is a good first issue, as it seems like in the preferences it is required to select a file via three clicks, so we cannot just copy and paste the existing implementation, but need to come up with something new for the "view" menu.


@u7452206, @u7492883, For now, if you are in a hurry, please have a look at our other [good first issues](https://github.com/orgs/JabRef/projects/5) from the projects page. If you have time to wait for clarification, I think the principle of "first come, first served" could be applied here, so that would be u7492883. Usually, we only assign one student, to minimize trouble further down the road.

**Comment by calixtus** [comment]
Well, it should not be a bigger problem to add this feature, but the rela question is: Do we want this feature? What sense does this make to quickly switch between different styles? Who really would want this feature? JabRef is a citation management Software, not javafx CSS theme presentation software.

Thanks for your suggestion, but I'm not convinced of the practical advantage of this feature, imho this would add noise to the UI and the view menu.

**Comment by calixtus** [comment]
Maybe a better solution is to automatically select the theme depending of the os general theme and keep the option in the prefs to override this an select a theme manually. See #8729 Keep it simple.

**Comment by tobiasdiez** [comment]
I agree with @calixtus. Closing thus.
