### ISSUE TITLE
Not possible to disable user-specific comments

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10424]
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Go to the comments tab. There you now find fields of the form `comment-{name}`. This is might be nice if you work on the bib file with more than one person, but I would assume most people don't really need this. However, it doesn't seem to be possible to toggle it this feature off (and in my opinion it should be off by default).

Refs https://github.com/JabRef/jabref/pull/9727 and https://github.com/koppor/jabref/issues/543. @koppor 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
You are the only one concerned by this. We can keep the issue open and see if more have this suggestion.

Depends on https://github.com/JabRef/jabref/issues/8701.

Right click an disable. Then stored in library settings for future.

**Comment by tobiasdiez** [comment]
I don't think this should be stored in the bib file. I would add a toggle in the prefs (or actually respect what is written in the fields textbox). 

I think the comments tab is not used by many people in the first place. But right now I'm loosing half of my editor for nothing...

**Comment by Siedlerchr** [comment]
Have you tried modifying it with Custom editor tabs in the prefs? 
<img width="1104" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/8dfe8557-8926-4394-8b1f-3afbdf988ef1">

**Comment by tobiasdiez** [comment]
I don't know what I should specify there to hide the user comment. And looking at the code it's always shown.

**Comment by koppor** [comment]
> I don't think this should be stored in the bib file.

My reasoning: 

1. There are (at least) to types of .bib files: One shared within a research group and one used for one's own research (more on different types at https://github.com/JabRef/jabref/issues/160). Since I am very often working in research groups, I really rely on this commenting feature.
2. JabRef cannot know if the file at hand is a research-group file
3. I assume that users of JabRef work in research groups

Maybe assumption 3 is wrong.

Until we have a nice welcome screen advertisting features (refs https://github.com/JabRef/jabref-issue-melting-pot/issues/49), I would keep that feature.

Other options, I see:

- Not show it until there is one comment field in the whole library. Con: determing that needs time. Con: There needs to be at least one field

> I would add a toggle in the prefs (or actually respect what is written in the fields textbox).

The textbox needs to be reworked IMHO. It seems like a low-level configuration thing only "accessible" for JabRef pro users. JabRef's tabs are not fully configurable by that preference, only some. 

IMHO, that configuration makes sense if JabRef is used for something different than literature management. For instance, DVD collections, person list, ... - In the field of literature management, JabRef should offer "best practices" and not force the users to configure something.

**Comment by tobiasdiez** [comment]
If you need the user specific comments you can enable them in your jabref, if not then let it be disabled. Sounds like a good enough solution to me, a finer per-bib solution is not necessary. Just keep it simple I would say.

**Comment by koppor** [comment]
I changed the logic not to show the user-specific comment field and to contain an "Add" button below the normal field. Feel free to try out the build at https://builds.jabref.org/pull/10610/merge/.

For me, promoting the feature is important - even though it is useful for group-work only. Let's see whether this is acceptible for you @PenguinJunk

**Comment by PenguinJunk** [comment]
That works very nicely!
