### ISSUE TITLE
Crossref fetcher has incomplete data

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10455]
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

https://github.com/JabRef/jabref/blob/3f53201dea6640bd2b0f903a257b8f772ba206a8/src/test/java/org/jabref/logic/importer/fetcher/CrossRefTest.java#L123-L132
misses from the [api result](https://api.crossref.org/works/10.1023/a:1003473214310):
- the journal
- the issue number
- the keywords (subjects)
- the publisher

Especially the missing journal is annoying.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by sayyidhussain** [comment]
Hi @tobiasdiez is this open to work.

**Comment by ThiloteE** [comment]
I think @Luggas4you was about to work on this?

**Comment by ThiloteE** [comment]
Hello, @sayyidhussain. Thank you for your interest, I would suggest to choose another issue from our [good first issues](https://github.com/orgs/JabRef/projects/5) projects page, unless you want to do it together with @Luggas4you? If you are a student and you have certain course requirements, you can also choose from our university projects page.

@Siedlerchr If you put an issue into the internal tracker for Luggas, I would suggest to mark the issues as reserved and to assign luggas, so that people can see.
