### ISSUE TITLE
Moving linked pdf's with Cleanup tool does not work if 'Move URL..' option is enabled

### ISSUE THREAD

**Issue by NickVanOosterwyck** [JabRef/jabref#10479]
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Add pdf (which is not yet in the default directory) to an entry.
2. Select entry and click 'Cleanup entries'
3. Enable the options 'Move URL in note field to URL field' and 'Move linked files to default file directory'
4. Click 'OK'.

The file will not be moved. However, if you repeat steps 2 to 4 with the option 'Move URL in note field to URL field' disabled, the file does move to the default file directory.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
