### ISSUE TITLE
Add library selection to "Aux file import"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10472]
At "Tools" > "New sub library based on AUX file", JabRef generates a new .bib file based on the cited entries

![image](https://github.com/JabRef/jabref/assets/1366654/cec046ce-71ed-40a4-b7e3-5f0228f2fe36)

The dialog shows then following

![image](https://github.com/JabRef/jabref/assets/1366654/f9a6a518-e0d8-46a2-af98-c468329a9677)

Currently, JabRef uses the currently opened library. This may lead to confusion.

We need a library selector (similar to the import dialog)

![image](https://github.com/JabRef/jabref/assets/1366654/f291200a-d5a9-4893-899b-2e27b619c8ee)

Hints:

For the import dialog, the implementation was done at https://github.com/JabRef/jabref/pull/9402

**Comment by caitlinlilley** [comment]
Hi, I would like to work on this issue as a part of my university assignment. Could I please be assigned to it?

**Comment by OMEN-Watson** [comment]
Hi, may i give it a try as well ?  although it has been assigned to someone,  I also  would like to solve this issue as a part of my uni assignment.

**Comment by caitlinlilley** [comment]
Hi, I am still working on this.

**Comment by ThiloteE** [comment]
@OMEN-Watson Students are special. We usually only assign one group or one student to an issue. This is, because we don't know the grading scheme and the course requirements. We also try to minimize conflict and aim to have good organisational workflows for all parties involved. We have had conflicts because of this in the past. Both publishing similar or different fixes at the same time or at different times for the same issue creates all sorts of trouble for the person that has to give you your grade. It is hard to differentiate between "cheating" and "fixing an issue in mostly similar way to what another student has been done prior".

For all these reasons, I would kindly ask you to choose another issue.

If no students were involved, we would be happy to have cooperation and groupwork, but students are special!

**Comment by ThiloteE** [comment]
You can find other good first issues at our projects page: https://github.com/orgs/JabRef/projects/5

**Comment by OMEN-Watson** [comment]
ok,easy~ i will not submit any PR,just try to fix it locally

**Comment by caitlinlilley** [comment]
Hi, I have added the visuals for the library selector but I am stuck on how to implement the logic to actually select and use a particular library. Could I please have some guidance?

**Comment by Siedlerchr** [comment]
@caitlinlilley  check out the implementation in the ImportEntriesDialog:

https://github.com/JabRef/jabref/blob/8ede31a7fd7957ca81fc5b0fde04b6971fa11bfd/src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java#L108-L129
