### ISSUE TITLE
Some minor problems with Springer fetcher

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#1068]
Using: JabRef 3.2 on Windows10

Have a look at the following example entry:
http://link.springer.com/chapter/10.1057/9781137028303_4

Its type is: Incollection

Steps to reproduce:

1. Use Websearch "Springer" to crawl entry
2. Enter search term: "fine Neoliberalism in Retrospect?"
-> Issue 1 the entry is not found due to the question mark.

3. Enter search term: "fine Neoliberalism in Retrospect"
4. Mark the correct entry and import

-> Issue 2 the entrytype is "article", it should be "InCollection"
(According to the source code the fetcher does guess the type by isbn, but the entry above has an isbn, which is also exported if one uses the "export to jabref" function on the website)

**Comment by matthiasgeiger** [comment]
First issue is caused by springer itself: If you search there with the questionmark the article will not be found ([as the questionmark is interpreted as an wildcard](http://link.springer.com/searchhelp#search-help-6)).

Regarding the second aspect: For me the imported entry is "InCollection" and not "Article"... However, the officially exported bib-files says it is "InBook"...

**Comment by teertinker** [comment]
Regarding the first issue: Thanks for clarification. This probably means, that each webimporter can have its own specifications. Didn't know that. 

Second issue: Ok. Thanks! Using the development shapshot and not 3.2 I get the correct: "Incollection"! (In my opinion "InBook" as suggested on the springer homepage is wrong)
