### ISSUE TITLE
Feature: basic operations on multiple keywords (join / replace)

### ISSUE THREAD

**Issue by davydden** [JabRef/jabref#1076]
The current 3.3 version has `Manage keywords` section, which is however a bit limited.
It would be good to be able to choose all the entries in database and then manually rework keywords so that there are no duplicates. To that end a user needs to be able to:
1. select several keywords and then `join` them to one.
2. or select several keywords and do `replace with` and provide a new keyword.

Perhaps (2) is more convenient from the user perspective.

**Comment by matthiasgeiger** [comment]
Thank you for the suggestion!

If you know the entries with duplicates this already can be performed using the current dialog: Select affected entries, open "manage keywords" dialog, remove all duplicates of the keyword, add the replacement. 

However, this does not work if **all** entries are selected as in the second step the replacement would be added to **all** entries. 

So I agree, that a "replace with" function would be nice. 

(Potential workaround: search for the duplicate keyword using the search `Keywords=value1 OR Keywords=value2`, the select all found entries and then remove and add the replacement as mentioned above)

**Comment by Andrew-Lev** [comment]
Hey I'm new and can take a shot at adding this.  

However, I just got the application running and am still getting used to the program, so it will probably take me a while.

I went ahead and played around with the keyword feature, and may have found a little bug in it.  If you have a the same keyword for more than one entry, choose 'appearing in any' in the keyword manager, and delete one of them (no way to know which entity its tied to) it appears to do so, but after clicking ok nothing changes.

I would propose a few changes to the keyword manager popup:
1)Adding a second column to reference the title (i.e. Mybook | myKeyword1) 
2)Make the columns sortable
3)Fix the issue I mentioned earlier
4)Add the requested 'replace with' feature as a new button
5)Make the key field clickable (like a textbox) so that the user can manually change keywords

Let me know if you would like me to try working on some of these points, if you think they are worthwhile, or if they are even achievable (I havent looked at the code much yet).

Any relevant info and what files that might be involved for this would be appreciated. Also, some tips on importing a sample library would be great.  I get an error when trying to import one with error text along the lines of 'are you running directly from source'.
