### ISSUE TITLE
Fails to launch on Windows, no GUI or error messages

### ISSUE THREAD

**Issue by fpdotmonkey** [JabRef/jabref#10767]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 Version 22H2

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Simply launch JabRef, e.g. from Start, cmd, or File Explorer

### Appendix

Logs 5.12--2023-12-24--4233bad [log.txt](https://github.com/JabRef/jabref/files/13901279/log.txt)

Logs 5.13--2024-01-09--01c3e15 [log.txt](https://github.com/JabRef/jabref/files/13901286/log.txt)

**Comment by HoussemNasri** [comment]
The problem seems to originate from [oshi](https://github.com/oshi/oshi). According to this issue https://github.com/oshi/oshi/issues/2285 the developers suggest that getting this error indicate there are some missing or corrupt WMI related binaries. 

Try following the answers in this post and see if the problem persists: https://learn.microsoft.com/en-us/answers/questions/684166/failed-to-initialize-all-required-wmi-classes.

**Comment by Siedlerchr** [comment]
This probably comes from the automatic dark\light  theme detection. We should use a, default in case such exceptions happens so that JabRef starts

**Comment by HoussemNasri** [comment]
> We should use a default in case such exceptions happen so that JabRef starts

I'm fine with that, but we should at least log a warning so it wouldn't be confusing that the theme is not switched automatically to the OS's theme.

**Comment by Siedlerchr** [comment]
@fpdotmonkey  Can you please try this version? https://builds.jabref.org/pull/10777/merge
