### ISSUE TITLE
Preview not updated when selecting another entry

### ISSUE THREAD

**Issue by gpagnon** [JabRef/jabref#10839]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.12--2023-12-24--4233bad Mac OS X 13.6.3 x86_64  Java 21.0.1  JavaFX 21.0.1+6

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When I move down with the cursor in the Table of Entries from one item to the other, the Preview section of the Entry Panel often does not get updated, showing the information relative to a previously selected item.  This does not occur with the latest development version, which works fine.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by gpagnon** [comment]
Thank you, the development build does not show the issue.

**Comment by koppor** [comment]
Similar issue: https://github.com/JabRef/jabref/issues/9172
