### ISSUE TITLE
Add wrapping at import dialog

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10931]
1. Go to https://link.springer.com/chapter/10.1007/978-3-031-24066-9_5
2. Use the browser extension button to import into JabRef
3. See following dialog: 
    ![image](https://github.com/JabRef/jabref/assets/1366654/8d06c9f9-783e-428f-b9d2-dfd5e3932138)

The text should be wrapped (no horizontal scrolling)

**Comment by Ahmed-Khaled-dev** [comment]
Hello, I would like to be assigned to this issue.

**Comment by Ahmed-Khaled-dev** [comment]
### Status Update
I am currently having issues with opening the [Importer](https://github.com/JabRef/jabref/tree/main/src/main/java/org/jabref/gui/importer)  ``.fxml`` files using the JavaFX [Scene Builder](https://gluonhq.com/products/scene-builder/), It gave me errors due to the usage of external libraries like ``controlsfx`` and ``fxmisc richtext``

While solving this issue, I encountered additional complications with the build, Currently, I am working on rebuilding the project from scratch and setting up a clean development environment, In which I believe these issues will be fixed

I will send another status update once I reach something new

**Comment by koppor** [comment]
@Ahmed-Khaled-dev You are right, Scene Builder cannot be used. "Just code". ^^. The steps to have a clean build are explained at https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/. You can share your complications on gitter. Hopefully, someone is on and can comment on it.

**Comment by Ahmed-Khaled-dev** [comment]
I greatly apologize for the very long period with no updates, I still wasn't able to completely wrap my head around the codebase, and I have a lot of stuff taking my time currently, so please unassign me and once I have gained a deeper understanding of the codebase and resolved my current commitments I will request to be assigned to a new issue.
