### ISSUE TITLE
Tests for Push application (Lyx,SublimeText,Texmaker,TeXstudio,Vim,WinEdt,TexShop)

### ISSUE THREAD

**Issue by lachiri-ilias** [JabRef/jabref#10941]
Me and my group (@Blezie, @JohannBiorck @vladdobre @Kr1st1an-F) are currently working on the Issue ([#3191 TeXworks](https://github.com/JabRef/jabref/issues/3197)). We are currently writing tests for this issue.

We have noticed that all the push method (Lyx, SublimeText, Texmaker, TeXstudio, Vim, WinEdt, TexShop) doesn't contain test and they are very similar. So we wonder if we can contribute to create these tests ?

**Comment by koppor** [comment]
Adding tests is kind of "integration test". An X server needs to be started. We do that for https://github.com/JabRef/jabref/blob/62ee331ef0c6a6404492c35fb1dced0c9f6417dc/.github/workflows/tests.yml#L245.

The test needs to do following:

1. Install tool X
2. Open "example.tex" in tool X
3. Set JabRef to push to tool X
4. Instruct tool X to save the file
5. Check "example.tex" for differences.

"example.tex" can be an empty file at step 2.

Steps 2 and 4 can be very difficult from a command line. I expect 10 to 20 hours per tool to find out how to automate.

Thus, I agree with the comment at https://github.com/JabRef/jabref/issues/10941#issuecomment-1969889636 so that the generated string is correct.

**Comment by AdamWysokinski** [comment]
> The test needs to do following:
> 
>     1. Install tool X
> 
>     2. Open "example.tex" in tool X
> 
>     3. Set JabRef to push to tool X
> 
>     4. Instruct tool X to save the file
> 
>     5. Check "example.tex" for differences.
> 
> 
> "example.tex" can be an empty file at step 2.
> 
> Steps 2 and 4 can be very difficult from a command line. I expect 10 to 20 hours per tool to find out how to automate.
> 
> Thus, I agree with the comment at [#10941 (comment)](https://github.com/JabRef/jabref/issues/10941#issuecomment-1969889636) so that the generated string is correct.

If this would be of any use, in SublimeText commands may be run from CLI:
```
subl -b --command open "example.tex"
subl -b --command save
```

**Comment by koppor** [comment]
I close this issue as this is neither a user-facing issue nor something reported by the maintainers of JabRef.

Nevertheless, thank you for choosing JabRef.
