### ISSUE TITLE
Add compare button to duplicates in Citation relations tab

### ISSUE THREAD

**Issue by AbdAlRahmanGad** [JabRef/jabref#11192]
I think it would be nice if we added a compare button to the duplicates in the citation relations tab.
The compare button will open the "[Possible duplicate entries](https://docs.jabref.org/finding-sorting-and-cleaning-entries/mergeentries)" window.

It will look something like this:
<img width="615" alt="Screenshot 2024-04-14 at 10 51 47 AM" src="https://github.com/JabRef/jabref/assets/89566409/063ef61e-8302-48ec-9e6d-1b013880452e">

For more context:
The duplication detection in the citation relations tab was implemented in this PR https://github.com/JabRef/jabref/pull/11186

**Comment by koppor** [comment]
@AbdAlRahmanGad Nice idea! Helps to see if JabRef works right - and also helps to add missing data to JabRef (if available)

**Comment by harshithap2000** [comment]
@koppor I wish to work on this issue with a teammate for university assignment. 

I had a query, I see that `gui/entryeditor/citationrelationtab/CitationRelationsTab.java` (shown below) has the code for rendering the citation list. Where can I find the UI files for the same? So that I can add a compare button along with the link button.

```
.map(localEntry -> new CitationRelationItem(entr, localEntry, true)) // duplicate entry
.orElseGet(() -> new CitationRelationItem(entr, false)))

**Comment by Siedlerchr** [comment]
The UI is direclty construced in CitationRelationsTab getPaneAndStartSearch

**Comment by KumaLuo** [comment]
Hi @HoussemNasri , Could you please assign this issue to me?
