### ISSUE TITLE
Translation challenge!

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1128]
@JabRef/translators 
@oscargus (maybe you should add yourself to the translators' team?)

Many changes have been done to the JabRef code in the past weeks. This will lead to the release of JabRef version 3.3 on April 15. So it is time for us, translators, to tidy up the localizations in our respective language.
The files are in this directory: <https://github.com/JabRef/jabref/tree/master/src/main/resources/l10n>
If you have any issue with the localization, this issue is waiting for your comments!

**Comment by Siedlerchr** [comment]
I'm onto for German.

**Comment by mlep** [comment]
Great!
FYI, I will try to update the translation status (https://github.com/JabRef/jabref/wiki/Translating-JabRef) everyday up to the release of version 3.3

**Comment by Siedlerchr** [comment]
Properties_de (and menu) are now complete.  I will now look at the help files

**Comment by mlep** [comment]
@Siedlerchr About the help files, I do not know which ones are up-to-date in English, and which ones are obsolete. Better make sure before translating.
See https://github.com/JabRef/help.jabref.org/issues/11

**Comment by hakova** [comment]
I translated all entries in properties_tr and menu_tr to Turkish and committed them last night but I cannot see them today. Can you help figure out what went wrong? Please don't tell me that I have to do them again!

**Comment by hakova** [comment]
In a closer look today, I see that there is this message on the web page that is supposed to allow editing:

"You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork hakova/jabref, so you can send a pull request. "

My questions:
1. Why do I not have write access? Is this the way it is supposed to work?
2. If not, is there any way to find that file in the fork mentioned above, since I cannot find my edits in that location (hakova/jabref) either?

Any help will be greatly appreciated.

**Comment by koppor** [comment]
# 1st question
We had the issue that once the whole history has been corrupt, because me and a translator did something wrong with git. We want to prevent that. Github's pull request system is perfectly working for that. - In short: Yes, this is the way it is supposed to work

# 2nd question
Where did you edit? Can you show me the output of `gitk --all` on your machine? - You can add my on Skype (same username as here) and we can have a discussion how to find your commits.

**Comment by mlep** [comment]
@hakova 
My guess is that you are editing directly the files in your browser. If so:
The message is part of the normal (updated) procedure.
At the bottom of the page, add a title, and then, right below, click on the green button "Propose file change".
A new page is displayed. Click on "Create a pull-request".

The programmer group will then review it. They may add some remarks, and, if everything is ok, they will merge your changes to the master branch.

**Comment by hakova** [comment]
mlep is correct. I am editing the files directly in my browser. I did everything as he suggested, including clicking on the green button "Propose file change". A new page is displayed but I did not click on "Create a pull request". Can those files still be found somewhere? It was quite a lot of work and I would love to avoid duplicating it if possible.

@koppor Thanks for your response. When issue the command `gitk --all` it opens up a window with code structure. I am not sure how to show it to you other than a screenshot, which may not be effective, since the code is far too long than the window height can show at once. Unfortunately, I don't have Skype :(.

**Comment by Siedlerchr** [comment]
@hakova  Your commits are in your fork of the repository. 
https://github.com/hakova/jabref/commits/master

Now go to Jabref/Jabref->Pull Requests  https://github.com/JabRef/jabref/pulls -> new PR-> Compare across forks.
Now on the right side chose your  fork <Username>/jabref. -> Create PR.
For future work it is better to create a new branch for it. Makes it easier to merge.

When you edit sth for the first time, github forks the repository from Jabrref/jabref to /<Username>/jabref

**Comment by mlep** [comment]
@JabRef/translators  @oscargus 
Currently, we have succeeded in completing the localizations of the menus in 5 languages (Chinese, Farsi, French, German and Turkish).

Some menus are missing a few strings only (Dutch: 6; Italian:6; Japanese: 4; Portuguese: 1; Spanish: 1; Swedish:5), while others are a bit behind (Danish:15; Indonesian: 15; Norvegian:13; Vietnamese:17).

In order to have the localizations of menus as complete as possible for version 3.3, **I am planning to ask users (via the mailing list) to send translations for the missing strings by Tuesday evening (European time)**. I am thinking about sending one email per language with the missing strings included. That should attract new contributors and make their work as easy as possible.
**Please, let me know if you prefer to complete the localization by yourself.**

**Comment by Siedlerchr** [comment]
@mlep For the Dutch and Spanish string I could ask someone I know from Google+, if  you can find nobody.  Maybe Indonesia, too.

**Comment by mlep** [comment]
@Siedlerchr Thanks for the offer! I plan to send the email tomorrow (i.e. Tuesday evening). If, by Wednesday evening the localizations for Dutch, Spanish or Indonesian are not complete, I will let you know.

**Comment by jtornero** [comment]
Don't worry about Spanish. Justo busy but it'lll be con time
Cheers

**Comment by mlep** [comment]
Thank you @jtornero for completing the Spanish localization (100% for both Spanish files!).
@JabRef/translators @oscargus: At the moment, since @koppor will contribute the Norwegian translations and Dutch is under way, only Vietnamese and Japanese have incomplete menus. Not too bad!

**Comment by stefan-kolb** [comment]
Thanks a lot to all translaters :+1: :heart:

**Comment by koppor** [comment]
Dutsch is in (53eb87c4c16d3249), Norwegian, too (fdded30b2222a4b7).
