### ISSUE TITLE
Enable pasting SSRN entries

### ISSUE THREAD

**Issue by e-pet** [JabRef/jabref#11687]
It is very nicely possible to simply copy-paste links to arxiv or DOIs. This is currently not possible for SSRN papers, as far as I can tell?

It would be very nice to be able to copy-paste links such as https://ssrn.com/abstract=4904445.

**Comment by Siedlerchr** [comment]
As a workaround you can use the browser plugin from JabRef to import such entries

**Comment by trickypr** [comment]
Hey, I would be interested in implementing this. Would I be able to be assigned to this issue?

**Comment by Siedlerchr** [comment]
@trickypr  You can try but this is a non trivial issue. You might want to check https://github.com/orgs/JabRef/projects/5

**Comment by trickypr** [comment]
I think that I have a relatively simple solution. SSRN has been assigning DOIs to all of their preprints since the end of 2023 [^1]. These DOIs are of the format `10.2139/ssrn.<abstract_id>`. I figured that a solution would be:
1. Check the clipboard text in [`handleStringData`](https://github.com/JabRef/jabref/blob/7d480508632b4619cb662d4b9f5a1078990da827/src/main/java/org/jabref/gui/externalfiles/ImportHandler.java#L356) for a SSRN URL
2. Convert it to a DOI
3. Pass it to [`fetchByDOI`](https://github.com/JabRef/jabref/blob/7d480508632b4619cb662d4b9f5a1078990da827/src/main/java/org/jabref/gui/externalfiles/ImportHandler.java#L395)

Would this be a fine solution, or is there some context I am missing?

[^1]: https://blog.ssrn.com/2023/01/31/ssrn-uses-doi-for-preprint-articles/

**Comment by koppor** [comment]
> SSRN has been assigning DOIs to all of their preprints since the end of 2023 [1](#user-content-fn-1-e24098f8ca71e38c7a17a59df95f1ad1). These DOIs are of the format `10.2139/ssrn.<abstract_id>`. 

Nice information!

>     1. Check the clipboard text in [`handleStringData`](https://github.com/JabRef/jabref/blob/7d480508632b4619cb662d4b9f5a1078990da827/src/main/java/org/jabref/gui/externalfiles/ImportHandler.java#L356) for a SSRN URL
>     2. Convert it to a DOI

No. 

Adapt org.jabref.logic.importer.CompositeIdFetcher#performSearchById.

Before, introduce `SSRN` in package org.jabref.model.entry.identifier. Offer `parse` and `toDoi`. The `toDoi` returns `DOI`, which can then be used to be passed to `DoiFetcher`.

>     3. Pass it to [`fetchByDOI`](https://github.com/JabRef/jabref/blob/7d480508632b4619cb662d4b9f5a1078990da827/src/main/java/org/jabref/gui/externalfiles/ImportHandler.java#L395)

Side comment: Rewrite this - https://github.com/JabRef/jabref/issues/12004.
