### ISSUE TITLE
Keyword Groups Not Updated When New Entry Saved

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#1173]
JabRef version-3.2 on Slackware-14.1
Hint: If you use a [development version](http://builds.jabref.org/master/), ensure that you use the latest one.

Steps to reproduce:
1. ...Add a new article, tech report, or similar entry.
2. ...Save (^s)
3. ...Look in group listing at the left for a new keyword. It's not there.
4. ...Remove all group entries (I have only one branch).
   5 ...Exit JafRef (^q)
   6....Restart JabRef
   7....Create new groups from keywords. Newly added keywords now appear in the list.

If applicable, excerpt of the bibliography file, screenshot, and excerpt of log (available in the error console)

**Comment by tobiasdiez** [comment]
"Create new groups from keywords" is a static one-time thing. Changes to the specified keyword field are not reflected in new groups. This is more or less by design. 

We will implement a mechanism to automatically create "groups" based on keywords, which then also stay in sync with the keyword values. So right now for me it is interesting what you exactly tried to accomplish, i.e. for which keywords did you created the groups, which separators etc. Thanks!

**Comment by tobiasdiez** [comment]
The latest development version has a new "automatic group" that also updates its subgroups (generated from keywords) if the data is changed.
