### ISSUE TITLE
New entry dialog GUI is broken when "Others" is expanded

### ISSUE THREAD

**Issue by InAnYan** [JabRef/jabref#11748]
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Details on version and operating system

Linux Mint 22 (XFCE)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Click "New Entry" (a dialog appears).
2. Click "Others" to expand other entry typers

The UI is not expanded (that's the problem No 1).

3. Expand window (seems to work okay).
4. Close "Others".

Now there is a black rectangle. And mouse events does not correspond to UI elements.

See the video attached.

### Appendix

<details>

[Uploading jabref_ui_bug.mp4…](https://github.com/user-attachments/assets/66c626c2-0f1d-4b8e-8210-9f282008ec62)

</details>

**Comment by koppor** [comment]
Can you try with the build at https://builds.jabref.org/jdk-ea/?

**Comment by Siedlerchr** [comment]
Can you please check the latest dev version? We just merged javafx 23

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
