### ISSUE TITLE
Finish ToDo in localizationParameterMustIncludeAString

### ISSUE THREAD

**Issue by leaf-soba** [JabRef/jabref#11784]
**Is your suggestion for improvement related to a problem? Please describe.**
1. I saw a ToDo in this unit test, said "TODO: Localization.lang(var1 + "test" + var2) not covered", and I want to finish it.
2. I checked all strings in `Localization.lang` parameter in repo now, only got string begin with ". 
3. It means we don't have case `Localization.lang(var + "test")` or `Localization.lang(var1 + "test" + var2)` in repo, do I need to cover them when I finish the ToDo?
4. I think only when developers need string concatenation in `Localization.lang` would use `Localization.lang(var + "test")` and `Localization.lang(var1 + "test" + var2)`

**Describe the solution you'd like**
- one of these solution should work, not all of them.
1. finish the ToDo, to cover future string concatenation case in `Localization.lang` by add `StringUtils.countMatches(e.getKey(), "\"") >= 2`
```
assertTrue(e.getKey().startsWith("\"") || e.getKey().endsWith("\"") || StringUtils.countMatches(e.getKey(), "\"") >= 2, "Illegal localization parameter found. Must include a String with potential concatenation or replacement parameters. Illegal parameter: Localization.lang(" + e.getKey());
```
2. just fix comment without code change, such as delete the ToDo comment and add the link to https://devdocs.jabref.org/code-howtos/localization.html

3. fix the code by delete `e.getKey().endsWith("\"")`
```
assertTrue(e.getKey().startsWith("\""), "Illegal localization parameter found. Must include a String with potential concatenation or replacement parameters. Illegal parameter: Localization.lang(" + e.getKey());
```

**Comment by koppor** [comment]
>     1. finish the ToDo, to cover future string concatenation case in `Localization.lang` by add `StringUtils.countMatches(e.getKey(), "\"") >= 2`

It needs to be `==`.

We just support `Localization.lang("fixed-string");`.

That should be checked. Nothing more.

`StringUtils.countMatches(e.getKey()` is a great idea 👍. Simple and efficient.

---

Note that I tried to use `Java Parser`, but I failed. https://github.com/JabRef/jabref/pull/8050#issuecomment-911975558

The other solution for localization is to use [Kilt](https://poiu-de.github.io/kilt/).

However, this does NOT solve the issue of string concatenation. We also do not want that concatenation, because we want to have the strings literally in the source code. Paramters by `%0` etc.

We also do NOT want to switch to the syntax of [MessageFormat](https://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html)

You can write an [ADR](https://adr.github.io/madr/) if you want 😅

**Comment by koppor** [comment]
We worked in the DevCall to a more refined comment. Hope, that helps.

Implemented at https://github.com/JabRef/jabref/pull/11820
