### ISSUE TITLE
Lookup -> Search Unlinked local files: Improve dialog

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11878]
![Image](https://github.com/user-attachments/assets/e285f9f3-9aee-43b5-8976-fad59f8e2e26)

**Is your suggestion for improvement related to a problem? Please describe.**

I am using Lookup -> Search for unlinked local files 

**Describe the solution you'd like**

    1a: The column "File" should contain relative paths starting from the Directory given in the field "Directory", not the full path
    1b: The column should use "..." on the left, not on the right
 (if possible)
    2: The columns should be resizable

**Additional context**

Open a bib file (e.g. chocolate bib) and point to a directory with pdfs

**Comment by agondekova** [comment]
Hi! I'd like to work on this issue. Could you please assign it to me?

**Comment by master-vibe** [comment]
Hey I would like to work on it! Could you please assign it to me?

**Comment by Siedlerchr** [comment]
@master-vibe the issue is already assigned to someone else

**Comment by master-vibe** [comment]
Okay, Anyway I fixed the issue.

**Comment by ThiloteE** [comment]
@agondekova What do you think? Do you mind?
@master-vibe I propose to wait for a response by agondekova. At JabRef we try to lookout for students who may work on issues as part of their course assignments. If somebody else buts in, it may lead to problems with their grading. Since it has only been a day since the assignment, maybe it is possible for agondekova to switch to another good first issue, but you are definitely complicating things. Next time definitely make sure to choose a good first issue or university project that is "free to take".
![Image](https://github.com/user-attachments/assets/68192914-062d-45a9-a27a-7e7a46875055)
If you are confident you also can choose any other issue that is not curated, but those might be more difficult to solve.

A compromise could be for you to make your proposed solution only public once agondekova has opened the pull-request. Then we can compare and merge the better one.

**Comment by master-vibe** [comment]
Okay, I understand. Thank you for the info.

**Comment by agondekova** [comment]
@ThiloteE I would like to work on this issue because it is important to me and related to my studies. If I had to change the assignment, it could mean losing points for me. 
I appreciate your initiative @master-vibe  and I am open to compare our pull requests and choose the best solution.

**Comment by master-vibe** [comment]
@ThiloteE, I don't mean to interrupt your studies, but I would appreciate the chance to compare our code since I have already worked on it and want to ensure it isn't in vain. 
Let's compare and choose the best solution, as this would also give me insight into my own code.

**Comment by ThiloteE** [comment]
I am sure you did not mean to tag me, but here my recommendation anyway: If you want to absolutely make sure to not have worked in vain and minimize the risk thereof, please choose a different issue.

**Comment by master-vibe** [comment]
Yeah, I tagged the wrong person. I was supposed to tag @agondekova I guess. Anyways, It's alright, Good luck @agondekova.

**Comment by Siedlerchr** [comment]
@tohfas  Aren't you part of the group that is assigned to another issue?

**Comment by tohfas** [comment]
> [@tohfas](https://github.com/tohfas) Aren't you part of the group that is assigned to another issue?

Right. I will in that issue. Its sorted. Thanks

**Comment by tohfas** [comment]
> > [@tohfas](https://github.com/tohfas) Aren't you part of the group that is assigned to another issue?
> 
> Right. I will in that issue. Its sorted. Thanks

However, we need more issues for  team as we are a group of 5. Is this issue available so that we can take?

**Comment by koppor** [comment]
Addition:  If you work as team, work together on a medium-sized issue; this offers more group-collaboration possibilities.
