### ISSUE TITLE
Double-click on preview style should add it to "Selected"

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11902]
![image](https://user-images.githubusercontent.com/1366654/203511710-cb75ea51-f8fa-476f-8610-dffde3c061b5.png)

**Is your suggestion for improvement related to a problem? Please describe.**
It would be more convenient to use a double click to move preview styles between the two lists.

**Describe the solution you'd **like**Preferences -> Entry Preview 
1. Double click on one of the styles in "Available"   should add it to the "Selected" listview
2. Double click on one of the styles in "Selected"  should remove it from the "Selected" listview 

**Additional context**

Implementation notes:
PreviewTab under gui/preferences needs to be adjusted.
Add a click handler `withOnMouseClickedEvent` to the listViews and check for a double click

**Comment by iUnknownGalaxy** [comment]
Hey, I'd like to work on this issue. I'm a Junior CS student at GMU looking to contribute to open source projects.

**Comment by hemangtk** [comment]
Hey @Siedlerchr i would like to contribute in this issue 
could you please assign me the issue so that i can start working right away

**Comment by lzmmxh** [comment]
Hi, I’m interested in taking on this issue. Could you assign it to me? @koppor

**Comment by lzmmxh** [comment]
Hi, I’m interested in taking on this issue. Could you assign it to me? @Siedlerchr

**Comment by ThiloteE** [comment]
Are you kidding me? We are not playing lottery here. JabRef has a first come first served policy, so I am going to assing @iUnknownGalaxy. Everybody else, please choose another "free to take" issue from https://github.com/orgs/JabRef/projects/5

### Why?

We have issues that are reserved (you can see it in the top right corner at the projects section), as grading requirements may differ and group work may not be permitted by some lecturers and in some courses.

Keep also in mind that double work must not be, but can be inefficient. 
   - In principle, all issues are free to take, so if you are fast you could theoretically come up with your own solution first and propose a change, but since somebody already asked to be assigned to this issue and may already have started working on a fix, it could lead to disappointment and double work for the both of you. Ultimately only one of your pull-requests will be merged, so if your study course requires you to demonstrage a successfully merged commit this is a risky plan.
   - Supervising two different pull-requests creates more work for maintainers, since they have to hop between pull-requests to compare them and communicate with the both of you.

### Why not a first come first served?
In principle, you could work together on this issue (groupwork), but this would require good communication skills on your part. If both of you are willing, you should exchange contact details (e.g. via gitter/e-mail etc.), but this is probably really an easy fix, so the effort to coordinate might be higher than the effort to simply fix the issue.

**Comment by iUnknownGalaxy** [comment]
It seems that the issue has already been resolved without any intervention. I checked the application, added a test.bst and was able to move it between available and selected.

Do you mind checking to confirm that the existing behavior is correct?
