### ISSUE TITLE
Update to MADR 4.0.0

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#11912]
(This is a non-coding issue)

[MADR 4.0.0 was released](https://github.com/adr/madr/releases/tag/4.0.0).

The decisiosn in https://github.com/JabRef/jabref/tree/main/docs/decisions should be updated to that format.

**Comment by lzmmxh** [comment]
Hi, |'m interested in taking on this issue. Could you assign it to me?

**Comment by RabidGhost** [comment]
Hi, Ive had a look at the MADR 4.0.0 changes, and the list of decisions you linked. Im a new contributor and i would like to tackle this issue. 

Thanks!

**Comment by RabidGhost** [comment]
Ive making some small changes only to fix typos and MADR 4.0.0 changes. I found this [malformed decision](https://github.com/JabRef/jabref/blob/6537bc957171775ca15b730af9084834a236c1ef/docs/decisions/0011-test-external-links-in-documentation.md) while working. Is this intentional?

![Image](https://github.com/user-attachments/assets/469c531f-7d72-4efe-92d9-f1ff7c9c82fc)


Additionally are there any changes to be made other than formatting of decision outcome quotes? It seems the adr-template and most adrs are up to date. Thanks
