### ISSUE TITLE
Minimum Window Sizing when Adding a New Entry

### ISSUE THREAD

**Issue by ityyrm** [JabRef/jabref#11944]
Hello,  

Sorry for adding more during what I’m sure is an annoying time for this repo with the sudden influx of students. I am a university student with an assessment which involves contributing to an open-source project (as many others seem to be).  

After messing around with JabRef for a bit, I have noticed that in the New Entry window, it is possible to make the window too small, making buttons invisible or unreachable

When everything fits onto the window:
![Image](https://github.com/user-attachments/assets/e374b361-3a86-4eef-97f0-a42f641bd3b5)

When the window is too small to fit all the element in
![Image](https://github.com/user-attachments/assets/1c946460-0df1-4274-8d55-fe3d48bae2a6)

Would it be possible for me to make a modification to give it a set minimum window size or an ability to “scroll” the window when it doesn’t fit properly?

**Comment by GiannisPep** [comment]
Hello,

I’ve reviewed the issue you raised regarding the window resizing in the New Entry window of JabRef. I understand the problem of elements becoming invisible or unreachable when the window is resized too small. I'd be happy to work on fixing this by:

-Setting a minimum window size to prevent users from resizing the window too small, ensuring all elements remain visible and usable.
-Alternatively, or additionally, I can add a scrollable view so that when the window is smaller, users can scroll to access any hidden elements.

Please let me know if you would like me to proceed with this solution, and feel free to assign the issue to me. I look forward to contributing!

**Comment by ThiloteE** [comment]
@GiannisPep there is a group of students working on https://github.com/JabRef/jabref/issues/8808. I can assign you to this one. Let's hope there will not be any conflicts when they open a pull-request. I see that this is one of your first issues ever on GitHub, so let's hope this one turns out to be an easy one ;-) If not, you could try yourself on a "free to take" one from [good first issues](https://github.com/orgs/JabRef/projects/5).

**Comment by ThiloteE** [comment]
Wait a minute. @ityyrm was asking to work on this him/herself.
@GiannisPep Sorry, I have to unassign you! We try to look out for students to avoid trouble with grading.
