### ISSUE TITLE
Allow custom ordering of fields in the edit panel

### ISSUE THREAD

**Issue by scoavoux** [JabRef/jabref#120]
When customizing entry types, we can pick which fields should be proposed for various types, as well as *the order in which they should appear*. The order, however, does not survive closing and reopening JabRef.

Could there be an option to force JabRef not to reorder fields? 

To reproduce this: in custom entry type/journal, move title up before journal. The edit panel for an article now shows the title field before the journal field. Quit and restart Jabref. The original order has been restored. 

This issue was brought up [here](http://sourceforge.net/p/jabref/mailman/message/31795245/), but I don't think it has been dealt with.

**Comment by koppor** [comment]
I'm having email access only, therefore,only short answer. Will update the next days.

It should ne fixed in the dev 2.11 branch, but no release yet. Can you download the dev2.11 source and execute gradlew run and verify?

----- Ursprüngliche Nachricht -----
Von: "scoavoux" <notifications@github.com>
Gesendet: ‎22.‎08.‎2015 10:00
An: "JabRef/jabref" <jabref@noreply.github.com>
Betreff: [jabref] Allow custom ordering of fields in the edit panel (#120)

When customizing entry types, we can pick which fields should be proposed for various types, as well as the order in which they should appear. The order, however, does not survive closing and reopening JabRef.
Could there be an option to force JabRef not to reorder fields? 
To reproduce this: in custom entry type/journal, move title up before journal. The edit panel for an article now shows the title field before the journal field. Quit and restart Jabref. The original order has been restored. 
This issue was brought up here, but I don't think it has been dealt with.

**Comment by bluebirch** [comment]
I have followed this issue for a long time and is the sole reason why I
insist on staying with 2.9.2. I would gladly help testing and veritying,
but I have never succeeded in running JabRef from source (github
repository). Is there, by any chance, someone that could help me with that?

lör 22 aug. 2015 kl 10:20 skrev Oliver Kopp <notifications@github.com>:

**Comment by koppor** [comment]
Plz subscribe to the jabref-devel and describe your probs there.

If you have JDK8 running, a simple git clone (or even downloading the ZIP)  and a gradlew run should work. No need to install a build system...

----- Ursprüngliche Nachricht -----
Von: "Stefan Björk" <notifications@github.com>
Gesendet: ‎22.‎08.‎2015 10:26
An: "JabRef/jabref" <jabref@noreply.github.com>
Cc: "Oliver Kopp" <koppdev@googlemail.com>
Betreff: Re: [jabref] Allow custom ordering of fields in the edit panel (#120)

I have followed this issue for a long time and is the sole reason why I
insist on staying with 2.9.2. I would gladly help testing and veritying,
but I have never succeeded in running JabRef from source (github
repository). Is there, by any chance, someone that could help me with that?

lör 22 aug. 2015 kl 10:20 skrev Oliver Kopp <notifications@github.com>:

**Comment by scoavoux** [comment]
It is fixed in 2.11 indeed. Thank you!
