### ISSUE TITLE
Provide URN support similar to the one of DOI

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1210]
URNs are quite similar to DOI, as they identify specific publications. We should enable the features for DOIs also for URNs, including fetch by URN, get bibtex data from URN, and open entry in web.

**Comment by matthiasgeiger** [comment]
Potential resources:
* http://nbn-resolving.org/resolve_urn.htm - which provide XML output for URNs
* http://nbn-resolving.de/
* Example URN: urn:nbn:de:bvb:473-opus4-102147

**Comment by Siedlerchr** [comment]
More Information, RFC: 
http://www.ietf.org/rfc/rfc3188.txt

**Comment by dret** [comment]
these things are apples and oranges because DOI is a specific namespace with a defined authority and lookup mechanism. URN is simply a tree under which many concrete URN namespaces live. but you could support some of them, such as ISBN or IETF document lookup. a complete list of all registered URN namespaces is here: http://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml

**Comment by oscargus** [comment]
I think we could at least implement something extracting the urn information and move it to the "correct" field. This should be possible for:
* ISBN
* ISSN

For NBN (through the links above) the information extraction is nationality dependent. At least for the Nordic countries there is a feasible path to get a BibTeX record.

**Comment by lenhard** [comment]
Meanwhile, we have an ISBN fetcher. Let us consider this as the solution to this problem. Things like a URN fetcher won't be coming.
