### ISSUE TITLE
Upgrade from 3.2 to 3.3: BibtexKeyGenerator preferences are lost

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#1257]
JabRef version 3.3 on OSX 10.11.4

Steps to reproduce:

1. Install 3.3 on OSX, selecting to replace 3.2.
2. After installation, launch Preferences, and note that there are differences (most notably in hand-specified BibTeX key generator formats.
3. Attempt to reimport old preferences file.  Choose preferences file, click OK.  A dialog shows "You must restart JabRef for this to come into effect."  Click OK. Click OK.  ⌘-Q to Quit fully.
4. Relaunch and note that preferences are not updated.

**Comment by matthiasgeiger** [comment]
Manually changing the preferences and saving does work?

**Comment by jkulesza** [comment]
Yes, manually updating a key generator entry, saving, quitting, and restarting preserves the change.

**Comment by matthiasgeiger** [comment]
I can confirm, this at least partially... The bug only affects the exported/imported "BibTeX key generator formats": Those settings are not loaded automatically and also import of exported 3.2 settings does not work. 

Other settings are imported correctly. 

This is caused by some changes in the casing of the stored information: In JabRef 3.2 the exported XML contains the following:
```xml
            <node name="labelPattern">
              <map>
                <entry key="article" value="[author][year]"/>
              </map>
            </node>
```
In JabRef 3.3 this is slightly changed: 
```xml
            <node name="labelpattern">
              <map>
                <entry key="article" value="[author][year]"/>
              </map>
            </node>
```
--> `labelPattern` vs. `labelpattern` (small vs. capital P)

**Quick-Fix for users: Open the exported preferences in a text editor and replace the `labelPattern` with `labelpattern`, save the file and import again in JabRef 3.3.**

**Comment by simonharrer** [comment]
I think we should bring the JabRef preferences and the labelPattern preferences together, and on the way solve this issue as well.

**Comment by stefan-kolb** [comment]
Lots of old artifacts...
```xml
          <node name="labelPattern">
            <map/>
          </node>
          <node name="logic">
            <map/>
            <node name="labelPattern">
              <map/>
            </node>
            <node name="labelpattern">
              <map/>
            </node>
          </node>
```

**Comment by matthiasgeiger** [comment]
Starting from version 3.6 key pattern  preferences will bemigrated upon first start of the new JabRef version.
