### ISSUE TITLE
S with caron does not render correctly

### ISSUE THREAD

**Issue by pirlite2** [JabRef/jabref#1264]
JabRef version 3.3 on Mint 17.3

The escaped character  `\v{S}' ('S' with caron) does not render properly in the main panel. On the other hand, '\v{Z}' does render correctly. (BTW: Having just upgraded to v3.x, the correct rendering of characters with diacritics as a Unicode character is a massive step forward!)

**Comment by oscargus** [comment]
This is (most likely) a limitation of Java/your system. I've also noted that some characters just do not render properly without knowing why (probably font issue, I cannot really think of anything else because I am quite sure that the actual conversion is correct). In general, the preview panel (which use HTML) will be more successful in rendering non-standard characters, even Unicode ones (meaning that if you for fun convert your field to Unicode by right clicking in the field editor and select LaTeX to Unicode, it will not necessarily display correctly in the field editor, nor in the table, but will show it correctly in the preview).

**Comment by pirlite2** [comment]
In fact, the preview panel also makes a mess of things. S-with-caron 
renders correctly but the following characters in the name are trashed. 
Similarly, Z-with-caron displays properly in the table but renders as 
"Z\caron..." in the preview pane. :-(

As to the experiment you suggest with converting to Unicode in the entry 
editor (nice new feature!), everything renders properly apart from 
S-with-caron (U 0160).

Does the same problem exist on Windows?

Peter

**Comment by pirlite2** [comment]
FWIW: v3.3 displays identical behaviour on Win7! So I would suggest this 
narrows it down to a Java problem at best. Same behaviour on two 
radically different OSs!

Out of interest, I am using openjdk-8. Is this behaviour apparent using 
the Oracle JVM? Does "\v{S}iroky" display correctly as an uppercase 'S' 
with a caron?

P.

**Comment by mlep** [comment]
JabRef version 3.3 on Linux Mint LMDE with Java(TM) SE Runtime Environment (build 1.8.0_66-b17):
- `\v{S}' is displayed as a little rectangle
- '\v{Z}' is ok

**Comment by pirlite2** [comment]
I have now been through my database. Basically, 'S' or 's' (upper or lowercase) with caron does not render properly. It always produces a little rectangle. Lots of other characters (Z,z,n, etc.) with carons do render perectly. It seems to be only the letter 'S' (upper and lowercase) that is wrong.

Also, this behaviour appears to be constant across Linux & Windows, and across the OpenJDK and Oracle JVMs. Is it now time to think bug in JabRef? A common upstream bug seems unlikely. Is it possible to check - maybe with a simple 10 line program - whether U-0160 and U-0161 do or do not render properly under Java?

P.

**Comment by Siedlerchr** [comment]
Confirmed in JabRef on Win 7 x64 with Oracle JDK 1.8.0_76
I will try to create a simple testApp to test this.

**Comment by Siedlerchr** [comment]
Update: I found something interesting. When you enter the Š directly, it is displayed correctly, with Arial font family. It is also rendered correctly.
 
@pirlite2 Seems like a problem with the displaying of the LaTex \v{S} symbol

**Comment by oscargus** [comment]
Well, I checked the source now and it is not yet included. I'll add it to #1215 so once added everything should be fine.

**Comment by oscargus** [comment]
Checking again, I was wrong. It is actually included (just in a different position from where I looked). I'll look more into it.

**Comment by oscargus** [comment]
I do not fully get this... That square converts back to {\v{S}}... For me, the HTML rendering works. However, for {\v{C}}, the Unicode rendering works, but the HTML preview rendering shows &Ccaron;. Strange...

**Comment by Siedlerchr** [comment]
@oscargus Can you tell me the relevant code/method? And did you try with the Unicode Symbol rendering directly?  Š

**Comment by oscargus** [comment]
LatexToUnicodeFormatter and HTMLUnicodeConversionMaps

Now, I tried `&#348;&#349;&#350;&#351;&#352;&#353;` (352 is Scaron) which gives: `{{\^{S}}}{\^{s}}{{\c{S}}}{\c{s}}{{\v{S}}}{\v{s}}` which when converted to Unicode gives: ŜŝŞş (you will probably not get it since I added 350 and 351 in my PR). On the other hand, for the preview I get `&Scirc;&scirc;&Scedil;&scedil;Šš`.

**Comment by oscargus** [comment]
The LatexToUnicode converter correctly detects the command v and argument S (line 153) which it  then looks up as vS in a map generated from stripped versions of the LaTeX command generated in HTMLUnicodeConversionMaps, which should return a String consisting of the unicode character corresponding to 352 (which apparently works for 348 and so on...). An alternative here might be to use combining accents, but that shouldn't really be required and it is better to use the character directly.

**Comment by Siedlerchr** [comment]
@oscargus  I imported your PR as patch (simply add .patch at the url ). Will look at it tomorrow,

**Comment by oscargus** [comment]
The main difference in that patch is that the strings are replaced directly
instead of as regular expressions (which really was just plain strings
anyway), so the list is a bit easier to read. I have not pushed the
additional characters, but you can try other HTML numbers if you easily
want to generate long sequences of characters...

**Comment by simonharrer** [comment]
@Siedlerchr you can also check out any PR see https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by pirlite2** [comment]
This issue is still not fixed! An 'S' with caron _still_ displays as a little rectangle! (Version 3.5 under Mint 17.3).

**Comment by oscargus** [comment]
It is fixed in the current master, so in the next version it shouldn't be
an issue.

There are almost daily improvements of JabRef but at some stage one will
have to release a new version. This was fixed the day after 3.5 was
released.
