### ISSUE TITLE
use the systems default language per default

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#1266]
JabRef version <2.10b2> on <Kubuntu 14.04.3 LTS 32bit>

Steps to reproduce:

1. Install via apt-get from the oficial Ubuntu repros.
2. Start.

Then you can see that "english" is the default language for JabRef.
But this isn't the systems default language.

JabRef should use the systems default language per default.

**Comment by koppor** [comment]
This is [fixed since JabRef 3.0](https://github.com/JabRef/jabref/blob/master/CHANGELOG.md#changed-4) (existing since November, 29 2015). Due to capacity reasons, we do not support the 2.x development line any more. See: https://github.com/JabRef/jabref/wiki/Branches. We are well aware that Java 8 is not that straight forward available at all platforms. Nevertheless, it is possible to install it on recent Linux operating systems.

One can help to get JabRef 3.3 into Ubuntu, if one works on following issues:

 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819669
 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819668
 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819670
 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819672

The alternative is to download the most recent jar file and let this run.

Please understand that we modernize JabRef and cannot support old Java versions any more. A considerable [donation to us](https://github.com/JabRef/jabref/wiki/Donations) or [to Debian](https://www.debian.org/donations) could help to speed up the process upgrading JabRef from 2.x to 3.3 in Debian and Ubuntu.

**Comment by buhtz** [comment]
I can not see an offical download on jabref.org. There is only a download offered by a unknown (untrusted) third-party company (fosshub) not working without javascript. When I have to activate javascript just do make an download-button available...
You could use the release-area of github for example.

**Comment by matthiasgeiger** [comment]
> You could use the release-area of github for example.

... where you can find the download files as well.

**Comment by buhtz** [comment]
Then you should use that as a official Download link.
No one need untrusted third-party Download-Hoster. Even GitHub is discussable enough with its closed source policy.
