### ISSUE TITLE
More advanced support for journal abbreviations

### ISSUE THREAD

**Issue by ikuraj** [JabRef/jabref#1285]
Many of the exported bibtex files (e.g. from DBLP or ACM) contain journal/conference names together with additional information (like the city where the conference was held, year, etc.).

For example:

```
booktitle = {Proceedings of the 2015 {ACM} {SIGPLAN} International Conference on
               Object-Oriented Programming, Systems, Languages, and Applications,
               {OOPSLA} 2015, part of {SPLASH} 2015, Pittsburgh, PA, USA, October
               25-30, 2015},
```

while the conference name is `International Conference on Object-Oriented Programming, Systems, Languages, and Applications`, which should have the following abbreviation

```
booktitle = {OOPSLA},
```

Simple string replace is not sufficient in those cases, while more advanced abbreviation defined with string patterns (e.g. regular expressions) might work.

Would it be worthwhile to support journal abbreviations in such (more complex) cases?

**Comment by oscargus** [comment]
Ignoring that it is a sub-conference, I would define a string `OOPSLA = Proc. {ACM} {SIGPLAN} Int. Conf. Object-Oriented Programming, Syst., Languages, Applicat.` (or slightly more carefully edited), move the location to `address`, date to `month` (or `date` fro Biblatex) and 2015 to `year`. For the subconference, it is not obvious how to handle it. If OOPSLA is always part of SPLASH one can probably add it to the OOPSLA string.

This doesn't really answer your question though, but I am in general surprised to see those type of references which says `Proc. of the 20XX Conf. (YYY 20XX), 20XX`. Seems like it is enough to state the year once and for all.

**Comment by simonharrer** [comment]
Ideas:

- create a checker (Integrity Check) which detects year numbers, locations, page numbers in the booktitle string (should be moved to their appropriate fields) and issue a warning to the user
- give the user a hint which entries cannot be shortened and which can be shortened (so that the user can improve this `.bib` file based on this information so that JabRef can help more

**Comment by kaptoxic** [comment]
Note that other info (like year, location, ...) are still there in the `.bib`, so I think that essentially, instead of having a simple string-replace functionality, having a regexp-based one would suffice.

**Comment by simonharrer** [comment]
The current abbreviation systems works in a completely different way. Instead of being one way (LONG -> short) it supports a round trip (LONG -> SHORT -> SHORTEST -> LONG) so you can always restore the previous information. This would be lost with your approach. 

Your idea could be implemented when using a minimal .bib file which is automatically derived from the normal .bib file. But I cannot find the issue right now in which we discussed this. The idea is to define rules from which one can derive the .min.bib based on the .bib file. The rules could be based on the save actions.

**Comment by matthiasgeiger** [comment]
@simonharrer I think you mean #160.

**Comment by kaptoxic** [comment]
Oh I see, but note there is no inherent reason to have that transformation only one way, since, as per our assumption, all the data is in the bibtex entry anyway (but in separate fields).

**Comment by koppor** [comment]
dblp offers

- with crossref
- standard
- condensed

See e.g., http://dblp.org/rec/bibtex0/conf/zeus/KoppB17

We should support that somehow.

**Comment by koppor** [comment]
I split the issue and ideas in smaller issues. Therefore closing this.
