### ISSUE TITLE
Feature request: format preview using BibLaTeX-files (*.bbx and *.cbx-files)

### ISSUE THREAD

**Issue by domhardt** [JabRef/jabref#1339]
Preview section should be able to render entry according to native BibLaTeX style.

**Comment by koppor** [comment]
Refs #119, because CitationStyles are easier to implement in comparison to Biblatex.

Refs #110, because our BibtexVM can be used to process `bst` styles. In the most cases, the old-fashioned `bst` styles are still the main styles to use. Examples: Springer LNCS (refs https://github.com/latextemplates/LNCS/issues/3), IEEE (refs https://github.com/josephwright/biblatex-ieee/pull/22#issuecomment-206542227), and GI's LNI (refs https://github.com/latextemplates/LNI/issues/1).

**Comment by domhardt** [comment]
Springer LNCS and IEEE seem to be available as BibLaTeX-Sytle too:
- [https://github.com/gvdgdo/biblatex-lncs](https://github.com/gvdgdo/biblatex-lncs)
- [https://www.ctan.org/pkg/biblatex-ieee?lang=de](https://www.ctan.org/pkg/biblatex-ieee?lang=de)
Only GI's LNI is available as old fashioned bst-style.

**Comment by koppor** [comment]
Not officially. The linked LNCS biblatex repo is not recent. There is a
fork, where I contribute. Regarding IEEE, the linked pull request states
that the style is NOT intended to be used at IEEEtran.cls.

I also like biblatex, but please understand that we are asking for pull
requests in this case and focus on other issues.

**Comment by koppor** [comment]
For LNI, there is work in progress at https://github.com/latextemplates/LNI/pull/3

**Comment by koppor** [comment]
Please use a development build from http://builds.jabref.org/master - there is support for citation styles added (see https://github.com/JabRef/jabref/pull/1928). Maybe that helps as workaround.

**Comment by Siedlerchr** [comment]
I think with the more universal support of the CSL styles in JabRef it's superflous to add a biblatex style rendering. Therefore I would vote to close this issue.
