### ISSUE TITLE
Rename INSPIRE into INSPIRE-HEP

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1363]
It seems that the official name for the INSPIRE bibliographic database is in fact INSPIRE-HEP.
Hence, in the web search, it should be renamed.

- https://en.wikipedia.org/wiki/INSPIRE-HEP
- https://inspirehep.net

**Comment by Siedlerchr** [comment]
Against it. Since on the website it is also called INSPIRE without HEP.
Despite that, in the help files it is also mentioned that the search is for the specific physics system.
I do not see a need for renaming it. I am sure most users don't care if its just INSPIRE or INSPIRE HEP
https://inspirehep.net/info/general/project/index

On FAQ:  INSPIRE
https://inspirehep.net/info/faq/general

**Comment by simonharrer** [comment]
Rejected during dev call.
