### ISSUE TITLE
JabRef 3.x default bibtex changed

### ISSUE THREAD

**Issue by leosenko** [JabRef/jabref#1365]
JabRef version <3.3> on <Windows 7.>
There is an inconsistency with the version 2.x of JabRef where the default bibtext key was [auth][year]. It seems to have been changed to [authors3][year] which is undesirable. Further, If I change the new format back to the proper format [auth][year] I get the following nonsense (I do not speak Indonesian, the language should be English as set) - what does that mean?:

![image](https://cloud.githubusercontent.com/assets/3658579/15098812/e7794648-1513-11e6-9fe7-d37a4e0250c5.png)

Steps to reproduce:

1. add a new source
2. geenrate bibtex key
3. the new default is [authors3][year]

**Comment by Siedlerchr** [comment]
I can only reproduce the  authors3, year when I click on the Default button. Changing back to auth, year works fine.

The error message states that you have changed the language settings:
Anda_telah_mengganti_pengaturan_bahasa. =  You_have_changed_the_language_setting.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`. Can you please try the latest build from http://builds.jabref.org/master.

Also, maybe resetting the preferences before changing it again might solve this issue? It could be that some old settings are interfering here.

As for authors3 BibTeX key: I will ask the other developers why this was changed and what we will do about it.

**Comment by koppor** [comment]
Half of the users use the default pattern `[auth][year]`, while the other half uses something else or doesn't care: http://www.jabref.org/surveys/2015/analysis -> "The default key pattern is ok, but the use of another pattern is common"

In my field of research it is common to know the second and the third author, too. Therefore, I personally always changed the default to `[authorsAlpha][year]`. 

The change to `[authors3][year]` happened before 3.0 release at 7a381287184bac3 on 2015-10-10, because we thought that including more authors helps to identify the paper more clearly. The main reason was that there are cases where one main author regularly authors more than one paper a year. Now, these papers should be distinguished. Using the names of the second and the third author is helpful.

I wonder why this comes up now and not earlier.

Since half of the user wants something else than `[author][year]`, I would vote to JabRef to ask for the desired setting when pushing the button "Reset preferences".

For reference: All label patterns: http://help.jabref.org/en/LabelPatterns

**Comment by simonharrer** [comment]
I am against asking the user when resetting the preferences!

Either we leave it at authors3, or change it back to author.
