### ISSUE TITLE
Synchronize PDF highlighted text, comments, and bookmarks

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#139]
[Docear Desktop](https://github.com/Docear/Desktop) has the feature to synchronize highlighted text, comments, and bookmarks from a PDF with Docear. The same should be done at JabRef.

Highlighted text:
![pdfviewer](https://cloud.githubusercontent.com/assets/1366654/9620492/f71985e4-511a-11e5-99db-1607363dae14.png)

Rendering in Docear:
![docear](https://cloud.githubusercontent.com/assets/1366654/9620497/fb3b09e0-511a-11e5-924c-4285fd3da899.png)

(via @Joeran, @Docear)

**Comment by koppor** [comment]
Refs #662

**Comment by Joeran** [comment]
the public docear version of cannot extract "real" highlighted text but only text that is stored in "pop-up" boxes
![image](https://cloud.githubusercontent.com/assets/2410381/15660017/4ae65654-2710-11e6-94d5-87b4773f379a.png)
we recently paid a student to enhance docear, so docear could also extract the "real" highlighted text. unfortunately, the student never 100% completed the job (the new function has some bugs, but they relate mostly to Docear not the extraction of highlighted text itself). 

if you are interested in using that add-on for JabRef, let me know. Otherwise, you are welcome to just copy the functionality from Docear's public repository on GitHub. https://github.com/Docear

**Comment by tobiasdiez** [comment]
This might be helpful: http://stackoverflow.com/questions/33253757/java-apache-pdfbox-extract-highlighted-text

**Comment by lenhard** [comment]
Now tracked in  #2545.

**Comment by lenhard** [comment]
#2545 is merged now, so we can display pdf comments and highlighting.

Hence, I am merging this issue.
