### ISSUE TITLE
Journal abbreviations dialog mock up for JavaFX port

### ISSUE THREAD

**Issue by boceckts** [JabRef/jabref#1396]
I want to port the journal abbreviations dialog to JavaFX. When playing with the dialog I first I didn't understand what everything meant. It was quite confusing why there were 3 sections - JabRef internal list, personal list, external list. Why can I only have one personal list? Why can't I edit the external lists? Why do I need different windows to view external lists or JabRef internal list? What does the download button do since there is no hint in the dialog itself and is it really necessary to have it? Therefore I thought when porting the dialog I could also redesign it. The following dialogs mock ups concentrate all the different lists in one place and treat them as the same.

The first mock up treats all lists the same, a user can set up multiple personal journal lists or open some from this hard drive. The user can also edit any journal list (except the JabRef internal journal list). Also entries in the lists should be able to be edited instead of deleted and then added as new.

![journalabbreviationsnewnew](https://cloud.githubusercontent.com/assets/15340757/15244225/5f562998-1900-11e6-87df-c87663e69141.png)

The second one treats the JabRef internal journal list as non editable and has to be viewed through a different window. Other lists will be shown in the top list.

![journalabbreviationsoldnew](https://cloud.githubusercontent.com/assets/15340757/15244226/5f59951a-1900-11e6-95b0-a142717b4ceb.png)

**Comment by boceckts** [comment]
@JabRef/developers some feedback would be appreciated.

**Comment by tobiasdiez** [comment]
I really like the idea to unify the ui for all abbreviation lists, so I prefer the first mockup.
What I don't like are the buttons on the right side. In my opinion, these should be integrated into the list. 

Some suggestions:
- I would replace the first list with a drop-down list so that it is clear which journal list the user is currently editing
- Switch order of Save and Cancel button, because the default one should be "Save"
- Make the help button a bit less dominant.

So I would propose:
![Image](https://jabref.mybalsamiq.com/mockups/4555701.png)
https://jabref.mybalsamiq.com/projects/ui/Journal%20Abbreviations

**Comment by Siedlerchr** [comment]
The mockup of @tobiasdiez  looks nice. One thing we should think about is wether we allow editing the Abbrevation direct in the Table or open it in a new window.

**Comment by koppor** [comment]
I also like the mockup of @tobiasdiez. The "view" button of @boceckts means "show source"? Maybe we could link the GitHub repo for the internal list. The others are just plain text imported files.

In this context, I want to remind of the important feature request https://sourceforge.net/p/jabref/feature-requests/731/.
