### ISSUE TITLE
No visual feedback for pasting when having a filtered view

### ISSUE THREAD

**Issue by ziggystar** [JabRef/jabref#1404]
JabRef version 3.3

Steps to reproduce:
1. Apply a filter by typing something into the search box.
2. Copy a bibtex entry (`[Ctrl-C]`) that you want to insert into your database (and that doesn't match the filter).
3. Paste the new entry via `[Ctrl-V]`.
4. Do it again because you receive no feedback that it worked.
5. Repeat step 4 some more times.
6. Clear the filter rule and see that you have inserted ten copies of the same entry.

I'm not sure about the correct resolution of this problem. Here are some ideas.
- exit filter view on pasting
- make some hacky stuff to show the new entry despite the filter hides it
- show a popup that asserts that the entry has been inserted
- show a popup that asks about clearing the filter, and asserts that the entry has been inserted

**Comment by matthiasgeiger** [comment]
Thanks for your report! 

I can reproduce this behavior and I'm also not happy with it. :wink: (Although, there is a note in the status bar "Pasted 1 entry" - but it is rather easy to miss.)

In my opinion your last suggestion is the best one: Just show a "warning" that the pasted entry is hidden by the filter - with an option to remove the filter.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
Thanks for your report.! We recently migrated the UI of JabRef to JavaFX. Therefore, we need to reevaluate all issues targeting the old Swing UI. Feel free to reopen, if the problem persists with the new JavaFX UI.
Download the current development version at http://builds.jabref.org/master/
