### ISSUE TITLE
Positioning of variables in GUIGlobals

### ISSUE THREAD

**Issue by lenhard** [JabRef/jabref#1408]
I am currently doing some architecture analysis of JabRef and stumbled into some part of the code that I'd like to discuss. 

We have the infamous class `GUIGlobals` in which several settings are hard-coded as public static instance variables. I noticed that some of these variables are only used in a single other class, thereby creating a dependency of that class to the gui package (which is very ugly). Example: The class `LatexFieldFormatter` is the only user of `GUIGlobals.LINE_LENGTH`, which prohibits the moval of `LatexFieldFormatter` into the `bibtex` package and makes that package transitively dependent of the `gui` package. Ultimately, if we fix this class and this dependency we can make the `bibtex` package completely self-contained and move it into logic. 

Several other variables in `GUIGlobals` are just used in a single other class. Therefore, I propose to move the variables closer to the scope of their usage where possible. This destroys `GUIGlobals` as a single point of configuration, but also improves our package dependencies. @JabRef/developers Are there objections to this?

**Comment by tobiasdiez** [comment]
:+1: for removing GUIGlobals.

**Comment by Siedlerchr** [comment]
Yes, I fully agree with removing Globals. Maybe you can also check for obsolete  Settings/Variables.

**Comment by simonharrer** [comment]
Also think about whether they still make sense. Why do we need a line_length in that case anyway?

**Comment by lenhard** [comment]
Ok, will do. @simonharrer: Honestly, I have no clue. But it is sometimes hard to decide if something still makes sense or not.

**Comment by koppor** [comment]
I would not refactor just because ofa metrics value getting better.

Half of the values (such as `INDENT`, `NUMBER_COL_LENGTH`, `EXPORT_DIALOG_COL_0_WIDTH`) look like configuration variables. We had the feedback that one main value of JabRef is the plethora of configuration options. I don't know whether these values also fall in that category or whether we should reduce the configuration options.

I'm unsure whether we should switch to [Apache Commons Configuration 2.0](https://commons.apache.org/proper/commons-configuration/), where I really liked the 1.x series and the 2.x series seems even better.

Back to topic: For each value, it should be decided if it's a configuration option or if it's just a constant to gain code readability.

For the former, we should move it to our configuration thing, for the latter, we should move it to the appropriate places.

Beware: A configuration thing could also be used at one place only, but it really makes sense to have it stored at a central place to make users and programmers aware that this can be configured. `GUIGlobals.LINE_LENGTH` seems to be such a candidate.

If we want to keep that we programmers can configure JabRef code wise, we could introduce a new `Configuration` class or add it to our class `net.sf.jabref.Defaults`.

Side comment: The whole configuration of [dwm](http://dwm.suckless.org/) takes place in the source files, not in ASCII configuration files.

**Comment by lenhard** [comment]
@koppor: The thing is, all this stuff is not a configuration option, but a constant. The values are hard-coded and the variables themselves get eliminated and inlined during compilation. There is no position in the code that modifies their value and very often there is only a single line of code that reads their value. This applies to `GUIGlobals.LINE_LENGTH`, which is only read in `LatexFieldFormatter`. Despite its important sounding name, the variable matters to no other class in all of JabRef. Hence, it makes sense to move these variables closer to their actual usage.

Just as a side note: This is not about metric values, but about the dependency tree of the system, which is arguably much more crucial.

**Comment by matthiasgeiger** [comment]
> Because dwm is customized through editing its source code, it’s pointless to make binary packages of it. This keeps its userbase small and elitist. No novices asking stupid questions.

@koppor ? :wink:

**Comment by simonharrer** [comment]
@koppor has a point there. Whether it is a hard coded or dynamically loaded configuration option makes no difference when creating a class to configure the GUI. As long as the configuration options are still used they should reside in a single place, same as JabRefPreferences, so they can be made dynamically configurable if necessary later on. Otherwise, they will be scattered all over the app through inlining them.

**Comment by lenhard** [comment]
@simonharrer: Maybe this should be decided on a case by case basis. Please have a look at #1409 and tell me if you feel that a certain variable is important enough to warrant a global scope.

**Comment by simonharrer** [comment]
This is really hard to review. Next time, please inline each variable in a separate commit so one can see its usages separately. 

OK:

- BACKUP_EXTENSION
- FRAME_TITLE
- EXPORT/IMPORT_DIALOG_*
- NUMBER_COL_LENGTH 
- TABLE_ROW_PADDING

NOT OK

- Colors: I would leave the colors there, as they have the potential to be made a config options and be used by multiple classes
- Same holds for the variables controlling any output, e.g., indent or line_length - either remove them or leave them as configuration possibilities. Maybe even create preferences for them. 
- WIDTH_ICON_COL is used by multiple classes and in the gui globals, but WIDTH_ICON_COL_RANKING is inlined. This, I think hides their dependency between them (one being the special case of the other). 
- MAX_BACK_HISTORY_SIZE  seems to be an interesting setting which should not be hidden in some class underneath, but brought to the light/user/developer in some way.

**Comment by lenhard** [comment]
Oh come on, seriously? On another occasion, I have been told (by @koppor I think) that I should squash all commits of a PR into a *single* commit instead of a series of commits. I am at a loss, now what is our policy?

Concerning the remarks: Will do!

**Comment by matthiasgeiger** [comment]
Single commits for [WIP] which will then be squashed (using the GitHub-Squash-Button-Feature)?

**Comment by koppor** [comment]
Meanwhile, I learned that squashing is (mostly) obsolete, because GitHub
can squash and also offer reviewing all changes at once... 😇

Nevertheless, directly related commits (fixup, var renaming, ...) not
having a value being separated for reviewing should be squashed :innocent:

**Comment by lenhard** [comment]
Ok, thanks for clarifying this! I turn back to making commits as atomic as possible (keeping things like the renaming or moving of a variable in one commit of course)

**Comment by lenhard** [comment]
Implemented with #1409
