### ISSUE TITLE
Should we remove the possibility to sort the file links?

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1418]
![image](https://cloud.githubusercontent.com/assets/2141507/15396010/75658e52-1dda-11e6-8d41-7f67dc44546e.png)

Should we remove the possibility to sort the file links? What does this function really do? It just has influences on the opening of files when clicking on the icons in the main table when multiple files are linked?!

![image](https://cloud.githubusercontent.com/assets/2141507/15396038/963a0036-1dda-11e6-9fee-6ab1b8905597.png)

However, I think (as discussed with @matthiasgeiger ) we should change the behavior here, so that if multiple files are linked the righklick menu with all files gets shown as left click. otherwise, there should be no right click menu and left click just opens the file.

![image](https://cloud.githubusercontent.com/assets/2141507/15396095/d306c2a6-1dda-11e6-9c7b-b29a4536a572.png)

**Comment by tobiasdiez** [comment]
Sounds reasonable. :+1: for removing sorting and changing the right/left click behaviour

**Comment by simonharrer** [comment]
I am against this, as one normally has a primary file plus some secondary ones. I want to work quickly with the primary one 99% of the time. This would make the 99% case more problematic, and the 1% case more easily.

**Comment by mlep** [comment]
I second @simonharrer  for keeping this feature, for the exact same reasons.

**Comment by stefan-kolb** [comment]
I can understand your reasons here. Maybe keeping the order still makes sense.

But what about the other thing? Making left click behave like rightklick for multiple documents?
Makes it clearer that there are multiple docs that can be opened. Still it would add one more click...

**Comment by mlep** [comment]
I am used (JabRef, Thunderbird, LibreOffice, etc.) that a left-click does an action directly (select/open/etc.), while a right-click displays a list of (menu) items. So the current behavior seems to be the standard behavior.

Maybe the issue here is about the graphic design: the icon should look more like an button, so that users know instinctively that this part of the entry table is "special" (i.e. does more than selecting the entry)

Note: Whatever you decide, obviously, the URL/DOI column should look/behave like the "file" column.

**Comment by simonharrer** [comment]
@stefan-kolb still, the 99% case is to open the primary document as quickly as possible using a left click. Having a right-click which opens the different documents would seem ok to me.
