### ISSUE TITLE
Unreadable Russian text in Windows installer

### ISSUE THREAD

**Issue by Johnssm** [JabRef/jabref#144]
When I runs JabRef-2.10-setup.exe, downloaded from this site, there are two screens with unreadable text appears (I bound it with red line):
1. Greeting screen 
![screenshot1](https://cloud.githubusercontent.com/assets/14159451/9713172/d6fdefbc-5579-11e5-8dbc-fc78c0fd3366.jpg)

2. Components selection screen
![screenshot2](https://cloud.githubusercontent.com/assets/14159451/9713175/dd76c062-5579-11e5-8533-4f24792b0648.jpg)

I Use Russian version of Windows 7 x64 SP1.

P.S. There is same issue in JabRef-2.11b3-setup.exe

**Comment by simonharrer** [comment]
Problem is among others the Key `WelcomePageText` in `buildres/nsis/installer_languages/russian.nsh`.

**Comment by matthiasgeiger** [comment]
Note: Check whether nsis is capable of UTF coded language files. Maybe switching to http://www.scratchpaper.com/ which is a dedicated Unicode installer based on NSIS is necessary.

**Comment by matthiasgeiger** [comment]
Problem is indeed the UTF8 encoding of the russian language file. 
Two possible solutions: 
a) *Use NSIS 3:* Since NSIS 3 beta the usage of Unicode is possible and the cyrillic letters are displayed correctly. However, as this is still a beta the artefacts are not available using the default package repositories - so the circleci builds (which use nsis 2.46) will fail. 
b) *Change Encoding to Windows-1251:* If I got it right, the default encoding assumed by NSIS for russian installers is "Windows-1251" - I changed the encoding of the file accordingly - but as the installer autodetects my machine as "German" I'm not able to test whether the installer now works fine...

@Johnssm Can you please check the installer created during the latest build here: https://circle-artifacts.com/gh/JabRef/jabref/443/artifacts/0/home/ubuntu/jabref/build/releases/JabRefSetup.exe
Are the russian characters displayed correctly here?

**Comment by Johnssm** [comment]
Hi.

I runs the installer on Windows 7 SP1 with Russian locale. Encoding is correct. There is a little problem on Welcome Screen – some text is trimmed by another (Screenshot1.png). Components selection screen is quite correct (Screenshot2.png).

**Comment by matthiasgeiger** [comment]
Hi @Johnssm,
unfortunately Github does not show your mail attachments. Would you please upload them here.
Thanks in advance!

**Comment by Johnssm** [comment]
There is a little problem on Welcome Screen – some text is trimmed by another. Perhaps it's due to big length of the version number.
![screenshot1](https://cloud.githubusercontent.com/assets/14159451/9761732/b3b51a0c-5728-11e5-855d-0b002ddf3202.png)


Components selection screen is quite correct 
![screenshot2](https://cloud.githubusercontent.com/assets/14159451/9761681/74962a78-5728-11e5-8394-b59a12deb596.png)
.

**Comment by matthiasgeiger** [comment]
Okay - this is another problem (in this Snapshot build the version number is too long to be displayed correctly) which will not be any issue in the next "real" release.

As the original bug is fixed I will close this issue.
Thanks again for reporting this bug!
