### ISSUE TITLE
Issue when searching a regular expression

### ISSUE THREAD

**Issue by olivierfruchart** [JabRef/jabref#1505]
JabRef version 3.5dev 2016-06-14 on Windows 10

In the search textbox if one types keywords="dzy", then I expect that entries are shown only if there is at least one keyword with this exact sequence. Instead, entries are also select, if one keyword contains a "z", another one a "d" and one with a "y". This behavior remains whetever the search options checked, regular expression on or off.

**Comment by Siedlerchr** [comment]
Hi, thanks for your report.
In the 3.4 release  on Win7 it works accurate.
Having one entry with keyword dzy and other entries with keyword "d" and "z"  and using your search terms it correctly  displays only one result.

Did you check the Float/Filter Option in the Search?
It can either hide all other entries or just gray them out. Maybe this is the problem?

**Comment by olivierfruchart** [comment]
Hi, thanks for the feedback.
I finally found out the problem. Entries with a tag always appear at the top of the list in the 'float' mode, even if they do not fit the search. In the 'filter' mode they are not visible, which is more consistent. Thus it is not a bug but rather an annoying feature. In my view, tagged entries not fulfilling the search may appear first atop the grayed items, however not at the very top.

**Comment by matthiasgeiger** [comment]
Thanks for your feedback!
Yes, if the option "Float marked entries" is activated in the prefs ("Entry Table" tab) the entries are still floating even if they do not match the active search.

@simonharrer I think that @olivierfruchart is right: The marking entries should placed beneath the search hits. WDYT?

**Comment by simonharrer** [comment]
Yep, this seems to be a bug.

**Comment by ajbelle** [comment]
Although this is closed I post here as a user report as I think my experience on Win7 JabRef 3.5 is related to the “uncertain” search nomenclature that is required.  Also issue #1505
regarding the apparent heterogeneous regex-regular expression implementation seems involved. IMHO being able to search reliably IS ESSENTIAL and of high priority for large database situation, and it is one of the poorest features in JabRef.
I was attempting to do a general search with a specific exclusion (word1 and not word2) and conclude that at best the current help files [(http://help.jabref.org/en/SearchHelp)] and [(http://jabref.sourceforge.net/help/SearchHelp.php)] for JabRef `Search` are misleading and incomplete. The poor search behaviour (explanation) has been present within JabRef for years.

Hover-over the search entry shows the full logic in words. This is a great feature, but doesn't seem to reflect what the help file suggest is should, or what the search seems to do.
""word1 and not word2""  selects all entries and highlights all those words including 'and' and 'not'.
""word1 not word2"" selects all entries and highlights all those words including 'not'.

If I enter "word1 and not field2=word2""  eg: "flow and not memo=PhD" search totally fails with hover-over showing "... flowand and  not and memo=PhD"  It appears to not recognise the and, instead ignoring the space and adding it to the word, then inserting extra ands!

I concluded the algorithm has be rewritten to look for "Field2=word1...Field2=word2..." but how do you specify to search all fields for one of the statements? 

From the helpfile the following should work
 title|keywords = "image processing" 
 title--keywords = "image processing"  but neither works.
 eg: (author = miller or title|keywords = "image processing") and not author = brown cut and paste from the help file does work (neither with a hyphen or a double hypen)

Interestingly `Search` automatically decides content in a non-regex entry is regex, but it doesn't seem to work.
A very useful trick to solve my composite search on all fields requirement would be .* =flow . The hover over pop-up states that "any entries in which the field matching .* contains the word flow"." however this does not do this in practice.  Note this is assuming JabRef can handle a multi part search with sections being taken as regex and others as regular instructions (I suspect it is simpy auto switching to complete regex).

entrytype=Phdthesis where = means contains works
entrytype!=PhD where != means does not contain works
entrytype==Phdthesis  where == means is exactly works
"word1 word2 word 3" where "" indicate a string works

Bracketing doesn't work at all as I expect from the help files. Spaces before and after words change the hover-over displayed meaning with `and` being added in seemingly random places.

I expect the majority of my tests are not bugs and due to different logic of the programmers exacebated by the limited examples/guidance given in Help. If so could this be a request for clearer and more complete help file please.
