### ISSUE TITLE
Link to online help does not exist

### ISSUE THREAD

**Issue by Alfonsib** [JabRef/jabref#1509]
Hi!

I use latest release of JabRef (3.4, x64). Until the 2.x series, JabRef installed its help with the program. It seems to have been replaced with an Online help link, which does not work on my system (Win7 Pro SP1). What can be done?

**Comment by koppor** [comment]
What does "not work on my system" mean? Is the browser opened? Which page is displayed in the browser?

Due to other planned support channels, we reconfigured our DNS entries and it seems that help.jabref.org had DNS issues. I just fixed it. DNS usually takes 24 to 48 hours to update. Could you check again in a few hours?

1. Open http://help.jabref.org/ in your browser.  Does the following page appear?

![grabbed_20160622-075947](https://cloud.githubusercontent.com/assets/1366654/16256045/5074e036-384f-11e6-9722-4ac42b16f8b0.png)

2. Click Hep -> Online help in JabRef. Does the browser open? Does following page appear?

![grabbed_20160622-080106](https://cloud.githubusercontent.com/assets/1366654/16256066/7dc1c3c4-384f-11e6-9791-8975a02e4940.png)

**Comment by stefan-kolb** [comment]
I recently added a test that all help links are available (return status 200), so this should normaly work...
