### ISSUE TITLE
Consistent casing of file types. Best practice?

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1558]
Currently the naming of file types is quite inconsistent: PDF, pdf, Zip, ZIP, AUX, aux, etc...

I'm not sure if I have a strong opinion here, but it would be nice to have it consistent.

Also, one one occasion it says `.bib file`, i.e. a dot before the file ending. Some of them have a dash, like `Zip-archive`.

Any opinions on the correct way of doing it? Lower case, except when starting a sentence, without a leading dot and no trailing dash?

**Comment by lenhard** [comment]
I agree that this should be consistent, but have no strong opinion in which way. We should probably just reach an agreement during a devcall and document that.

**Comment by simonharrer** [comment]
What a nightmare to rename all this with git+windows :(

**Comment by koppor** [comment]
Can this be done using `sed/s/zip/ZIP/g *.properties` with a review using git gui and line-based adding to index?

**Comment by matthiasgeiger** [comment]
During the dev call we were not quite sure what the general scope of your question is @oscargus 

The general rule of thumb should be:  the extension alone should be used in lowercase - if used in a sentence/context uppercase should be used ("Please select a PDF file"). 

An example for this is the manage file type dialog:
![filetypes](https://cloud.githubusercontent.com/assets/676652/17129450/8005d844-5313-11e6-9b8e-59137af36cdf.png)

**Comment by oscargus** [comment]
Makes sense. I should have been more clear. These are some examples of current strings:

```
Follow_DOI_or_URL_link_and_try_to_locate_PDF_full_text_document
No_meta_data_present_in_bibfile._Cannot_regenerate_BibTeX_keys
Ill-formed_entrytype_comment_in_bib_file
The_Zip-archive_need_not_be_on_the_classpath_of_JabRef.
Add_from_jar
Always_reformat_.bib_file_on_save_and_export
AUX_file_import
found_in_aux_file
Use_the_bib_file_location_as_primary_file_directory
Autogenerate_PDF_Names
```

The "correct" should be
```
Follow_DOI_or_URL_link_and_try_to_locate_PDF_full_text_document
No_meta_data_present_in_BIB_file._Cannot_regenerate_BibTeX_keys
Ill-formed_entrytype_comment_in_BIB_file
The_ZIP_archive_need_not_be_on_the_classpath_of_JabRef.
Add_from_JAR
Always_reformat_BIB_file_on_save_and_export
AUX_file_import
found_in_AUX_file
Use_the_BIB_file_location_as_primary_file_directory
Autogenerate_PDF_Names
```
?

**Comment by lenhard** [comment]
@oscargus Yes, that is correct.

**Comment by oscargus** [comment]
Most (all?) of this is fixed in #1629.

**Comment by tobiasdiez** [comment]
I know I'm a bit late to the party, but I'm not completely satisfied with `BIB file` and `AUX file` and thought that we arrived at a different result in the dev call. Speaking of a `PDF file` kind of makes sense if one think of it as an abbreviation of `a file which is in "Portable Document Format"`. Hence one uses `PDF` as an acronym. But for `BIB file` there is no such interpretation. What is really meant is a file with ending ".bib". Note that a similar remark also applies to `ZIP`, which is why [wikipedia](https://en.wikipedia.org/wiki/Zip_(file_format)) uses a preceding dot everytime (i.e `.ZIP archive`).

On the other hand, `.bib file` is kind of ugly in my opinion. Thus in summary I would propose to always use `bibliography / bibliographic file` and `auxiliary file`. If one really wants to emphasize that a file with `bib` ending was meant, then `bibliography (.bib file)` would make sense.

**Comment by Siedlerchr** [comment]
Just my 0,02€, we should not spend too much on this, as I doubt that the normal user really thinks about if it is now BIB or bib or whatever.

**Comment by matthiasgeiger** [comment]
I agree with @Siedlerchr and close this again :wink:
