### ISSUE TITLE
CLI mode does not work with .exe

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#1600]
JabRef version 3.5 on Win10

Steps to reproduce:

1. Try to run some CLI commands, e.g., `jabref -h`
2. nothing is displayed

(works fine with the jar: `java -jar JabRef-3.5.jar -h`)

Caused by install4j? Can we fix this or should we document that the CLI mode is only supported using the jar?

**Comment by stefan-kolb** [comment]
The installer allows to configure the app launcher as GUI or Console, but not both.
it is possible to set a `-console` flag so that the standardoutput gets redirected to the console.
Somehow theres a function for command line parameters (http://stackoverflow.com/questions/29751721/is-it-possible-to-pass-through-commandline-parameters-to-the-execute-launcher) but I haven't found out how to pass them through the launcher.

Maybe it is a good idea to separate the console program from the GUI program with this issue. So two different executables?

**Comment by stefan-kolb** [comment]
You can try out a version from the `comsole` branch. http://builds.jabref.org/comsole/
If you use `JabRef -console` the console mode gets launched. At the moment it breaks, as we do not recognize this option internally. You can then pass all normal options like `Jabref -console -h`. it behaves a little wierd as it "restarts" a new command inside the prompt but kind og emulates the console behavior. I'm not sure if we can work on from that. Still thinking about extracting the console to another jar/exe would be best.

**Comment by matthiasgeiger** [comment]
Adjust documentation to indicate that CLI mode should only be used with jar

**Comment by matthiasgeiger** [comment]
Done.

**Comment by lenhard** [comment]
Let me add that the console works in principle, there is just now output. For instance, it is possible to use the aux export feature with the 3.6 exe just fine, e.g.: `JabRef.exe -n -a main.aux,test.bib references.bib` will create `test.bib` (supposing the others exist), but there will just be no output.
