### ISSUE TITLE
Latex code in groups

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1681]
JabRef version 3.5 on Windows 10

Steps to reproduce:
1. (Main menu) Groups
2. Toggle groups interface
3. Automatically create groups for database (Magic wand symbol)
4. Generate groups for author last names
5. (Some) Group entries are created in Latex code (example: B{"{o}}hmer)
6. Selecting entries fails (no result)

**Comment by oscargus** [comment]
I tried this now and to me it works (current development version, but I do not see that anything should have been fixed since 3.5). I'm wondering if it related to how the names are written? To me, the following works: `Palom\"aki`, `Curtic\u{a}pean`, `P\'{a}pay`, `K\"{a}llstr\"{o}m`. After doing Latex -> Unicode -> Latex it also works for `Curtic{\u{a}}pean`, etc.

Do you have the number of entries showing? Are there any entries in the group you selected? (Groups settings button.)

**Comment by grimes2** [comment]
Show number of elements is off. Toggling Show number of elements and then automatically generate groups generates also Latex code groups, but these Latex code groups are now filled with elements. Strange!

**Comment by oscargus** [comment]
OK, I think I found the reason. The groups are not loaded correctly. So while the generate group contains ` B{\"{o}}hmer`, the loaded group contains `B{"{o}}hmer` (despite being saved as `B{\\\\"{o}}hmer`). I mark this as a bug and hope that someone with more insight can sort it out.

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
