### ISSUE TITLE
"Upper Each First" should not case all words

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#169]
According to the [German Wikipedia Article on Headings](https://de.wikipedia.org/wiki/Gro%C3%9Fschreibung#Gro.C3.9Fschreibung_in_.C3.9Cberschriften), not all words are written in upper case in titles. I would suggest to change the behaviour of "Upper Each First" accordingly or to implement an additional "Change case" functionaltiy.

**Comment by matthiasgeiger** [comment]
Is already there in https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/logic/util/strings/CaseChangers.java - class TitleCaseChanger ?

**Comment by simonharrer** [comment]
See https://sourceforge.net/p/jabref/feature-requests/847/

There is a feature request to improve the title case changer even further. We are open to pull requests for this. :)

I propose to close this issue. Any objections?

**Comment by koppor** [comment]
The TitelCaseChanger should be wired to the "Case change" menu somehow. Is there another way to reach "TitleCaseChanger"?

The improvements suggested by Ben Heuwing at https://sourceforge.net/p/jabref/feature-requests/847/#0810 are not tracked anywhere else and the ticket itself is closed. :disappointed:

**Comment by oscargus** [comment]
This issue made me set up a build environment again. However, I have not completely figured out how to work with GitHub yet. I've forked to my GitHub-account, got a copy of that on to my laptop but the reverse process may take a bit more time to figure out... :-)

Anyway, I've improved this a bit, with more words that shouldn't be capitalized, but the problem is that there isn't a single way to write title case. Especially, some publishers (APA and IEEE at least) capitalize all words with more than three characters (basically, I guess, to avoid the confusion that some words are sometimes prepositions, which shouldn't be capitalized, sometimes major words, which should). How do you recon we should go about with that? Have two different TitleCaseChangers?

In addition, I made sure that words within brackets are kept as is for all CaseChangers.

The things that remain are making sure that the first word after ":" is capitalized and that both parts of a hyphenated word is capitalized (such as "First-Time GitHub-User").

**Comment by matthiasgeiger** [comment]
Great!
[Here is a link to the official GitHub Help](https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/) regarding "Pull-Requests" which is the standard GitHub way to contribute to JabRef after you have pushed the changes to your fork. 
We will review your work and can than merge it into the project codebase.
If you should have any questions or trouble just contact us!

**Comment by koppor** [comment]
The other page is https://help.github.com/articles/using-pull-requests/ (which is also in our CONTRIBUTING.md). I wonder why these two pages are not cross-linked. I also cannot decide which page is better. Should we link both in our CONTRIBUTING.md?

**Comment by oscargus** [comment]
Thanks! The problem is more how to use GitHub Desktop or Eclipse as Git client. I was quite familiar with SmartGit, but somehow that ceased to work. Also, I do not really understand how to update my fork from JabRef, but forking again is quite OK at the moment. :-)

Now, I just pasted the changed file into the web browser and edited ChangeLog there as well. Hence, the two commits in my PR.

**Comment by koppor** [comment]
@oscargus Updating your fork on github? Just cloning it and pushing back to origin doesn't work? Or maybe, I did not get your question. We can also continue discussing that on gitter ^^.

**Comment by simonharrer** [comment]
https://github.com/JabRef/jabref/pull/215 now handles protected chars.

**Comment by koppor** [comment]
For the record: #176 was a first attempt to solve the issue. https://github.com/JabRef/jabref/pull/176#issuecomment-142723792 states some test cases. #215 is an improvement. Discussion whether we should support edge cases is still going on at #215.
