### ISSUE TITLE
Support Native filedialogs (JavaFX only)

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1711]
Currently the jFileChooser in Swing does not show a native file dialog.
However, JavaFX does. 
With the new implementation in #1336 a further change is made easier.
Steps to consider:
- [ ] Investigate if JavaFx FileChooser supports all relevant methods needed
- [ ] Integration into Swing dialogs

http://docs.oracle.com/javafx/2/ui_controls/file-chooser.htm
http://javafxtuts.com/javafx-file-chooser/

**Comment by tobiasdiez** [comment]
Good idea and should be definitely done (after migration to javafx happened).

**Comment by jdpipe** [comment]
That would be great. On Windows 7, with Jabref 3.7, everything looks good enough. But on Ubuntu 16.04, the Java file dialog is aweful, very hard to navigate using keyboard and quite awkward. 
There must be ways to link to the GTK file chooser somehow, perhaps this JavaFX thing will do that for us? http://java-gnome.sourceforge.net/doc/api/4.1/org/gnome/gtk/FileChooser.html

**Comment by jdpipe** [comment]
Hi Tobias

I tested the 'javafx' build (JabRef-4.0.0-dev--snapshot--2017-03-12--master--f0d79f876.jar) and it worked well. However, I did have to install some openfx packages on my machine first. Without those packages, there is just a cryptic message "Error: Could not find or load main class org.jabref.JabRefMain".

This raises a question -- with JabRef .jar package now topping 50MB, is there any prospect of some kind of lighter .jar that makes more use of the packages available on our machines? On Ubuntu, somebody from time to time re-packages Jabref into a much smaller 4 MB package (nice) but it obviously must be difficult, since it hasn't been updated beyond JabRef version 2.10.

Cheers
JP

**Comment by Siedlerchr** [comment]
Hi JP,

thanks for testing. As we are switching to the new gui technology JavaFX, it requires the openjfx package.
Since a while the JabRef Version 3.8.2 succesfully is integrated into debian experimental and of course we hope to integrate the 4.0.0 version there one time, too.
https://packages.debian.org/experimental/jabref

At the moment the 4.0.0 is still under development, so we only provide the fat-jar files, which are automatically build from the CI server

Regards
Christoph

**Comment by koppor** [comment]
I hope, our installation page covers that, doesn't it?
https://help.jabref.org/en/Installation

Am 13.03.2017 09:17 schrieb "Christoph" <notifications@github.com>:
