### ISSUE TITLE
Wrong usage of BibEntry field `id`

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#1721]
The field `id` in `BibEntry` is the internal ID used by JabRef and **NOT** the bibtexKey (which is set using (`setCiteKey(...)`). Moreover, the ID should be unique.

However, a lot of the importers and also at other spots either the bibtexkey, or a fixed value is used to set the ID.

I'm not sure whether this is already causing real trouble, but it is at least a source for potential bugs if we rely on the uniqueness of the IDs somewhere in the code.

Thus: `setId()` and the constructors of `BibEntry` should always use `IdGenerator.next()` to create a valid, unique ID value.

**Comment by oscargus** [comment]
I think it is only `EntryFromPDFCreator` that actually does something wrong (the remaning search hits on "id" in importers is the "id" field in the import rather than the entry field, at least after a quick search). I fully agree with you that there should be no disadvantages and only advantages that the constructors handles the id (I do not even see the purpose of `setId()` then, all other uses of `setId()` just gets the next id anyway).

**Comment by oscargus** [comment]
It would probably be good to do the corresponding changes in `BibtexString` as well.

**Comment by tobiasdiez** [comment]
As far as I know the id is used only in two places:
- keep the order of bib entries when writing the file (IdComparator or something like this)
- sync with external database

I'm not sure, but I kind of remember that the recent database sync redesign introduced another id field. If this is the case, then I would propose to remove the old id completely.

**Comment by oscargus** [comment]
Also: detect circular referencing when resolving strings.

**Comment by oscargus** [comment]
There is another potential use case: when clicking on an entry in the integrity check dialog the entry is selected based on BibTeX key. Here it would be better to select it based on Id  (although of course show the key as now).
