### ISSUE TITLE
ArXiv fetcher seems to be broken

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1776]
Check current builds. https://travis-ci.org/JabRef/jabref/builds/153277476

**Comment by Siedlerchr** [comment]
Mabye not our fault:
`arXiv.org will be down for maintenance August 18th 2016 from 8:20am to 9:20am EDT. To view articles please use the mirrors. The submission system and user log-in will be unavailable during the maintenance time.
`

**Comment by Siedlerchr** [comment]
Update: It's a jabref problem. Server Response is okay (did a quick capturing with wireshark)

**Comment by tobiasdiez** [comment]
Yes, it is a problem with JabRef. The query
http://export.arxiv.org/api/query?search_query=ti:"slice theorem for Frechet"
works fine. Maybe there is a problem with the accents, since
http://export.arxiv.org/api/query?search_query=ti:"slice theorem for Fréchet"
results in a bad response. However, accents should be stripped https://github.com/JabRef/jabref/blob/5fdb61f6577d0801218cf779fadffb13902b1477/src/main/java/net/sf/jabref/logic/importer/fetcher/ArXiv.java#L170. I have no time for further investigations, sorry.

**Comment by Siedlerchr** [comment]
3.5 works fine when entering an identifier.
Only entering words does not work.

**Comment by Siedlerchr** [comment]
Our Cookie Handler class should be removed.
When I remove/comment out the usage of our cookieHandlerImplemenation then arxiv works again...

**Comment by stefan-kolb** [comment]
Strangely enough the build is working again...

**Comment by Siedlerchr** [comment]
Makes one believe in supernatural things going on here ;) Especially on travis...
Nonetheless we should get rid of that Cookie class.
