### ISSUE TITLE
Wrong table background color in author/editor field

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1795]
JabRef 3.6dev--snapshot--2016-08-19--fix-scholar-encoding--b3671a0
windows 10 10.0 amd64 
Java 1.8.0_101

In entrytype article author is a required field. The background color for required fields should be grey. But the color of the author field is white. (Default color codes are activated)

**Comment by oscargus** [comment]
A guess: your column is actually showing "author/editor"? I had a look at the code the other day, but couldn't figure out how to deal with it with multiple fields.

**Comment by grimes2** [comment]
That's bad. So the coloring doesn't make sense. By the way, the editor field in entrytype book is also a required field.

**Comment by oscargus** [comment]
There is an easy approach:

* check if any of the fields in a column are required, in that case mark it
as required (similar to optional, but with priority for required).

The problem is the potential confusion if the article has an editor, but
not an author. Then it looks like the mandatory field is filled, but it is
not. The option of having white background in that case may also be quite
confusing (and I do not think it is so easy to implement at the moment
since code selecting the background does not know which field is actually
returned, although that can probably be sorted out).

As long as one can find an OK behaviour, covering "all" cases, it should
most likely  be quite OK to actually implement it.

(If only tooltips worked one could use that to clarify...)

**Comment by grimes2** [comment]
I have now removed these combined fields author/editor and journal/booktitle. I have removed editor, because it is for me of minor interest and I made two seperate columns journal and booktitle.
