### ISSUE TITLE
Compiling last master failed

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1895]
I've difficulties to compile last master (Latest commit 6bfac2b). Is this only my problem or a problem with the master?

**Comment by Siedlerchr** [comment]
Hi, I have no problems. Could you please specify some more details, e.g. which IDE do you use? Did you run gradlew check (or eclipse or build)?  It is always useful to run gradlew <target> before because it takes care of external library-dependencies etc.

My workflow is (eclipse user)
(Git bash) 
git fetch upstream
git merge upstream/master
git push 
./gradlew eclipse

PS: Sonst kannst du mich auch auf Skype hinzufügen: siedlerkiller2.0

**Comment by grimes2** [comment]
Problem solved. @Siedlerchr: Thanks for your help.
