### ISSUE TITLE
Can't open attached PDF file

### ISSUE THREAD

**Issue by yanfeit** [JabRef/jabref#1946]
JabRef version 3.6 on Mac OS X 10.11.5

Steps to reproduce:

1. I upgraded JabRef to version 3.6. Now I can't open attached PDF file by right click---> Open file.
2. The left bottom Status shows External viewer called. But nothing happens.

```
Put the excerpt of the log file here
```

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`. 
Please try to reset the external application for PDF in the `Options - Manage external file types dialog.`
![image](https://cloud.githubusercontent.com/assets/2141507/18411399/f5789fda-7776-11e6-9b8e-23594f3aee0f.png)
Otherwise, please try to reset the preferences `Options - Preferences - Reset Preferences`.

**Comment by yanfeit** [comment]
Thank you for your response. I can not solve my problem by reseting the preference. By the way, I didn't change preference before.

I also tried to reinstall JabRef, but it can not solve my problem. I tried to attach a PDF file to an entry, then open PDF by right click. But nothing happens. But if I try to open URL or DOI, Chrome can open the link for me. 

Can you please tell  me if I can find a previous version? Then I will try to degrade to a 2.X version to see if it fix my problem.

Thanks!

**Comment by Siedlerchr** [comment]
Thanks for your report. Can you please check if you have som errors in your log?
Help->Show Error console?

**Comment by yanfeit** [comment]
![image](https://cloud.githubusercontent.com/assets/13397298/18412219/3a27ef48-7757-11e6-8b02-2bca7698e3f6.png)

This is what I have in my error console. Thanks!

**Comment by stefan-kolb** [comment]
@yanfeit We need to see the full log messages. The picture is cropped in your post...Although it dosn't look like any errors occured.

**Comment by yanfeit** [comment]
@stefan-kolb Thanks! The problem has been fixed. I restart my computer, then it works fine now.
