### ISSUE TITLE
Stable library version for citationStyles  

### ISSUE THREAD

**Issue by bartsch-dev** [JabRef/jabref#1956]
The last stable version was in 13-Sep-2013 ([according to MavenCentral](http://search.maven.org/#search|ga|1|citationstyles)) and they contain only the old 1.0  CitationStyles.

For the new v1.0.1 CitationStyles we have to use the snapshots (for now, I asked in the official CitationStyles repo for a stable release citation-style-language/styles#2221)

Important for PR: #1928

**Comment by koppor** [comment]
The usage of `SNAPSHOT` is intentional by the developers (see https://github.com/citation-style-language/styles/issues/2221#issuecomment-246404544): They ensure that this artifact always includes all citation styles. Further, they have quality control in place ensuring that nothing breaks at `SNAPSHOT` (https://github.com/citation-style-language/styles/issues/2221#issuecomment-246456294). So it is OK to keep `SNAPSHOT`.

Note: This is only the dependency containing the citation styles. Not the library used for transformation. For that library, a stable version is used.
