### ISSUE TITLE
Abstract Action and Lambdas

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1957]
Unfortunately it is not yet possible to use lambdas in AbstractActions. 
I googled a bit around and found this (see also the linked PR) which introduces a nice solution for the problem:

What is your opinion about?

https://github.com/triplea-game/triplea/issues/410

https://github.com/triplea-game/triplea/pull/439/files

**Comment by tobiasdiez** [comment]
Good idea but I would push it a bit further and construct a fluent builder API. 
````
AbstractAction myAction = Action.of(e -> somethingToDo()).
     withText("Click me").
     withDescription("if you can").
     withDisabled({} -> meDecides()).
     build()
````
This can also be extended to create special builders for certain cases. For example `Action.forSelectedEntries(entries -> doSomethingWithTheEntries).withBlablaBlub...`

It would be nice to make it compatible to the [JavaFX Action interface](http://controlsfx.bitbucket.org/org/controlsfx/control/action/Action.html) so that we can replace it later on.

**Comment by Siedlerchr** [comment]
Yeah, the idea of compatibility with javafx sonds good. However, most of the time the AbstractAction is only used for adding a single Action do an input/action Map.

When I understand you correctly, you want to further get rid of our Custom Action classes?

```
  ActionMap am = statusPanel.getActionMap();
        InputMap im = statusPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        im.put(Globals.getKeyPrefs().getKey(KeyBinding.CLOSE_DIALOG), "close");
        am.put("close", new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
```

**Comment by stefan-kolb** [comment]
This issue doesn't seem too important for me. No strong opinion here.

**Comment by stefan-kolb** [comment]
I also talked with @simonharrer about this. Imho this is overuse of lambdas and introduces unnecessary complexity for saving a minimal amount of lines of code. Closing this for now.
