### ISSUE TITLE
Java Code Convention

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1980]
In the JabRef code I found several violations of the Java Code Conventions.
Examples are:

>-for (int i=0; i < SCROLL_ACTION_EXECUTION; i++) {
>+for (int i = 0; i < SCROLL_ACTION_EXECUTION; i++) {

>-public class EntryTableTest extends AbstractUITest{
>+public class EntryTableTest extends AbstractUITest {

(Eclipse Java Convention formatter used)

The question is:
Should we use a formatter to unify the complete old code?
If yes, which formatter?

**Comment by Siedlerchr** [comment]
I do not see the importance to reformat the whole code...I think it is enough when someone touches the code to reformat it.
We have a custom JabRef Code Formatter for Eclipse. If you use gradlew eclipse, the formatter automatically gets added. You can check it under Source->Cleanup

**Comment by lenhard** [comment]
The code used to violate code conventions and common sense practically all over the place. The policy so far was to gradually move the code towards the code conventions whenever one touches it. So, if you modify code or add new code, it definitely has to confirm to the code conventions. 

Reformatting all code might be a little over the top, since it changes everything and making sure that nothing breaks in the process is hard. But some people, especially @oscargus I think, are often doing PRs that do not change functionality, but restructure the code in a better fashion or eliminate issues in some subset of classes. Such code-improvement PRs are also welcome, and you can do something like that if you want. If you do, just be sure that you keep it localized enough so that we can review it (any PR with ~ 500+ changes gets more difficult to review, even if changes are simple). 

If this answers your question, please close the issue (for issue tracking purposes). If you want to discuss this further, just do so!

**Comment by oscargus** [comment]
I've used quite a lot of static code analysis tools to get rid of warnings and similar things. FindBugs, SonarLink, and PMD are quite nicely integrated in Eclipse, but especially the latter two may need a bit of configuration to not get too many issues (many which are not really relevant).

Eclipse does indeed reformat the code as in your examples and as @lenhard says this usually treated as positive when it happens (you edit something else in the file), but really no need to reformat everything. (Although I'm often tempted to do ctrl-a shift-ctrl-f ....)
