### ISSUE TITLE
after clear rank, the ranking tag in bibtex remained "ranking = {zero}," instead of being removed

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#209]
I found that, when I clicked "Clear rank", the ranking tag is set to "ranking = {zero},", instead of being removed as Priority tag.
Perhaps there is a little bug, or it is a feature ?
Thank you

I'm under 2.11b3

**Comment by koppor** [comment]
Plz try 2.11b4. Due to localization the behavior changed from b2 to b3 to b4.

----- Ursprüngliche Nachricht -----
Von: "g10996694" <notifications@github.com>
Gesendet: ‎05.‎10.‎2015 12:39
An: "JabRef/jabref" <jabref@noreply.github.com>
Betreff: [jabref] after clear rank, the ranking tag in bibtex remained"ranking = {zero}," instead of being removed (#209)

I found that, when I clicked "Clear rank", the ranking tag is set to "ranking = {zero},", instead of being removed as Priority tag.
Perhaps there is a little bug, or it is a feature ?
Thank you
I'm under 2.11b3

**Comment by g10996694** [comment]
@koppor Thanks, I tried under 2.11b4, there is no this problem:
only problem is that I can only try 2.11b4 in virtual machine, on my working station, b4 doesn't start - up than 3 bib files, just no UI but only javaw.exe. 
I haven't tried git to find the exact error as you suggested. Hope that I can figure it out.
:)

**Comment by koppor** [comment]
For the record: The three files issue is discussed at #174.
