### ISSUE TITLE
Question about the position of the search bar

### ISSUE THREAD

**Issue by h3691512** [JabRef/jabref#2216]
Dear Developers,
  I used since years JabRef, and thank you all for the hard and excellent work.  I test regularly the newest version of JabRef. We had no separated search bar in old version, then this bar is made separately, this reduces the usable height in the wide-screen age. But this is still usable, since it is under the tabs.
  In the latest build, I find that the search bar is docked just under the main toolbar, so the usable workspace is reduced even more and makes the reading be more difficult. 
  I was wondering, if the search bar can be movable, or this has been decided without any possibility of modification. Or probably there's a way to reduce the toolbar icon size ?
Thank you all,

**Comment by koppor** [comment]
I think, this is no real issue, but more a discussion thing. Would you mind to place the question in the discussion forum? http://discourse.jabref.org/. I will close this here and hope you will follow up at the forum. In case you want to follow up here, for whatever reason, please reopen the issue.

Could you also provide screenshots at the forum article so that other readers can also follow up?

**Comment by h3691512** [comment]
@koppor Sorry I did not about the discussion forum. I'll take a look over there.
Thank you,
