### ISSUE TITLE
Advanced PDF features

### ISSUE THREAD

**Issue by JingyunLiang** [JabRef/jabref#2263]
JabRef version 3.6 on window8

more features:

1. ...add the global search from PDFs
2. ...add an inner PDF reader, which can be used to read papers easily and make notes
3. ...make adding remarks easier

```
Put the excerpt of the log file here
```

**Comment by koppor** [comment]
This feature request provides highlights given at https://github.com/JabRef/jabref/wiki/FeatureRequests-Sorted#better-management-of-my-linked-files-please and https://github.com/JabRef/jabref/wiki/FeatureRequests-Sorted#make-a-better-use-of-my-linked-files-please

The search within PDFs is started at https://github.com/JabRef/jabref/pull/2264. We need help to finish that features.

A PDF reader was included until version 3.1 of JabRef. [It was removed in version 3.2](https://github.com/JabRef/jabref/blob/master/CHANGELOG.md#removed-3), because it was very ugly and we will never achieve that the inner PDF pdf reader is as good as a professional PDF reader such as SumatraPDF or Acrobat Reader. Therefore, we focus our energy to a good improvement of these readers. See #1883

Regarding the remarks: Do you talk about PDF remarks or about "Review" comments, which should go into the "Review" tab?

In case you want to help us improving JabRef, we would like to point you to our [CONTRIBUTING.md](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md). You can also contact us via [slack](http://jabref.slack.com/), email or via the forum if you need support.

**Comment by Siedlerchr** [comment]
We could include the pdfjs lib which is used on Firefox

**Comment by koppor** [comment]
It has difficulties in handling comments. For instance, highlight text, put a comment on it and open the PDF in pdfjs. The comment on the text is not displayed.

@Joeran (Docear) also wrote some thoughts on integrating a PDFViewer: http://www.docear.org/2012/05/22/dreaming-of-an-integrated-java-pdf-viewer-for-docear/

A feature comparison of current PDF readers is provided at http://www.docear.org/support/user-manual/#PDF_Editors

**Comment by Joeran** [comment]
we tried for a while to integrate some pdf viewer into docear, but we failed, i.e. every library we looked at had some serious problems or did run properly with docear. of course, that was 4 years ago and lots of things might have changed since then. anyway, i generally would advise to let users use their own preferred pdf reader and try to make jabref work with those other PDF readers. 

btw. we developed a nice pdf library for docear based on JPOD that could extract highlighted text, comments etc. quite well. it had some bugs, which is why we never publicly released it
http://www.docear.org/software/add-ons/docears-real-highlights/

the source code is on github in a private repository. if you want access to it, send me an email.

**Comment by tobiasdiez** [comment]
[I already worked](https://github.com/tobiasdiez/jabref/tree/pdfViewer) on an integrated PDF-Reader. While it had a few display problems (pictures and math was distorted sometimes) it should be sufficient for a quick browse or for showing search results. I think nobody expects JabRef's reader to compete with special PDF reader/editors.

**Comment by jorgman1** [comment]
Have there been any updates on point 1 in the last years? It could be indeed very useful to have it within Jabref. Maybe as a search tool or as an extra filter, because it could take a while to search through many pds.

**Comment by koppor** [comment]
@jorgman1 Thank you for reaching us out. Seeing the long-lasting activity on JabRef, it may be seem strange, but all developers on JabRef work on JabRef for free. Our motivation is to work on things we have fun to work on. See <https://opensource.guide/getting-paid/> for some thoughts on that. We currently have no money to pay someone for that (see our donations page at http://donations.jabref.org). We really welcome feedback on our volunteer work. In case you can spend some more time (other than reporting issues), we would really like to encourage you to check https://contribute.jabref.org/ - especially the part asking for improvement of our help pages (https://help.jabref.org/en/). This would help JabRef getting better as a whole. 🥇 - With contributions coming in, we feel motivated to work on highly-demanded features.

**Comment by Siedlerchr** [comment]
The latest development version of JabRef now contains a full text search of attached PDF files!
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
