### ISSUE TITLE
2 links in file when autolink with RegEx and literature in subfolder

### ISSUE THREAD

**Issue by Schnet** [JabRef/jabref#2274]
JabRef 3.7-dev--snapshot--2016-11-10--master--2441675
windows 7 6.1 amd64 
Java 1.8.0_111

Steps to reproduce:

1. BibTeX-File in a folder (e.g. /root) and literature in a subfolder (e.g. /root/literature)
2. names of files in /root/literature in the form "bibtexkey_*.pdf"
2. in JabRef perferences: 
    a. "Main file directory = /root/literature"
    b. "Use regular expression search = **/([bibtexkey]_).*\\.[extension]
3. Autolink yields "file = {bibtexkey_filename.pdf:literature\\bibtexkey_filename.pdf:PDF;bibtexkey_filename.pdf:root\\literature\\bibtexkey_filename.pdf:PDF},

**Comment by lenhard** [comment]
@Schnet: Thanks for your report. In my point of view, this is a little bit of a edge case. The main file directory is a global setting that applies to all bib files. For this problem to matter, either you have just one bib file ever, or you store all your bib files in the same folder. Both ways seem strange to me, but I guess: different people, different workflows. Typically, I would expect one global file directory to which bib files from all over the system point to. I guess this thinking is why we did not run into the problem before.

Anyway, there should of course just be one entry if this is the exact same pdf. Hence, we should have a look at the duplicate detection in the autolink action. Since the current behavior not shoot down JabRef (both links should work), but just duplicates some information, I will categorize it as an enhancement issue and not as a bug.

**Comment by Siedlerchr** [comment]
@tilsche submitted a PR which maybe fixed this bug.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
