### ISSUE TITLE
Jabref changes the file permissions of the database

### ISSUE THREAD

**Issue by g-mos** [JabRef/jabref#2279]
JabRef version 3.7 on Ubuntu 16.04

If you save the database it changes the permissions of the file to 600 (read/write for user and no access to anybody else). This can be a problem in shared databases where all users belong to the same group, but are different users.

**Comment by lenhard** [comment]
JabRef uses standard Java classes to write the file on save, essentially an `OutputStreamWriter`. I guess the permissions of the file are somehow derived from the permissions of the user that executes the process. For the record: What are the permissions before they are re-written by JabRef? What happens when other programs implemented in Java write to that shared folder your database is in? Do permissions change?

I am not yet convinced that your problem is not due to the configuration of your system. Lacking a Ubuntu installation, I cannot verify your problem unfortunately.

**Comment by g-mos** [comment]
Jabref version 3.6 did not have that problem. Let's say that you have a file with rw permissions for user/group/everyone. In v3.6 when you save it the permissions stay the same. In v3.7 they change to rw for user and no access for group/everyone.
Therefore I believe it has to do with changes in the latest version.

**Comment by lenhard** [comment]
Thanks for the reply @g-mos! If 3.6 is doing this correctly in your environment, then so should 3.7. 

I am a little bit at a loss as to what might be causing this behavior, but maybe one of the other developers knows more.
