### ISSUE TITLE
Metadata properties on shared databases.

### ISSUE THREAD

**Issue by g-mos** [JabRef/jabref#2284]
JabRef version 3.7 on Ubuntu 16.04 with PostgreSQL database

Steps to reproduce:
The metadata of the user are saved in the database as common metadata. Therefore the last users general file directory is saved in the database and when an other user opens the database he loads these metadata, and this general file directory
This also affects #2255 
Furthermore is the groups structure somehow handled in SQL databases?

**Comment by koppor** [comment]
Firstly, #2219 has to be fixed. Otherwise, metadata is lost anyway.

When you use the "User-specific file directory", everything should work as expected: Each user has its own file directory. This assumes that each user has a separate Windows/Linux/Mac login name. This name is used at the user-specific-file-directory-setting. The general file directory, as you also noticed, applies for all users.

In any case, each user can configure his JabRef instance at Options->Preferences->File->"Main file directory". This directory also applies for shared databases.

All in all, I think, this is more a documentation issue (http://help.jabref.org/en/FileLinks is outdated) than a real issue of JabRef. Could you try with the "user-specific dirctory"?

The storage of the group structure has changed since version 3.4 (https://github.com/JabRef/jabref/pull/1276). It still has some issues (https://github.com/JabRef/jabref/issues/1495), but works well in other regards.

**Comment by g-mos** [comment]
@koppor, thank you for your reply.
Concerning "User-specific file directory" I will reply to that tomorrow, when I have multiple users in the database environment. We have a common user logging in the database, so the general directory was false. Definitely the documentation needs more clarification!
Concerning the groups I will put my two cents in #1495, since in a shared database things are missing!

**Comment by g-mos** [comment]
I am now using the JabRef 3.8-dev--snapshot--2016-11-21--master--7362d02
 version which fixes the #2219 problem. This had a significant impact as @koppor suggested. In the database when you use user-specific file directory these user information are also stored in the db and can be handled properly. Furthermore in this version the groups tree is also saved in the metadata information.
Yet the program seems a little unstable. If you pull  changes from the shared db (which by the way I believe is the wrong name for these button, sync with db might be more accurate) the program hangs with no error messages. Sometimes the groups info are not saved when you close jabref (but I cannot steadily reproduce this error).

**Comment by koppor** [comment]
@g-mos If understand correctly, your issue is solved, but JabRef is unstable in this regard.

Can we have a chat on skype or slack? Feel free to write me on my email address published on my GitHub profile.

**Comment by g-mos** [comment]
@koppor Yes and yes. I have send you a mail with my skype contacts!

**Comment by Fab7c4** [comment]
Are there any news regarding this issue.
I am also using a MySQL dataset in combination with version 3.8.2, but the grouptree information gets lost.  For some reason a single group does work but as soon I add a second group I get problems and the whole tree disappears. I also tried directly adding groups by manipulating the entry directly in the database. From my perspective (but I am new to the JabRef code), would it maybe not easier to parse a grouptree using a format which actually supports trees e.g. xml, yaml or so on? At least the current format is not really intuitive.

**Comment by koppor** [comment]
The issue is with the syncing code of metadata. We had discussions of the metadata format, but we decided to keep as is to be safe to stay bibtex compatible.

**Comment by Fab7c4** [comment]
Ok I understand the benefit of staying close to the bibtex format. May I ask how close you are in solving this issue? The issue seems to be clearly while syncing from local to the shared database. Because when I add a tree directly to the groupstree cell and pull the changes from the db, it gets displayed correctly.

**Comment by koppor** [comment]
We really need help in solving this issue, because @obraliar seems to be very busy and cannot invest time in the near future.
