### ISSUE TITLE
When autosave is not activated, JabRef does reconnect to shared database upon startup

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2294]
JabRef version 3.8dev on Windows 10

Steps to reproduce:

1. Open connection to a shared database (e.g., one hosted using ElephantSQL).
2. Be sure not to use autosave
3. close jabref
4. open jabref
5. JabRef shows an IO exception instead of reconnection

```
23:52:55.139 [AWT-EventQueue-0] ERROR net.sf.jabref.logic.importer.OpenDatabase - Problem opening .bib-file
java.io.FileNotFoundException: C:\git-repositories\jabref\jabref (Zugriff verweigert)
```

**Comment by lenhard** [comment]
Github auto-closed this on merging 2295, which stated that is does not fix this issue. So, I'll reopen...

**Comment by koppor** [comment]
In master of today, JabRef simply does not reopen the last connection.

**Comment by mwessley** [comment]
Still no news on this one.

**Comment by koppor** [comment]
@mwessley We currently have no money to pay someone for that. Thus, it depends on the availability of our free time. - If you can spend some more time, we would like to encourage you to check https://help.jabref.org/en/FAQcontributing - especially the part asking for improvement of our help pages <https://help.jabref.org/en/>. We have plenty of open issues there: https://github.com/JabRef/help.jabref.org/issues/

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
