### ISSUE TITLE
Select all (ctrl + A)

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#2322]
I have intermittent problem with the universal shortcut to select all.
1. ctrl+a = select the first item of the list
2. ctrl+a = select the whole list

Strangely, sometimes it works as expected, but I could'nt yet been able to identify when it happens.  

JabRef 3.7
windows 7 6.1 x86 
Java 1.8.0_111

**Comment by lenhard** [comment]
It seems that:
 1. CTRL+A + Entry Editor open = select the first item of the list
 2. CTRL+A + Entry Editor closed = select the whole list

I'm not 100% sure, but i think this is intentional. CTRL+A is the bash shortcut to move to the head of the current line you are editing, so somebody might have wanted this command to move to the head of the list. Actually, there is someone who asked for exactly this in the forum: http://discourse.jabref.org/t/strange-look-of-new-version-in-linux/310/6

**Comment by koppor** [comment]
<kbd>Ctrl</kbd> + <kbd>A</kbd> goes to the beginning of the line in the current field in the entry editor, if the EMACS shortcuts are activated.

**Comment by melTr** [comment]
Thanks for quick answer.  I didn't use at all emacs (even not sure what is it). Only the checkbox "re-associate c-a" but not "use emacs shortcut" was checked. Whatever, now it's "normal". But I got this behavior only recently, it is why I was thinking something was changed.
Sorry for the derangement.

**Comment by matthiasgeiger** [comment]
Allright. I'll close this now - feel free to reopen if the problem occurrs again.
