### ISSUE TITLE
Right click on article in main article list causes a move to that article

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2397]
If I'm in the main article list window, and if I right click on an article, then the right click menu pops up, as expected.  But also, JabRef moves to the article I right clicked on.  This is new behavior.  

It's undesirable because before, it was possible to be writing a review in article A, and to quickly copy the bibtex key from some other article, B, by right clicking on B's entry in the article list.  Now it's necessary to navigate back to article after copying the key.

Related note: I'd much rather that "copy bibtex key" be on the top right-click menu and that, if necessary, the other copy functions be buried one level down.  This is because I'm frequently copying bibtex keys (for making cross references) and rarely copying whole bibtex entries.

JabRef version: JabRef 3.8, windows 10 10.0 amd64, Java 1.8.0_77

**Comment by lenhard** [comment]
@notuntoward That screenshot might not be what you intended to post.

If I am not mistaken (someone else from @JabRef/developers may clarify), the behavior you describe is intentional. Several users complained about the entry not being focused when clicked in the main table. It is impossible to make everyone happy, and I personally would be strongly opposed to reverting this, because it would just mean that we get new complaints by other people. But let us see what the others say.

**Comment by notuntoward** [comment]
Thanks for the quick response, and yes, you're right; I just removed that screenshot.

Let me emphasize that I'm talking about the RIGHT click, not the left click, which I would also expect to focus the article.  I could be wrong, but I'd guess that the other users weren't complaining about the right click behavior.

**Comment by stefan-kolb** [comment]
@JabRef/developers Has this something to do with the event system?

**Comment by stefan-kolb** [comment]
Will be rewritten with the new JavaFX maintable.
