### ISSUE TITLE
DOI url is generated for create entry by doi

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#2417]
JabRef version JabRef 3.8.1-dev--snapshot--2016-12-21--master--e6318f6
windows 10 10.0 amd64 
Java 1.8.0_112

Steps to reproduce:

1. Create entry by DOI 10.1186/s13677-016-0054-z
2. doi field and url field is set: `doi = {10.1186/s13677-016-0054-z}, url = {http://dx.doi.org/10.1186/s13677-016-0054-z}`
3. url field should be blank, as "http://dx.doi.org/10.1186/s13677-016-0054-z" does not bring any additional value

**Comment by lenhard** [comment]
I disagree. The URL has the benefit that I can just copy it and send it to someone else to directly access the paper. In your post above I can just click the link and there I am. With the doi only, I have to go through a search engine first.

Why should entries just contain the most minimal information? I am pretty sure many users would like to get as much information automatically as possible.

**Comment by koppor** [comment]
Right click on DOI - Copy URL

+1 for minimal info. I always use the cleanuo after fetching. With BibLaTeX
defaults.

Am 21.12.2016 16:12 schrieb "Jörg Lenhard" <notifications@github.com>:

I disagree. The URL has the benefit that I can just copy it and send it to
someone else to directly access the paper. In your post above I can just
click the link and there I am. With the doi only, I have to go through a
search engine first.

Why should entries just contain the most minimal information? I am pretty
sure many users would like to get as much information automatically as
possible.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/issues/2417#issuecomment-268546470>, or mute
the thread

**Comment by simonharrer** [comment]
Okay, maybe I should elaborate more.

1. If you want the DOI url, you can get them by rightclick on the DOI field and click on "Copy DOI url". The url is computed by simple string concatenation with "http://dx.doi.org/". As Olly said in this email. This also works on right-click of the icon in the main table. 
2. If you have both a DOI and a URL, the icon changes in the main table of JabRef. It is no longer obvious that I have a DOI for that entry, but the icon only shows that there are several urls available. It does not detect that the url and the automatically computed DOI url is the same - hence, showing both on the right click.

**Comment by lenhard** [comment]
Ok, I see. Let us just discuss this in the devcall tomorrow.

**Comment by matthiasgeiger** [comment]
As I won't make it for the call tommorow: I'm on Olly's and Simon's side :wink:

**Comment by lenhard** [comment]
Since the majority is not on my side, we can rate this as a enhancement :-) @simonharrer You are welcome to submit a PR.

**Comment by simonharrer** [comment]
Time to PR in less than 10 minutes. A sign I should be doing something else... ;)
