### ISSUE TITLE
"\~" Escape Sequence Does Not Display Correctly in Entry Table

### ISSUE THREAD

**Issue by pirlite2** [JabRef/jabref#2458]
JabRef 3.8.1 on Linux Mint 17.3

The Latex backslash tilde escaped diacritic "\\\~" does not display correctly in the entry table. So, for example, the bibtex entry of "Monta\\\~{n}a" displays as "Monta na". Note the space in the middle of the word. The "\\" escape character seems to be ignored and the "~" character treated as a non-breaking space.

Peter

**Comment by lenhard** [comment]
Hi Peter,

thanks for reporting. I can confirm this, it is a bug in our LaTeX to Unicode converter. 

For the record:
 - input: Monta\~{n}a
 - desired output: Montaña

**Comment by lenhard** [comment]
Turns out it was not a problem in the converter. We simply forgot to apply the converter for the author column.

@pirlite2 In a few minutes a new version of JabRef that fixes this issue will be available at http://builds.jabref.org/fix-conversion-of-tilde-n/ Could you please install this and verify that it solves your problem?

**Comment by pirlite2** [comment]
Yep! That fixes "Monta\~{n}a". Thanks.

Curious fix though as many characters with diacritics displayed fine before!

I have, however, found another problem. "Mali\'{n}ski" does not display correctly - it displays as "Mali'nski". Note the acute accent does not appear over the 'n' but before it, implying that the "\\" is ignored and the single quote is interpreted literally. 

Peter

**Comment by pirlite2** [comment]
Sorry. Damn Markdown! I should have checked the preview before posting.

I meant "Mali\\'{n}ski"

Peter

**Comment by Siedlerchr** [comment]
@pirlite2  Does this happen with the fixed version?
Regarding the Markdown here, best way is to put such encoded things into code tags

**Comment by pirlite2** [comment]
I'm afraid so. It happens with both versions - the 3.8.1 release and the fixed version.

**Comment by lenhard** [comment]
> Curious fix though as many characters with diacritics displayed fine before!

For most fields they should work fine. The author field is just very special. In contrast to other fields it has an internal structure (different items separated by `and`, `,`, etc.), which is why we have a separate and complex parsing for it. And there, we forgot to perform the Unicode conversion.

Anyway, I can confirm that "Mali\\'{n}ski" does not render as it should. Hopefully, this is just a problem in the Unicode conversion this time. I will look into this and follow up with a separate PR, probably later today.

**Comment by AEgit** [comment]
@lenhard:
I just tried the new version 3.8.2. I can confirm that this works for the author column in the entry table. In the entry preview of the article, however, you still get "Mali\'{n}ski".

**Comment by lenhard** [comment]
@AEgit: Thanks for noticing! I think it would be best if you open a new issue for this. I guess it is a similar problem: We are not applying our LatexToUnicode conversion somewhere in the entry preview. 

#2460 is something different. There, we do apply the conversion, but the conversion somehow does not work correctly.

**Comment by AEgit** [comment]
@lenhard : Done, see here:
https://github.com/JabRef/jabref/issues/2498
