### ISSUE TITLE
Entry preview: wrong display of apostrophe (treated as special character)

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2500]
JabRef version 3.8.2 and  JabRef-4.0.0-dev--snapshot--2017-01-29--masr--7191a7055.jar 
on Linux LMDE Betsy

Steps to reproduce:

1. Create a new entry
2. As title of the article, type ````L'oscillation```` (for example)
3. In the table entry, the title is displayed as ````Lòscillation````
Note: the display is OK in the entry preview

![apostrophe](https://cloud.githubusercontent.com/assets/6931104/22422399/6b22c9a6-e6ec-11e6-96b3-e0a50f2ca94c.png)

**Comment by lenhard** [comment]
The reason for this is that we are doing a LaTeX to unicode conversion for the entry table. Unfortunately, the plain text `L'oscillation` can be interpreted as valid LaTeX. There is no clean way to solve this issue, as there is no way to know that this text is not meant as LaTeX.

The only thing I can think of is to offer a preference option to turn of LaTeX rendering for the main table.  So that people can decide what is more important to them: LaTeX rendering including the above error, or no LaTeX rendering. @JabRef/developers WDYT?

**Comment by matthiasgeiger** [comment]
Isn't the "correct" LaTeX command (without the usage of special packages) `{\'o}` ?

**Comment by lenhard** [comment]
@matthiasgeiger  Indeed! Stupid me, I should have tested this in a tex editor directly! In this case, it is just a bug in our converter, which is something that can be solved :-) Preferably with #2465

**Comment by mlep** [comment]
Similar issue with some TeX special characters.
For example, ````Topo\_2d```` is displayed as ````Topo2d```` (no underscore)

**Comment by lenhard** [comment]
The more issues we get in the display, the more I am convinced that we should use an external library for tex to unicode conversion.

**Comment by AEgit** [comment]
Similar issue with author name (with Preferences set to `LatexToUnicode` instead of `HTMLChars`):

O'Connor

is displayed

as

OĆonnor

**Comment by lenhard** [comment]
So, after some contemplation, I am almost certain that the issues described here are caused by this PR: #2464 

There, I implemented special handling for `'n`, which really is a valid in LaTeX. Unfortunately this seems to have affected all other occurrences of `'` and other letters. @JabRef/developers We should probably revert #2464 and go for a new solution for #2458.
