### ISSUE TITLE
Save All as new CTRL+S shortcut

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#254]
- [ ] Make CTRL-UMSCHALT?-S for save this file.
- [ ] Remove Save icon in toolbar
- [ ] Keep Save file in menu

**Comment by oscargus** [comment]
Not convinced. Mainly as I sometimes have open files with bad encoding, so getting that "Can not encode" dialog every time I try to save a file is not so appealing...

**Comment by stefan-kolb** [comment]
That's why we still want to keep the save file option. But save all should be really the default workflow for users?! Also compare to new editors like Intelij or Atom,...

**Comment by koppor** [comment]
I also wasn't convinced, but this seems to be the current trend. One window: Save: Everything is saved. I know that Firefox behaves differently, but it is not an editor.

Regarding the encoding, I fear that only notepad++ can currently help there. In the long run, JabRef should support the user with that regard, too. -> Let's have a discussion via mail or via a new issue.

**Comment by matthiasgeiger** [comment]
I'm also not convinced. :wink: 
Sublime Text and Atom still use "ctrl-s" for "save" and have no short-cut for "save all" - Intellij has a short-cut for "save all" but due to the auto-saving concept of Intellij this is more or less obsolete...

My default use case is working with only one open bib file - so there would be no real difference. But I'm not sure whether "save all" is always useful when working with more than one file at the same time... 
So I would suggest to stick to the old (and standard) behavior.

**Comment by stefan-kolb** [comment]
@JabRef/developers So what's our decision here? Keep it the way it is for now?

**Comment by simonharrer** [comment]
nice, did not know you can mention the whole team. :)

We could also leave it as it is. My opinion is not that strong on this issue.

**Comment by mlep** [comment]
As a user, I like various piece of software to have consistent behavior. In all software I use, Ctrl-s is for saving the current file. I think JabRef development as to follow the principle of least surprise.
