### ISSUE TITLE
Provide Field formatter to escape DOI

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#2542]
... as underscore might cause trouble when used in BibTeX.

**Comment by Siedlerchr** [comment]
At least in biblatex it is defined as verbatim field like url etc, so it does not produce any errors. So no need to escape any special chars.
Otherwise it could be handled by LaTeX Cleanup

**Comment by matthiasgeiger** [comment]
Mhm... just tested it with a "Latex cleanup" action on the "doi" field: this does not work as the underscore is not escaped...

**Comment by lenhard** [comment]
With 40621b64d06b5e21d2b03b972fb4b92307168dc7 the formatter is now in place and fully integrated into the formatter framework (including tests). 

It is important to note that using the formatter with the DOI field will disable other functionality (since the DOI is no longer correct, it is escaped). There is no clean way around this and one should either use the url package in LaTeX (to avoid the need for escaping) or separate between libraries for a TeX document project and for sorting/managing the references

**Comment by matthiasgeiger** [comment]
@ronsei you can use the escape underscore functionality now in the least recent Dev builds (Caution: is currently an alpha state)
