### ISSUE TITLE
Remove from group ignores the current selected group-tree-entry

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#2606]
I am using JabRef 3.8.1 on Debian unstable.

I have an entrie with two or more groups.
The group-tree is shown and one of the two groups is selected.
Entries not belonging to the selected group are not shown ("hide non-hits") in the table view.

Clicking in the context-menu (please keep the word **context** in mind!)  of the entrie on "Remove from group" activates a new window with a group-tree. I think I should select the group I want to remove here.

This make no sense in that situation. "Remove from group" should assume the currently selected group from the group-tree.

**Comment by Siedlerchr** [comment]
@tobiasdiez  Is there a way/method to get the current selected group?
groupSelector in Base Panel doesn't really work

**Comment by tobiasdiez** [comment]
Yes via https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/StateManager.java#L47 (which should probably be rename to `selectedGroupCurrentDatabase`).

Concerning this issue, I think we should conserve the consistency between "Remove from group" and "Add to group" and always shows the dialog. However, I propose to preselect the currently selected database in the dialog; saving one click per remove.

**Comment by lenhard** [comment]
Not sure, but there's a chance that this will be fixed by  #3484

**Comment by stefan-kolb** [comment]
This may be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Why do you close an Issue when you ask the opener for feedback? This is unpolite.

**Comment by stefan-kolb** [comment]
We were working through the issues but cannot test all of them in detail.
Also because WE had huge changes. So we rely on the issue Opener to Tell us
If it is still valid. We think it is easy for the Opener to quickly reopen
If the issue still persists. Often issue openers dont reply to older issues
so it is tedious Work to Just ask for reply and then noone responds and we
need to come Back and remember to do so after some time (please remember we
had 200+ issues).

Codeberg-AsGithubAlternative-buhtz <notifications@github.com> schrieb am
So., 25. Aug. 2019, 22:29:
