### ISSUE TITLE
Cannot call TexStudio from JabRef

### ISSUE THREAD

**Issue by L0rdKelvin** [JabRef/jabref#2613]
JabRef version 3.8.2on 

I've set the right path /Applications/texstudio.app in the preference, but when I click on the icon in menu bar I receive the message: Could not call executable '/Applications/texstudio.app'

 Thanks for the support.

**Comment by chochreiner** [comment]
I can reproduce the error, though I cannot fix it atm, because i do no manage to import Jabref to Intellij...

Long story short: this is a permission issue because Texstudio is not signed; but you can open applications with the *open* statement.

A solution approach would be to introduce a MacOS specific statement which executes the program with open + applicationbinary on the commanline:

        if (OS.OS_X) {
            Runtime.getRuntime().exec("open /Applications/texstudio.app");
        }

**Comment by stefan-kolb** [comment]
@chochreiner Did you just import the gradle file in Intellij? Should work out of the box. Do not try to create an Intellij project at first. Also feel free to contact me on Skype!

**Comment by stefan-kolb** [comment]
@chochreiner Take a look at `OSX.java` there are methods that use `open -a`

**Comment by chochreiner** [comment]
@stefan-kolb the problem was an outdated java version

I've had a closer look at the problem and found out that the official recommended command *open -a  /Applications/texstudio.app/Contents/MacOS/texstudio --args --insert-cite xx* to open programs on the commandline does not work for some reason for texstudio - though it works for other applications; therefore the open approach does not really help to solve the problem

On MacOS, all programms, e.g. textstudio.app are in fact *special folders*, which wrap some things among the actual executable, which is fine to trigger the citation insert

e.g. fot texstudio: the path */Applications/texstudio.app/Contents/MacOS/texstudio* works at least for me @L0rdKelvin 

the most suitable shortime soluation would be to add the full path to the executables to the FAQ

**Comment by L0rdKelvin** [comment]
2017-03-06 13:03 GMT+01:00 Christoph Hochreiner <notifications@github.com>:

> */Applications/texstudio.app/Contents/MacOS/texstudio*


Dear Staff,
you are wonderfully efficient, and I confirm that the new path works
perfectly.
Probably could be useful to set as default this path for Mac version of
JabRef.

Thank you so much!

Daniele

**Comment by chochreiner** [comment]
I've just found the solution to rely on the normal application paths.
The dev build on: http://builds.jabref.org/fix2613/ already fixes the problem.
