### ISSUE TITLE
Group information not saved in a Postgres db

### ISSUE THREAD

**Issue by g-mos** [JabRef/jabref#2647]
JabRef version JabRef-4.0.0-dev on Ubuntu 16.04

Steps to reproduce:

1. Opened a Postegres literature db
2. Created some groups
3. Closed and reopend the db. The groups have disappered

**Comment by koppor** [comment]
When #2284 is fixed, this should be fixed, too.

**Comment by tgkolda** [comment]
I have the same problem with 

JabRef 4.0.0-dev--snapshot--2017-06-09--master--b5f1e7d7e
Windows 7 6.1 amd64 
Java 1.8.0_66

Thanks for any help! I use the groups frequently and really need them to work. I've switched to the latest snapshot due to Bug #2898. I'm really stuck because I need both groups and DOIs to work! Thanks for any help.

**Comment by lenhard** [comment]
@koppor: You've written above that this is fixed by #2284. That has been merged, so I guess we can close the issue?
