### ISSUE TITLE
TeX commands not properly interpreted for unicode display

### ISSUE THREAD

**Issue by spontaneous-emission** [JabRef/jabref#2651]
I am using JabRef version 3.8.2 on Windows 10.

Bib files produced by APS journals include TeX commands `\ifmmode ... \else ... \fi{}` when including certain special characters, such as Č. See, for example, http://journals.aps.org/pra/export/10.1103/PhysRevA.94.012340
`author = {\ifmmode \check{C}\else \v{C}\fi{}ernot\'{\i}k, Ond\ifmmode \check{r}\else \v{r}\fi{}ej and Hammerer, Klemens}`

This TeX code is not processed correctly by the Latex to unicode conversion and shows up in the author field in JabRef. For example, for the above, Jabref displays:
`ifmmode Celse &Ccaron;fiernot\ik, O, r. ř. & Hammerer, K.`

Manually removing the math-mode statement and leaving only the LaTeX text mode command for the letter results in correct display, but it is tedious to manually correct all of these entries.

Trying out the online latex2unicode demo, this text is also not processed correctly there, with two copies of the letter inside the `\ifmmode ... \fi` displayed.

**Comment by matthiasgeiger** [comment]
Hi,
if you use [a current dev build](https://builds.jabref.org/master) the situation is improved - however, not perfect:
The Latex-to-unicode conversion produces: `Č Černotı́k, Ond ř řej and Hammerer, Klemens` - so the `\ifmode ... \fi` statements are correctly removed, but both cases (if and else) are interpreted and converted to the same unicode character.

As we can not implement a fully fledged latex parser and interpreter for such edge cases, I fear that you'll have to fix this manually. Or as a workaround you can use the RIS export of APS and the RIS-Import of JabRef which does not produce this problem...

**Comment by koppor** [comment]
Could you file an issue at https://github.com/tomtung/latex2unicode? We are
using that library to convert the characters.

Even though, I fear, implementing that could be out of scope of that
library.

Am 16.03.2017 10:05 schrieb "spontaneous-emission" <notifications@github.com
>:

I am using JabRef version 3.8.2 on Windows 10.

Bib files produced by APS journals include TeX commands \ifmmode ... \else
... \fi{} when including certain special characters, such as Č. See, for
example, http://journals.aps.org/pra/export/10.1103/PhysRevA.94.012340
author = {\ifmmode \check{C}\else \v{C}\fi{}ernot\'{\i}k, Ond\ifmmode
\check{r}\else \v{r}\fi{}ej and Hammerer, Klemens}

This TeX code is not processed correctly by the Latex to unicode conversion
and shows up in the author field in JabRef. For example, for the above,
Jabref displays:
ifmmode Celse &Ccaron;fiernot\ik, O, r. ř. & Hammerer, K.

Manually removing the math-mode statement and leaving only the LaTeX text
mode command for the letter results in correct display, but it is tedious
to manually correct all of these entries.

Trying out the online latex2unicode demo, this text is also not processed
correctly there, with two copies of the letter inside the \ifmmode ... \fi
displayed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/issues/2651>, or mute the thread

**Comment by spontaneous-emission** [comment]
Okay, thanks for the extremely prompt responses.

I will try filing this as an issue for the latex2unicode library.
