### ISSUE TITLE
String to Integer/int conversion

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#269]
In the Util class, there is a method intValueOf which converts a String to an int using a method claimed at StackExchange to be the fastest, see http://stackoverflow.com/questions/1030479/most-efficient-way-of-converting-string-to-integer-in-java

Now, it makes either sense to consistently use this, because it is efficient, or remove it and use some "standard" function, to reduce the amount of code to maintain.

Any opinions on which way to go?

**Comment by simonharrer** [comment]
I introduced this method because when saving (and generally working with) large .bib files (>1000) entries, this method could be called several 100.000 times per action. 

I replaced only the calls that had O(n²) complexity, causing this large number of calls to occur. 

From my point of view, it is OK to always use this method.

**Comment by oscargus** [comment]
OK! Thanks for a quick response (although I do think that my actions will not be as quick). Didn't know the background of the method, but I'll use that then.

**Comment by oscargus** [comment]
A related question: util.Util is quite large. Would it make sense to move intValueOf to logic.util.strings.StringUtil?

Should, in general, as many functions as possible move from util.Util to a more well defined home such as logic.util.*.*Util?

**Comment by simonharrer** [comment]
Yes, splitting up large classes into smaller ones make sense.

**Comment by matthiasgeiger** [comment]
Issue can be closed?
