### ISSUE TITLE
Saving files as executables

### ISSUE THREAD

**Issue by hmontenegro** [JabRef/jabref#2725]
When saving a new bib file (bibliography.bib, bibliography.bib.bak and bibliography.bib.sav), they are saved with +x permission. After removing +x (chmod -x bibliography.bib*), saving again will turn bibliography.bib.sav into executable again.

 

JabRef 3.8.2  linux 4.9.0-2-amd64 amd64 Java 1.8.0_121 
 

Steps to reproduce:

1. ... create a bib file
2. ... save it
3. ... check permission of .bib, .bib.bak and .bib.sav

```
Put the excerpt of the log file here
```

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release. 
See #2635 and #2637 

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

Please note that for the new dev-4x version you need to have the opfenjfx package to be installed if you use the openjdf.  If you want to try the current version, it is advisable to backup any bib files in advance.

**Comment by hmontenegro** [comment]
Indeed it works.

**Comment by hmontenegro** [comment]
However, now JabRef-4.0.0-dev keeps popping a dialog window asking to share telemetry statistics. I tried several times to click on "Do not share", and after a few moments, the dialog would pop up again. It seems clicking on "Share" finally disables the dialog, but this defeats the purpose of asking in the first place. Should I open a new issue?

**Comment by matthiasgeiger** [comment]
Yes. Please Open a new issue.

**Comment by tobiasdiez** [comment]
@hmontenegro Thanks for the report. This should be fixed now in the latest build http://builds.jabref.org/master/
