### ISSUE TITLE
dropdown for the date field is not convenient for early dates

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#2821]
The new drop-down for entering a date is too inflexible for early dates.  As a historian I often refer to books published in earlier centuries, and it's more or less impossible to wind labouriously back through the calendar to a year more than a couple of years ago.  Of course I can go to the biblatex display and just enter the date there.  But that's not really the point of a nice interface like JabRef.

JabRef version

JabRef-4.0.0-dev--snapshot--2017-05-03--master--a16e6123d.jar

running with Linux Mint 18.1, with file manager Nemo 3.2.2

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by tobiasdiez** [comment]
In principle it should be possible to use a dropdown field instead of the "spinner" (by overwriting https://github.com/Debian/openjfx/blob/ff306f7191c8501495ed05516f4e0cc318db489b/modules/controls/src/main/java/com/sun/javafx/scene/control/skin/DatePickerContent.java#L297). However, I doubt that this more convenient for dates in the 18th century since you still need to scroll 100 years up. Thus I would vote for "wont-fix".

By the way, you can always just insert the year or date directly in the textbox.

**Comment by wujastyk** [comment]
On 4 May 2017 at 16:29, Tobias Diez <notifications@github.com> wrote:

> By the way, you can always just insert the year or date directly in the
> textbox.
>

​Unfortunately this direct solution doesn't work.  You can enter the date
but it is erased when the cursor is move to another field.

Dominik​

**Comment by Siedlerchr** [comment]
@wujastyk  This bug has been fixed just in #2816 , so I would advise you to try out the latest version

**Comment by wujastyk** [comment]
Yes, it works fine now.  Thanks!
