### ISSUE TITLE
Fields should be automatically trimmed by Jabref

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2830]
To avoid strange artifacts in Bibtex like this:
![image](https://cloud.githubusercontent.com/assets/2141507/25847403/5000149a-34b6-11e7-9862-3322b9f0f768.png)
Caused by a whitespace in the title.
```
@Article{Garg2013,
  author  = {Saurabh Kumar Garg and Steve Versteeg and Rajkumar Buyya},
  title   = {{A framework for ranking of cloud computing services }},
  journal = {Future Generation Computer Systems},
  year    = {2013},
  volume  = {29},
  number  = {4},
  doi     = {10.1016/j.future.2012.06.006},
  file    = {:Brokering\\IaaS\\Smicloud a framework for ranking cloud services.pdf:PDF},
}
```

**Comment by lenhard** [comment]
To be fair, this strangeness applies to the title only.

Didn't we agree that JabRef should not automatically modify the BibTeX data? To me, this use case sounds perfect for a save action with a trim formatter.

**Comment by stefan-kolb** [comment]
Initially I thought this is a general problem, but actually we already trim all data. This one is caused by a space inside the braces. Not sure if we can or should handle this.

**Comment by Siedlerchr** [comment]
Don't we have a cleanup formatter for this already?

2017-05-09 13:47 GMT+02:00 Stefan Kolb <notifications@github.com>:

**Comment by lenhard** [comment]
@stefan-kolb Ok, this might be tough then. I would say we do not touch this, because braces generally indicate that a user wants the text contained therein exactly as-is. If we start fixing text inside braces, we might end up changing things that we should not. I cannot come up with a use case where it makes sense to have that trailing space, but experience has taught me to be careful with such assumptions.

**Comment by stefan-kolb** [comment]
Hm, I agree with you. I just logged it here because it broke the layout in a recent paper of mine.
