### ISSUE TITLE
Sciencedirect Full text download failed due to redirection

### ISSUE THREAD

**Issue by haakonbuer** [JabRef/jabref#2846]
JabRef 4.0.0-dev--snapshot--2017-05-16--master--f81716173
Mac OS X 10.11.6 x86_64 
Java 1.8.0_91

Steps to reproduce:

With the following BibTex source I get "Full text download failed". Am I doing something wrong?
```
@Article{Frazzini_2014,
  author    = {Andrea Frazzini and Lasse Heje Pedersen},
  title     = {Betting against beta},
  journal   = {Journal of Financial Economics},
  year      = {2014},
  volume    = {111},
  number    = {1},
  pages     = {1--25},
  month     = {jan},
  doi       = {10.1016/j.jfineco.2013.10.005},
  publisher = {Elsevier {BV}},
}
```

<details>
<summary>Detail information:</summary>

```
Migrating old custom entry types.
Opening: /Users/haakon/git/papers/references.bib
Fulltext PDF found @ ScienceDirect (old page).
Fulltext PDF found @ Google: http://www.sciencedirect.com/science/article/pii/S0304405X13002675
```

</details>

**Comment by stefan-kolb** [comment]
This is a redirection problem. Trying to investigate how we can fix this.

**Comment by bernhard-kleine** [comment]
downloading works, but using Jabfox does not work for this article.

**Comment by haakonbuer** [comment]
I'm not using Jabfox here..

**Comment by Siedlerchr** [comment]
I looked into this. The problem is actually the mimetype, The code checks for mimetype application/pdf, but the actual mimetype is reported as html - but which is in reality a pdf...
I uncommented the second condition and it downloads a html page which in reality is a pdf..

In FulltextFetchers.java 
`                if (result.isPresent() && new URLDownload(result.get().toString()).isPdf()) {`

**Comment by stefan-kolb** [comment]
@Siedlerchr It is correct that the "wrong" mime type is detected, but this is somehow related with the redirection. We cannot just uncomment this check because it would serve all unauthorized html pages afterwards. When I remember the case here correctly (I already debuged quite a bit) the java code gets redirected to another page then the browser will be. That's the problem with Sciencedirect here I think. So the MIME type is actually correct but the site we reach with the java code is wrong.

**Comment by stefan-kolb** [comment]
Checked again, this is not in our hands. I improved the Google Scholar fetcher so that we can fix at least the example for this issue. See 9db52ea1ba71fc66fcdcb6a8079bf6dcc8623c0b
