### ISSUE TITLE
JabRef 4.0.0-beta not starting on Linux: Could not find or load main class

### ISSUE THREAD

**Issue by mathiasbockwoldt** [JabRef/jabref#2867]
I downloaded **JabRef version 4.0.0-beta** (latest Github release: `JabRef-4.0.0-beta.jar`). This JabRef version just denies to start with a message in the terminal saying: `Error: Could not find or load main class org.jabref.JabRefMain`.

My system:

```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

$ uname -a
Linux NATUR-BFE-00155 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Linux Mint 18 Sarah \n \l
```

Steps to reproduce:

1. Download [JabRef 4.0.0-beta](https://github.com/JabRef/jabref/releases/download/v4.0-beta/JabRef-4.0.0-beta.jar)
2. Open a terminal, cd to the location of the jar file
3. Run `java -jar JabRef-4.0.0-beta.jar`

As far as I can see, no log file was created.

**Comment by tobiasdiez** [comment]
You need to install javafx as outlined in the help: http://help.jabref.org/en/Installation#installation-commands

**Comment by Siedlerchr** [comment]
Please look at the installation instructions in the help section. You need
to install the additional package openfx for the javafx support.

Am 25.05.2017 12:32 nachm. schrieb "Mathias Bockwoldt" <
notifications@github.com>:

I downloaded *JabRef version 4.0.0-beta* (latest Github release:
JabRef-4.0.0-beta.jar). This JabRef version just denies to start with a
message in the terminal saying: Error: Could not find or load main class
org.jabref.JabRefMain.

My system:

$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

$ uname -a
Linux NATUR-BFE-00155 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27
15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Linux Mint 18 Sarah \n \l

Steps to reproduce:

   1. Download JabRef 4.0.0-beta
   <https://github.com/JabRef/jabref/releases/download/v4.0-beta/JabRef-4.0.0-beta.jar>
   2. Open a terminal, cd to the location of the jar file
   3. Run java -jar JabRef-4.0.0-beta.jar

As far as I can see, no log file was created.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/issues/2867>, or mute the thread

**Comment by mathiasbockwoldt** [comment]
Wow, that were two fast answers! Installing javafx solved the issue. Thank you very much!

**Comment by raffam** [comment]
I still have the same issue

> java -jar JabRef-4.3.1.jar 
> Error: Could not find or load main class org.jabref.JabRefMain
> Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

Installing `javafx` did *not* solve the problem

Can we re-open this?

java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)

uname -a
Linux raffa-kubuntu 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

**Comment by Siedlerchr** [comment]
JabRef explicit requires JDK8 and openjfx8!

**Comment by mukundmath** [comment]
I have the following version of Java installed on my Ubuntu 18.04 bionic.
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
While trying to run JabRef using 
java -jar JabRef-4.3.1.jar 
The following error message appeared

Error: Could not find or load main class org.jabref.JabRefMain

After reading this post, I installed openjfx using 
sudo apt-get install openjfx

still facing the same problem.

**Comment by Siedlerchr** [comment]
See https://github.com/JabRef/help.jabref.org/issues/204  your ubuntu probably installed the openjfx11 version!
