### ISSUE TITLE
Accented French accented c not correctly rendered

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2919]
For the 
[example.txt](https://github.com/JabRef/jabref/files/1080445/example.txt)
bibtex entry at the end of this report, the accented French 'c' is rendered incorrectly in the entry table and in the preview (see screenshots.

JabRef version 

JabRef 3.8.2
windows 7 6.1 amd64 
Java 1.8.0_131

![example](https://user-images.githubusercontent.com/3851891/27222378-4ed186b4-528c-11e7-8d54-5ad0442b9442.PNG)

[example.txt](https://github.com/JabRef/jabref/files/1080446/example.txt)

**Comment by AEgit** [comment]
This is fixed in:
`JabRef 4.0.0-dev--snapshot--2017-06-06--master--5dcdd79ab`
windows 10 10.0 amd64 
Java 1.8.0_131

Note, however, that you could already achieve the same result with JabRef 3.8,2 if you were to use
`Fran{\c{c}}ois` or `Fran{\cc}ois` instead of `Fran{\c c}ois` (I don't think that `Fran{\c c}ois` is the correct way to store the accented French `c').

**Comment by notuntoward** [comment]
This did used to work in older JabRef versions, and I think when I made this bibtex entry,  I was going by the table here:

https://tex.stackexchange.com/questions/8857/how-to-type-special-accented-letters-in-latex

But thanks for the correct answer!
