### ISSUE TITLE
Pressing Escape does not close entry editor

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2949]

**Comment by Siedlerchr** [comment]
Could be related to my last changes, we probably just need to add a Check
for the escape key

Am 28.06.2017 3:54 nachm. schrieb "Tobias Diez" <notifications@github.com>:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/issues/2949>, or mute the thread

**Comment by koppor** [comment]
Somehow related:

- [ ] <kbd>Ctrl</kbd>+<kbd>S</kbd> does not work. Neither when focused in the entry nor when 
- [ ] Star for modified database not shown if I change something in the entry editor

**Comment by Siedlerchr** [comment]
This does not work when you are in an entry editor field.

**Comment by Siedlerchr** [comment]
Escape now works. For save, we first need to create a save action in the entry editor. I will create a follow up PR

**Comment by tobiasdiez** [comment]
The save command shouldn't be handled by the entry editor but by a higher instance (probably JabRefMain).

**Comment by Siedlerchr** [comment]
Yes, but the problem is that it is not that easy to filter out the command from the JFX panel, because we would need to map between awt keyEvents and javafx keyEvents/KeyCombination. Unfortuately there is no easy way to do this.
So I would suggest creating a save action analogous to the close action in EntryEditor/ setupKeyBindings

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by koppor** [comment]
Since two years, this does not work. At https://github.com/JabRef/jabref/pull/11190#issuecomment-2054006956, we decided to stick with <kbd>Ctrl</kbd>+<kbd>E</kbd> to open/close the entry editor.
