### ISSUE TITLE
File: aboutdialog.css not found, attempting with camel case 

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2956]
Jabref claims about several missing files on STDERR:

```
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
File: aboutdialog.fxml not found, attempting with camel case
File: aboutdialog.css not found, attempting with camel case
```

```
JabRef 4.0.0-dev--snapshot--2017-06-29--master--7e50e84a1
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131
```

**Comment by tobiasdiez** [comment]
These messages are actually no problem since the corresponding files are found with the camel case version (e.g. `GroupTree.fxml`). However, it would be nice to remove/hide these messages. A corresponding issue https://github.com/AdamBien/afterburner.fx/issues/67 is already reported at the library we use. At the moment, [I don't see any possibility](https://github.com/AdamBien/afterburner.fx/blob/a24f8cbf34136fcc65823c3aff9ed7c31c338c70/src/main/java/com/airhacks/afterburner/views/FXMLView.java#L214) to hide this message.

**Comment by Siedlerchr** [comment]
I  would close this issue as we can't do anything about it atm and because we still have some other more important issues left.

**Comment by jonasstein** [comment]
I do not think this bug should be closed, just because there are much more severe bugs, until it is fixed. 
Could we reopen this, please?

**Comment by tobiasdiez** [comment]
This should be fixed with https://github.com/JabRef/jabref/pull/3880. Thus removing the freeze label....
