### ISSUE TITLE
The autocompletion does not work perfectly

### ISSUE THREAD

**Issue by iTao8** [JabRef/jabref#2998]
JabRef 4.0.0-dev--snapshot--2017-07-11--master--e35b6ac2c
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

The bugs: 
1. The autocompletion does not work in the author and journal fields. 

2. The autocompletion dropdown box gives many same items. When you search something once more, there are two dropdown boxes overlap there.

![screen shot 2017-07-12 at 6 47 45 am](https://user-images.githubusercontent.com/28705547/28094335-9cc7078a-66ce-11e7-8a02-64ab54fa8818.png)
![screen shot 2017-07-12 at 6 48 05 am](https://user-images.githubusercontent.com/28705547/28094343-a2713444-66ce-11e7-9815-9e6af682f719.png)

**Comment by tobiasdiez** [comment]
Thanks for the quick feedback! 

This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
Sometimes you still get the same suggestion in the search bar. This happens when the same author is entered in different ways (for example, once as "Tao, I." and also as "Tao, IdontKnow" so that the suggestion is "Tao, I." in both cases). There is nothing I can do at the moment but reporting the issue at []().

Moreover, I couldn't replicate the two overlapping dropdown boxes (on Windows). What are the exact steps to reproduce this problem?

**Comment by iTao8** [comment]
JabRef 4.0-dev--snapshot--2017-07-19--master--894799b2f
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

The autocompletion dropdown box for the journal field covers the input
![screen shot 2017-07-21 at 6 27 11 pm](https://user-images.githubusercontent.com/28705547/28460120-3a96268c-6e43-11e7-8089-d62c815a35d8.png)

**Comment by iTao8** [comment]
@tobiasdiez To reproduce the overlapping dropdown box, you just need to search an author two or more times. 

It seems that the autocompletion in the search bar can only work for the author, not for journal and some other thing, is it?

My current version is 
JabRef 4.0-dev--snapshot--2017-07-19--master--894799b2f
Mac OS X 10.11.6 x86_64
Java 1.8.0_131

**Comment by tobiasdiez** [comment]
In order to adress https://github.com/JabRef/jabref/issues/2998#issuecomment-316968028, @lenhard do you think we can adopt your recent solution for the BackupManager so that only bigger changes lead to an update of the autocompletion suggestions?

**Comment by lenhard** [comment]
@tobiasdiez Sorry, I have very little time at the moment. You should be able to do something similar as for the BackupManager, though. The DatabaseChangedEvent carries information about the delta that you can use.
