### ISSUE TITLE
Ctrl+F does not select the search field

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3062]
Keywords: shortcut, short cut, keybinding, key binding, hotkey, hot key

JabRef 4.0-dev, Windows 10 10.0 amd64, Java 1.8.0_144

Steps to reproduce:

1. Focus is on the main table
2. I press <kbd>Ctrl</kbd>+<kbd>F</kbd>
3. Nothing happens

Expected: Focus is on the search field.

**Comment by Siedlerchr** [comment]
I debugged a bit, and the action is correclty recognized and the method to requestFocus is called, but somehow the textfield is not focused. Maybe @tobiasdiez  has an idea, because he changed that together with the autocompletion.

I even tried to wrap it in a Platform.runLater call, but that did not work

**Comment by koppor** [comment]
Happens again in the `maintable-beta` branch. As discussed in the devcall, I should open issues for issues with that branch (which will become the master branch).
