### ISSUE TITLE
Autocompletion in search field

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#3068]
JabRef 4.0-dev--snapshot--2017-08-02--master--63414b030
Windows 10 10.0 amd64 
Java 1.8.0_66

Steps to reproduce:

1. Type last name of the author say "Lastname"
2. A suggestion pops up "Lastname, F." and you can already see the item you want in the list
3. You hit enter, no item is found

This happens in particular if the author field is encoded as e.g. "F. Lastname and G. Rdsfdsf and Z. Ddslkfjddf" instead of "Lastname, F. and Rdsfdsf, G. and Ddslkfjddf, Z."

**Comment by lc9275** [comment]
As a side note, is there a way to turn auto-completion of? It is very slow and instead of being helpful it just slows me down.

**Comment by lenhard** [comment]
I can confirm this, author autocompletion has a chance of breaking main table selection. However, let me point out that if you don't hit enter, table sorting works as expected and the correct entries are displayed. So as a quick fix for your problem: don't hit enter.

You can turn of the autocompletion for the entry editor under preferences -> Entry editor -> Enable word/name completion. However, that disables the autocompletion only for the entry editor. We should extend it so that it covers the search box as well.

**Comment by Doc73** [comment]
Similar issue:

1. I want to add author in the form "surname, name"
2. I write "surname" --> autocompletion suggests "surname, n."
3. I continue typing "name" and... then? If I press the Enter key, editor prints "surname, n." and the only way to write "surname, name" appears to be to go with the mouse on another field, because other keys (ex. tab) don't work

It is very annoying!

**Comment by lenhard** [comment]
@Doc73 You might want to have a look at the autocompletion preferences under Options->Preferences->Entry Editor.

There's different ways you can set the autocompletion for names. I have selected "Autocomplete names in Firstname Lastname format only" and "Use full firstname whenever possible". With this setting, I cannot reproduce the problem you describe, I always get the full author name.

Moreover, when you do not like the suggested autocompletion, you can just hit the escape key. Then the autocompletion suggestion disappears and there's no need to select a different field.

**Comment by Doc73** [comment]
@lenhard 
Many thanks! I could not find this section in preferences, maybe due to italian translation: "Entry editor" becomes "Modifica voci". I can not imagine a better translation: in this case, English is clearer to me.

I would suggest: "Editor delle voci"

**Comment by lenhard** [comment]
I am glad to hear it helped :)

Regarding the translation: We are always looking for people who help us translate the interface into their native language. It's actually quite easy, requires no programming knowledge, and can be done in your browser. It would be really cool if you help :) Have a look at the contribution guide, the example there is even for the italian menu translation: https://help.jabref.org/en/TranslatingGUI

**Comment by Siedlerchr** [comment]
@Doc73  If you find some other inconsistencies in the Italian translation which could be improved, either do it as @lenhard  suggests - or you could also talk to @frithnanth who actually does most of the Italian translation.

**Comment by Doc73** [comment]
@lenhard  @Siedlerchr 
Yes, I'll take a look at these things!

**Comment by lenhard** [comment]
@tobiasdiez Could we modify the enter key in the search box so that it does not select the top autocompletion suggestion? Maybe it would be better to only auto complete in the search box if a user actively selects a suggestion. The current behavior seems to confuse some users.

**Comment by stefan-kolb** [comment]
#3522

**Comment by lc9275** [comment]
I am closing this, as all these issues have been fixed (as far as i can tell). Thanks a lot!
