### ISSUE TITLE
Group names 

### ISSUE THREAD

**Issue by mpele** [JabRef/jabref#3075]
JabRef-4.0-dev--snapshot--2017-08-03--master--ea29f5600.jar

Steps to reproduce:

1. Create group "one"
2. Create group "two"
3. Create group "one, two"
4. Add article to group "one, two"

The article is presented in all tree groups.

**Comment by lenhard** [comment]
I am not 100% sure, but this behavior might actually be intended.

@tobiasdiez Can you clarify?

**Comment by tobiasdiez** [comment]
Yes this behavior is kind of by design since the group membership is stored as a comma separated list. If you want to use the comma in the group name, you have to change the keyword separator under Preferences > Groups > "When adding/removing keywords, separate them by".

With https://github.com/JabRef/jabref/pull/3077 a proper error message will be displayed when a group name contains the keyword separator.

**Comment by retorquere** [comment]
Is the group separator saved in the BibTeX file? I import jabref - generated bibliographies using zotero better bibtex (bbt) and this new groups format is a bit of a challenge.

**Comment by tobiasdiez** [comment]
No the keyword separator is only stored in the preferences and not in the bib file (but we probably want to change this at some point).
