### ISSUE TITLE
new entry displayed twice in sql database with jabref 4

### ISSUE THREAD

**Issue by napseis** [JabRef/jabref#3164]
hi,

When connected to a remote database (mariadb), when I add an entry, the entry is always added twice. If i want to remove one, both are removed.

This happens with Jabref 4 final, but works ok in 3.8.2

Furthermore, entries added using version 3.8.2 appear correctly when opened with jabref 4, i don't see any duplicate.

tell me if i can provide something more.

Thanks

**Comment by MarioLipinski** [comment]
I think this just a presentation bug after adding the entry to the database. It seems the entry is only added once.

**Comment by napseis** [comment]
hi,
Maybe, but there is something more, as I said, when I create with 3.8, i see it only once when i open the database with 4 beta3

**Comment by napseis** [comment]
It is indeed displayed bug. If database is opened with 3.x verion, entry shows up once. But it's quite annoying, in version 4 I have to close database and reopen it in order to fix the display. Pulling change from sql doesn't  refresh correctly.

**Comment by mwessley** [comment]
Having the same Problem and sadly did not find a solution yet

**Comment by mwessley** [comment]
Any Ideas on why this bug occurs so I could go on myself and fix this?

**Comment by tobiasdiez** [comment]
I have no idea but can point you to the relevant code: since it appears to be a problem with the update of the maintable, I would start debugging https://github.com/JabRef/jabref/blob/ebbeb1d249edf7134abf92d24c2031ae54d19881/src/main/java/org/jabref/gui/maintable/ListSynchronizer.java (best set breakpoints in the listener methods). This class ensures that the backend (List<BibEntry>) is properly synchronized with what is shown (EventList<BibEntry>). The list synchronizer is bound to the backend here: https://github.com/JabRef/jabref/blob/c6f39cbab33e56bdc704d9575efc661b78c7b9c2/src/main/java/org/jabref/gui/BasePanel.java#L1231

**Comment by koppor** [comment]
@obraliar Can you have a look, please?

**Comment by obraliar** [comment]
@koppor yes :)
@napseis @mwessley I would appreciate if you could test this fix on your local machine.

**Comment by napseis** [comment]
hi,
I tried JabRef 4.1-dev--snapshot--2017-11-07--master--efdf91a7d , and it persists, but i think the fix is not yet incorporated in this snapshot ?

**Comment by koppor** [comment]
@obraliar What do you mean by "this fix"? 🕺

**Comment by lenhard** [comment]
@obraliar @koppor: The fix is on a fork of JabRef and that's why there's no executable on our build server that @napseis could try out.

**Comment by mwessley** [comment]
@obraliar I could try it out if the fix would be included in the snapshot, sadly currently too little time at home to compile.
