### ISSUE TITLE
Localisation test for invalid Strings

### ISSUE THREAD

**Issue by lynyus** [JabRef/jabref#3185]
@mlep suggested this in https://github.com/JabRef/jabref/pull/3184#issuecomment-326588019.

There should be another localisation consistency check that detects invalid characters like spaces in the localisation strings.

**Comment by steph37tours** [comment]
Hi, I am a very beginner. I would like to try to help. Could you give more details about this issue to help me to find a solution ? Thank you very much.

**Comment by Siedlerchr** [comment]
Hi,
thanks for your interest in JabRef. The problem is about the localization keys and their translations in the l10n properties file, e.g. here for English:
https://github.com/JabRef/jabref/blob/master/src/main/resources/l10n/JabRef_en.properties

A solution would be to add a consistency Test to make sure that there are no whitespaces in the keys and the translations. Whitespaces have to be replaced with underscores.
We have already a Test class with consistency checks:
https://github.com/JabRef/jabref/blob/master/src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java

You can simply expand that for a new test case.
Some general information about contribution can be found in our contribution guide https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md

**Comment by lynyus** [comment]
Hi, @steph37tours!
I guess the first step is to check if there are spaces in the localisation strings.
`src/main/resources/l10n` contains all localisation files. A possible check should detect any spaces in these files that are not commented out (using the `#`).

**Comment by steph37tours** [comment]
Thank you for your quick answers ! I look at this and I come back.

**Comment by steph37tours** [comment]
Firstable, thank you very much for your help !
So I write the beginning of the method. But I'm not sure for instance how to parse all the properties object. And after that, how to replace the spaces by an underscore.
It was too my first pull request.

**Comment by lynyus** [comment]
Well, I think you shouldn't replace the spaces, just let the test fail, so the author will be notified, that there are invalid characters in the localization properties file.

regarding the parsing, just read in all properties like done in the other tests of https://github.com/JabRef/jabref/blob/master/src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java and then check if there are spaces in the strings.

**Comment by steph37tours** [comment]
I just push again. I think it's good. Does I have to make a new pull request ?

**Comment by steph37tours** [comment]
I use properties.replace(" ",""). It was not possible to use replaceAll. I think it's not a trouble as long as the assertEquals compare the String object, with the modified. Just one replace make a difference.

**Comment by lynyus** [comment]
Let's discuss the PR in the [PR-Thread](https://github.com/JabRef/jabref/pull/3198).

**Comment by aayush2610** [comment]
Hi Guys,
I would like to help if the issue is not yet solved. It would be great if I
could get some context.

Thanks

**Comment by lynyus** [comment]
Hey @aayush2610, Mr. @steph37tours  is working on this at #3198, and I'm sure he will resolve this soon. 

Feel free to jump into any other [issue](https://github.com/JabRef/jabref/issues). There are some labeled with [beginner](https://github.com/JabRef/jabref/labels/beginner) which we think are easier to resolve, even if you are new to JabRef.

**Comment by lynyus** [comment]
fixed in https://github.com/JabRef/jabref/pull/3198
