### ISSUE TITLE
Dragging an entry to group brings the display to the beginning of the datafile

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3216]
JabRef 4.0-beta3
Windows 7 6.1 amd64 
Java 1.8.0_144

Steps to reproduce:

1. open a large database
2. go to the end of database display
3. drag an entry to a group on the left group panel
4. The display jumbs to the beginning of the database

This is most inconvenient since one is loosing the focus of the entry which was dragged. With some 2000 entries you have restart searching for that entry. Not at all recommended and I think newly introduced.

**Comment by AEgit** [comment]
Might be a duplicate of https://github.com/JabRef/jabref/issues/3176

**Comment by bernhard-kleine** [comment]
I checked #3176, I am not convinced it the same issue: The display of entries should not be dependent of whether you have dragged any entry to the group panel. It should stay as it was before the dragging. 
my 5€-cts
Bernhard

**Comment by AEgit** [comment]
I agree with you, that this should not happen. The reason I think this might be a duplicate of https://github.com/JabRef/jabref/issues/3176 is because I have the impression that the current development version of JabRef generally has a problem in updating the main table and keeping the focus on items on the main table. If that's the case, then both https://github.com/JabRef/jabref/issues/3176 and this problem are caused by the same issue.

**Comment by bernhard-kleine** [comment]
This is still the behaviour of fresh Jabref 4.0
