### ISSUE TITLE
JabRef CSL issue

### ISSUE THREAD

**Issue by cMadan** [JabRef/jabref#3259]
JabRef version 4.0 on Windows 10

Using the "European Journal of Neuroscience" formatting renders the journal name twice, once in italics and once in regular text. The CSL file is correct and works in other programs correctly. I tried 'adjusting' the CSL to only show the journal name once (in italics) but was unable to.

**Comment by AEgit** [comment]
Just a guess, but could it be that the item in your Bibtex file contains the journal name twice, i. e. does the journal name appear in the "journal field" and in another field (that has happened to me before, when automatically importing Bibtex files provided by the publisher)? If that's the case, the issue is problem unrelated to CSL.

**Comment by cMadan** [comment]
No, that doesn't seem to be the case here.

**Comment by Siedlerchr** [comment]
@halirutan  As you are currently into the CSL stuff, could you take a look at that issue, here?

**Comment by halirutan** [comment]
@Siedlerchr @cMadan I guess I can explain what happens and it looks like the mistake is coming from `de.undercouch.citeproc.bibtex.BibTeXConverter#toItemData(org.jbibtex.BibTeXEntry)`. The rundown is as follows:

- User clicks on an entry which is then sent to create the preview.
- We create an `org.jbibtex.BibTeXEntry` instance from the information we have. Since we only have the journal name in one field, we create only one field inside this `BibTeXEntry` with key "journal` (or smth similar) and the name of the journal as value
- This created instance is sent to `de.undercouch.citeproc.bibtex.BibTeXConverter#toItemData(org.jbibtex.BibTeXEntry)` which creates the representation that is used in the `CSL` formatting engine

The last step creates [the following representation](https://hastebin.com/fasuzeguxa.json) for a simple article entry. Please note the double entry `collection-title` and `container-title`. When you look at the `.csl` file you can easily spot what happens. There is a macro `containter` with several conditional expressions. An "article" goes to the last `else` branch which states

``` xml
<else>
    <group prefix=". " suffix="," delimiter=", ">
        <text variable="container-title" form="short" font-style="italic"/>
        <text variable="collection-title"/>
    </group>
</else>
```

My guess is that this is really meant to contain the Journal name and the Collection name, but I'm unable to create an example where this works. I tried with an example of `InCollection` but I always end up with a double "BookTitle".

**Comment by Siedlerchr** [comment]
@cMadan 
Could you please try the latest snapshot and report back if it works or still is an issue?
http://builds.jabref.org/master/
There have been changes to the CSL engine.
