### ISSUE TITLE
The display on a high-resolution screen is kind of messy on Windows 10

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3276]
JabRef version `4.0` on  `1.8.0_144`

See the following two screenshots:

![image](https://user-images.githubusercontent.com/13306020/31306286-48443fca-ab7f-11e7-93de-ff9bd1743333.png)

![image](https://user-images.githubusercontent.com/13306020/31306290-5e43c3a4-ab7f-11e7-9070-51edef169f7a.png)

The menu titles seems to be too big and the font size for groups and entries is too small, which renders a kind of messy display. I think maybe Windows might be to blame for part of the problem, but I have seen many successful instances, such as `RStudio`, `MATLAB`. Hopefully, `JabRef` will handle this better, too.

**Comment by tobiasdiez** [comment]
You can increase the font size in the preferences to get a somewhat working version. But I agree that a lot has to improve on high-res displays.

**Comment by psychelzh** [comment]
Thank you. It would be much appreciated if it supports high-res displays, now I have to resort to the so-called System-wide UI enhancement, which unfortunately blurrs the fonts as following screenshot.

![image](https://user-images.githubusercontent.com/13306020/31307327-b60e80d2-ab94-11e7-9aab-2a6349c8457f.png)

**Comment by lenhard** [comment]
Apart from the font and icon sizes (that you can already increase right now), what are concrete actions that we can take to improve the user experience on high-res displays? I am a bit at a loss as to what to do about this exactly.

**Comment by psychelzh** [comment]
FYI, what I have lastly posted is not the effect after the change of font and icon sizes, but the effect of the Windows's System Wide Enhancement.

I think the problem here is that although the high-res displays will enlarge fonts automatically, it only affect the menu titles, whereas the entries and groups do not change font size. The asynchronous behavior result into the inconguent appearances between entries/groups and menue titles. Just as the screenshots in the main post.

**Comment by matthiasgeiger** [comment]
You can also increase the size of the main table font by hitting CTRL-+ as in the web browsers

**Comment by Siedlerchr** [comment]
I am using Win 10 as well, 1900x1200 on 24" Display, Scaling is 100%
On my desktop it looks fine, but on my notebook (smaller resolution) I have very small fonts.

![grafik](https://user-images.githubusercontent.com/320228/31308687-2711e144-ab7b-11e7-9597-32b25ae9cf6f.png)

You should check the options and remove the checkmark at override  menu table. that made it look appropriate for me 

![grafik](https://user-images.githubusercontent.com/320228/31308690-2ec66216-ab7b-11e7-9952-30ec6dc7d505.png)

**Comment by psychelzh** [comment]
Thank you.

Maybe it is because of the scaling. I use two different screens, [one](https://www.microsoft.com/en-us/search/result.aspx?q=Surface+Pro+4) smaller in size (`12.3"`) but higher in resolution (`2736 * 1824`), so a 200% scaling is used; [the other](https://www.amazon.com/Dell-P2416D-Monitor-23-8-Inch-Screen/dp/B00ZFFN656) larger in size (`23.8"`) but lower in resolution (`2560 * 1440`), so a 150% scaling is then used. Only that 100% scaling is not appropriate here.

I guess the problem here is to support the scaling larger than 100%.

**Comment by tobiasdiez** [comment]
@lenhard: here is a bunch of things that we should change so that JabRef works out of the box on high resolution displays:
- Calculate a good default font size based on the resolution and dpi. (`-fx-font-size` is also used as the base for control sizes)
- Specify sizes in `em` instead of `px` to ensure good scaling (including the DPI)
- Turn off the "java dpi fixing" to get a crystal clear view

(these are all specific to JavaFX since I wouldn't spend much energy in improving the old swing controls)

**Comment by koppor** [comment]
Does any setting of "Override high DPI scaling behavior" help? See also https://intellij-support.jetbrains.com/hc/en-us/articles/115001260010/comments/115000141770

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/2409

**Comment by psychelzh** [comment]
@koppor Thank you for your attention. I have posted one screenshot above, which displayed the effect of turning on the "Override high DPI scaling behavior" feature on Windows 10 after its Creators' Update. It relieves the problem a bit, but just as I said, the characters are rather blurring.

**Comment by shortda** [comment]
I'm having a similar problem with microsoft's surface book. The native resolution is 3000x2000 and there aren't good options for changing it. I set the windows display text scaling to 250% for handling documents because fonts are too small otherwise. JabRef is unusable with these settings but I would very much like to get it running again! The following screenshots are with JabRef's default settings, with com.jgoodies.looks.windows.WindowsLookAndFeel look and feel, and with com.jgoodies.looks.windows.WindowsLookAndFeel plus manual overrides for font and icon sizes. The size settings in the third screenshot are "menu and label font size" = 32, "size of large icons" = 64, "size of small icons" = 48, and "table row height padding" = 32.
![defaultsettings](https://user-images.githubusercontent.com/13423221/33687740-e63b5c9e-da8d-11e7-9e16-0696b0c4098f.png)
![goodieslookfeel](https://user-images.githubusercontent.com/13423221/33687745-ebabb20a-da8d-11e7-8243-98e782dfea4a.png)
![override32-64-48-32](https://user-images.githubusercontent.com/13423221/33687749-ef741b52-da8d-11e7-81cf-c8451479d532.png)

**Comment by psychelzh** [comment]
@tobiasdiez @lenhard @matthiasgeiger @Siedlerchr @koppor  Are there any updates for this issue?

**Comment by koppor** [comment]
help wanted

**Comment by psychelzh** [comment]
Okay, thanks. Looking forward to some expert's solution! 😃

**Comment by spicydonkey** [comment]
@psychelzh 

> Thank you for you advice. I have tried Ctrl + -, the font size of main table decreased; but when I tried Ctrl + +/= or Ctrl + Shift + +/=, the font size of main table just did not increase.

I had this same issue plus all the ones you are having *PLUS* when certain new windows open, they are out of the page and I must Win+space+M(ove) it with keyboard into page... 

Good news. The Ctrl + PLUS bug can be solved by re-mapping it to your favourite keyboard stroke. Apparently, my PC thinks Ctrl + "PLUS" is Ctrl + "EQUALS"... No idea what's going on.

**Comment by Siedlerchr** [comment]
Another reason to move towards java 9, there recently have been some improviements:
http://news.kynosarges.org/2018/01/26/javafx-dpi-scaling-in-java-9/

**Comment by arnyeinstein** [comment]
Hi
I use Jabref on my notebook and at home with an external 4k monitor connected to my notebook.
I only can use it on my 4k monitor if I adjust the font-sizes, but when I then work on my notebook, everything is too big. Any idea on how to solve this? I am thinking of having two instances, one for my notebook and one for my 4k. But other ideas are welcome
Cheers
Renger

**Comment by Siedlerchr** [comment]
We are currently working on converting the whole maintable and all other windows to JavaFX. You can try out the version here https://builds.jabref.org/maintable-beta/
Note that not all may work as expected as we are still working on it. 

Otherwise 
You could use the portable version and have two instances of it then

**Comment by psychelzh** [comment]
@Siedlerchr Awesome job! The new UI is so modern that it makes `JabRef` more fascinating than ever. And the high resolution problem is seemingly solved, too. Look at the screenshot.

![image](https://user-images.githubusercontent.com/13306020/37249002-4b547554-2519-11e8-96c6-934ce96b662b.png)

**Comment by Siedlerchr** [comment]
Thanks for the feedback! Some of the dialogs and settings are still on the old gui so they might look very small 
We will soon release a stable version with the old current gui.
Then we will focus on stability in the new maintable version. It's still missing some features and needs some performance tuning. You are happily invited to test it and report bugs you encounter.

**Comment by psychelzh** [comment]
I am very glad to test this version with the fancy UI. 💯

**Comment by psychelzh** [comment]
I would say the UI's other than maintable need to be consistent with maintable, for now they are not upgraded to the new design.

`Group Edit`:
![image](https://user-images.githubusercontent.com/13306020/37550670-3d22bc5e-29cc-11e8-98c8-18e97c218236.png)

`Entries cleanup`:
![image](https://user-images.githubusercontent.com/13306020/37550675-551f504c-29cc-11e8-9239-ee9bf68fef6b.png)

And etc.

**Comment by psychelzh** [comment]
And the `TEXStudio` icon is a little smaller than other icons:

![image](https://user-images.githubusercontent.com/13306020/37550690-947f1ba0-29cc-11e8-92bb-07d31ef153e1.png)

**Comment by g-bull** [comment]
This solved the problem for me: https://stackoverflow.com/questions/30555401/java-disable-dpi-aware-not-working
Except I had to create a JabRef.exe.manifest, in the manner described for java.exe, next to the JabRef.exe.
Works fine now. 
JabRef 4.2
Windows 10 10.0 amd64  (with latest update)
Java 1.8.0_171

**Comment by Siedlerchr** [comment]
Most of the issues should be fixed in the current master https://builds.jabref.org/master
There are still some dialogs which are in the old swing and not yet converted and tracked in  #3861 
Therefore I would close this one here. Feel free to reopen of the issue exist.
