### ISSUE TITLE
Can the context-menus for the field editor be reused?

### ISSUE THREAD

**Issue by halirutan** [JabRef/jabref#3335]
A great deal of work was done lately on the entry editor. One last thing that waves a red flag there are (surprise, surprise) the context menus. Believe it or not, those tooltips are waste more memory than you would think considering those are simple text things.

Let me make it clear: One run with opened editor through the 200 entry example bibfile. This does now only use 30MB of memory on its way. The "required tab" is of course always visible and therefore, the contents of this tab needs to be initialized and filled with data. Now hold your breath: 22MB of those 30MB are the context menus for the text fields.

<img width="1550" alt="screen shot 2017-10-23 at 11 50 28" src="https://user-images.githubusercontent.com/511683/31882869-709c03d4-b7e8-11e7-849f-015e6a536862.png">

I have seen that for each of those text fields, every tooltip and every context menu is a new instance. The question is, is it possible to make this more static. Tooltips can surely be initialized once and reused. But maybe it is possible to do this to a certain extent for the whole context menu like the `CaseChangeMenu`? Tooltips alone would account for 12MB and basically, only the 4 classes under `package org.jabref.gui.fieldeditors.contextmenu` need to be changed.

Is this possible?

**Comment by tobiasdiez** [comment]
Thanks again for your investigations!

You can try to modify
https://github.com/JabRef/jabref/blob/d922e5597f7496515ca5e8d274190539405cc5ae/src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java#L54-L63
to take a `Supplier<List<MenuItem>>` as the argument (instead of the already created list of items) and generate the list in the overriden `populate` method. This might work (depending on whether `populate` is always called or only when the context menu is needed).

But I wouldn't spend to much energy on the context menus. If this is now the biggest contributor, we are in quite a luxury position and think we shouldn't overpush.

**Comment by halirutan** [comment]
@tobiasdiez Thanks for the tip!

**Comment by lenhard** [comment]
Fixed with #3340
