### ISSUE TITLE
Html code in the tooltip of the search field

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3381]
```
JabRef 4.1-dev--snapshot--2017-10-31--master--42ea6bc9c
Linux 4.12.12-gentoo+ amd64 
Java 1.8.0_152
```
There is html code in the tooltip of the search field (click to enlarge the screenshot)

![jabref_376](https://user-images.githubusercontent.com/298682/32246612-d24045da-be7f-11e7-8fb4-6411cb6ab6f4.png)

**Comment by jupf** [comment]
Hey, I looked into this issue and would be glad to take it.

It's possible to display a WebView inside the Tooltip which renders the HTML as a graphic. Or was there any other solution intended?

Does anyone know why the background of the search field tooltip is black-ish? Shouldn't it be grey or light blue? Seems strange to me and I couldnt find out why.

This is my first approach to contribute in an open source project, i already read your contributing guide. Is there something else to consider?

**Comment by jonasstein** [comment]
As user I would expect plain text with proper line break

**Comment by jupf** [comment]
It would be text, but with the possibility to make some words e.g. bold

**Comment by Siedlerchr** [comment]
Hi, thanks for your interest in this issue. Both javafx and swing support html toolips out of the box. 
See https://docs.oracle.com/javafx/2/ui_controls/tooltip.htm
. Regarding the color, I think it depends on the look and feel you choose.

Some General Tipps for contributing, make sure to set up your IDE accordingly so that you have the code formatter rules we use.
Just create a new branch and add a PR. If you have questions or need help, just ask

**Comment by Siedlerchr** [comment]
I think you should use the html option, to make sure the author names are shown correctly

**Comment by tobiasdiez** [comment]
@jupf Thanks for your interest in contributing!

JavaFX actually does not support HTML in its controls and I think this is a good design. Instead of using a webview (which would work in principle), JavaFX introduced the [TextFlow](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextFlow.html) to support rich text.
Thus I would propose to change https://github.com/JabRef/jabref/blob/ebbeb1d249edf7134abf92d24c2031ae54d19881/src/main/java/org/jabref/logic/search/rules/describer/SearchDescriber.java#L6 to return a `TextFlow` instead of `String`. Note that as a consequence of this the `search/rules/describer/` package should move to gui instead. If you feel not yet comfortable enough to do this refactoring, it is no problem - we can help you with it or take over this final step.
If you have any questions, feel free to ask them here (or open a PR with your initial progress).

**Comment by jupf** [comment]
Okay, I will open a PR as soon as there is progress to discuss

**Comment by Siedlerchr** [comment]
@jupf  Any updates on this?

**Comment by jupf** [comment]
I have a few open questions after making the main changes proposed from @tobiasdiez. I detailed them in the pull request. Sorry this took so long

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version thanks to @jupf. Could you please check the build from http://builds.jabref.org/master/. Thanks!
