### ISSUE TITLE
Internet searches return only first page of hits (20 for Google Scholar, 50 for PubMed)

### ISSUE THREAD

**Issue by heseber** [JabRef/jabref#3392]
JabRef version 4.0 on Windows 7

Steps to reproduce:

Use any pubmed search which returns more than 50 hits on the original PubMed site. Running the same query from JabRef only returns 50 hits. In previous versions of JabRef (3.x) I did not observe this behavior. I did not find a configuration setting which would set an upper limit for the number of returned entries.

**Comment by heseber** [comment]
... and Google Scholar only returns the first 20 hits.

This looks to me as if you only retrieve the first page of results and do not check for additional result pages. This worked on previous versions, so I guess this is a bug introduced with 4.0.

A fix would be urgently needed. Thanks for your help!

**Comment by lenhard** [comment]
That is by design. We had some users who were using the fetchers and got problems with their administrators, because JabRef was sending too many requests to some database. Also blocking on Google Scholar happened very frequently.

People were very angry and pissed at us because of this. And because we do not like getting angry messages, we made the decision that JabRef is no tool for mass download of citations. I understand your frustration with this, but I hope you are equally understanding when it comes to our position.

The limits are hard-coded and there's no chance of changing this, except by recompiling JabRef. This would be very easy for you, you just have to change this line in the code: 

https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/importer/fetcher/MedlineFetcher.java#L47

Alternatively, you can just export your search directly from the medline website, store it in some local file, and import it into JabRef.

**Comment by Siedlerchr** [comment]
See also: 
https://github.com/JabRef/jabref/issues/2360

**Comment by heseber** [comment]
Thanks for explaining, and I can understand your intention. However, it would be very helpful if these limits were more prominently shown in the result list and not just explained somewhere in the help. I have been using JabRef for many years (thank you!) and typically don't need the help any more. However, these newly introduced limits really took me by surprise and I only noticed this after a while when I figured out that some references were missing in the search results.
