### ISSUE TITLE
LaTeX commands not displayed in the table

### ISSUE THREAD

**Issue by olivierfruchart** [JabRef/jabref#3408]
JabRef version
JabRef 4.1-dev--snapshot--2017-11-06--master--f43ed43df
Windows 10 10.0 amd64 
Java 1.8.0_77

Steps to reproduce:

1. Enter a LaTeX command in a field, such as "This is a \prl manuscript" in the Title textbox, or "\prl" in the Journal textbox. 

In the list of entries, the Title reads: "This is a manuscript", while the journal reads empty: "". 

In the "Entry preview" window the title reads: "This is a prl manuscript", while the journal reads"prl". 

This is particularly annoying if one uses LaTeX commands in place of the journal, as I have always done: \prl, \apl etc. Now, I have no view of hte journal in the entry table. The issue appeared at JabRef 4.0.

**Comment by lenhard** [comment]
Hi Olivier,

in 4.0, we've replaced the incomplete and buggy LaTeX to unicode conversion (used in the main table) with a quite sophisticated library: https://github.com/tomtung/latex2unicode That way we get mathematical symbols and similar things displayed correctly.

This library removes all non-standard tex commands, which is probably what you are seeing. The entry preview is different, because it displays HTML.

Before you ask: We won't be switching back to the old version, because it was broken in many instances and very hard to maintain. And we will also not implement tex processing on top of it, because we simply have no resources for this. That's why I am marking this issue as "won't fix".

If you want to change the way in which LaTeX is displayed in the main table, e.g. keeping non-standard commands, the best thing you could do is to create a feature request at https://github.com/tomtung/latex2unicode JabRef will use whatever latex2unicode produces and if it had an option to keep unknown commands, we could integrate that.

**Comment by olivierfruchart** [comment]
Dear Jörg,

  I thank you for your prompt and precise answer, which makes perfect sense. What you suggest is exactly what I was thinking of. I accordingly posted an issue on latex2unicode:

https://github.com/tomtung/latex2unicode/issues/8

Kind regards, and many thanks for your efforts for the community.

Olivier.
