### ISSUE TITLE
JabRef Java version check does not work correclty if java9 and java8 are installed parallel

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3434]
Have both java 9.01 and java 8 installed: (latter one is default)

![grafik](https://user-images.githubusercontent.com/320228/32846827-978fba74-ca28-11e7-8ed9-9c12362e19e5.png)

C:\Windows\System32>java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by halirutan** [comment]
Well, that is quite nice. I'm using

```
JAVA_VERSION = System.getProperty("java.version");
```

to extract the java version from the running JabRef instance. I believed this is the standard way of extracting this information. I have not the slightest idea why this happens. Can you set a [break-point here](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/util/JavaVersion.java#L21) and check other properties inside the debugger? You could use the static methods of `org.apache.commons.lang3.SystemUtils` to access all important information.

**Comment by Siedlerchr** [comment]
That's odd: I debugged from Eclipse and got correctly: java version 1.8.0_152 and running it from gradle, too:
java version 1.8.0_152

When I run the snapshot's JabRef.exe I get the above dialog. when I run it from command line  java -jar in the snapshot folder C:\Program Files\Jabref , I get no dialog.

**Comment by halirutan** [comment]
@Siedlerchr That narrows it down. It seems that the "default" JRE that JabRef uses is not the "default" JRE that you have set on your system. Unfortunately, I have no dev-environment at all on my windows partition, but I'm sure someone should know what exactly happens when JabRef is packed into an exe.

**Comment by tobiasdiez** [comment]
Its definitely a problem with the JabRef.exe file. I have java 8.131 and 8.151 installed, but JabRef.exe runs with the older version.

Jabref.exe output
```
JabRef 4.1-dev--snapshot--2017-11-13--master--c1d425a31
Windows 10 10.0 amd64 
Java 1.8.0_131 
```

java -jar output
```
JabRef 4.1-dev--snapshot--2017-11-13--master--c1d425a31
Windows 10 10.0 x86 
Java 1.8.0_151
```

**Comment by halirutan** [comment]
I had a look at the `install4j` config. There are several points that we should probably think over. First, the general Java Version setting does not reflect what we try to enforce:

![install4j1](http://i.imgur.com/pPkKNIR.png)

We should set the maximum version to 1.8 as long as long as we are sure version 9 will not work. Additionally, this screenshot gives a clue what might go wrong with windows. As you can see, it uses the version from the registry. Can someone check what you have set there? Here are two related SO posts about this [[1](https://stackoverflow.com/questions/5492937/windows-ignores-java-home-how-to-set-jdk-as-default), [2](https://stackoverflow.com/questions/551668/how-do-i-set-the-default-java-installation-runtime-windows)].

Furthermore, was there a good reason for not enforcing the bundled JRE?

![install4j2](http://i.imgur.com/Qlr0azo.png)

Wouldn't it be better to include the JRE without installing (if that's possible)? With this, we could ensure the correct Java version. Developers will most of the time debug the application through the IDE or start it with `java -jar ...` so that they can use whatever version they want to test. Any suggestions?

**Comment by Siedlerchr** [comment]
`C:\ProgramData\Oracle\Java\javapath` is a symlink to the actual java path. This value is added to the PATH variable.
The old vars like JAVA_HOME etc do no longer exist on my win10 sys. (Enter set in cmd and you get a list of all env variables you have).
So it should be sufficient to just check the path var
