### ISSUE TITLE
Biblatex dates like "19uu" not saved.

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3483]
JabRef 4.1-dev--snapshot--2017-12-03--master--56aa71671
Linux 4.10.0-40-generic amd64 
Java 1.8.0_151

The "Date" field will not accept a Biblatex-legal date of the form "19uu".  One can enter the date, but on moving the cursor to another field, the date is erased.

**Comment by Siedlerchr** [comment]
There is also an issue for planning the support/integrity check of all dates #2753

**Comment by Siedlerchr** [comment]
For the moment we need to decouple the date picker from the field

**Comment by Siedlerchr** [comment]
I looked into the code and the problem is that there is a StringConverter, which tries to convert to a date or TemporalAcessor.                
DateEditorViewModel         
https://github.com/JabRef/jabref/blob/f0b90baf80aa9b2bcc48991923637e3ed0861436/src/main/java/org/jabref/gui/fieldeditors/DateEditorViewModel.java#L41

**Comment by tobiasdiez** [comment]
So as soon as #2753 is implemented, this should work automatically, right? I remove this from the 4.1 milestone as a fix seems to be a longer story.

**Comment by Siedlerchr** [comment]
Could we as a workaround just return the original date if parsing was not successful?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
This is so great how to take care of Issues. Ignore them for months and then let them close by a bot.
