### ISSUE TITLE
Only log failed junit tests in travis

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3510]
Currently, all stuff from all tests is logged and printed out.
This makes it really hard to identify real failed tests, because some test throw exceptions, which are expected.
Nonetheless the internal JabRef logger log4j2 logs all this stuff, which makes it hard to find the real probelmatic issue

**Comment by tobiasdiez** [comment]
I actually liked the output since it shows that we have a lot to improve 😄 In my opinion, a successful test should not log any errors (and actually also no warnings). But currently we have a lot of error-catcher that log and then rethrow the exception, witch lead to these verbose logs. I would attack it at the root, i.e. fix the code.

**Comment by koppor** [comment]
@Siedlerchr Could you provide screenshots of the logs or a pointer? So that quick-readers get an impression? - On Windows, I recommend [snipaste](https://www.microsoft.com/de-de/store/p/snipaste/9p1wxpkb68kx).

**Comment by tobiasdiez** [comment]
@koppor It's on every Travis build, e.g. https://travis-ci.org/JabRef/jabref/jobs/314497777 and look at the output of the "check" job.

**Comment by Siedlerchr** [comment]
Maybe we can add it to the .gitignore files and so you can locally enable you debug mode and it won't affect the remote (travis) one

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
