### ISSUE TITLE
Gradle task localizationUpdate does not work

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#3573]
`localizationUpdate` leads to resorting and adding of many language keys due to the recent changes. Thus, at the moment it is not possible to remove a pair from the english file and propagate this change to the other languages.

**Comment by koppor** [comment]
I think, I can work on that in January. Meanwhile, you should be able to log in at crowdin and remove the key there. Need to make you maintainer there, though.

**Comment by koppor** [comment]
Please DO NOT remove obsolete keys in other language files. This is done by crowdin automatically: https://github.com/JabRef/jabref/pull/3585

I will remove the task completely or have it output that there is no need for a check, because of crowdin!

**Comment by tobiasdiez** [comment]
@koppor Right now we have tests in place that require to remove obsolete language keys from other languages. It would be nice if we could remove the `localizationUpdate` step completely (less things to do manually), but then the tests should be adopted accordingly.

**Comment by koppor** [comment]
I thought, I adapted the tests. Seems, I missed something. Have to check...

Am 05.01.2018 12:01 schrieb "Tobias Diez" <notifications@github.com>:

**Comment by tobiasdiez** [comment]
This test fails if you remove language keys from the english file but not from the others:
https://github.com/JabRef/jabref/blob/3b2d35f28f87038b1824bf1178d264cfb1984597/src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java#L50-L51
(If crowdin handles this case automatically, then there is no need for this test, right?)

A few other cases still refer to the `localizationUpdate` (which should not be invoked, right?), e.g.,
https://github.com/JabRef/jabref/blob/3b2d35f28f87038b1824bf1178d264cfb1984597/src/test/java/org/jabref/logic/l10n/LocalizationConsistencyTest.java#L140-L142

**Comment by koppor** [comment]
It is not as straight-forward as I thought.

English escapes more characters than non-English:

    Executing\ command\ \"%0\"...=Executing command \"%0\"...

German:

    Executing\ command\ "%0"...=AusfÃ¼hrung des Kommandos "%0"...

**Comment by Siedlerchr** [comment]
Any updates on this? I think we don't need the script anylonger or?

**Comment by koppor** [comment]
A admin might still need it. Quoting: https://github.com/JabRef/jabref/pull/3635#issuecomment-357869322

> That task won't be necessary for all contributors, only for maintainers wanting to cleanup the files (like sorting, ...). However, this is not absolutely necessary anymore since Crowdin basically takes care.

I think, I just close it and put an "on-hold" label on it.

**Comment by koppor** [comment]
Maybe we need to rework the quotes in the English file.

**Comment by Brainsucker92** [comment]
Finally I found some time to take a closer look at the syncLang.py script. To be honest, it's pretty difficult to determine the exact origin of this problem. My very first thought was that there might be a problem with different character encodings. The script always assumes the content of the property files is written in UTF-8 encoding. But Eclipse is using ISO-8859-1 encoding by default which is determined by the content type. After some more research within the script I found some really nasty little mistake, if you have a closer look at lines 52 and 53:
https://github.com/JabRef/jabref/blob/01d3d4b95b9295e681da5e20f0b0c7c3d07c5e22/scripts/syncLang.py#L52-L53
I'm not 100% certain if this will fix the whole problem but we're going to find out real soon, I guess.

I pushed the fix for this issue here:
https://github.com/Brainsucker92/jabref/commit/ea5d56e4a7a8bcb25c2bb00dc3651c807bc9739e

Additionally I added a new class that allows the script to locate it's position within the repository.
This might be helpful at some point.
