### ISSUE TITLE
Special fields are not saved and CLEARED

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#363]
The special fields (priority, read status, printed, ranking) etc. are not stored if I choose 
"Write values of special fields as separate fields to BibTeX".

Moreover, and this is even worse, if you load a database which contains these fields in the form `field={value}` then these information are lost on save.

**Comment by koppor** [comment]
Maybe we should drop the functionality to write the special fields as fields and only use the keyword synchronization?

**Comment by tobiasdiez** [comment]
No, please not! Keywords should describe the content of the document and not some state in JabRef. They are understood (although often not printed) by biblatex, so I would even vote against making keyword synchronization the default option. Special fields can be easily filtered out by biblatex, but modifying the keyword field to not contain "prio3" etc. is very difficult.

**Comment by koppor** [comment]
I used the words as keywords in my bib files and added the special fields functionality as rendering possibility. While editing an entry, I sometimes also add keywords manually instead of using the UI to set something.

Maybe the special fields are "only" a special rendering of the group functionality and should be replaced completely by groups. JabRef then introduces predefined groups ("prio1", "printed", ...) and adds a special rendering in the table for this groups. Possibly, this rendering can be configured completely freely :innocent:.

**Comment by tobiasdiez** [comment]
Good idea to merge them with static groups (at least on the code level). However, should static groups still be saved as an comment at the end of file or be in-lined as a special field `groups=statica, staticb`?

**Comment by matthiasgeiger** [comment]
Sorry currently not that much time - but has anybody checked whether is actually broken? 

At least a few days ago this was still working for me?!

**Comment by koppor** [comment]
Oh, it works fine here, even with the synchronization in the fields. @tobiasdiez Could you export your preferences, reset them and try again? If that works, please export the preferences and compare them with the old version.

**Comment by tobiasdiez** [comment]
I couldn't reproduce this error in the current master (to be honest, I don't know what happened exactly. At some point, I just lost all my special fields). So I close this...

**Comment by koppor** [comment]
Maybe there was an NPE somewhere. If that ever happens again, please show into the error log.
