### ISSUE TITLE
Static group not working

### ISSUE THREAD

**Issue by piovisqui** [JabRef/jabref#3802]
I'm on JabRef 4.1 and believe that bug #2408 (or something similar) is back.

I created static groups, however all entries from the database appear on it. The ordering is random. I see 29 correct entries, then 600+ entries not assigned to the group, then 10 correct and the remaining database.

![bug jabref](https://user-images.githubusercontent.com/11858817/36927344-bccbcd3c-1e5b-11e8-9f18-1112355ce88e.png)

JabRef 4.1
Linux 4.15.4-200.fc26.x86_64 amd64 
Java 1.8.0_161
java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
Fedora 26

**Comment by stefan-kolb** [comment]
@tobiasdiez Is this reproducable somehow?

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

Please make a backup of your db before using this version.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by piovisqui** [comment]
I'm currently on Windows using JabRef  4.3.1 and the bugs seems fixed. Thank you.
