### ISSUE TITLE
Related Article style

### ISSUE THREAD

**Issue by halirutan** [JabRef/jabref#3816]
Currently, the *related article* tab has a very different style than the rest of the application. On my machine in looks like this:

![old](http://i.imgur.com/2hfKKhe.png)

I propose to make this (and later the article preview as well) more consistent by styling the used *webview* correctly. I hacked this quickly and I'm giving this issue for discussion as I'm having some questions regarding this. With the fix applied it looks like that. Not perfect, but better:

![new](http://i.imgur.com/isjouB1.png)

## Patch

In `org.jabref.gui.entryeditor.RelatedArticlesTab` we apply a CSS style to the used web-engine

```
browser.getEngine().setUserStyleSheetLocation(
    getClass().getResource("RelatedArticlesWebView.css").toString()
);
```
In addition, I have thrown out all explicit style settings in the `convertToHtml` method in this class.
The used CSS file needs to be created and here, I put it in the same folder as we do with all the JavaFX CSS files too. It contains currently the *sample* content

```
html {
    color: #24292e;
    font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
    font-size: 12px;
    font-style: normal;
    font-variant: normal;
    font-weight: 400;
    line-height: 20px;
}

a {
    color: #50618F;
    text-decoration: none;
}

a:hover {
    color: #2b3357;
}

.mdl-title {
    font-weight: bold;
}

.mdl-year {
    font-weight: bold;
}
```

To make it work, we need to adjust the `org.jabref.logic.importer.fileformat.MrDLibImporter`, because it currently uses HTML code that contains explicit font and color settings. Therefore, I changed line 214 to

```
if (qName.equalsIgnoreCase("snippet")                                
        && attributes.getValue(0).equalsIgnoreCase("html_and_css")) {
    snippet = true;                                                  
}                                                                    
```

to make it use HTML from MrDLib that marks the text with style classes. Here are some questions:

- Is the `MrDLibImporter` used for something else so that changing the HTML style we catch breaks something?
- How can we ensure a CSS style that matches our FX style? JavaFX CSS files are extensions to normal CSS files and cannot simply be used. This means we have to repeat or manually set font-sizes and colors there. Is it really that hard or has someone a better idea? Specifically, I would like the fonts and font-sizes to match.

The patch file is here if someone is going to work on this and doesn't want to start from zero

[Improve_style_of__related_article_.patch.zip](https://github.com/JabRef/jabref/files/1791374/Improve_style_of__related_article_.patch.zip)

**Comment by tobiasdiez** [comment]
It looks indeed better now and your code changes sound reasonable to me. The MrDlib Importer is only used for the related articles tab. I'm not aware of any way to reuse the JavaFX css for the webview. I think, we should consider to use the information provided by MrDlib (like author/title/...) directly and display it using JavaFX controls, instead of playing around with HTML.

For the next time, please open a PR with your preliminary code changes. It makes reviewing code (even unfinished one) easier than a patch file.

**Comment by koppor** [comment]
We agreed in long phone conferences with https://github.com/Joeran that we agree to render the HTML. The reason is that the data structure of MrDLib can change during research. Thus, JabRef might not be able to display the data. We should not have the workload to adapt the results at each change. Thus, we agreed to have HTML as "interface".

**Comment by koppor** [comment]
Fun fact: https://github.com/Mr-DLib/mdl-server/issues/81

**Comment by stefan-kolb** [comment]
@koppor So can we applay this patch now? Looks reasonable to me, currently mrdlib really looks ugly.

**Comment by koppor** [comment]
OK, just go ahead with applying!

**Comment by stefan-kolb** [comment]
@halirutan Are you still interested in applying this patch?

**Comment by halirutan** [comment]
@stefan-kolb I'm not up-to-date with the latest developments. Is the style of the "related articles" panel still different from the main app style? If yes, maybe someone can pick up my suggestion and implement them into the current master.

**Comment by stefan-kolb** [comment]
We did not Change anything yet. I also think that noone of us really has
the resources at the moment. Basically this is up to the mrdlib guys
@connorfos?

Patrick Scheibe <notifications@github.com> schrieb am So., 25. Aug. 2019,
19:42:

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
