### ISSUE TITLE
Ampersand is rendered as &amp;amp; in preview (double HTML escaping)

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3840]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2-dev

Steps to reproduce:

1. look at some entry with ampersand, e.g. Morgan & Claypool

**Comment by j0hannes** [comment]
it's actually the same for any HTML entity: &amp;eacute <- note the missing semicolon

**Comment by psychelzh** [comment]
Actually ,`&amp;` is in the HTML conversion table:

https://github.com/JabRef/jabref/blob/3c54c02e8f56b5aa319892cc5ce5a481bb6b6e21/src/main/java/org/jabref/logic/util/strings/HTMLUnicodeConversionMaps.java#L435

Would you like to give a simple sample of raw `.bib` text for us to test?

**Comment by j0hannes** [comment]
```
@Misc{b1111,
  author = {b, a},
  title  = {c \& d},
  year   = {1111},
}
```
renders as `a b. 1111. c &amp;amp; d.`

**Comment by stefan-kolb** [comment]
```
@Misc{b1111,
  author = {b, a},
  title  = {c \& d},
  year   = {1111},
}
```

renders as

![image](https://user-images.githubusercontent.com/2141507/37412447-385db468-27a5-11e8-849e-8c0787471e84.png)

for me.

**Comment by j0hannes** [comment]
the error happens when you go to "Next preview layout":
![image](https://user-images.githubusercontent.com/3944397/37421403-7f646eba-27b9-11e8-83aa-2092a0ab92d6.png)

**Comment by tobiasdiez** [comment]
This issue probably only happens for CSL-previews and not for the layout based ones. 
I guess there is a problem with our latex to html formatter.

**Comment by KarlMagnusLarsson** [comment]
This is the same thing as I reported, post closed, in Entry preview: Umlaut and ring diacritic not rendered correctly when APA and IEEE preview layout is selected #5779, just like @tobiasdiez  point out.

**Comment by tobiasdiez** [comment]
Thanks to @JosejeSinohui this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by geoffcallender** [comment]
I've spent a couple of hours on this and my findings are very unclear...

I can no longer recreate the issue.

If the Vimeo video has not been pre-loaded, when you tap on it you'll a button for sound (note that we are using muted=1) and another for full screen. If you tap either, then the next bit of speech will cause the video to pause. This can be prevented by setting autopause=0 (by hand, through the inspector). But the odd thing is that if you debug the code, it looks like autopause=0 should already have been in the URL.

VideoUtil.buildVimeoOptions has been returning strings with "&amp;" in them. The manual Vimeo videos end up with "&amp;amp;" in the URL, which might be causing issues. Much better is to use just "&" in the string, then return it to the TML with _new URL(string)_, which will encode it as needed. However, VideoUtil.toEmbeddedURLWithOptions has 9 callers. I will have to return to this issue when I have time to change and test them all.

But... there is no guarantee that the above will solve the issue, because I can't recreate it.
