### ISSUE TITLE
Default sorting of entry table is lost

### ISSUE THREAD

**Issue by miwurster** [JabRef/jabref#3850]
I try to set a default sorting in the options dialog for the entry table, for example, `priority`, `year`, `title`. 
In some case I want to sort the entry table for a quick review/search, for example, to a sorting based on the `bibtexkey` to see all works related to that key.
However, when I click on the column headers, the default sorting criteria in the options is lost (or rather got overwritten) - see before and after screenshots.

I would have expected the following behavior:
* Set a default sorting for the entry table
* On changing the sorting
    * the first click applies the ascending order
    * the second click applies the descending order
    * the third click removes the sorting of that column
* So, after the third click, I expect that the default sorting from the options dialog will be applied again

Would love to hear what others think :-)

Cheers
Michael

---

- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 

Steps to reproduce:

1. Set default sorting options dialog for the entry table
2. Go back to your list of references, click on a column header to change the sort
3. Check the default sorting in the options, they got overwritten

Before: 
![image](https://user-images.githubusercontent.com/2610997/37449226-c7c082dc-2829-11e8-9e9f-e83cd1bef994.png)

After:
![image](https://user-images.githubusercontent.com/2610997/37449490-aa76dd42-282a-11e8-80bd-5b8a3cbd563a.png)

**Comment by Siedlerchr** [comment]
This issue is now fixed in the latest master version. Note, the sort order of the table is now stored directly on change. Multiple columns can be sorted by holding SHIFT + clicking on the column header.
The table sort order in the preferences got removed.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
