### ISSUE TITLE
Magnifier changes colors wrong

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3870]
JabRef offers two search modes: normal search and the grammar based ("advanced") search. See https://help.jabref.org/en/Search#search-modes.

In JabRef 3.6, the initial search was the normal search. This changed in JabRef 3.7 somehow. This seems to be wrong.

Action points:

1. Dig into the change made between JabRef 3.6 and 3.7
2. Find out whether the change is right or wrong. Current assumption: It was wrong
3. Take appropriate action.

Refs https://github.com/JabRef/jabref/issues/3535 and the fix https://github.com/JabRef/jabref/pull/3708

**Comment by lenhard** [comment]
Instead of 1. and 2., can't we just go to 3.? Wouldn't the solution be to switch the coloring (i.e. initially purple and then cyan)? That would be a two-liner I can easily do once you tell me that the assumption is correct.

In adition, I'd like to mention the fact that the whole coloring feature is gone (again) in the maintable-beta branch. If you want it to be preserved, you'll probably need to do some lobbying there.

**Comment by koppor** [comment]
If 3 is easily possible, please go ahead.

**Comment by lenhard** [comment]
Et voilà: #3871

**Comment by tobiasdiez** [comment]
I think the underlying problem is that simple terms like "test" are interpreted as grammar-based searches. This is also the reason why the tooltip shows "This search contains entries" twice in the tooltip (at least on maintable-beta).
