### ISSUE TITLE
Look up fulltext documents does not link existing PDFs

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3874]
It looks like the autolink functionality does not work as expected anymore:

1. I already have a file starting with the correct BibTeX key in my PDF repo
2. It still downloads the file from the web

I expect to pick up the file from the PDF repo instead.

**Comment by stefan-kolb** [comment]
Instead I get this icon in the file tab:
![image](https://user-images.githubusercontent.com/2141507/37759835-14614f14-2db5-11e8-947c-37b0a5c9d30f.png)
When I hover it says it found the PDF and if I want to accept it. 
However, this is 
- hardly recognizable
- a simple click wont do anything
- a double click seems to do the trick
- it still downloads the new PDF in the background

This is a little bit akward.

**Comment by stefan-kolb** [comment]
I guess if we find a matching paper we can just add it without further user confirmation, as it is configured like that in the preferences.

**Comment by tobiasdiez** [comment]
Yes, I implemented that automatically found files are displayed in the entry editor. The display is indeed a bit irritating and we should improve it (tracked in https://github.com/JabRef/jabref/issues/3607).

I don't understand why "auto-link" should download PDF's at all. We have a different button/menu entry for fulltext download, this should suffice.

**Comment by stefan-kolb** [comment]
Ah sorry, I mean `Quality - Look up fulltext documents`. The former behavior was:
- PDF already found link it instead of download it a new.

**Comment by tobiasdiez** [comment]
Ok, I can't remember I changed anything there but I do like the new behavior better and find it logical. If I click on "Look up fulltext document" I expect that JabRef downloads the fulltext for me regardless of whether there are already files linked or not.

**Comment by stefan-kolb** [comment]
Hm, well we could leave it in such a way but then downloa full text would be more appropriate than lookup.
Also, it means two steps for the users. Try to autolink files, iff not found download files.
Formerly, this was integrated in one step.

**Comment by Siedlerchr** [comment]
+1 for Looking up Fulldocuments should first try to search autolink file.
If not found -> Download from web

**Comment by stefan-kolb** [comment]
This is important as a user cannot know if a file already exists in some subfolder for example and then downloads it again.

**Comment by koppor** [comment]
Do we have a "force-download" button?

Currently, I think, the common usecase is that one has one PDF for one entry. I am aware that sometimes, one collect's author copy, presentation, publisher version, ...

Maybe, the file handling can be improved in general... Giving "types" to file entries. Not the media types, but the semantic types (author's copy, publisher, draft, submitted, ...)

Refs https://github.com/JabRef/jabref/issues/98 somehow

**Comment by tobiasdiez** [comment]
I've thought a bit more about this and now I'm more convinced than ever that we should change the name of the action to "Download full text" (as @stefan-kolb proposed) instead of changing the current behavior. I think there are mainly the following uses cases:
- The user created a new entry based off some source (e.g. website). In this case, he just wants to download the pdf (as there is no local file). It would be not harmful to look for a matching local pdf first, because it does not exist (in this use case).
- The user just downloaded the pdf (and renamed it) and the database already contains a matching entry. In this case, the user wants to simply link the new file. If the linking fails (e.g. because the name of the pdf was slightly off) and we would change the behavior, JabRef then downloads a new pdf and the user now has two files for the same entry. Not what he wants. Instead it would be may more helpful if JabRef would realize that there is a similarly named file and propose to link that...
- The user has an entry and does not remember if he already downloaded the corresponding pdf. In this case, he wants to first look for a local pdf and if that does not exist search for an online full text. For this use case, the new behavior would be perfectly fitting. However, it is also currently very easy to proceed: just open the general tab of the entry and you see if JabRef finds a local file (it would be shown in the list of files). Depending on that the user can accept the link or download the pdf.

Thus, the only advantage of the new behavior is saving a single click in the last use case. At the cost of a (in my opinion) somewhat confusing and complex feature. It definitely needs further explanation (since nobody would guess that Lookup = local lookup + online download). Thus, in summary, I'm strongly in favor of a simple "Download full text" feature that everybody understands when reading the action name. Long live "Do one thing, and do it well" ;-)
