### ISSUE TITLE
Suggestion to remove the ability to download multiple fulltexts at once

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3892]
@JabRef/developers I propose to remove the ability to download multiple fulltexts at once:

- we should not enable users crawling scientific full texts in batches (defensive strategy)
- I don't see a use case where multiple documents need to be crawled at once (if I want to take a look at a document, you can download it if it is not there even in a large DB)
- our current workflow is not made for downloading multipe docs, for each doc a dialog pops up. it should be automatically saved in the background for such a process
- the current workflow is not adequate: right now i need to check the PDF after the download. I am thinking about a process where one request the fulltext, gets a mini preview of the PDF and then can save accept or decline the fulltext

WDYT?

**Comment by Siedlerchr** [comment]
The use case I see is that you collect some entries from different fetchers and then you want to do a bulk download to get all PDFs for the entries.

Not my personal use case, I usually download the papers manually because outside university network I can either login via Shibboleth or use a slow VPN.

**Comment by stefan-kolb** [comment]
Yeah but you still need to confirm that it is the correct PDF and I also don't know if we should foster such approaches.

**Comment by lenhard** [comment]
Some users will be annoyed (like they have been when we introduced limits for Google Scholar and Medline), but this proposal has my full support. JabRef is not a tool for mass download.

**Comment by tobiasdiez** [comment]
I agree that we shouldn't focus on mass download, but the feature is also helpful if you want to download fulltexts for a small number of entries since you don't have to click the "download fulltexts" button for each entry separately. 

As I don't see any harm in having such a feature, I would keep it...

**Comment by koppor** [comment]
I think, we are talking about multi-download **for the same entry**. In that case, I fully agree with @stefan-kolb's proposal

> one request the fulltext, gets a mini preview of the PDF and then can save accept or decline the fulltext

**Comment by stefan-kolb** [comment]
Decision is to keep it as is for now.
