### ISSUE TITLE
[macOS] native menus & javaFX

### ISSUE THREAD

**Issue by urielz** [JabRef/jabref#4020]
My understanding is that JabRef switch to javaFX since 4.0. Since then, macOS users no longer have native menus (last version with native menus was 3.8). 

I'm curious whether this was intended or just a side effect of switching to javaFX. If this was not intended, are there plans to bring back native menus?

**Comment by tobiasdiez** [comment]
Yes, this was a negative side-effect of our partial transition to JavaFX. We are currently working hard to finish the migration. The current development version https://builds.jabref.org/maintable-beta/ already brings back support for native menus. A few bugs still need to be ironed-out (see https://github.com/JabRef/jabref/pull/3621 for an overview of known issues) but you are happily invited to try out this version and report any issues you encounter. 

Closing since this is fixed in the dev build.

**Comment by urielz** [comment]
Glad to read that. Thanks for the reply!
