### ISSUE TITLE
Changing group descriptions takes endlessly or lets jabref choke

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4022]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.3-dev--snapshot--2018-05-07--maintable-beta--35b068386
Windows 7 6.1 amd64 
Java 1.8.0_171

Steps to reproduce:

1. Open a large database (2300 entries)...
2. add a color and and icon e.g yellow and folder to a group description
3. jabref stops working with 4.9 GB in memory, the some 150 entries in the group were lost, the dialogue which opened when right clicking on an entry was passed to other programs

![20180508screenshotjabreferror](https://user-images.githubusercontent.com/9216487/39779501-ab1deda8-5309-11e8-8b47-8b57e5479662.PNG)

**Comment by bernhard-kleine** [comment]
I was very astonished to see in parallel to JabRef 4.1; Windows 7 6.1 amd64 ; Java 1.8.0_171
 JabRef 4.3-dev--snapshot--2018-05-07--maintable-beta--35b068386.
Both programs have the port 6500 checked and tell me that only one instance of jabref would be running.
I think an error of the snapshot version which does not respect that an instance of jabref is already running.

**Comment by Siedlerchr** [comment]
Can confirm this behaviour. It seems to completely reload the whole?  group tree. Tested with the Huge-File.bib

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
