### ISSUE TITLE
JabRef no longer pushes citations to TeXstudio

### ISSUE THREAD

**Issue by jimboz** [JabRef/jabref#4041]
Hi,

JabRef version 4.2 
MacOS High Sierra 
Java 1.8.0_112 (also tested on 10.0.1)

Steps to reproduce:

1. Launch JabRef and TeXstudio
2. Select a bibliographic item
3. Click push to TeXstudio
4. Nothing happens

In settings 'External Programs' path to TeXstudio: /Applications/texstudio.app/Contents/MacOS/texstudio

Previously worked very well until latest upgrade JabRef to 4.2.

Thanks in advance,

**Comment by Siedlerchr** [comment]
Do you get any error in the log? Help-> View Event log?
On Windows 10 this works as expected.

**Comment by halirutan** [comment]
I believe this is a valid issue. I could reproduce it with the current master and what happens is highly non-trivial to me. I'm almost certain that the bug is not JabRefs faults but it has its cause much deeper in `java.lang.UNIXProcess`. Initially, I thought it might be problematic that we give the command as one string as opposed to a list of arguments, but that seems not the case. I could track it down to 

```
return new UNIXProcess      
    (toCString(cmdarray[0]),
     argBlock, args.length, 
     envBlock, envc[0],     
     toCString(dir),        
         std_fds,           
     redirectErrorStream);  
}
```

inside `java.lang.ProcessImpl` but at the moment, I have no clue what happens there. As @jimboz already observed, running the command from the terminal does the correct thing. Maybe I have time on the weekend to have a closer look.

**Comment by halirutan** [comment]
I have to revise my analysis. My initial guess was correct and the reason for the bug seems to be that we provide the command as one long string. @jimboz can you test this JabRef version?

https://builds.jabref.org/bug_4041_pushToTSfails/

**Comment by jimboz** [comment]
Thank you guys! I can confirm the JabRef_macos_4_3-dev--snapshot-2018-05-27--master--XXX.dmg version now pushes citations to TeXstudio.
