### ISSUE TITLE
Feature request: Monospaced font for bibtex source code

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#4064]
In version

```
JabRef 4.3-dev--snapshot--2018-05-27--master--d2ddf9380
Linux 4.16.3-gentoo+ amd64 
Java 1.8.0_172
```
a proportional font is used to display the bibtex source code. This is difficult to read:
![selection_506](https://user-images.githubusercontent.com/298682/40591258-28634890-620e-11e8-8bb4-456d2bc41abc.png)
![selection_505](https://user-images.githubusercontent.com/298682/40591253-03bb166c-620e-11e8-93e0-be127d292fe0.png)

It would be gread to have a monospaced font here so that the code is much more readable and one can see the nice automatic alignment:
![selection_507](https://user-images.githubusercontent.com/298682/40591270-58681bb0-620e-11e8-9b34-d845615527e0.png)

**Comment by tobiasdiez** [comment]
The use of proportional fonts is just a temporary workaround to fix some freeze issues with the source tab. 
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/ (please remember to make a backup of your library before trying-out this version). Thanks!
