### ISSUE TITLE
Never display html containing the unsanitized data from third-party sources in your app

### ISSUE THREAD

**Issue by KOLANICH** [JabRef/jabref#4084]
I wonder if it is possible to inject malicious HTML code (i.e. with javascript or making requests to external resources or just exploiting a vulnr) into a page displayed because of https://github.com/JabRef/jabref/blob/227cccad87405cffe363236f497b67d55e7fa5d9/src/main/java/org/jabref/gui/entryeditor/RelatedArticlesTab.java#L70

Anyway, sanitization may be hard, it may be more secure not to display any html at all.

**Comment by Siedlerchr** [comment]
The related articles and will hopefully be redesigned with a better data source by

**Comment by tobiasdiez** [comment]
The data comes from Mr Dlib, a befriended service of JabRef, so there is no immediate security concern. Nonetheless, I agree that displaying HTML is not the best solution and hopefully Mr Dlib provides a more convenient data source in the future (e.g. bibtex or json).

As we cannot do at the moment, I'll close this issue (and mark as freeze).

**Comment by KOLANICH** [comment]
>so there is no immediate security concern.

it is. The software should be designed in the way protecting it from compromise even if other party is compromised.

>I agree that displaying HTML is not the best solution and hopefully Mr Dlib provides a more convenient data source in the future (e.g. bibtex or json).

I guess you can scrape html into data and use the data in a safer way.

>As we cannot do at the moment, I'll close this issue (and mark as freeze).

Not OK, but thank you for saying that directly.

**Comment by tobiasdiez** [comment]
I completely agree! (and "close and freeze" just means that we cannot really do something at the moment and does not imply that we forget about this issue and the valid points you raise)

@Joeran: ping

**Comment by Joeran** [comment]
Hi,

The motivation for displaying HTML from Mr. DLib was twofold:

1. We wanted the option to A/B test different recommendation layouts as part of our research. This requires that the layout is created and managed on our servers. Please keep in mind here that Mr. DLib offers the recommendations for free and the reason for this is that we can do some experiments that we can publish. 

2. We agreed with the JabRef team that we maintain the client, i.e. the recommendation component in Jabref. However, we hope to have someday dozens or even hundreds of partners like JabRef. This requires a simple solution that works for all partners and hence, we need to run as much functionality as possible on our servers. We simply cannot maintain 100 individual solutions. Hence, HTML seems the most sensible solution to us, because many of our other partners are (or will) be normal websites. 

Personally, I consider the risk of displaying HTML to be minimal, in particular when you consider that all the recommendations point to some web pages anyway. Even if we would replace the HTML with JSON, and JabRef would render the JSON, then a hacker could still hack Mr. DLib and replace any URL to a recommendation (e.g. https://core.ac.uk/display/288858?recSetID=36b3f1307eae92fc9e564f7ca251c161::5b165a0fc1e0f2.48127215 ) with a malicious URL (e.g. http://hacker-website.0-day.com ). 

However, I understand that the current solution is not ideal, particularly when thinking of GDPR. My suggestion would be that we change JabRef as follows: When a user clicks for the first time on the "related article" tab, a dialogue is shown that informs the user that this function is provided by Mr. DLib. The user is further informed what data is transferred to Mr. DLib, what we intend to do with the data, and what the potential risks are (forwarding to malicious URLs). Only if the user confirms this, recommendations will be requested. If the user declines, then the user cannot receive recommendations.

**Comment by KOLANICH** [comment]
>Even if we would replace the HTML with JSON, and JabRef would render the JSON, then a hacker could still hack Mr. DLib and replace any URL to a recommendation (e.g. https://core.ac.uk/display/288858?recSetID=36b3f1307eae92fc9e564f7ca251c161::5b165a0fc1e0f2.48127215 ) with a malicious URL (e.g. http://hacker-website.0-day.com ).

The difference is that that malicious URL will be opened with a browser constantly repelling these kind of threats (because it is constantly attacked) and having necessary tools in it like anti-tracking addons, Google Safebrowsing. Built-in browser components are not browsers, are not meant to be used in the environment compromised by an attacker, and they are security nightmare if they are used with the data which may be tampered by an attacker. They may be safer because of their limitations, like lack of JIT, lack of support of modern web standards or being implemented in a memory safe slow language. But they are not well-researched because they are not browsers and are not used every day for browsing Web by millions of users. In other words, if a blackhat finds a flaw in them, this flaw will affect only limited amount of users : the users of the apps embedding the data from the webfite an adversary has control on, which most likely don't worth an effort. But the things change when the adversary is the site owner himself. I don't think that they should be trusted. 

>We wanted the option to A/B test different recommendation layouts as part of our research. This requires that the layout is created and managed on our servers. Please keep in mind here that Mr. DLib offers the recommendations for free and the reason for this is that we can do some experiments that we can publish.

Then this page should be opened in a browser, not in JabRef itself. I guess both scraping the data from the page or getting it from your API, and rendering it in a secure way, or removal of the tab from the client and replacing it with a button opening a real browser on your page are both acceptable.

If you wanna get some compensation for the work done by your services, you can request it through the API, for example yoj can require the client to compute a proof-of-work and use it as your shares for mining cryptocurrencies. Or you can try merge ads with captcha and quis the users about ads content.

But risking users' security and privacy for someone's business goals is not acceptable, IMHO.

**Comment by tobiasdiez** [comment]
@Joeran Thanks for the details and the refresher about the reasons why we choose to display the recommendation as HTML. I absolutely don't want to undermine our agreement in this regard but you might want to reconsider your strategy. I doubt that all services that may want include Mr Dlib want to display it in exactly the same way. Especially for websites it is standard to send JSON and then to render the information in the browser using templates. You may still provide HTML as an option but to me a standard format like JSON and/or bibtex seems preferable (from a consumer viewpoint, not speaking about the research-related side).

**Comment by Joeran** [comment]
Hi @tobiasdiez in the long run, we hope to offer many different options to partners, ranging from pure json/xml to a "toolkit" similar to Google Adsense where users can use a wizard to create a custom JavaScript snippet that displays content in the layout the user want. Ideally, we will also offer an automated A/B engine that tests and automatically finds the best layout for a given partner.

**Comment by Joeran** [comment]
We would also be very open to using something like this https://github.com/google/caja/blob/master/README.md to restrict the type of HTML and JS that may be executed in JabRef. Not sure if that particular library (caja) is suitable for JabRef and our current recommendations, I just had a quick glance at it. If anyone knows similar or better libraries, feel free to let me know.

**Comment by KOLANICH** [comment]
I wanna say that any trackers and active ads using any active content are completely inacceptable, especially in such poorly protected environments as embedded "browsers". Again, if you wanna show ads, just give a text or a picture. "Poor" text without any html markup. If you wanna make sure that a user hqve read it, make the advertisment a captcha and require a user to solve it. But tracking and opening possibilities for malware delivery are completely inacceptable.
