### ISSUE TITLE
lack of features in the current master

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4099]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.4-dev--snapshot--2018-06-04--master--ee669a542
Windows 7 6.1 amd64 
Java 1.8.0_172

Feature to worked at

- a search item is remembered even after it had been cleared
- the ^ and &#x2304; do not work in the entry editor
- drag and drop to groups is not possible

**Comment by Siedlerchr** [comment]
DnD refs #3765

**Comment by Siedlerchr** [comment]
Drag and drop is now implemented

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
