### ISSUE TITLE
Disabled Entry preview still shows up

### ISSUE THREAD

**Issue by mcspritz** [JabRef/jabref#4159]
Hi all,

I disabled the entry preview but it continues to show up at any time.

- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.3.1
Linux 4.14.48-2-manjaro amd64 
Java 1.8.0_172

Steps to reproduce:

1. Disabled the Entry preview
2. Select randomly an entry

**Comment by upupming** [comment]
@mcspritz 

Hi,

I have tested it on both Ubuntu and Windows, and it seems like a platform-specified issue.

|![](https://raw.githubusercontent.com/upupming/paste/master/img/20180710115259.png)|<img src="https://raw.githubusercontent.com/upupming/paste/master/img/20180710115712.png"/>|
|:--:|:--:|
|When "View -> Toggle entry preview" is selected, the entry preview in the bottom shows properly.|If I deselect the "View -> Toggle entry preview", the entry preview in the bottom will disappear.|

|<img src="https://raw.githubusercontent.com/upupming/paste/master/img/Selection_006.png"/>|<img src="https://raw.githubusercontent.com/upupming/paste/master/img/20180710120132.png"/>|
|:--:|:--:|
|JabRef 4.3.1 <br> Linux 4.15.0-24-generic amd64 <br> Java 1.8.0_172 <br><hr> However, when I select another entry, the bug comes out. The entry preview shows when "View -> Toggle entry preview" is not selected.|JabRef 4.3.1 <br> Windows 10 10.0 amd64 <br> Java 1.8.0_172 <br><hr> After deselecting, there will be no entry preview any more no matter whether the "View -> Toggle entry preview" is selected or not.|

If possible, I will try to fix this bug!

**Comment by upupming** [comment]
It seems [the latest build](http://builds.jabref.org/master/) on the master branch doesn't have this bug.

Also, the UI of 5.0 version has been changed a lot. There is no selected dot on the left anymore.

![selection_007](https://user-images.githubusercontent.com/24741764/42815066-d3fe836a-89f8-11e8-9459-a242367d10dd.png)

I have also tested on https://github.com/JabRef/jabref/commit/9b2fedc238d1ba64875c96cf8f59645f36a65635 (the branch point of master branch and v4.x branch), the bug exists there.

So the bug must have been fixed somewhere on the master branch. I will figure it out.

**Comment by Siedlerchr** [comment]
Sometimes it can happen that the entry preview is minimized, the window is there, but it is minimized at the bottom.

**Comment by upupming** [comment]
Yes, I find that on Windows 4.3.1 version, the entry preview is minimized actually.

**Comment by tobiasdiez** [comment]
So this appears to be fixed in the latest development version. Thanks @upupming for your investigation. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
