### ISSUE TITLE
Focus jumps after adding new entry

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#4167]
1. Add a new entry
2. Select row in main table
3. First field in the entry editor is focused

I would expect that 3. no focus is inside the entry editor.
Also, sometimes when selecting the entry row the focus jums inside the first field and sometimes not.

**Comment by tobiasdiez** [comment]
I think @koppor wanted to have the auto-focus on the first text field. I agree that it makes navigating the entries using up/down harder / impossible.

**Comment by koppor** [comment]
In case the entry editor is opened:

Spontaneous interpretation of the feature: If new table field is activated, the user presses <kbd>Tab</kbd> the last edited filed in the entry editor is selected. If the entry editor was not opened before, the first field is selected.

So, cursor up/down should work as expected.

(Did not search for the issue describing the behavior outlined by @tobiasdiez)

**Comment by PUKK** [comment]
Since my issue is closely related, I add it to this entry:

After closing the import window, Jabref 4.2 used to jump to (or select) the imported entry in the main window. Since one cannot edit entries in the import window (or even see all fields depending on the preview), one always has to search for the newly imported entry to check if the entry is fine and often manual fine-tuning is still needed. 

This feature has disappeared with the newest versions of Jabref. 

JabRef 5.0-dev--snapshot--2018-08-03--master--611ac5564
Linux 4.12.14-lp150.12.7-default amd64 
Java 1.8.0_171

**Comment by matthiasgeiger** [comment]
I'm not sure this whether this should not be an own issue, but I also miss this selecting of the newly created/imported entry.

**Comment by Siedlerchr** [comment]
Current 5.0 dev: Cursor no longer jumps in first field, but row is not seleced either

**Comment by PUKK** [comment]
I tried to check the behavior but for me newly imported items are not shown in the list at all. If I search for the new item, it is there. For the import, I use a script only containing the following line: 
java -jar ~/bin/JabRef.jar --importToOpen $(readlink -f $1) 
When I try to save, Jabref complains "The library has been modified by another program."
After a restart of jabref, the newly imported item is shown properly in the list.
