### ISSUE TITLE
Group sidebar background changes color

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#4168]
**Actual:** When selecting a group inside the group sidebar the grey background changes to white.
**Expected:** Background stays the same.

![image](https://user-images.githubusercontent.com/2141507/42307526-029125cc-8033-11e8-8765-40fa1835914a.png)

![image](https://user-images.githubusercontent.com/2141507/42307516-fc24b366-8032-11e8-82d0-c63df1c65cf8.png)

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
