### ISSUE TITLE
Jabref 5.0dev does not respect the standard directory

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4201]
JabRef 5.0-dev--snapshot--2018-07-12--master--dd9b22911
Windows 7 6.1 amd64 
Java 1.8.0_172
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

Steps to reproduce:

1. load jabref 5.0dev and any library
2. try to save a pdf entry for an entry
3. you will notice that the path which is saved is the full path, the directory in the standard directory entry included

This is a Verschlimmbesserung, sorry for the nice German word. it means changing not for the better, but for the worth.

For first entry is manually edited, the second not
![grafik](https://user-images.githubusercontent.com/9216487/42723317-e533c108-875b-11e8-8c41-4102e171cb8d.png)
the standard directory is:
![grafik](https://user-images.githubusercontent.com/9216487/42723330-1c08e69a-875c-11e8-8090-24fa5e38ec8d.png)

**Comment by bernhard-kleine** [comment]
Sorry for the delay:
I used the rightclick add file for adding the pdf.

**Comment by Siedlerchr** [comment]
It only happens if you use Rightclick on entry -> Attach file.
Inside the General Tab it works fine.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
