### ISSUE TITLE
Readd notifications for important actions (like save status)

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4223]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 5.0-dev--snapshot--2018-07-15--master--a44d31668
Windows 7 6.1 amd64 
Java 1.8.0_181

I have got to rely on the status line to know that the library has been saved. In the snapshot 5.0 there is no status line left. Please let me know to re-enable it or make it available again.

**Comment by tobiasdiez** [comment]
I'm not a big fan of the old status line, especially when it is used to communicate errors to the user. In most cases, displaying a message right in the context of the action is preferable (e.g. a small flyout of the button that triggered the action). Only for actions that are triggered trough the menu, something like a global status line makes sense (because the menu vanishes after the action is triggered and hence there is no context to show the result). But then again, if the information is important enough to show it to the user, a status line has usual not the visual weight to ensure that the user really reads the message. I would use something like the [NotificationPane](http://fxexperience.com/controlsfx/features/#notifications) in such cases (and remove most of the other status line messages).

**Comment by Siedlerchr** [comment]
I am very much in favor of the Notficiation pane or either as the other option, a notification "window" at the right of the desktop (jdownloader 2 does it that way, with a notifaction window which can be moved.

**Comment by tobiasdiez** [comment]
This is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
