### ISSUE TITLE
Missing: Move to file folder and rename the file

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#4238]
Using JabRef 4.3.1 on Windows10.

In JabRef 3.8.2:
When I attached a file to an entry I was able to right click on the file-entry and there was a "Rename and Move to file data folder" (free translation).
This means
`C:/Desktop/838283832.pdf` would be renamed to `C:/mybib/Doe2000_AnyTitle.pdf`

In JabRef 4.3.1:
This entry in the context menu is missing. Now I have to do two separate things. First I have to move and then I have to rename.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by noMICROSOFTbuhtz** [comment]
Yes it is fixed. Thanks.
