### ISSUE TITLE
The snapshot 2018-07-30--master--89f855d76 keeps to the background

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4243]
JabRef_windows-x64_5_0-dev--snapshot--2018-07-30--master--89f855d76
Windows 7 6.1 amd64 
Java 1.8.0_181

- [x ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

When I start the snapshot jabref it will open but it does not come up to the desktop. I can use alt-tab and I see that is open, but it never surfaces. I think it is no use to show you an empty desktop. Earlier snapshots work proberly in that regard.

**Comment by tobiasdiez** [comment]
Do you know which version you had installed before?

**Comment by bernhard-kleine** [comment]
JabRef_windows-x64_5_0-dev--snapshot--2018-07-25--master--077fdacc2

**Comment by tobiasdiez** [comment]
Ok that narrows down the problem because the only change since then was https://github.com/JabRef/jabref/commit/89f855d76713b4cd25ac0830c719cd61c511851e. Honestly, I doubt that this change (which was local to the Microsoft Word importer) leads to the issues you describe. It is more likely that something changed on your side (e.g. java update?) or there was a problem with the installation (did you tried to reinstall?).

**Comment by bernhard-kleine** [comment]
I reinstalled the snapshot in the very same directory, this time JabRef opens properly. Thanks

**Comment by Siedlerchr** [comment]
@skanskan  Please try again with the new build of the dev version again in a few minutes. There was a bug which prevented the start of JabRef standalone
