### ISSUE TITLE
Convert swing dialogs (Quality->Cleanup Entries)to javafx

### ISSUE THREAD

**Issue by 1160300614** [JabRef/jabref#4267]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 

I have done some changes about convert the swing dialogs to javafx.
It's about Quality->Cleanup Entries.[part of it](https://github.com/1160300614/jabref/blob/dcfa70a7a134b97202e49a5856fe31e6562a782b/src/main/java/org/jabref/gui/cleanup/CleanupPresetPanel.java#L48-L125)

But when the component became the node, it doesn't work. I mean these checkbox won't change its value when i click them.

**Comment by tobiasdiez** [comment]
The code looks good to me, I'm not sure where the issue lies. Did you use the most recent code from the master (since I've fixed the display of the checkboxes a few days ago)?

Moreover, please open a PR when you want to discuss implementation details. The issue section is for bug reports or suggestions for improvement. Thanks!
