### ISSUE TITLE
& character in GUI strings

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#4339]
In the current dev (5.*) version on Win10 there are an `&` character in some of the GUI elements (e.g. menu entries).

I open this Issue because on that [forum thread](discourse.jabref.org/t/zeichen-in-5-gui).

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
