### ISSUE TITLE
Copy-paste citation to BibTex not working 

### ISSUE THREAD

**Issue by arnyeinstein** [JabRef/jabref#4380]
JabRef 5.0-dev--snapshot--2018-10-14--master--73ec32189
Windows 10 10.0 amd64 
Java 1.8.0_172

Steps to reproduce:

1. Copy the following text into the tab "{} BibTex Source"
@ARTICLE{6773024, 
author={C. E. Shannon}, 
journal={The Bell System Technical Journal}, 
title={A mathematical theory of communication}, 
year={1948}, 
volume={27}, 
number={3}, 
pages={379-423}, 
keywords={}, 
doi={10.1002/j.1538-7305.1948.tb01338.x}, 
ISSN={0005-8580}, 
month={July},}

2. Click on the "Required fields" tab: Nothing is shown.
Furthermore, trying to mark the text in the "{} BibTex Source" field behaves strangely (only showing parts of text marked)
No messages in log file.

Just noticed: existing entries in the jabref file do not show information in the "{} BibTex Source" tab.

Cheers
Renger

**Comment by Siedlerchr** [comment]
you can copy/paste directly on the maintable

**Comment by Ali96kz** [comment]
If we paste data via 'BibTex Source', should it create a new line in table or overwrite data in opened entry ?

**Comment by Siedlerchr** [comment]
If you paste the bibtex data into an exiting entry, the data should be overwritten.

People often are unaware of the fact that you can directly paste on the maintable (only possible since a few version), so they create a  new entry, copy the bibtex code in the tab and expect their entry to be updated.

**Comment by Siedlerchr** [comment]
We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
