### ISSUE TITLE
autogenerate bibtex key not working

### ISSUE THREAD

**Issue by springzfx** [JabRef/jabref#4417]
In master branch, autogenerate bibtex key not working
1. open Jabref click one entry
2. press ctrl+G, the confirmation dialog not pop up, and nothing change
3. from the menu click, it's the same result.

The reason seems to be the confirmation dialog can not up, hope someone to fix this:
https://github.com/JabRef/jabref/blob/940fa2ce3f5579d65b503d4d294f832be5c9d2a9/src/main/java/org/jabref/gui/actions/GenerateBibtexKeyAction.java#L59

 

JabRef version: current master
 on 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Can not confirm this. You have probably enabled the settings Do not overwite keys and disabled the confirmation dialog in the settings "Warn before overwriting keys"

**Comment by springzfx** [comment]
If disabled the confirmation dialog, it worked as expected.
If enable the confirmation dialog, it won't work, no dialog, no key generated.

![peek 2018-10-27 17-36](https://user-images.githubusercontent.com/8992037/47602269-1ff03280-da0f-11e8-9689-f2067029116e.gif)

**Comment by Siedlerchr** [comment]
Ah okay, now I reproduce it as well. No dialog is shown

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
