### ISSUE TITLE
Strange focus behaviour of search field above literature entry list

### ISSUE THREAD

**Issue by andre8s** [JabRef/jabref#4472]
JabRef version JabRef 5.0-dev--snapshot--2018-11-07--master--144522d61
on Windows 10 10.0 amd64 
Java 1.8.0_181 

1. Open a literature database
2. Use search field above entry list e.g. for searching an author name
3. Double-click on one of the found entries to open its edit section
4. Click on the 'x' at the right side of the search field in order to empty it and type a new search string

When I do that, shortly after step 4 the focus is suddenly put onto the Author field of the edit section instead of the search field. If I do not care, I am then overwriting the author information with my new search string. 

Edit: There seem a few similar issues already posted in this list, however they are from 2016 and clearly do not address the newest developer snapshot.

**Comment by wujastyk** [comment]
JabRef 5.0-dev--snapshot--2019-03-16--master--d7dd41b00
Linux 4.15.0-46-generic amd64 
Java 1.8.0_201

Me too.

**Comment by AEgit** [comment]
Can confirm for:

JabRef 5.0-alpha--snapshot--2019-08-25--master--0c342bdc7
Windows 10 10.0 amd64 
Java 1.8.0_221

Note, that this now an even bigger problem, since it is no longer possible to get an entry preview without opening the entry editor:

https://github.com/JabRef/jabref/pull/4976#issuecomment-524625559
https://github.com/JabRef/jabref/issues/5244

**Comment by Siedlerchr** [comment]
Fixed in #5432 . Should be fixed now in the latest master.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
