### ISSUE TITLE
multi-line fields not necessarily working

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#4479]
following issue https://github.com/JabRef/jabref/issues/555 , it should be possible to define some fields as multi-line fields by adding these fields in the Preferences/File/Do not wrap section.

Not all the fields that I listed there are actually shown/represented as multi-line fields in the entry editor.

JabRef 5.0-dev--snapshot--2018-11-11--master--50875f967
Linux 4.18.17-200.fc28.x86_64 amd64 
Java 1.8.0_172

**Comment by johann-petrak** [comment]
I am not sure if this is the right issue, but when I started to use JabRef, I used the option "Set up general fields"  to add a tab with one large field (for my notes about the content). It was easy to enter multi-line text into that field.

Now that I have to use version 5.0-dev (because of other issues I had I was told to do that), that same field behaves like a single-line field. It is impossible to break up the text into several lines, the Enter key does not create a new line etc. 

Is there any way at all to get back the old behaviour? This was one of the killer features of JabRef for me: the ability to add arbitrary notes about a paper and keep it with the citation itself.

I also notice that JabRef now seems to always generate DOS-style new lines in the bib file that gets saved, even though I am on Linux? Could this be related or is this a separate bug?

Using: 
* JabRef 5.0-dev--snapshot--2019-06-16--master--8d99db113
* Linux 4.15.0-52-generic amd64 
* Java 1.8.0_172

**Comment by AlexNi245** [comment]
Helllo iam an compoter science student from germany and intressted in contributing to open source. may i work at this issue? I would define every field as multiline field except the field is listed in Preferences/File/ Do not Wrap.
Please tell me if this approach is right an if there is anything i should know.

**Comment by ilippert** [comment]
#4373 shows this is still an issue in
JabRef 5.0--2020-03-08--93de138
Linux 5.5.7-200.fc31.x86_64 amd64 
Java 13.0.2

**Comment by Siedlerchr** [comment]
Closing this in favor of #4373 as there is the problematic code listet
