### ISSUE TITLE
Preferences window not shown JabRef 5.0 dev

### ISSUE THREAD

**Issue by funclesz** [JabRef/jabref#4516]
JabRef 5.0-dev--snapshot--2018-11-26--master--89d4d745c
Windows 7 6.1 amd64 
Java 1.8.0_191

The preferences window is no longer shown. Is that a known issue?

Try to select: Menu - Options - Preferences

**Comment by Siedlerchr** [comment]
Hi, please look at the error console, there should be an error logged. You can also try to reset your preferences

**Comment by funclesz** [comment]
I probably overlook something. I see only the Event log, is that the error log you mean?
The even log says: "Uncaught exception occurred[JavaFX Application Thread,5,main]

Is there a simple way to reset the preferences?

**Comment by Siedlerchr** [comment]
Please add the whole log output, the stack trace helps us to locate the error . 
For preferences resetting have a look at the help here https://help.jabref.org/en/CommandLine#reset-preferences--d-key

**Comment by wujastyk** [comment]
I had this problem.  I solved it by hunting down and deleting all jabref configuration files on my disk and reinstalling JabRef 5.

**Comment by Siedlerchr** [comment]
Can you run it from terminal with java -jar JabRef.jar and show the whole output?

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
