### ISSUE TITLE
Entry-preview 

### ISSUE THREAD

**Issue by funclesz** [JabRef/jabref#4517]
JabRef 5.0-dev--snapshot--2018-11-26--master--89d4d745c
Windows 7 6.1 amd64 
Java 1.8.0_191

At the moment I use "Keyword Groups" a lot to manage my PDF's. 
I have the Entry-preview open.
When you select a Keyword from the groups panel, the entry-list displays the matching references.
However, in the Entry-preview, the last selected reference is still shown.
For me it would work best if either the first reference from the newly selected (Keyword)group would be shown OR if no reference at all would be selected (Entry-preview becomes empty).
So, selecting a Group should maybe trigger a purge action or so?

Is it currently working as intended?

**Comment by DOFfactory** [comment]
If you implement this suggestion, I would kindly request to make it optional. I would rather prefer the behaviour as it is now.

**Comment by noMICROSOFTbuhtz** [comment]
Could you please update the title of that Issue to be more specific.

**Comment by stefan-kolb** [comment]
This works as expected because 
- when you select an entry it displays the entry information
- when you select a different group  the filter of the maintable is updated as you selected a group filter
- the selection of the last entry is still valid as you didn't select a new entry but only a filter
Therefore, we only change the display when you select a new entry from the new group list
