### ISSUE TITLE
Main Menu: change Edit tab

### ISSUE THREAD

**Issue by MartinKarim** [JabRef/jabref#4669]
![mmedit](https://user-images.githubusercontent.com/26404402/53028478-38c19f80-3467-11e9-9d39-0d3e4942b7ff.png)

|Description of Issue|Possible Solution|  Warnings |
|:-----------------------------------------:|:-------------------------------------------------:|:---------------:|
| _Rank_ feature rated as unimportant in a user survey| Remove _Rank_ from main menu| -|
|complex editing functions should be tools;<br/>sending as email does not edit anything|move _Send as email_ and _Replace string_ to Tools tab|see prototype in #4672 |
| _Set/clear/rename/append fields_ applies to whole library;<br/>item name is too long;|move to Library tab;<br/>rename to _manage field names&content_| see prototype in #4670 |
|-|-|other changes can be found in issues #4665 , #4666 , #4667 |

**Comment by AEgit** [comment]
As long as the _Rank_ feature is available when right-clicking an entry, I don't mind it being removed from the Main Menu. The _Rank_ feature itself, however, absolutely needs to be remain part of JabRef, since it replaced the old marking scheme of entries using colours (which, to be honest, I still prefer). I guess this is of minor importance for people with small databases, but for someone with thousands of entries (currently >17,000 entries), the _Rank_ feature is really useful.
