### ISSUE TITLE
Add JabRef Setup Icon for the install4j installation procedures

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#482]
We should create a JabRef installation icon and use this for the installer and uninstaller.

**Comment by stefan-kolb** [comment]
Should be done when creating a fresh new Icon design. Or we can just use the normal Jabref icon for now?

**Comment by simonharrer** [comment]
It should not be the field of the app itself, as this may be confusing.

**Comment by stefan-kolb** [comment]
http://stackoverflow.com/questions/19199826/how-to-customize-the-icon-of-installer-exe-created-by-install4j

**Comment by Siedlerchr** [comment]
Is this issue resolved?

**Comment by stefan-kolb** [comment]
Nope, no setup icon yet.

**Comment by miderleta** [comment]
Is this issue resolved? If not, can I have a go at it?

**Comment by tobiasdiez** [comment]
@miderleta Sure go ahead, this issue is still open!
<img width="455" alt="annotation" src="https://user-images.githubusercontent.com/5037600/45553974-96f1b300-b835-11e8-8068-e163dd71d1ae.png">
When you are at it, it would be nice if you could replace the "install4j" text by "JabRef".

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

Unfortunately I could only change the watermark and the icon on the top right. Changing the icon in the header-bar did not work.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by tobiasdiez** [comment]
https://stackoverflow.com/questions/19199826/how-to-customize-the-icon-of-installer-exe-created-by-install4j
this does not work?

**Comment by Siedlerchr** [comment]
@tobiasdiez  That is already done. That is the icon you have when you download JabRef. However, that does not influence the icon installer_header which is the one I could not replace.

![grafik](https://user-images.githubusercontent.com/320228/47615485-9e041600-daaf-11e8-8a63-c5ec53e9899b.png)
