### ISSUE TITLE
mvbook and mvcollection

### ISSUE THREAD

**Issue by twsh** [JabRef/jabref#489]
The types 'mvbook' and 'mvcollection' aren't recognised and produce an error. (They are standard types described in the biblatex manual.)

**Comment by oscargus** [comment]
This should be fixed in Master with #469 

@twsh can you try a version in http://builds.jabref.org/betterduplicatechecket/ to confirm? (Not sure why the builds in http://builds.jabref.org/master/ are not updated automatically... The build above is fully merged now, so quite OK as an approximation of current master.)

**Comment by twsh** [comment]
The first link seems to be broken.

**Comment by koppor** [comment]
@twsh I just moved it to http://builds.jabref.org/master/. Please check that build.
@oscargus Something is wrong with the cleanup script running. I'll investigate later on. After something is pushed to the master branch, the new build will be back in place.

**Comment by twsh** [comment]
Yes, it's fixed in the master. Cheers!
