### ISSUE TITLE
Get Fulltext produces PDF without filetype in name

### ISSUE THREAD

**Issue by geyslein** [JabRef/jabref#4929]
```
JabRef 4.3.1
Linux 5.0.9-arch1-1-arch amd64 
Java 1.8.0_212
```
- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

For some reasons, the document download (File -> Get Fulltext) would sometimes name the downloaded PDF without the filetype. So that the file is named: Smith2016 - TITLE and not Smith2016 - Title.pdf

I can not reproduce why is that so. The last DOI for which this happened to me: https://doi.org/10.1080/09537325.2013.850158

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

For arch unit you can get the latest version here:
https://aur.archlinux.org/packages/jabref-latest/

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
