### ISSUE TITLE
Default Preview Setting doesn't display comment

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#4937]
The default entry preview format is referencing the old "review" field.  This doesn't exist anymore, as it was renamed to "comment" or "Comments," depending upon where you look.

The problematic line is:

` \begin{review}<BR><BR><b>Review: </b> \format[HTMLChars]{\review} \end{review}</dd>
`

The "comment" field is displayed in the entry preview if I change the above line to this:

`\begin{comment}<BR><BR><b>Comments: </b> \format[HTMLChars]{\comment} \end{comment}</dd>`

JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_201

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
