### ISSUE TITLE
[Code] Some problems with entries and entry types

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#495]
I have some problems how entries and entry types are handled at the moment. See also #469 for some background.

1. There is currently (nearly) no way to access the data stored in the entry in a meaningful way. I would like to call `entry.getAuthors()` to get an `AuthorList` containing the data in a non-stringy version. 
2. There are four different modes for a type (BibTex, BibLatex and customized; or unknown). The user could switch between these modes at any time. In the ideal case, this switch would be localized in some class. The localization would make it obsolete to change the type of every entry everywhere by hand if the user switches modes.
3. There should be a way to say that an entry has a given type (e.g. is an article) irrespective of its mode (BibTex, BibLatex, ...).

I thought a little bit about these issues but couldn't come up with a solution I liked. Hopefully somebody else has a good idea to improve the system.

**Comment by lenhard** [comment]
I aggree, there is potential for building a more beatiful API here.

Regarding 1.: Yes, maybe methods like this could be offered for all required fields that are shared by all entry types. I just fear that there is no intersection in required fields for all entry types. 

Regarding 2. and 3.: I think there is a misunderstanding here. The semantics of `equals` are very narrowly defined and a `BibtexEntryType` is just not equal to a `BibLatexEntryType`. This is not a "mode", but different instances of `EntryType`. Their contents are different. What you are talking about is the name of the entry type, which can very well be equal, regardless of whether there is a Bibtex entry or a Biblatex entry underneath. To sum up: you can say that an entry has a given *type name* regardless of its `EntryType`. I mean something like:
```
myBibtexEntry.getType().getName().equals(myBibLatexEntry.getType().getName()); // returns true
```
instead of 
```
myBibtexEntry.getType().equals(myBibLatexEntry.getType()); // returns false
```
From what I understand, this is all that you want.

**Comment by tobiasdiez** [comment]
@lenhard 
1. Do you think it also makes sense to define such methods if the field is not defined for every entry type? For example, `Optional<AuthorList> getAuthors()`?

2. Maybe it is not clear what I mean and it is better to view it from the other side. So the parser reads `article` in the bibfile and thus wants to assign the type article to the entry. Currently, he just puts `BibtexEntryType.Article` in it. However, this is "wrong" if JabRef is in Biblatex mode. On the other hand, the parser shouldn't care about biblatex mode or not. So there should be a way to say that an entry is an article without exactly specifying the mode (tex, latex, customized). I have a few solutions to this, but I'm not completely convinced by them:
- Simply store the type as a string.
- Store the type in an enum. This is better but I'm not sure how unknown entry types should be handled.
- Create a class for every known entry type, e.g. `ArticleEntryType` and store this information in the entry. Then the class could encapsulate the specific mode or state through the [state design pattern](https://en.wikipedia.org/wiki/State_pattern). I like this idea the most but on the other hand it seems a little bit to complicated.

**Comment by lenhard** [comment]
Hm, not an easy decision... If we add such methods, then using `Optional` would propably be the most reasonable solution (much better than just defining `AuthorList` as return type and potentially returning null). Since we do already have similar methods, such as `getAuthorTitleYear`, you could just go ahead and add the methods you need, from my point of view. If you implement them with `Optional`, this is already a huge improvement over the existing code. @JabRef/developers Any other thoughts on this?

Regarding equality: Ok, I think I understand now. The problem is that the parser decides on the entry type based on a preference setting and before it can actually really infer the type. To infer the type, the parser would have to read the complete entry and see which fields are used. We could modify the parser to set the entry type after reading the complete entry. I just had a look at the parser code. This is not trivial, but also not too hard. Alternatively, the parser could first read the complete database and finally adjust types in a post-processing step. Ultimately, this means that it would be possible to write a database which contains bibtex and biblatex entries and it is vulnerable to a diagnosis of false-positives. Is that what we want?

Although I personally do not like the option very much, we could also store this information in the file header (in a `@preamble`) or something similar.

The quick hack solution would be to just depend on the string (possible through `myEntry.getType().getName()`).

I'm not so much in favor of creating a class for every `EntryType`. Large class hierarchies are seldom beautiful and the design principle [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) tops the state design pattern :smile:

**Comment by stefan-kolb** [comment]
I'm currently writing a Class to infer the type of a database.

**Comment by lenhard** [comment]
and it is the post-processing solution that works on a `BibtexDatabase`, as far as I see. Let's try going down that road!

**Comment by tobiasdiez** [comment]
I'm also in favor of post-processing the entry type. But for this the entry type has to be stored in some intermediate form. And I really don't like the solution based on strings.

**Comment by lenhard** [comment]
The `BibtexEntry` is post-processed, not its type. The type of the entry that is initially stored might be wrong (as it currently is) and would be replaced on post-processing. That would be fine by me.

**Comment by oscargus** [comment]
I think it very much makes sense to define methods as `getAuthors()`. What is meant by the field is not defined by the entry type here? Even though they are not required nor optional, one can add any field to the entry, so just returning an empty AuthorList if the entry does not have an author-field would make sense, just as returning an empty String (or null) if your query the field "jlijlkvjdsklj" (most of the times).

I also think it makes sense to define a `equalType`(?) method that compares the strings. In the tests I didn't really reflect on that, but was rather assuming that assumeNotEquals looked at the Java Object rather than the equals function in that case (which I now realize was a bit naïve).

I recently learnt that one shouldn't access `BibtexEntryType.Article` directly, but use `EntryTypes.getType("article")`, see #337 . So any direct access should be replaced (unless in the tests then maybe...).

**Comment by simonharrer** [comment]
My idea around the model would be creating concentric circles with dependencies pointing always towards the center. I would propose to have the classes bibtexentry and the bibtexentrytypes in the middle which only work on Strings. If a field has special meaning, e.g., the authors field, I would add this functionality on the second circle, which can provide richer values ontop. This would make it very flexibel to add arbitrary functionality for each field without having to alter the inner core so to say of the model. What do you think?

**Comment by lenhard** [comment]
Of course, an empty `AuthorList` would be preferable to `Optional<AuthorList>`! Sometimes I am blind... However the `Optional` is preferable for return types that are not data structures or do not have a valid empty initialization. In the case of strings, the empty string would propably be fine unless it has a special meaning in `BibtexEntry`. The point is to not to add too many methods to `BibtexEntry` which will only make sense for few types. `getAuthors`, `getTitle`, etc. would propably make sense, but a `getJournal` method would make little sense for a `BibtexEntry` of type `InProceedings`.

Adding an `equalType` method that uses `getType().getName()` sounds fine for me.

**Comment by oscargus** [comment]
I have no idea how `Optional`works, so it wasn't really a comment against that. :-)

Proposed simple rule: methods that only return the String that is the field content are not really needed.

**Comment by stefan-kolb** [comment]
> So there should be a way to say that an entry is an article without exactly specifying the mode (tex, latex, customized).

From my point of view, it doesn't matter for the parser which type an entry is. It is just a `BibEntry` with fields and a name at first. 

Only when we combine this data inside a `BibDatabase` with a particular working mode (bibtex or biblatex) we can enhance the database's entries with meaningful `EntryTypes` including required and optional fields. 

We also wanted to make this decision file-based, not preferences-based as it is now.
Imho, this is the direction we should go.

**Comment by koppor** [comment]
What is our current state regarding `entry.getAuthors()`?
