### ISSUE TITLE
CONTRIBUTING.md Improvement With Issue Tracker Link

### ISSUE THREAD

**Issue by wangch7** [JabRef/jabref#4990]
**Is your suggestion for improvement related to a problem? Please describe.**
No instruction of next step to take after a newcomer reads CONTRIBUTING.md.

**Describe the solution you'd like**
Add the link to issue tracker (the same name and link as shown in README.md) at the end of the CONTRIBUTING.md page.

**Comment by davidemdot** [comment]
Hey, @wangch7!

CONTRIBUTION.md contains our guidelines for contributing, especially for new contributors. That is the reason because in the first line of that file there is a link to our issue tracker, filtered by "good first issue" label.

Even though if you prefer to work on any other issue, you can uncheck this label on the dropdown menu that is showed when you click in "Labels".

Thanks for your time! :")

**Comment by davidemdot** [comment]
This is the menu I was talking about:

![good_first_issue](https://user-images.githubusercontent.com/12954316/58220712-33971980-7d10-11e9-9bea-59c86b29746c.png)

**Comment by tobiasdiez** [comment]
I agree with @davidemdot that the first sentence in contributing.md is enough. Thanks nonetheless for your suggestion.
