### ISSUE TITLE
Multiscreen issue

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#5037]
I have a strange issue, not sure whether this is JabRef or general Windows 10 issue. I have a multimonitor setup, if I leave JabRef open on the monitor that is later detached, JabRef remains inaccessible in the notebook monitor. While all the windows move to the notebook monitor, JabRef stays on the "extended" one, even if I close JabRef and reopen.

**Comment by Siedlerchr** [comment]
Hm, that is probably related to the fact that JabRef stores the window position at closing and restores it at startup. So JabRef will start in the void.

However, there are some tricks to get the window back:
https://www.technipages.com/bring-off-screen-window-back-onto-screen

**Comment by DOFfactory** [comment]
The tricks are fine, however, it would be good if JabRef would work as every other window in Windows 10, without the need of a trick. Am I wrong with this expectation?

**Comment by Siedlerchr** [comment]
A quick search turned out that it is possible to detect the screens in javafx, but I am not sure if this helps with storing the coordinates. Maybe at startup one could check if the coordinates are outside the current screen. But that the window automatically comes back to the main monitor seems to be a java? problem. No idea though
https://stackoverflow.com/a/34948184

**Comment by tobiasdiez** [comment]
Thanks to @MisterM13 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
