### ISSUE TITLE
Mystic "Ändern der Gruppierungsmethode" dialog after modfing a group

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5065]
Current dev version from today.

I modified an existing group. I tried color and also the name/title.
When clicking "Ok" the attached dialog appears.

![Zwischenablage01](https://user-images.githubusercontent.com/11861496/59763506-08b1ce00-929a-11e9-9397-45334bcefe07.png)

Maybe it depends on the translation but for me as a user I have no idea what it means. I have not changed the "Gruppierungsmethode". Clicking on Ok should just close the group settings dialog not more.

I see no sense in that extra dialog.

**Comment by Siedlerchr** [comment]
You modified a group, JabRef asks now if you want to reassign the original entries from that group to that modified group.
E.g. you change group name from A to B, so JabRef is asking if the entries assigned to your group A should be assigned to the group B now.
So it updates for each entry the group field from A to B.

**Comment by noMICROSOFTbuhtz** [comment]
I see. Technical it make sense.
But from the users point of view it does not. The user did not created a new group where the entries need to be moved to. The user just modified the group. The entries in their did not change.

See the point?

Do not bother the users with questions like that. I also see no case where it would make sense to press Cancel/Abbrechen.

**Comment by AEgit** [comment]
I disagree with the position of @noMICROSOFTbuhtz : If you, by mistake, modify a group name so that it suddenly has the same name as another group in your database and if entries are then automatically changed to the new group name (without asking the user), all hell breaks loose, i. e. it will be really difficult and tedious to get the original group assignment for those items.

So, I would argue to keep this feature as it is (and has been - I am still using 3.8.2 and I am quite happy, that this feature is still in the newer versions as well).

**Comment by noMICROSOFTbuhtz** [comment]
@AEgit I disagree also. If I rename the group to the name of another group that should be checked automaticly by JabRef. If this is the case I would like to have a (well formualted and understandable) warning message about it.

That would be what I expect as a user.

btw: The fact that the name of a group (combined with its path!) is its object-identifier also is a bug by design. But I want open that topic here. I think JabRef has other problems with more priority.

**Comment by AEgit** [comment]
@noMICROSOFTbuhtz Will I see your point and I agree in an ideal world this would be a good solution, for now we should probably not rely on JabRef checking this. There are several bugs (as you allude to) that affect the stability and performance of the current JabRef version, that probably should have higher priority at the moment.
This is by no means meant as a critique of the developers: They are doing this work for free and mostly (all?) in their spare time and the transition to JavaFX, as far as I understand, was a necessary (even though painful) step. Right now, the focus should probably be on getting the current JabRef version back to the stability and performance level of version 3.8.2 (if I have time I might be able to provide some benchmarks this weekend that will show that the current JabRef version can be at least 3 times as slow as version 3.8.2 for large databases). I think there also a couple of issues that particularly affect the Linux version of JabRef.
After that, additional focus like you mentioned might be worthwhile to think about.

Again a big shout-out and thanks to all the JabRef developers for their help and continuous support!

**Comment by tobiasdiez** [comment]
According to the code
https://github.com/JabRef/jabref/blob/6265e246023f1dfff20fe819f99cb40ff2e948d0/src/main/java/org/jabref/gui/groups/GroupDialog.java#L304
 a warning message should be displayed if there is a group with the same name. Do you still see a reason for the above warning dialog if duplicate group names are prevented?

**Comment by AEgit** [comment]
Ah there you go, this has already been solved in the current developer version (I thought I had seen this issue some time ago on Github but did not bother to check with the new version):

JabRef 5.0-dev--snapshot--2019-06-14--master--d811c175b
Windows 10 10.0 amd64 
Java 1.8.0_211

So, there is a warning message which prevents you from creating groups with the same name (nice, this was not the case with JabRef 3.8.2). If this feature is absolutely rock-solid (I have not tested it enough to confirm that), then yes, maybe the dialog mentioned by @noMICROSOFTbuhtz could be removed. I have the feeling the dialog still might be needed in some other rare special-cases, but currently I cannot remember the details. The only thing I remember was, that I was grateful at the time that it existed and I have used the "Cancel" part of the dialog a couple of times (but maybe that was just because groups could have the same name at the time?).
