### ISSUE TITLE
Store LaTeX-free version inside each BibTeX entry

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#518]
Each bibtex entry should store a latex-free version of its fields for searching and passing to search engines/downloader/general search/... Add wrapper to be able to change default returns of getField to latex-free version of the field value. Probably useful for all fetchers to get correct results.

**Comment by oscargus** [comment]
Should this field be UTF-8 or how should non-ASCII characters be handled? Should it be stored it the .bib-field or dynamically generated?

**Comment by keinstein** [comment]
I'd suggest to use the internal Java Unicode encoding. if I understand stefan-kolb right he wants to have a clean and easy to use API. Caching would improve the performance at the cost of memory. May be it can be made configurable? If the cache value exists hand it out, otherwise check whether the caching bit is set and save the generated value in the cache. The performance-hit should not be very large.

**Comment by koppor** [comment]
+1 for internal Java Unicode encoding which should be equal to UTF-8 and +1 for caching. No storage in the fields read or written by BibtexParser or BibEntryWriter.

Refs #161.

**Comment by oscargus** [comment]
Just noting that this sort of functionality (minus the caching) have been sort of implemented in the new and improved main table renderer.

**Comment by stefan-kolb** [comment]
See #1252

**Comment by koppor** [comment]
I think, this is implemented in  #2091.

**Comment by stefan-kolb** [comment]
In a way, but not properly.

**Comment by lenhard** [comment]
Is implemented in #2102
