### ISSUE TITLE
The context menu for entries is gone

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#5254]
JabRef version 5.0-dev

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

There is no context menu for Bibtex entries anymore (e.g. to change a field to Unicode)

1. Right click on any field (the only remaining option is "select all")

**Comment by tobiasdiez** [comment]
Reason is that the following code was commented-out:
https://github.com/JabRef/jabref/blob/f85c081e75e373820077e720fe9d48db6542704c/src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java#L51-L61

**Comment by Siedlerchr** [comment]
Ah, yes I remember it was accessing jdk internals or other forbidden things

**Comment by tobiasdiez** [comment]
This will not be easy to make work again I guess.

The relevant code moved now to TextInputControlBehavior
https://github.com/javafxports/openjdk-jfx/blob/662281e733fe59c667e8ba5e1d45eef1fcd93681/modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/TextInputControlBehavior.java#L661.

Thus, it would be simple to derive from this behavior class and add additional items to the context menu. However, I don't see a way to replace the original behavior by our customized one, because the behavior is initialized here:
https://github.com/javafxports/openjdk-jfx/blob/4f0addff16de7182752bc60541f44baeb0e99d2a/modules/javafx.controls/src/main/java/javafx/scene/control/skin/TextFieldSkin.java#L151-L154
and `behavior` in `TextFieldSkin` is private. Thus, there seems to be no easy way to register a custom behavior class. Moreover, there are no real plans from the JavaFX team to make the behavior part open to customization: https://github.com/javafxports/openjdk-jfx/issues/241.

Only option I see is the following:
Add listener for `ContextMenuEvent` and then get the `behavior.contextMenu` via reflection to add items. That's really ugly.

**Comment by Siedlerchr** [comment]
The only other ways is to only add a new context menu. This disables the default one.

**Comment by j0hannes** [comment]
What about a button for each text field? That button could also indicate possible issues (like the ugly yellow triangle to the left bottom of each field, which was always a pain to hit).

**Comment by tobiasdiez** [comment]
This is now re-implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
