### ISSUE TITLE
framedrops while in jabref window

### ISSUE THREAD

**Issue by Language44** [JabRef/jabref#5260]
I have the newest jre, newest build of jabref and I get framedrops. Its when I am in the window doing something, like moving it on desktop or working with it, fps drops from 144 Hz to around 15-20 (but 8 was the lowest Ive seen yet), the drops last for 2-5 seconds and occur every 5-10 seconds. When the window is minimized or it is still visible but I am in another window its fine, no framedrops.

My specs:
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_221

I am also on a gaming PC here, so the issue should not be hardware related.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by Language44** [comment]
nope, still framedrops. When using, always framedrops, not just periodically. I can let it be active and just move the corsor away from it to another window (not clicking it) and fps recover, I go back with the cursor, so icons get highlighted there and frame drops.

**Comment by Language44** [comment]
well, seems like noone cares

**Comment by Siedlerchr** [comment]
@Language44 Sorry, but all developers are working on JabRef in their free time and we do care about performance as well, it's just like that we not always can control all variables regarding it and most often lack developer resources. 
See also #5071

**Comment by Language44** [comment]
Hello again, this appears to be an issue with java and GSync. I have tried out another java software and the fps drops are the same, so I turned off GSync and no fps drops. Does any1 here have an idea what can be done?

**Comment by Siedlerchr** [comment]
Hm, thanks for the insight. I searched a bit around and only found some issues with Ubuntu and or that it might be some rendering which occurs when the control is moved. No idea what to do exactly. Sorry.

**Comment by AEgit** [comment]
@Language44 Have you tried using an older version of JabRef? I am using 3.8.2 because the performance of newer versions is (at the moment - I know, that the JabRef team is working on this :D) too low to operate with large databases.

Careful: JabRef 3.8.2 stores groups in a different way compared to newer versions such as 4.3.1 (or the current development version). If you try the old version you should have a copy of your database in the old format. If not, the groups you introduced in JabRef 4.3.1 will not work with JabRef 3.8.2. Similarly, if you save a database in 3.8.2 it will use the old groups format. So always keep backups of your database, before playing around with different versions.

**Comment by Language44** [comment]
I just tried 3.8.2 now and it is the same.
Well I thought it would be, because as I said its the same for other java software, like josm, which has nothing to do with jabref, just the java is the common part.
Also to mention is that the frame drops are database size independent, even if I have no database loaded, just the blank window I get framedrops.
Its just something with java and nvidia GSync.

**Comment by tobiasdiez** [comment]
Then I fear we cannot do anything on the JabRef side. I recommend that you create an issue at the official Java repository: https://github.com/javafxports/openjdk-jfx Hopefully the people there know how to fix the bug.
