### ISSUE TITLE
Error: Could not find or load main class org.jabref.org.jabref.JabRefLauncher

### ISSUE THREAD

**Issue by novak82** [JabRef/jabref#5314]
For some time I use bat file to start JabRef but master release from yesterday and today give me the error:

D:\>c:\jdk-11.0.4\bin\java.exe -jar JabRef--master--latest.jar
Error: Could not find or load main class org.jabref.org.jabref.JabRefLauncher
Caused by: java.lang.ClassNotFoundException: org.jabref.org.jabref.JabRefLauncher

It worked few days ago, but there is something wrong now.

**Comment by Siedlerchr** [comment]
Yes, this is known. The jar file can no longer be directly started. This is due to the module system with java 11.
For Windows just use the installer. You should also be able to install that in a separate dir if you want to keep an older JabRef version side by side.

**Comment by novak82** [comment]
It worked with Java 11 few days ago...

**Comment by tobiasdiez** [comment]
Support for a portable version (similar to the jar) is coming with https://github.com/JabRef/jabref/pull/5312. Shouldn't take that long until this PR is finished.

**Comment by NRJank** [comment]
with issue closed should start from .bat work again? due to apparent security/permissions issues with user folder in 5.1 I had been using shortcut to .bat file as per ["Fail to launch JVM" problem solution](https://discourse.jabref.org/t/failed-to-launch-jvm-error-prevents-jabref-to-startup/1980/10) as only way to start the program.  just checked 5.2 dev build and getting both Fail to launch JVM error and error above.

**Comment by Siedlerchr** [comment]
@NRJank  You probably need to modify the bat file again and add the arguments again. Please note that the Launcher class changed (the argument after the "-m" 
`pushd %DIR% & %JAVA_EXEC%  -p "%~dp0/../app" -m org.jabref/org.jabref.gui.JabRefLauncher`

**Comment by NRJank** [comment]
Ok, thanks. Just confirming that with that change I can load 5.2 with the bat file.
