### ISSUE TITLE
JabRef 4.3.1 slow on MacOS Mojave

### ISSUE THREAD

**Issue by bouldrini** [JabRef/jabref#5350]
Hi JabRef Dev-Team,

I'm experiencing heavy waittimes (about 10 seconds per GUI interaction) when using JabRef 4.3.1 on MacOS Mojave.

I didn't started JabRef from commandline so far. So I'm not sure if the bug occurs when running it from commandline.

I tried starting JabRef from command line using 

java -jar JabRef-4.3.1.jar 

what brought up this issue:

Error: Could not find or load main class org.jabref.JabRefMain
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

Maybe this is a local problem. I cant invest to much research here, but maybe you can figure out the problem if its a caused by JabRef application or give me a quick hint what to do to fix (if it is a local problem) so I can provide further error trace and report if the bug occurs when running from command line

best regards, bouldrini

**Comment by bouldrini** [comment]
javafx seems to provide hardware-accelerated user interface to java applications, so this seems legit to me to be a possible errorsource.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by bouldrini** [comment]
Running the development build works very well. Thank you very much @Siedlerchr
