### ISSUE TITLE
Build prcess: gradle cannot fetch mvvmfx

### ISSUE THREAD

**Issue by stefanhusmann** [JabRef/jabref#5373]
JabRef version: git commit g61e1a159cc

1. See my PKGBUILD for Arch Linux under Arch Linux https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jabref-git

Basically I use ./gradlew assemble and ./gradlew jlink

I get 
Could not find de.saxsys:mvvmfx-validation:1.9.0-SNAPSHOT.

Full buildlog :
[buildlog.txt](https://github.com/JabRef/jabref/files/3673482/buildlog.txt)

**Comment by tobiasdiez** [comment]
Our build servers have the same problem. The jar should be here: https://oss.sonatype.org/content/groups/public/de/saxsys/mvvmfx-validation/1.9.0-SNAPSHOT/ but this folder is empty. But this is not specific to this library but all folders of all libs on sonatype are currently empty, so this seems to be a (serve) problem on their side. As mvvmfx can only be found there, we have no choice and wait...

Instead of building on your own you can also download the latest build from https://builds.jabref.org/master/. Since a few days, we also provide different packages for linux as well as a tar archive that only needs to be extracted. I guess this is a preferable/easier way to distribute than to run gradlew.
