### ISSUE TITLE
Scroll bar missing

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#5374]
![grafik](https://user-images.githubusercontent.com/1366654/65935459-8056d380-e419-11e9-9ba8-0e8e8a6f8a1c.png)

**Comment by AEgit** [comment]
1) Regarding the topic mentioned here: Is this supposed to be a vertical or a horizontal scroll bar?

2) I don't know whether I should open a separate issue or whether this fits here. The scroll bar of the groups panel in the current development version is invisible when the mouse cursor is not hovered over it and barely visible when the mouse cursor touches it. This is due to the following issues:
a) Choice of colour for scroll bar and scroll bar column (both have the same grey colour when the mouse does not touch the scroll bar).
b) Very small scroll bar when there are many (i. e. thousands) groups.

A simple solution would be to just display the scroll bar in a different shade of grey all the time instead of only when the mouse cursor touches it.

**Comment by AEgit** [comment]
JabRef 5.0-dev--snapshot--2019-09-26--master--1a6c92c79
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft

Here two example pictures to showcase what I mean:

Mouse cursor does not touch the scroll bar:

![Scroll_bar_visibility](https://user-images.githubusercontent.com/12767489/65962555-df840a80-e450-11e9-9f51-139022cbeb31.png)

Mouse cursor touches the scroll bar:

![Scroll_bar_visibility2](https://user-images.githubusercontent.com/12767489/65962599-f6c2f800-e450-11e9-952f-f390ecc50f66.png)

**Comment by AEgit** [comment]
At the moment, it is impossible to know, where the scroll bar is, before moving the mouse cursor to the groups panel. Due to the chosen colour scheme, even after that, it is difficult to discern.

Changing the colour could alleviate the problem, but it does not fully address it. If I just change the colour but leave the scroll bar invisible, when the groups panel is not in focus, I still will not know, where to drag my mouse if I want to immediately use the scroll bar. Instead, I would first have to drag it to the groups panel and only then it would be possible to find the scroll bar.
This means I have to make at least 2 actions to get to the scroll bar - if the scroll bar was visible all the time, 1 action would be enough: I could immediately select the scroll bar.

**Comment by jecsanb** [comment]
Hello,
I am also trying to work on this but I am having trouble finding where the table and the scroll bar is defined. Could you point me to the file where this is suppose to be at?  I get to jabref/src/main/java/org/jabref/gui/maintable/MainTable.java but form here I am not sure what handles the scroll bar or if its parts of a scroll pane or something else. Also, did yall manually edit the fxml files or did you use something else to visually work with them? 
Thanks,

**Comment by tobiasdiez** [comment]
@jecsanb Thanks for your interest. You are on the right track, the `MainTable` class indeed handles the main table (no pun intended). However, the scrollbars are created by the built-in javafx controls (table/list) and are styled using the following css:
https://github.com/JabRef/jabref/blob/c33ba431723a345ca5877560e6c9faabd500451b/src/main/java/org/jabref/gui/Base.css#L699-L762

@AEgit 
As a compromise, I would suggest the following. Always show the scrollbars. If the users hovers something else, reduce the opacity so that the scrollbars are not emphasized that much (but are still distinguishable).

**Comment by AEgit** [comment]
@tobiasdiez 
Depending on how much they are distinguishable/visible that sounds like a fair compromise to me.

**Comment by AEgit** [comment]
Note, that the visibility problem of the scroll bar also affects the "Preferences" dialog:

1. Mouse cursor is on the right half of the "Preferences" dialog (i. e. does not touch the "Preferences" list). The scroll bar is invisible:
![Preferences_Scroll_bar_invisible](https://user-images.githubusercontent.com/12767489/66992638-0f264a00-f0c2-11e9-951d-fa50a4b6cab7.png)


2. Mouse cursor is on the left half of the "Preferences" dialog (i. e. it touches the "Preferences" list). The scroll bar is barely visible:
![Preferences_Scroll_bar_barely_visible](https://user-images.githubusercontent.com/12767489/66992655-13eafe00-f0c2-11e9-9f61-2e09a1c2e334.png)


3. Mouse cursor is direct placed on the "Preferences" scroll bar - its visibility has increased, but it is still far from being optimal:
![Preferences_Scroll_bar_visible](https://user-images.githubusercontent.com/12767489/66992668-177e8500-f0c2-11e9-8063-f10249281f07.png)

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-26----9fd49bcb2
Windows 10 10.0 amd64 
Java 12.0.2

I can confirm this has been fixed in the current dev version for the light theme. Personally, I would prefer to have a bigger contrast difference, when the cursor is not found in the groups window, but maybe this is just something I need to get used to.
Something that might need to change as well, is the thickness/width of the scroll bars - currently they seem a bit difficult to hit with the mouse: But again, this might just be something to get used to.

As mentioned in https://github.com/JabRef/jabref/pull/5515#issuecomment-546583703 there are some issues with the dark theme, but since I do not plan on using that anyway, I don't care so much about those minor issues.

Thanks again for your hard work!
