### ISSUE TITLE
Increase build number for each commit to master

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5399]
The MSI installer needs an increase in the version to properly upgrade a previous installation (otherwise you could end up with two installations in different locations). 

There are a few tools that provide such a functionality based on the git commit (i.e GitVersion WeightedPreReleaseNumber). Maybe it's also a good moment to switch to semantic versioning?

**Comment by koppor** [comment]
Wow, https://github.com/GitTools/GitVersion#--------gitversion looks really awesome.

I, however, think that we will release a new major version all times, because the user interface behaves differently. Alternatives, we will have debates on how semver works for tools.

Maybe, we can use the tool internally, but keep on our major minor versioning scheme.

More reading: use it in github workflow: https://octopus.com/blog/versioning-with-github-actions

**Comment by LyzardKing** [comment]
The releases from master, not being "stable" releases, if we want to consider the term..
could be set by `git describe --tags`
so it'll put together the latest tag plus the hash of the latest tag, to keep a different version number without having to create a different thing.
For example, in another project I have the main version set to "19.06" also as a git tag. So that will be the version one sees if they install the "stable" version. If they install from github releases or git clone/any other more up to date means they'll see "19.06-20-g0170bc3"
Not elegant, but it clearly states that they are different versions, and identifies the stable from the dev one.

**Comment by tobiasdiez** [comment]
That is a good idea but sadly does not work as the msi installer expects a version of the form 1.2.3.4 (with everything being numbers).

**Comment by LyzardKing** [comment]
From the man page:
`i.e. the current head of my "parent" branch is based on v1.0.4, but since it has a few commits on top of that, describe has added the number of additional commits ("14") and an abbreviated object name for the commit itself ("2414721") at the end.`

So the 20 after the proper version is an incremental number of commits, you could cut that.
So it would give a proper indication of the version also relative to the stable release (although jabref would be at v5.0.0-277 now)

**Comment by koppor** [comment]
We need to create different MSI installer filenames, too. This would fix https://discourse.jabref.org/t/downloading-the-snapshot-from-today-2019-10-17-fails/1775/3 with our current upload infrastructure.

**Comment by Siedlerchr** [comment]
But we still need to have symlink in the form jabref-latest-master-windows.msi to the latest snapshot then, because otherwise this is is not useful for people who uses wget or any other tool to automatically fetch the latest version.
Didn't we had this before already?

**Comment by koppor** [comment]
@Siedlerchr You refer to the long discussion at https://github.com/JabRef/jabref/pull/5312, especially https://github.com/JabRef/jabref/pull/5312#issuecomment-534897776.

Also refs https://github.com/JabRef/jabref/issues/5398.

**Comment by tobiasdiez** [comment]
With the latest update of jpackage, this issue has now increased priority as trying to install a dev version although a dev version is already installed results in the following:
![error](http://www.steelbytes.net/wp-content/uploads/2014/11/msi_error_1638_another_version_already_installed.png)

Thus, the user has to manually deinstall the previous version. 

@koppor This also means that if we release now a 5.0.0 (beta) the full release needs to have at least 5.0.1 as version number.

**Comment by bernhard-kleine** [comment]
Why do you not think about removing the previous version and then installing the new one"?

**Comment by stefan-kolb** [comment]
Refs #5657

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by bernhard-kleine** [comment]
@tobiasdiez The closing was premature. In the master dir there is still the file jabref-5.0.0.msi which is named as all the files before. No number to make it unique. And the other points about overinstalling are not yet tackled.

**Comment by tobiasdiez** [comment]
We had some problems with our build server. Should be fixed now.
