### ISSUE TITLE
Icon disappears on Mac OS X 10.15

### ISSUE THREAD

**Issue by perrogg** [JabRef/jabref#5419]
JabRef version <4.3.1> on <Mac OS X 10.15>

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. I installed  Jabref with "brew cask install jabref"
2. The icon disappears on Launchpad page 
<img width="348" alt="3" src="https://user-images.githubusercontent.com/14990848/66553181-3b4f4180-eb7d-11e9-8f9c-f58ca1224582.png">
3. If I put it in a subfolder on Launchpad page, I can see the  icon;
<img width="321" alt="1" src="https://user-images.githubusercontent.com/14990848/66553159-34c0ca00-eb7d-11e9-9b13-6ade39bdb310.png">
 but I click the subfolder, I cannot see the icon.<img width="913" alt="2" src="https://user-images.githubusercontent.com/14990848/66553168-38545100-eb7d-11e9-8f67-fddb23e58fb9.png"> 

I am not sure it is  a "bug" of Jabref or of Mac OS X.
It do not affect the normal use of the app. It just looks ugly.
 
Is there any solution?

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
