### ISSUE TITLE
Install instructions mention Java 11 but build expects Java 12

### ISSUE THREAD

**Issue by egonw** [JabRef/jabref#5478]
I'm following the build instructions from http://help.jabref.org/en/Installation#building-from-source (link given by the README), and running into a few issues. The first was easy to solve, but at least at Debian 10 you need to set JAVA_HOME (minor issue).

A bigger problem is that Java 11 does not seem enough anymore, and I get this error in the `./gradlew assemble` step:

```
Found module name 'org.jabref'

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not target platform: 'Java SE 12' using tool chain: 'JDK 11 (11)'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 6s
7 actionable tasks: 7 executed
```

**Comment by Siedlerchr** [comment]
Yes, sorry We recently upgraded to jdk 12 in #5426  and forgot to update the documentation

**Comment by Siedlerchr** [comment]
I upgraded the wiki part. If no jdk12 is avaiable in your repos you can install the version from here:
https://bell-sw.com/pages/java-12.0.2/
See you later ;)

**Comment by jairus-crabb** [comment]
Hi, I'm a newbie. I'm also experiencing this same issue. I initially started with Java 13 since Java stopped supporting it recently, but found this thread and switched over to Bell's Java 12 that you posted above. 

Still receiving the exact same errors as the original poster. I've checked PATH, JAVA_HOME, etc. Followed all the instructions over at: https://github.com/JabRef/jabref/wiki/Guidelines-for-setting-up-a-local-workspace

Only thing I am thinking is that I'm not super familiar with IDEA, and that maybe my compiler overrides are not formatted correctly? Not sure if this would affect anything. I'll try a restart and give an update if that fixes.

**Comment by Siedlerchr** [comment]
Best is to ask in our gitter chat, there are some folks who use Intellij https://gitter.im/JabRef/jabref

**Comment by Krzmbrzl** [comment]
I just encountered the same issue when following this instructions: http://help.jabref.org/en/Installation

I downgraded to Java 11 via the `build.gradle` and was able to successfully build JabRef as per the instructions though. So I don't know if Java 12 is actually really required :thinking:

**Comment by Siedlerchr** [comment]
@Krzmbrzl We explicitly moved to jdk12 in JabRef (although we previously used java 11 in the 5.0 alpha) to be able to check if it runs on newer jdks as well (13 does not yet work). And as the build tools now generates a custom jdk for running JabRef it's irrelevant for the end user which jdk he has installed.
So please change it to java 12 again.
https://builds.jabref.org/master

**Comment by Krzmbrzl** [comment]
> So please change it to java 12 again.

Nah I won't do that as I don't have Java 12 on my system. But I don't intend pushing these changes anywhere else so that's my personal mess :)

**Comment by tobiasdiez** [comment]
There are a few places in Intellij were one could select the JDK to run/compile the project. All of these have to be set to JDK 12 (or "use module/project"). 

For example: 
- Build, Execution, Deployment > Compiler
- Project Settings > Project > Project SDK and Pattform Settings > SDK
- Edit run configuration

Hope this helps!

**Comment by jairus-crabb** [comment]
I was able to get rid of this error by specifying Java 12 for Gradle, but now I'm getting an error due to possible duplicate VM options? The module overrides specified in the installation instructions also show up if you go to Run/Degub configurations for JabRef Main. You'll see them listed in "VM Options", as I remove them, the first one in that list will show up with the error:

> Task :JabRefMain.main() FAILED
Error occurred during initialization of boot layer
java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: test2 specified more than once to --patch-module

(this is after I removed the first option to specifiy "test" so it moved to the next one "test2")

I'm assuming these are needed to build, is there somewhere already in the code where these are specified? I think having them added to the VM options is what is giving me trouble. I'm also new to this so I want to make sure I'm not messing anything up.
