### ISSUE TITLE
Improve BibtexParser

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#548]
The following points should be improved/fixed in the BibTex parser:
- [x] Combine multiple keywords, SF Bug #1269 and test `parseCombinesMultipleKeywordsFields`
- [x] Recognize and warn about unmatched brackets, see test `parseIgnoresAndWarnsAboutEntryWithUnmatchedClosingBracket`
- [x] Recognize and warn about `@` symbol in brackets (it has to be escaped in quotation marks), see test `parseIgnoresAndWarnsAboutEntryWithAtSymbolInBrackets`
- [x] Bug: Month field ending with a comma is ignored. Compare SF Bug #1283 and test `parseRecognizesMonthFieldsWithFollowingComma`.
- [x] Bug: preamble is not recognize if there is a space between `@preamble` and the bracket, see test `parseRecognizesPreambleWithWhitespace`.
- [x] Bug: preamble is not recognized if it is encapsulated in round brackets, see test `parseRecognizesPreambleInParenthesis`
- [x] Bug: tabs and newlines in the file field should be ignored, see tests `parseRemovesTabsInFileField` and `parseRemovesNewlineInFileField`.
 
And some more coding-related issues:
- [ ] Add tests checking parsing of JabRef's metadata (groups etc.)
- [x] Enrich tests to check that parsed serialization is correctly determined. This is probably something for @lenhard. 
- [x] Move "Automaticaly remove double braces" to cleanup.
- [x] Remove all references of JabRefPreferences in parser class.

**Comment by oscargus** [comment]
I wasn't aware of that round brackets/parenthesis could be used and played around a bit with that. It turns out that one can match curly and round brackets around an entry. I guess that is OK from a practical perspective, although one could think of a warning.

Regarding `parseIgnoresAndWarnsAboutEntryWithUnmatchedClosingBracket`: how would one know that it is an extra closing bracket and not just a comment (i.e. everything outside of an entry)?

Do you have any reference for `parseIgnoresAndWarnsAboutEntryWithAtSymbolInBrackets`? I'm not sure the current behavior is incorrect. I tried running BibTex on an entry like this and for title it just ended up in the title, while adding a single @ in the author name resulted in a single . (i.e. an additional first name, but the @ was removed).

**Comment by tobiasdiez** [comment]
The problem with `@article{test,author={author bracket } to much}}` is that even if the first bracket ends the field, the end `to much` is no real field. So in either case, JabRef should warn the user.

For the @ sign, see ["The File Format"](http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html)

**Comment by oscargus** [comment]
Oh yeah, I missed that aspect.

I read that earlier and didn't find anything like that, but now I see what you are referring to. However, I'd say that it is not correct.
```
@Article{key01,
  title = { The history of @ sign } 
}
```
is indeed working well in Bibtex (I've only tested with IEEEtran.bst, though).

**Comment by lenhard** [comment]
I have now implemented a few things and have a few comments:
 - `parseRemovesTabsInFileField ` and `parseRemovesNewlineInFileField` will remain ignored. The parser should not modify field content. That is the purpose of validators that should be executed later 
 - I have real issues implementing `parseWarnsAboutUnmatchedContentInEntryWithoutComma` (refactored from parseIgnoresAndWarnsAboutEntryWithUnmatchedClosingBracket`). We need to be able to parse content after a field is concluded but before a comma is found to process Bibtex strings. Since this is just a rare edge case of an invalid entry, I do not want to waste too much time on it and will leave the test case ignored. If someone wants to, feel free to implement this validation.

**Comment by lenhard** [comment]
The thing that remains now is tests regarding meta data. I'll move this to a new issue.

**Comment by koppor** [comment]
Refs #123

**Comment by lenhard** [comment]
@koppor: Why did you add "Refs #123" here? We decided not to replace the parser and writer, but to keep and improve them. Thus, #123 is a non-issue, there is no reason to link back to it.

**Comment by koppor** [comment]
The decision not to use a grammar is documented at #123. I just put the
reference in case someone wonders why we did not use an existing library.
Architectural-Decisions-Complete 😇
