### ISSUE TITLE
Open PDF options

### ISSUE THREAD

**Issue by Krzmbrzl** [JabRef/jabref#5529]
In the settings under `External programs` -> `Open PDF` the only options are `Adobe Acrobat Reader` and `Sumatra Reader`. To me a generic field (e.g. `Other`) is missing here as one can't assume that all JabRef users have either one of those readers installed.

For instance I am running JabRef on Linux with `Okular` as my reader of choice. In my case neither of the two options is selected and it seems to be working reasonably well (see #5253). Still the settings page is very confusing for such a case.

My suggestion would be to
a) Add a hint that these paths are only needed if one wants to use either one of the listed applications and one doesn't need to worry about this setting if not
b) Add a generic `Other` field in which the user can add the path to the PDF reader of their choice

Maybe also a combination of a) and b)

**Comment by Siedlerchr** [comment]
The preferences are obsolete, more or less historic things.
Since several versions (maybe v4?) bvy default JabRef delegates file opening to the system and simply calls "xdg-open" with the filepath as argument on linux.

The code is in JabRefDesktop/NativeDesktop. Should be cleaned up. 

For custom external types, you can configure an apporiate applicaiton.

**Comment by Krzmbrzl** [comment]
So the solution woul be so simply remove these menu entries altogether?
