### ISSUE TITLE
Comment should be multi line field

### ISSUE THREAD

**Issue by boceckts** [JabRef/jabref#555]
MedlinePlain format supports multiple comments in its txt files. They will also be imported into multiple lines and shown as such in the comment section in the general tab. However when looking into the BibTex-Source the comment will be reduced to just one line. Now testing a file in medlineplain format with multiple line comments against its bibtex file will give me an ComparisonFailure error in the BibtexEntryAssert class.

**Comment by oscargus** [comment]
Yes, allowing more "advanced" formatting of comment, review, and abstract fields are indeed useful.

**Comment by lenhard** [comment]
As opposed to the `review` and `abstract` fields, `comment` is no "official" Bibtex field, at least in our model. We should propably just discard newline elimination for all fields.

**Comment by lenhard** [comment]
I just stumbled upon this old issue during house keeping. Since `comment` is no official field, we will certainly not hard-code special handling for it. However, the behavior desired here can be achieved by adding `comment` to the list of non-wrapable fields (preferences-file), since these are ignored during new line elimination.

**Comment by koppor** [comment]
+1 for configuring it as multiline field.
