### ISSUE TITLE
Gui tests are broken

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5602]
All special types of tests (fetcher, database and gui) are currently broken. At least the fetcher tests should be fixed before the release of 5.0.

I would also vote to remove the "allow failure" for these tests (as soon as they are fixed).

**Comment by koppor** [comment]
For reference: 

- Test results before junit5 conversion: https://travis-ci.org/JabRef/jabref/builds/610556163?utm_source=github_status&utm_medium=notification
- Test results after junit 5 conversion: https://travis-ci.org/JabRef/jabref/builds/610581351?utm_source=github_status&utm_medium=notification 

We once decided to allow failures at the fetcher tests, because we cannot control the online services. PRs will fail, because some external servers are down. This is not what we want to achieve (maybe it got better in 2019 with the external servers; however: data formats change in 2019, too. See #5582)

We decided to have fetcher tests running on a periodical schedule. Now, this is (easily?) possible with GitHub workflows. So, why not move the fetcher tests to a separate GitHub workflow running each Monday 6am?

In case a PR touches fetchers, we can trigger the check manually (can we?) or a developer has to execute it locally (or [using gitpod](https://medium.com/gitpod/github-flows-better-with-gitpod-e455d17990f9))

**Comment by Siedlerchr** [comment]
Note that the database Tests were not executed in gradle correctly before my PR.

**Comment by tobiasdiez** [comment]
Fetcher and database tests are now working, only the GUI tests are left.
