### ISSUE TITLE
Writing XMP data to PDF does not work

### ISSUE THREAD

**Issue by fmartelg** [JabRef/jabref#5605]
JabRef 5.0-alpha
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft

Steps to reproduce:

1. select entry
2. Tools > Write XMP metadata ...
3. Error 

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Writing XMP-metadata...
Finished writing XMP for 0 file (0 skipped, 1 errors).
```

</details>

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by fmartelg** [comment]
@tobiasdiez 

Same error on version

```
JabRef 5.0-alpha
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft
```

**Comment by AEgit** [comment]
@fmartelg : As far as I can tell, you are using the 5.0 Alpha version from https://github.com/JabRef/jabref/releases.

If so, you might want to try the latest development version: https://builds.jabref.org/master/
(I think at the moment you have to use the portable version, since there is a problem with the installer.) Before installing the dev version, always remember to make a backup of your database, in case something goes wrong.

**Comment by Siedlerchr** [comment]
If you have any previous 5.x version installed, you might need to uninstal it first

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by TPuupera** [comment]
Works now thanks!
