### ISSUE TITLE
Counts of selected items

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#5675]
Hi
In version 5, the line number are removed. I used previously those lines to help me counting how many results I had instead of manually counting them. 
Have you considered showing in state bar the number of selected items? For now, only the number of search results are shown, meaning I have to narrow my search to exactly fit my sub-selection to know how many items are selected. 
Thanks.

**Comment by CloudFenrir** [comment]
Hello, I'll work on this issue, it seems no else is doing it.

**Comment by calixtus** [comment]
Hi @melTr .
This issue should be fixed in the latest master build, you should be able to add an index column via options menu > preferences > entry table columns. I would appreciate it, if you could test it and tell us, if it is sufficient for your needs. Please don't forget to always backup your data before testing the current dev-build.

**Comment by melTr** [comment]
Thanks. Was able to try today and works as expected.

**Comment by mucmch** [comment]
Thanks a lot, was also looking for that feature. probably should be enabled by default. else takes a while to find that feature.
