### ISSUE TITLE
Rethink displayable fields vs. writeable fields

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#574]
JabRef has following flags for fields to distinguish between to be shown in the BibTeX source tab and to be written to a file.

In `net.sf.jabref.gui.BibtexFields` this is shown as follows:

``` java
private static final int STANDARD = 0x01; // it is a standard bibtex-field
private static final int PRIVATE = 0x02; // internal use, e.g. owner, timestamp
private static final int DISPLAYABLE = 0x04; // These fields cannot be shown inside the source editor panel
private static final int WRITEABLE = 0x08; // These fields will not be saved to the .bib file.
```

The comment at `DISPLAYABLE` and `WRITEABLE` should IMHO be the other way round.

With #391, the source editor tab also shows write-only fields when the entry was not modified:

![grabbed_20151223-181053](https://cloud.githubusercontent.com/assets/1366654/11981192/b43288f0-a9a0-11e5-9e61-ae1b51177bab.png)

A possible solution is to rethink non-displayable fields. My current opinion is to write these markings in a separate `@comment` entry (`jabref-meta`) or as comment above the entry itself to keep the original entry clean. Reason: (i) For me as user it is not understandable why the displayed rendering is different from the writing in the `.bib` file. (ii) For me as developer I do not want to offer easy change JabRef's internals. Therefore, I'd like to separate JabRef's markings from the entry data. This should remove the `DISPLAYABLE` and `WRITEABLE` flags.

Finally, the flags `STANDARD` and `PRIVATE` should be obsolete and removed.

**Comment by tobiasdiez** [comment]
In #629 I actually propose the converse for groups: serialize the explicit group membership as a field `groups` in the entry instead of a comment at the end. In my opinion the advantages of such an approach (as listed in #629) outweigh your concerns. In particular, concerning your remarks in the last paragraph:
1) This can be solved easily by displaying all the fields in the "Bibtex" tab.
2) From time to time I find it quite convenient to change the properties of an entry using the bibtex code instead of the UI. 

I think this is something for the next dev-call.

**Comment by koppor** [comment]
Decision: show all fields being written. It has to be the same serialization as being written.

TypedBibEntry has no own state. State only at BibEntry.

If possible, remove `isSearchHit()`.
