### ISSUE TITLE
Error installing latest beta on Windows

### ISSUE THREAD

**Issue by skanskan** [JabRef/jabref#5763]
Hello.

When I try to install the latest snapshot version (JabRef-5.0.msi beta) on Windows 10 I get this error:

This installation package could not be openened. Contact the application vendor...

**Comment by Siedlerchr** [comment]
Hi,
the official msi installer from works fine https://www.fosshub.com/JabRef-old.html

Regarding any newer master snapshots, we currently experience issues with our build server so it can happen that the files are not uploaded completely

**Comment by skanskan** [comment]
That one works, thank you.

**Comment by FossHub** [comment]
If the Jabref team agrees, I will make a suggestion. Set up a new project page where you can post the alpha/beta/nightlies/test versions of Jabref. Here's an example of projects that do this:

https://www.fosshub.com/Pre-Release.html

I thought to write here since you said that you're experiencing issues with the build server. Also, a friendly reminder that we have a 100% SLA agreement on the delivery part, unlimited bandwidth, and you can push updates (multiple users available) as much as you want through the API/CLI/web interface, etc.

**Comment by koppor** [comment]
Thank you for writing. I had this offer in today's inbox and also via mail on August, 25th. I did not make it transparent to @JabRef/developers (and only informed @stefan-kolb), because I thought, I should not take our time in that regard and have the other developers focused on fixing issues and improving the code.

Following are the alternatives:

Upload the files inside the existing version and at the version field enter "beta" "alpha" etc. qBittorrent, or Hwinfo did this:

https://www.fosshub.com/HWiNFO.html
https://www.fosshub.com/qBittorrent.html

2. Different page for JabRef, something like this. A few projects use this:

https://www.fosshub.com/Audacity.html
https://www.fosshub.com/Audacity-devel.html

https://www.fosshub.com/PSPad.html
https://www.fosshub.com/PSPad-devel.html

The proposal with "Pre-Release" is similar as "-devel". The issue we have with this is is that users cannot switch easy between beta and release version. With the current setup, it is just a click away:

From https://downloads.jabref.org (which should be linked everywhere), we redirect to https://www.fosshub.com/JabRef-old.html. There, the page renders as follows:

![grafik](https://user-images.githubusercontent.com/1366654/71117188-f1ff1c00-21d5-11ea-9708-7cfd22900e97.png)

With the highlighted button it is easy for users to go through our main download page:

![grafik](https://user-images.githubusercontent.com/1366654/71117223-03482880-21d6-11ea-85eb-793eb32238d2.png)

There, the button "Older Versions" leads to the beta page.

We decided to link to <https://www.fosshub.com/JabRef-old.html>, because we want to show the beta versions first and the label "Older Versions" is confusing. We cannot change the label of the button "Older Versions".

If we had https://www.fosshub.com/JabRef-devel.html, there was no link between that and https://www.fosshub.com/JabRef.html. This is IMHO not a good user experience. At other download pages, the versions of one tool are closely linked. 

See for instance our download at the German news magazine heise.de (<https://www.heise.de/download/product/jabref-24459/download>):

![grafik](https://user-images.githubusercontent.com/1366654/71117381-51f5c280-21d6-11ea-8150-ae15a9d6fa80.png)

Thinking of the #GenderMag method (@igorsteinmacher), I would say that the current solution is not as confusing to the downloaders than the proposed solution. I can also do the whole GenerMag analysis with sheets to have a more scientific basis on my thinking.

**Comment by FossHub** [comment]
@koppor I was trying to understand why you're putting them there. No worries, we noted down, this will be implemented in our next platform and site update, to provide an ETA it will be somewhere around January 2020 so approximately one month +/-
