### ISSUE TITLE
There is not a horizontal scroll bar in the entry table.

### ISSUE THREAD

**Issue by luo-chuan** [JabRef/jabref#5791]
There is not a horizontal scroll bar in the entry table. If there are too many columns in the entry table, user can not see the columns on the right side. Please add a horizontal scroll bar, thanks!

JabRef 5.0-beta.30--2019-12-23--51d6986
Windows 10 10.0 amd64 
Java 13.0.1

**Comment by calixtus** [comment]
Hi @luo-chuan 
I took a look at your issue: the horizontal bar is only displayed, if the table columns are not set to fit the window width. Otherwise the columns should all be resized automatically to fit the window size. This can sometimes mean, that you have to manually adjust the width of the columns, if they are too small or you added too many of the columns.
You can change that behaviour in the options menu > preferences > entry table > "Fit table horizontally on screen".
