### ISSUE TITLE
in: section missing in default style

### ISSUE THREAD

**Issue by soloturn** [JabRef/jabref#5792]
JabRef 4.3.1, linux imports a microsoft word "BookSection" as "Book". 

```
@Book{Klo18,
  author     = {Klopsch, Britta and Sliwka, Anne and Maksimovic, Aleksandra},
  title      = {Familie als Sozialisationsinstanz},
  year       = {2018},
  publisher  = {UTB},
  location   = {Regensburg},
  pages      = {375},
  bookauthor = {Gogolin, Ingrid and Georgi, Viola and Krüger-Potratz, Marianne and Lengyel, Drorit and Sandfuchs, Uwe},
  booktitle  = {Handbuch Interkulturelle Pädagogik},
}
```

when connecting to libreoffice 6.3.4 it ends up with:

Klopsch, B., Sliwka, A. & Maksimovic, A. (2018). Familie als Sozialisationsinstanz. Regensburg: UTB.

the "in" section seems to be missing in the default style to make it like this:

Klopsch, B., Sliwka, A., & Maksimovic, A. (2018). Familie als Sozialisationsinstanz. In I. Gogolin, V. Georgi, M. Krüger-Potratz, D. Lengyel, & U. Sandfuchs, Handbuch Interkulturelle Pädagogik (S. 375). Regensburg: UTB.

then i changed it to "inBook" - but still it is not doing as expected, there is a:

inbook=\format[Authors(LastFirst,Semicolon)]{\author} (<b>\year\uniq</b>). <i>\chapter</i>. In: \format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\editor} (Ed.), <i>\title</i>, \publisher.

**Comment by soloturn** [comment]
```
$ git diff
diff --git a/src/main/resources/resource/openoffice/default_authoryear.jstyle b/src/main/resources/resource/openoffice/default_authoryear.jstyle
index e0c5b2443..72777a76b 100644
--- a/src/main/resources/resource/openoffice/default_authoryear.jstyle
+++ b/src/main/resources/resource/openoffice/default_authoryear.jstyle
@@ -16,8 +16,8 @@ ReferenceHeaderParagraphFormat="Heading 2"
 
 CITATION
 BibtexKeyCitations=false
-AuthorField="author/editor"
-YearField="year"
+AuthorField="author"
+EditorField="editor/bookauthor"
 MaxAuthors="2"
 MaxAuthorsFirst="6"
 AuthorSeparator=","

```

**Comment by tobiasdiez** [comment]
I fear I cannot really help, as I've no experience with the openoffice integration but @Siedlerchr is our expert in this regard.

**Comment by Siedlerchr** [comment]
The real reason is that the style does not support the field bookauthor. 
Either you change the field to editor and use inbook or you can use your own style:

You can however create your own custom style based on the default open office style.
Just modify the book formatter entry, add bookauthor instead of editor,  and save it to another folder and give it a name, .e.g customauthoryear.jstyle 
Then in the OpenOffice style select dialog you can choose your own style.
See the documentation for reference: https://docs.jabref.org/import-export/other-integrations/openofficeintegration
