### ISSUE TITLE
Importing a duplicate reference entry via JabRef-Browser-Extensions and using the merge feature is erroneous

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5858]
I am using the latest JabRef 5 master build:
on Ubuntu 16.04

**Steps to reproduce it:**

1. Import reference R into JabRef using the official JabRef-Browser-Extension.
2. (Accidentally) delete some data/letters and/or add additional information to the imported reference R in JabRef (and optionally save updated library).
3. Trigger re-importing the same reference R to JabRef using the JabRef-Browser-Extension once again.
4. In JabRef's import dialog a small indicator appears, when hovering, it states "Possible duplicate of existing entry. Click to resolve."
5. Click the resolve button.
6. In the merge dialog select all those values of the reference R from the fresh import (labelled with "From import"), which have been (accidentally) deleted/modified previously.
7. Press the button "Keep merged entry only" at the merge dialogue.
8. The merge dialog vanishes.
9. Now, whatever I do with the still visible import dialogue (either pressing "Cancel" or "Import entries" to import the selected reference R once again), the previous merge process finalized in step 7. has no effect. **ADD:** Ok, now I see what is going on: The previously merged result is now "stored" in the entry which is shown in the import dialog. If this entry gets imported now and one clicks at the subsequent alert message "Duplicates found" the button "Continue with import", then the old (modified) entry and the freshly **merged** entry appear side by side in the reference list. In the merge process in step 7. I would have expected, that the already imported, old entry gets updated and no new reference gets imported due to the previous merge process, since the merge button is labelled with "Keep merged entry only".

Furthermore, in step 7. with the merge dialogue:
- If the button "Remove old entry" gets clicked instead of the button "Keep merged entry only", the old entry will still not be removed and nothing happens.
- I am not sure, whether the button "Keep both" is needed in the merge dialogue (or whether it has any effect), since it seems equivalent to "Cancel".
- The button "Remove old entry" is NOT operational.
- The button "Remove entry from import" is operational.

**Comment by systemoperator** [comment]
Issues still persists. Description has been extended.

**Comment by ruilvo** [comment]
I have this exact issue, as filed. Commenting to try re-opening it.

**Comment by ruilvo** [comment]
For completeness:

```
JabRef 5.3--2021-07-05--50c96a2
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8
```

My problem is *exactly* what the OP describes. I use the web extension a lot because it gathers more stuff than DoI. It's often that I add something via DoI or file, and then visit the webpage to get the extra information, and get it merged. But right now, I end up having to import, accept the merge error, and then manually merging. 

As the OP mentioned, the little button in the corner in the import window does nothing as far as I'm concerned. I try to "keep merge" but nothing happens....

I think this showcases the issue:


https://user-images.githubusercontent.com/8402646/129347349-da1edb3a-c79b-4dea-a6f9-58396a415ac1.mp4

**Comment by HoussemNasri** [comment]
Refs #6190

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
