### ISSUE TITLE
ScienceDirect Fulltext download does not work

### ISSUE THREAD

**Issue by reox** [JabRef/jabref#5860]
JabRef version
```
JabRef 5.0-beta.360--2020-01-21--7ddfd9f
Linux 3.10.0-1062.1.1.el7.centos.plus.x86_64 amd64 
Java 13.0.2
```
which is the latest linux portable version.

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Add article from journal published on ScienceDirect (for example https://doi.org/10.1016/j.bone.2020.115226 - should also be open access)
2. Fetch fulltext
3. No fulltext can be found

Is it possible that the sciencedirect fetcher does not work right now?
I have this problem with basically all articles on ScienceDirect. 

Unfortunately, I do not see an error on the console but only this:
```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

(JabRef:31036): dbind-WARNING **: 15:53:04.723: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-QJZBfCtpQI: Verbindungsaufbau abgelehnt

(JabRef:31036): Gdk-WARNING **: 15:53:05.744: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```
Also the event log (Help -> Event Log) is empty

**Comment by Siedlerchr** [comment]
You are right, there is a problem with the ScienceDirect Fetcher, more specifically with the download of the pdf. 
The underlying problem is that sciencedirect uses Cloudfare to protect the redirects/download and thus JabRef cannot download the pdf file.
I currently see no way how to easily fix this.

**Comment by reox** [comment]
thats too bad :( Looks like they want to push Mendeley...

**Comment by bernhard-kleine** [comment]
There is also a problem with Sciencedirect and Elsevier: Any download is possible for any German university since the contracts with Elsevier are not valid any further. Therefore you need to test this at a place where downloading from Elsevier is actually possible. I do not know whether there are problems for foreign universities, too.
