### ISSUE TITLE
[shorttitle] adds spaces between words for linked files

### ISSUE THREAD

**Issue by joelostblom** [JabRef/jabref#5889]
`[shorttitle]` behaves as expected when set in the "Bibtex key generator" section of the preferences dialog. However, when using it in the "Import" section and then right clicking a PDF file and clicking "Rename file to a defined pattern", the resulting PDF name will have spaces between the words in the title. For example, [this page](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0227707) becomes `Assessment peritoneal microbial` instead of `Assessmentperitonealmicrobial` which can be a problem in for applications that don't play well with spaces in filenames. Is there a fix or workaround for this behavior?

I also noticed that the file extension will be capitalized to `.PDF` rather than `.pdf`. I can open a separate issue for this, but thought I would ask here first if there is a setting for this somewhere or if I would need to report it as a feature request/bug.

I installed jabref via the `jabref-latest` AUR package.

```
JabRef 5.0-beta.382--2020-01-28--0b53d4b
Linux 5.4.14-arch1-1 amd64 
Java 13.0.2
```

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Would `[shorttitle:regex(" ", "")]` work?
Perhaps it is an idea for a new modifier?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
`[shorttitle:regex(" ","")]` probably won't work until #6893 is merged. Perhaps `[shorttitle:regex(" ","_")]` is a possible workaround until then.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
`[shorttitle]` should work as @joelostblom describes and currently `regex` is a viable workaround. Should this issue be closed and a separate one opened regarding the `PDF`/`pdf` issue?

**Comment by Siedlerchr** [comment]
If the things are working now as expected (the issue was about version 5.0beta), the issue can be closed

Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
