### ISSUE TITLE
JabRef5 vs Jabref4.3

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#5933]
JabRef 5.0-beta.409--2020-02-09--6a9c915
Windows 10 10.0 amd64 
Java 13.0.2

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open the file in the new JabRef5
2. Open the file in the old JabRef4.3
3. See screenshot below

Guys, backwards compatibility with Bibtex/Biblatex is quite important, especially if one is working across OSes and has a bibliography carefully tweaked and collected for decades!

![image](https://user-images.githubusercontent.com/10846169/74153147-37f1c280-4c10-11ea-9473-462d0f023e64.png)

**Comment by AEgit** [comment]
The developers always state clearly that you should create a backup of your database before using the current developer version of JabRef. It is well known, that the current dev version does not offer backwards compatibility for certain features. E.g.: I am still using version 3.8.2 in a productive environment, but from time to time I will install the latest developer version to help a bit with bug-testing. I never use my actual working database for these tests, but only copies, since the way groups are stored has dramatically changed between the different versions.

As far as I understand there are currently not enough developers to allow for backwards compatibility (and to be honest, I think currently stability, bug removal, and performance should be more of a priority than such an additional "nice-to-have" feature). But maybe it should be made more clear in the help files that you should ALWAYS make a backup of your database when using the developer version and that backwards compatibility can NOT be guaranteed at the moment.

**Comment by DOFfactory** [comment]
Yeah, the thing is that it is not the bib file that is screwed but somehow the settings (deep inside W10 somewhere). Tried to uninstall all JabRef, every version, and reinstall 4.3.1, using the backed up bib file (which I can visually check that is fine), but JabRef is still showing the same screwed up page as above (even in the old 4.3.1 version). This speaks for itself, you as a developer can congratulate yourself. All you can do is blaming the users...

**Comment by AEgit** [comment]
I am afraid, I am only a user myself - though one, that understands, that you cannot have everything you wish for, especially when dealing with a project of such size without any additional financial backup.

**Comment by calixtus** [comment]
Hello @DOFfactory , thank you for your problem report. We know that some people would like to have backwards compatibility, but please understand that we all do this in our spare time. Keeping JabRef backwards compatible and maintain old versions would require an enormous amount of resources and development time, which we just don't have.

Nevertheless, we try not to break anything on purpose. But since we are in the process of modernizing the code base of JabRef (which is almost 17 years old in its core), there may be some backward-incompatibilities between major releases.

About your problem: Please try to reset the settings in JabRef 3. The error you see is caused by the way Jabref handles the display of fields. None of your entries should be lost or damaged.

**Comment by DOFfactory** [comment]
I do not care about your JabRef software, but it should not break the `bib` file. That;s all I require in relation to "backward compatibility". 

Regarding resetting the settings, how should I do that if I cannot open the Preferences? It simply does not open.

**Comment by calixtus** [comment]
The command line option "-d all" should do the trick.
Depending on your OS this means e.g. "JabRef.exe -d all" or "java -jar JabRef.jar -d all"

Please be nice to each other. JabRef is a project of some open source enthusiast and we always welcome people who contribute to JabRef, with both issue reports and code contributions. Please also note, that we primarily use the forums or the gitter-chat for support.

I can understand, that you are upset if you think, JabRef corrupted your library. Please remember always to create backups of you libraries, if you try a beta-version of JabRef. But again, in this case the bib-file should not be corrupted, even if the main table in JabRef 3.8 appears empty.

**Comment by Siedlerchr** [comment]
Just for your information, on Windows the preferences are stored in the registry.

**Comment by DOFfactory** [comment]
Thanks, this reset the settings, wasted 2 hours on this. At least I am back to what I had.

**Comment by koppor** [comment]
@DOFfactory Maybe you will be happy that we are working on a fix for that for 5.1 at https://github.com/JabRef/jabref/pull/6296.
