### ISSUE TITLE
Font size increase does not increase preferences font size

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6039]
![grafik](https://user-images.githubusercontent.com/1366654/75488915-7ed20d00-59b1-11ea-9d83-80e76e90b355.png)

**Comment by LuckyOne09** [comment]
Hi, I found something strange when I try to reproduce this bug. If I increase the font size too large, then the UI will be like this: 
![bug_related_font_size](https://user-images.githubusercontent.com/38714962/77840262-ed280c00-71b7-11ea-8122-b0b98aac5022.JPG)
You can see when font size is too large, there is no menu displaying above. Hence, it will be very difficult to find what I want(In fact, I spent long time to try to find preference tab again.). So I guess that it may be another bug?

**Comment by LuckyOne09** [comment]
Hi，@koppor 

I have been working on this for a long time. I feel that I have found some useful things. But I am still confused about some implementations of JabRef. 
I found that in the ThemeLoader.java, there are codes that are responsible for changing the font-size according to JabRefPreferences.
 
https://github.com/JabRef/jabref/blob/7cb7ea60324932723db22fcd1964e26f73f7d9b4/src/main/java/org/jabref/gui/util/ThemeLoader.java#L75-L84

I guess that the cause of this bug is that these codes only change the font size of elements in root. But like elements in Apperance tab, they are in other more specific style class.

https://github.com/JabRef/jabref/blob/7cb7ea60324932723db22fcd1964e26f73f7d9b4/src/main/java/org/jabref/gui/preferences/AppearanceTab.fxml#L17-L19

Therefore, I think that is why the font size change in root can't affect the preferences font size. (By the way, except preferences dialog, nearly every dialog suffer this bug.)
![bug1](https://user-images.githubusercontent.com/38714962/81041860-70d4c700-8ee1-11ea-96f3-72ffd6864981.jpg)

I tried to get the specific style class of preferences dialog,so I added codes in Themeloader.java to solve this problem like that:

![solution](https://user-images.githubusercontent.com/38714962/81042054-e2ad1080-8ee1-11ea-8f9a-9a57491a50cd.JPG)

Unluckily, it didn't work.

I am wandering now...... So I will appreciate you very much if you could give me some hints or suggestions.

**Comment by Siedlerchr** [comment]
Hi, maybe that helps: The PreferencesDialog has it's own CSS file, I am not sure how it's overriden or related to the main file
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/preferences/PreferencesDialog.css

**Comment by LuckyOne09** [comment]
Hi,@Siedlerchr
Thanks for your help.
But I found that there are no invocation to add PreferencesDialog.css to any scene.

![screenShot](https://user-images.githubusercontent.com/38714962/81048520-117db380-8eef-11ea-8b01-bec8701b43e4.png)

And in the PreferencesDialog, there are no settings about font size. Therefore, it seems that it is not useful for fixing this bug?

**Comment by LuckyOne09** [comment]
Now, we guess that maybe the cause is that when click Preferences.
many scenes will be created according to the codes:

https://github.com/JabRef/jabref/blob/7cb7ea60324932723db22fcd1964e26f73f7d9b4/src/main/java/org/jabref/gui/preferences/PreferencesDialogViewModel.java#L39-L61

And we guess that these new scenes don't install css. Therefore we add some codes in 
https://github.com/JabRef/jabref/blob/7cb7ea60324932723db22fcd1964e26f73f7d9b4/src/main/java/org/jabref/gui/preferences/PreferencesDialogView.java#L113

we change it to this:

```
    @FXML
    void showAllPreferences() {
        preferenceTabList.getItems().forEach(tab -> Globals.getThemeLoader().installCss(tab.getBuilder().getScene(), Globals.prefs));
        viewModel.showPreferences();
    }
``` 

But it does not work again.  So, I  want to ask if there are some misunderstanding here?
