### ISSUE TITLE
File / Import / Append library freezes JabRef

### ISSUE THREAD

**Issue by calixtus** [JabRef/jabref#6049]
JabRef version 100.0.0 (current master 2020-03-01 14:00 PM) on Windows 10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open one library.
2. In the menu open file -> Append library
3. Check import entries
3. Select another library

**Comment by Siedlerchr** [comment]
I think we also need to show a progresbar

**Comment by koppor** [comment]
Similar issue: When opening a large library, JabRef takes much time to load. @tobiasdiez Will open an issue with "pain points"

**Comment by fanmingyu212** [comment]
Can also confirm the same issue with both JabRef 5.0 (public release version) and 5.1 (current master, https://github.com/JabRef/jabref/commit/acf2ac46a3bdc83d11e96e7f337783fcf197be61) on "Windows 10 10.0 amd64, Java 14"

**Comment by calixtus** [comment]
I'm not sure what the difference between AppendDatabaseAction and ImportAction into current Database is...

**Comment by koppor** [comment]
A quick look reveals following for me:

- AppendDatabaseAction: `org/jabref/gui/importer/actions/AppendDatabaseAction.java:97` --> `importGroups`, which relies on the old group format
- I forgot about the `ContentSelector`. This is somehow important - and not handled in the ImportAction (but in AppendDatabaseAction)
- The `ImportAction` opens a dialog for selecting entries. - The "AppendDataBaseAction" should not ask for confirmation, but just do it.

We discussed on JabCon 2018 that we should not add popups, but do more "magic". Then, the dialog in ImportAction could be deleted.

We used to have "mark entries" in JabRef 2.x. This was removed, because we replaced it by groups - and the current JavaFX table cannot show entries not matched by a filter :-\. -- This functionality comes into my mind, because we used to mark imported entries and moved them to the top of the entry table.

**Comment by calixtus** [comment]
I was asking, because in JabRefFrame a comment is indicating that those two commands should be merged... (`JabRefFrame.java:681`)

**Comment by tobiasdiez** [comment]
Both actions are more or less the same (at least from a user perspective): Select a file and put everything contained in that file into the current library.

Usually, the import action "only" imports entries while the "append" also includes metadata (e.g. groups). In my opinion, they can indeed be merged.
