### ISSUE TITLE
UI: maintable: right-click menu: reorder items

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6099]
In JabRef 5.0, when you right-click on an entry of the main table, you get the following menu:
![RightClick](https://user-images.githubusercontent.com/6931104/76404603-055df580-6387-11ea-9e92-b97c78740659.png)

**Is your suggestion for improvement related to a problem? Please describe.**
Some items are not consistently located: the nearby items are unrelated.

**Describe the solution you'd like**
- "Attach file" moved in the cluster "Open folder"..."Open URL or DOI"
- "Merge entries" moved in the cluster "Copy"..."Delete"

**Comment by stefan-kolb** [comment]
It depends on how you categorize things, I guess.
If you say the bottom group includes all `entry-related actions/changes to an entry` it is probably fine as is right now.
Can you elaborate more why you think your grouping is more consistent?

I would vote to keep it as is right now.
@JabRef/developers What do you think?

**Comment by koppor** [comment]
- Cut/Delete feels similar to merge entries (as one entry is deleted)
- Attach **file** is similar to Open **file**

So it would be fine for me to go with the propsoal.

**Comment by koppor** [comment]
Refs https://github.com/koppor/jabref/issues/410

**Comment by mlep** [comment]
@stefan-kolb  Oops, sorry, I did not notice that your asked for my rationale.
But @koppor did it!... :wink:

**Comment by mlep** [comment]
@stefan-kolb I guess the label "status: waiting for feedbak" is not needed anymore.

**Comment by mlep** [comment]
Issue still valid.

**Comment by JIANGJiaXiu** [comment]
Hi, we are a group of 8 students from Harbin IT. We are going to work on this issue as an assignment of a course. Hopefully we will try to submit a PR before Aug 6th. Any help will be appreciated as all of us are new contributors to OSS. Thanks a lot!
JiaXiu Jiang

**Comment by calixtus** [comment]
Thanks for your interest in this issue.
Implementation of this would probably not more than 5 minutes. Important thing is here to present the thought process of why you would chang the order and how.
So before sending a pull request, please provide your rationale.

**Comment by JIANGJiaXiu** [comment]
Thanks for your reply!

We agree with @koppor that

- Cut/Delete feels similar to merge entries (as one entry is deleted)

- Attach file is similar to Open file

As to Merge entries, we think it should be put between Cut and Delete Entry, since it has similar function as Delete Entry, and its shortcut is similar to Paste and Cut (using ctrl +) .
As to Attach file, it’s an operation to a local file consistent with Open file and Open folder, and, One shall attach a file before he/she opens it.

Moreover,  maybe Delete **E**ntry should be converted to Delete **e**ntry in order to be consistent with Merge **e**ntries.

like this,
![E26F91484C069082D73A433C158B86E5](https://user-images.githubusercontent.com/80106839/126898653-476ff454-cf14-46ad-9556-74d7e6a30cdd.jpg)

If out rationale is OK, our teammate @rayinfinite will submit a PR.
Thanks!

**Comment by mlep** [comment]
@rayinfinite  : thank you for making JabRef UI more consistent!
