### ISSUE TITLE
Version 3.1 keybinding for new entries

### ISSUE THREAD

**Issue by HainesB** [JabRef/jabref#615]
In an old version of JabRef, I could open a dialog to create a new entry using a shortcut, such as C-A for articles and C-B for books. With version 3.1 the only way create a new entry from the keyboard is to do C-n and then navigate the long list of types, apparently only by use of TAB key (it would be nice if they were numbered and I could immediately access which I wanted with C-<number>).

**Comment by Braunch** [comment]
In the referenced issue #1120 you metioned that "Enter" does not create the selected Entry. With the newest development version it seems to work. But still you can't navigate with the arrow keys, only with the tab key. I agree that this is very long-winded. But since there are 19 different types by default, using numbers is no option since double-digit combinations would lead to mistyping and slow down the user. I believe a compromise would be to be able to use the arrow-keys again and additionaly to jump through the headings (BibTex, IEEETran and custom). This would shrink down the 18 times tab-key to two commands (jump to IEEETran's first type and then arrow-down). What do you think of this method?

**Comment by koppor** [comment]
I think, this is solved by #1525. See http://blog.jabref.org/2016/08/15/HotkeyRevision/ for a blog article on the hot keys. Please also check "Options" -> "Customize key bindings". 

![grabbed_20161017-002046](https://cloud.githubusercontent.com/assets/1366654/19421361/8e51c9ee-93ff-11e6-8888-0f9ae6c0f1c7.png)

I think, the difference is that you have now to press <kbd>shift</kbd> additionally.

Please re-open if this issue persists.
