### ISSUE TITLE
Use GROBID for extraction of metadata from PDFs

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#6158]
Now that we have the GROBID server up and running, we can also use it to extract bibliographic metadata from PDFs.

https://grobid.readthedocs.io/en/latest/Grobid-service/
/api/processHeaderDocument

Old PR (using CERMINE instead of GROBID):  https://github.com/JabRef/jabref/pull/2474

**Comment by koppor** [comment]
Currently, it returns TEI XML format only, not BibTeX. I can try to patch the server accordingly.

I am curious in which cases GROBID is better than JabRef's custom implementation. It worked fine for me for IEEE and Springer LNCS. Still need to add more test cases though.

**Comment by tobiasdiez** [comment]
Would be nice if you could change the server accordingly. Grobid is the defacto standard for metadata extraction from pdf (and is used by ResearchGate, Mendeley, etc). Our implementation was really naïve and only works for a few publisher.

**Comment by Dellu** [comment]
> Grobid is the defacto standard for metadata extraction from pdf (and is used by ResearchGate, Mendeley, etc). Our implementation was really naïve and only works for a few publisher.

Mendeley gives junks. I havn't finished cleaning the junk Mendeley gave me 10 years ago. Using the system that Mendeley is using is really bad idea.  It never gets it right. 
- it is better to improve other aspects of Jabref than wasting resource on a system that will produce gibberish and unclean reference data.

**Comment by Siedlerchr** [comment]
JabRef now uses several sources for extracting metadata from PDF (XMP, embeded bibtex, DOI, Grobid) and allows comparing them

Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by koppor** [comment]
Fixed by https://github.com/JabRef/jabref/pull/2838
