### ISSUE TITLE
Improve entry merge dialog (3-way merge)

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#6190]
- [ ] Add option to show only differences
- [ ] Emphasize header (e.g. bold and with different background) as in ![](https://docs.servicenow.com/bundle/geneva-release-notes/page/build/team_development/image/CompareToCurrentForm.png)
- [ ] Concert to 3-way merge: the two entries to be merged on the left and right, in the mid the final merged entry. The values of the merged entry in the center should be editable (i.e. text fields). Similar to 
   ![](http://meldmerge.org/images/meld-merge-full.png) ![](http://www.deltawalker.com/compare-files/images/three-way-comparison-before.jpg)
	- Further Inspiration:
		- ![](https://www.elsevier.com/__data/assets/image/0007/100150/2-Librarian-Merge.jpg)
		- ![](https://cdn.css-tricks.com/wp-content/uploads/2014/04/03-merge-conflict-in-gui.jpg)
		- ![](https://www.oxygenxml.com/img/archive_diff_dirs_big.png)
                - http://baymard.com/ecommerce-product-lists/benchmark/page-types/comparison-tool

**Comment by koppor** [comment]
Should also support to merge keywords and groups (see https://github.com/koppor/jabref/issues/12).

**Comment by Siedlerchr** [comment]
Request fromt he forum: Should support merging of files. E.g. when I merge two entries with files attached create one entry with both files.

**Comment by koppor** [comment]
Current state: https://docs.jabref.org/finding-sorting-and-cleaning-entries/mergeentries

The main issue is that we do not show the result in the dialog

![grafik](https://user-images.githubusercontent.com/1366654/125686059-6f472473-d1ab-4aba-ac39-4d2994982097.png)

**Comment by koppor** [comment]
When working on that, one could also solve https://github.com/JabRef/jabref/issues/2961 (see especially https://github.com/JabRef/jabref/issues/2961#issuecomment-880164801).

**Comment by calixtus** [comment]
Something similar to here https://github.com/JabRef/jabref/pull/7929

**Comment by Rifat951** [comment]
Hello Team,
we are  group of 5 people(@Beingmani , @yogeshvar, @Rifat951, @LIM0000, @tirthvyas-tk-labs) from University of Adelaide.We are new to this community and want to start contributing to jabref. Therefore, would like to work on this specific issue. Is there any prerequisite before we start working on this issue ?

**Comment by calixtus** [comment]
Thank you for your interest in JabRef. Be aware that this issue is is a large GSoC proposal for about 175 dedicated estimated work hours and is no beginner project. You definitely need good knowledge of java and some decent knowledge of javafx for this issue.
I really would advise you to start with a good first issue to get familiar with the jabref code base before taking this project.
Please also read the developer documentation about preparing your workspace and checkstyle  to avoid unnecessary setbacks during the review process of your code changes. A good practice is also to make an early wip draft pull request so we can follow your changes and tell early if we thinks it's going in the wrong direction.
Feel free to use our Gitter chat for questions and have fun coding.

**Comment by Siedlerchr** [comment]
This should also fix #8745

**Comment by claell** [comment]
@Siedlerchr not sure, as #8745 is not about the user, but about the import logic, as far as I can see.

**Comment by Siedlerchr** [comment]
@HoussemNasri  Just stumbled across this issue? I think we can close this?

**Comment by HoussemNasri** [comment]
https://github.com/JabRef/jabref/wiki/GSoC-2022-%E2%80%94-Implement-a-Three-Way-Merge-UI-for-merging-BibTeX-entries
