### ISSUE TITLE
EndNote .xml import to JabRef: PDF links are not imported correctly.

### ISSUE THREAD

**Issue by AtaZadehgol** [JabRef/jabref#6199]
JabRef version <JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2>

- [ x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When importing an EndNote library in .xml format into JabRef, the PDF attachment links are not imported into JabRef correctly.

1. I followed instructions under "Importing an EndNote library into JabRef" at https://www.mcgill.ca/library/files/library/jabref_guide_2016.pdf, and exported the EndNote library as an .xml file (attached here as file "My EndNote Library-Converted_xml.txt") . See below snapshot (attached here as file "EndNote Export settings = xml.PNG") showing the export configuration of EndNote version X9.3.1 (Bld 13758).

2. I then imported the EndNote .xml library file into JabRef version 5.0.

3. The EndNote .xml library is imported into JabRef; however, the PDF file attachments are not imported automatically. 

4. It appears this is a bug because JabRef expects the pdf url to be encapsulated in a `style` span as this is the case for the other urls. As a temporary workaround, you can add the <style> ... </style> tag around the filename.pdf (i.e., filename.pdf  --> <style> filename.pdf </style>) yourself for the moment; this should work semi-automatically via a "search and replace" in your favorite text editor. Also, remember to replace the "internal-pdf://" before the filename.pdf with the correct path in your computer (e.g.,  "internal-pdf://path_folder1/filename.pdf"  --> "C:/EndNote/PDFs_Folder/path_folder1/filename.pdf" in Windows, etc.).

![EndNote Export settings = xml](https://user-images.githubusercontent.com/40124922/77837920-af79a380-7123-11ea-852c-6e7192ae13bb.PNG)

[My EndNote Library-Converted_xml.txt](https://github.com/JabRef/jabref/files/4398179/My.EndNote.Library-Converted_xml.txt)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by tobiasdiez** [comment]
Relevant code: https://github.com/JabRef/jabref/blob/06e3b7259098f344606c8580fa4cd8feb3476ee9/src/main/java/org/jabref/logic/importer/fileformat/EndnoteXmlImporter.java#L263-L268

**Comment by archeaopteryx** [comment]
@tobiasdiez , thank you for the hint for the relevant code. I am working on a fix but have an addition question. Should I post directly here, or can I send you an email?

**Comment by Siedlerchr** [comment]
@archeaopteryx  Please ask here so we all can help. Best is to create a draft PR and then ask a specific question about the code

**Comment by archeaopteryx** [comment]
@Siedlerchr , thank you for the advice.
The problem is that I'm not sure how to to get the URL content. As stated by OP, it's fine to have an empty ```style``` span, but having no ```style``` span means that the unmarshaller returns a null object with no content.

My naive approach would be to change the behavior of the url class referenced when defining the unmarshaller context, but that isn't possible since the context is defined by generated files. Am I missing a better solution? And, if not, is it possible for me to change the generated files?

**Comment by Siedlerchr** [comment]
I came across this issue and it's inded a problem of the generated unmarshaller. I am not an expert in xml and those schema stuff. But from my opinion it should be necessary to adjust the xsd schema to add some kind of content attribute for the url attribute to represent the text without a style.

```
<urls>
				<related-urls>
					<url>
						<style face="normal" font="default" size="100%">&lt;Go to
							ISI&gt;://WOS:000377368200039</style>
					</url>
				</related-urls>
				<pdf-urls>
					<url>/Users/xxxx/_JABREFTEP/Menezes2018 - Map2Check Using LLVM and KLEE.pdf</url>
				</pdf-urls>
			</urls>
```
The xsd file is here:
https://github.com/JabRef/jabref/blob/master/src/main/resources/xjc/endnote/endnote.xsd

**Comment by Aloofwisdom** [comment]
I am currently working on this issue, but I get a little lost  now. Could you give me some hints or start points on that issue @Siedlerchr?

**Comment by Siedlerchr** [comment]
@Aloofwisdom  Thanks for your interest. JabRef uses the xjc tool (which uses jaxb) to automatically generate java classes from an xsd/xml schema (see the gradle task generateSource).

The problem is that in the XSD defintion the element  `<pdf-urls>` contains a list of `<url> `with a style attribute. However, there can also be `<url>` without a style attribute.
However, as you see that actually xml file can also contain `<url>` without a style attribute.  

To ease your work, I already adjusted the xsd file for you. Replace the section in the` endnote.xsd` file under /`src/main/resouces/xjc/endote/` with the following.
Then do a ./gradlew clean and a ./gradlew run (or ./gradlew generate source first) to regenerate the new EndNote classes.

Then you can adjust the method in the java code @tobiasdiez showed above to take the new fact into account.

```
<xs:element name="url">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element minOccurs="0" ref="style" />
				</xs:sequence>
				<xs:element name="url" type="xs:string" />
			</xs:choice>
			<xs:attribute name="has-ut">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="yes" />
						<xs:enumeration value="no" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ppv-app" />
			<xs:attribute name="ppv-ref">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="yes" />
						<xs:enumeration value="no" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ppv-ut" />
		</xs:complexType>
	</xs:element>
```

**Comment by Aloofwisdom** [comment]
@Siedlerchr Your illustration is pretty clear, thanks. I will make a pull request as soon as I finish.
