### ISSUE TITLE
DOI-Import-entries not converted to biblatex

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#6267]
```
JabRef 5.1--2020-03-23--67daf36
Windows 10 10.0 amd64 
Java 14
```

**Get BibTeX-Data from DOI does not work for bib_LA_tex**
If I get BibTeX-Data from doi into `@Comment{jabref-meta: databaseType:biblatex;}` it shows the entry in a different format (bibtex istead of biblatex), this is as stupid as comparing ris-files with bib-files (whithout converting)
![Screenshot 2020-04-10 07 46 17](https://user-images.githubusercontent.com/15687581/78967933-e24c7000-7b03-11ea-8d50-beed4a46fe75.png)

**Describe the solution you'd like**
If importing a different file-format (BibTeX) it first has to be converted, as you convert [ris2bib](https://www.bruot.org/ris2bib/).

**Comment by koppor** [comment]
I don't understand the issue.

Wild guessing:

1. open a bib library
2. add an entry
3. fetch the same entry via a DOI
4. see that the DOI fetch result is different from the entry inserted at 2?

@JoKalliauer It would be really helpful if you could invest time to describe the issue in a more understandable way. We are planning to craft issues for external contributors and this seems to be ones. The external contributors might have more knowledge in Java than working with RIS oder BibTeX. Thus, this issue is currently only understandable by JabRef power users, which in turn do not have time to contribute to JabRef's code.

**Comment by JoKalliauer** [comment]
@koppor biblatex (differently to bibtex) uses `journaltitle` instead of `journal`

How to fix this issue:
Since the DOI-database has imho bibtex, you need to convert them bevore importing/comparing using folloging option:

![2020-09-05 (1)blur](https://user-images.githubusercontent.com/15687581/92312443-d71d4380-efc0-11ea-9241-4c229ddb6ace.png)

**Comment by JoKalliauer** [comment]
```bib
% Encoding: UTF-8

@String{apr        = {April}}
@String{aug        = {August}}
@String{dec        = {December}}
@String{feb        = {February}}
@String{jan        = {January}}
@String{jul        = {July}}
@String{jun        = {June}}
@String{mar        = {March}}
@String{may        = {May}}
@String{nov        = {November}}
@String{oct        = {October}}
@String{sep        = {September}}
@String{techreport = {Tech. Report}}

@Article{Ba_ant_2000,
  author       = {Bažant, Zdeněk P.},
  date         = {2000-01},
  journaltitle = {International Journal of Solids and Structures},
  title        = {Size effect},
  doi          = {10.1016/s0020-7683(99)00077-3},
  issn         = {0020-7683},
  number       = {1-2},
  pages        = {69--80},
  volume       = {37},
  publisher    = {Elsevier {BV}},
  timestamp    = {2020.01.10},
  urlx         = {http://www.sciencedirect.com/science/article/pii/S0020768399000773},
}

@Comment{jabref-meta: databaseType:biblatex;}
```

![Screenshot from 2021-03-07 09-50-13X](https://user-images.githubusercontent.com/15687581/110234556-6208d780-7f2b-11eb-9704-79441063ec9e.png)

The bibtex-doi-information dont get converted to biblatex, e.g. biblatex does not have a `journal` it has `journaltitle`.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by JoKalliauer** [comment]
`
JabRef 5.3--2021-04-27--d320975
Linux 5.11.15-100.fc32.x86_64 amd64 
Java 15.0.2 
JavaFX 16+8
`
![Screenshot from 2021-04-28 12-07-20](https://user-images.githubusercontent.com/15687581/116386683-4da1d680-a81a-11eb-86e6-bd56b04fddb6.png)


[6267.bib.txt](https://github.com/JabRef/jabref/files/6390979/6267.bib.txt)

![Screenshot from 2021-04-28 12-05-53](https://user-images.githubusercontent.com/15687581/116386624-4084e780-a81a-11eb-8526-c82517727654.png)

@Siedlerchr : The issue still persist.

**Comment by Siedlerchr** [comment]
Thanks, might have overlooked something will check it

**Comment by JoKalliauer** [comment]
I can confirm the issue is fixed. Thanks

```
JabRef 5.3--2021-04-29--cfb14b2
Linux 5.11.16-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 16+8
```
