### ISSUE TITLE
Cannot install JabRef 5.0 on macOS 10.15

### ISSUE THREAD

**Issue by mrakitin** [JabRef/jabref#6301]
## Environment
JabRef version v5.0 on macOS 10.15.4
Same issue is reproducible on the development snapshot from https://builds.jabref.org/master/ (v5.1).

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

## Steps to reproduce the behavior:
1. Download the .dmg or .pkg package from either:
  - https://www.fosshub.com/JabRef.html or
  - https://github.com/JabRef/jabref/releases/tag/v5.0
2. Attempt to install it.
3. Observe the error:
![image](https://user-images.githubusercontent.com/13209176/79506647-56a37980-8004-11ea-9e7d-a2b7e5bad973.png)

**Comment by Gena928** [comment]
Looks like this is because JabRef is not in the AppStore. New restrictions of MacOS.

Workaround:
- go to "System Preferences" - "Security & Privacy" - General tab;
As you can see, by default only AppStore or Identified developers allowed to install software (see "Allow apps downloaded from")
<img width="670" alt="Security and Privacy" src="https://user-images.githubusercontent.com/20572030/79579703-99cb1e80-80d0-11ea-8729-fa5d5b4466ca.png">

- Open you terminal 
- type `sudo spctl --master-disable`. An admin password will be required.

Now close your System preferences and open again. 
<img width="668" alt="Security and Privacy2" src="https://user-images.githubusercontent.com/20572030/79580906-5c679080-80d2-11ea-8b3f-0217433cdb2a.png">

Now you can install JabRef. 
After you finished open your terminal and type command `sudo spctl --master-enable` to enable restrictions again.

**Comment by mrakitin** [comment]
Thanks @Gena928! The instructions worked like a charm! Do you know if I need to unlock the option again in the future if I try to _update_ the package later from within the app?

**Comment by Siedlerchr** [comment]
The root cause is that we don't have a certificate for our software and getting one which does notrrequire a hardware dongle was unfortunately not successful.

**Comment by Gena928** [comment]
> Do you know if I need to unlock the option again in the future if I try to _update_ the package later from within the app?

Sorry, I've never tried yet. )) I'm new to JabRef.

**Comment by mrakitin** [comment]
Thanks for the information, everyone! The workaround works for me, and I'll keep it in mind next time I install this great piece of software. I'm your fan for about 10 years now :)
