### ISSUE TITLE
Formatting of main table ignored

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#6329]
JabRef 5.1--2020-04-20--bc57d22
Windows 10 10.0 amd64 
Java 14.0.1

I think this is a regression in the current dev version - it is not a big issue to me, but I reckon this is not intended behaviour.

1. Create a new item in JabRef which contains some Latex formatting, e. g. make parts of the title italic by using `textit{}` or by addind diacritics
2. Note, that the formatting is "ignored" in the main table, i. e. the formatting code is displayed instead of displaying the words in italic/with diacritics
3. The entry preview, on the other hand, translates the formatting code correctly and displays the words in italic/with diacritics

An example is attached.

![Issue](https://user-images.githubusercontent.com/12767489/79744678-b351ad80-82fe-11ea-8491-75943a81e1a1.png)

**Comment by Siedlerchr** [comment]
@tobiasdiez  You recently changed to the latexfree fields in the main table regarding caching etc, could this be a result?

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

Moreover, the performance for opening the database should be now way better than before. Could you please update the performance issues and outline what still needs to be improved. That would be really helpful. Thanks

**Comment by AEgit** [comment]
JabRef 5.1--2020-04-22--c7d7767
Windows 10 10.0 amd64 
Java 14.0.1

I can confirm this has been fixed in the current dev version. Well done!
