### ISSUE TITLE
Irregular behaviour of "change preview" F9

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6391]
JabRef version  on 
JabRef 5.1--2020-05-01--a123eb1
Linux 5.3.0-51-generic amd64 
Java 14.0.1

- [ x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open the entry editor
2. go to the field-editing area
3. Changing the preview style display with F9 only works when the "optional fields" tab is selected.

![image](https://user-images.githubusercontent.com/762246/80825700-26301380-8b9e-11ea-9757-b3cf8baf982d.png)

Press F9:

![image](https://user-images.githubusercontent.com/762246/80825720-2f20e500-8b9e-11ea-9f57-c8b16b22a70f.png)

**Comment by Vince250598** [comment]
I looked into it and i have a few questions i'm asking myself. 
First, i noted that almost every tab has its own previewPanel(Required fields, Optional Fields, Deprecated Fields, Other Fields, General, Abstract, Comments). I really don't think it's necessary to have one per tab, correct me if there's a reason.
I think this is the reason for this issue: when debugging i was looking at PreviewPanel's object reference number when pressing F9 and compared it to when i was clicking on the Popup menu item. The numbers were different, that means that it's changing the preview style in the wrong PreviewPanel in another tab. Sometimes it's the same reference number but in other cases it's not and i don't know why.
My breakpoint was set in the nextPreviewStyle() method of the PreviewPanel class (java/org/jabref/gui/preview/PreviewPanel.java)

**Comment by Siedlerchr** [comment]
Thanks for tackling this issue! I took a quick look and experimented and could confirm that each tabs has it's own instance of preview panel associated.
And to maybe solve the mystery, I think the issue lies here:
https://github.com/JabRef/jabref/blob/7cc57474b7aa991ef6ea148d4030d4bb68ee69bf/src/main/java/org/jabref/gui/entryeditor/EntryEditor.java#L230-L248
You are effectively creating a new Instance of FieldsEditorTab which then has it's own preview panel then.

A fix could to be to call the `private void updateLayoutByPreferences(JabRefPreferences preferences)` when changing tabs to ensure that the preview layout is updated correctly. Just an idea.

**Comment by Vince250598** [comment]
The problem is that when i'm in the Required fields and i press F9 to cycle through the preview layouts, it doesn't change the preview panel associated with the required fields tab, it changes the one in the comments tab. It's as if F9 didn't act on the right PreviewPanel. But when i use the popup menu it works as intended.

**Comment by Siedlerchr** [comment]
Okay that's weird, but sounds like  that somewhere the key listener in the wrong panel is triggered or takes precedence over another.
You might want to check the key listener events, e.g. In which tab the event is executed.

**Comment by Vince250598** [comment]
The problem is there for the other shortcuts of the popup menu: previous preview layout and copy preview. Altough, copy preview works properly if you click in the PreviewPanel before copying, if you don't click it just copies the last PreviewPanel that you clicked(in another tab for example)

**Comment by wujastyk** [comment]
Behaviour now as documented.
