### ISSUE TITLE
Main table: Coloured group indicator for cited entries does not show up consistently anymore

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#6394]
Tested with the latest JabRef development version (master branch) on Ubuntu 16.04

Unfortunately, the colored group indicator for cited entries does not show up consistently anymore in the main table: The badge icon with the number of cited entries works, but the colored group indicator in the main table does not show up for most of the cited entries. Sometimes only one, two or four indicators show up. (Updating the group repeatedly or restarting JabRef does not help either.)

@tobiasdiez I strongly suspect that the cause of this issue is connected with the recently conducted performance optimizations of the group functionality (faster group calculations). When reverting back for two weeks, this problem vanishes.

1. Create group of cited entries by linking the corresponding `.aux` file
1. Cite entries in a tex file and build the pdf file
2. Update group of cited entries
3. Observation: Not all indicators show up

**Comment by systemoperator** [comment]
The issue was caused by commit bc57d22f.

**Comment by systemoperator** [comment]
#6586 slightly reduced the problem, since when the library gets reopened or JabRef gets restarted, then all groups get freshly parsed and properly created now, but the underlying problem still persists in all other cases.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I'll start looking at this

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Should an entries group always show up in `StandardField.GROUPS`? I haven't been able to find any discussion regarding this topic.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
What is the expected behaviour for when you have a group selected, so that only entries in the .aux file is shown, and a change occur so that an entry is added/removed?
I am ok with an entry not being *removed* from the view (as it is indicated by the group color anyway, as shown in the screenshot below), but what about when they are added?

<img width="323" alt="Skärmavbild 2020-12-16 kl  14 35 40" src="https://user-images.githubusercontent.com/2598631/102397557-07a34f00-3fac-11eb-88b3-db944d131127.png">

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I am assuming that it should behave in the same way as for searches (the bib entry gets added/removed immediately but the entry editor still show the entry if it was selected)

**Comment by koppor** [comment]
According to the documentation (at https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups#using-the-cited-entries-of-a-latex-document), the `.aux` file is hot reloaded. Since the group changed, I would like to see all changes in the maintable, too. Which means: removal causes removal and addition causes addition. 😇

**Comment by koppor** [comment]
Removed from the milestone as we are going to release v5.2 today - and there is the PR https://github.com/JabRef/jabref/pull/7173 opened working on fixing the issue.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Sorry about the delay, hopefully it means it gets "right" in the end!

**Comment by Siedlerchr** [comment]
No problem, we just wanted to release today, no matter if it's done or not. Will probably create another release afterwards more soon

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
