### ISSUE TITLE
Entry is missing after sublibrary is generated from aux file

### ISSUE THREAD

**Issue by xx256xx** [JabRef/jabref#6405]
JabRef version 5.0 on Windows 10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. The test package is available at https://github.com/xx256xx/test, including a tex file, the original bib **my.bib**, a aux file **report.aux**.
2. I attempt to generate a sub library using **report.aux** from **my.bib**. 
3. In Jabref window, the sub library succeeds to generate the sub library. See ![jabref](https://user-images.githubusercontent.com/62489740/80926118-bf0b8e00-8d5a-11ea-99dc-36e24ce265d8.png)
4. However, this entry is not found in the saved bib file ( you can check it at my repo, named by **sub.bib**). ![jabref2](https://user-images.githubusercontent.com/62489740/80926150-f712d100-8d5a-11ea-8b8b-e6c26a2667dc.png)
5. If I fill in the "date" field and save again, the resultant bib is correct.

No log available.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by xx256xx** [comment]
The zip file is upload a test repo for the security purpose. You can find all the files at https://github.com/xx256xx/test. Run **test.bat** to quickly reproduce the issue.

**Comment by Siedlerchr** [comment]
I could confirm this issue. You are right, for some reason the entry gets deleted.
When I do this manually in JabRef and try to save the new library, I get the "Review changes" dialog which states that the entry got deleted.

![grafik](https://user-images.githubusercontent.com/320228/81437372-57df4680-916b-11ea-918d-37dc71ce575b.png)

**Comment by Siedlerchr** [comment]
Okay, this seems to be a bit weird. I debugged a bit further and found out that the problem lies in the following lines when saving:
https://github.com/JabRef/jabref/blob/7cc57474b7aa991ef6ea148d4030d4bb68ee69bf/src/main/java/org/jabref/logic/bibtex/BibEntryWriter.java#L58-L62

The second entry, the one with "lichman" has the flag changed = false and the getParsedSerialization() returns an empty string.
I don't know that much about the internal stuff and no idea when this flag or the serialization should be set
@koppor  @tobiasdiez  Any idea? I only noticed that the AuxParser "clones" the BibEntry before inserting into the database. But no idea if this affects the serialization

**Comment by koppor** [comment]
The code at hand ensures that entries are only written in JabRefs cool new "layout" if there is a change. This was a year-long discussion before you joined JabRef. - The idea is that JabRef stores the characters as they are read when reading the file. It writes out the characters as is when writing - except the user has changed something. - This is what the if condition states.

Now to the issue: I think, the code creating entries from the aux file just does not set the `reformat` flag correctly. I could also argue that we need a BibEntry clone method also cloning the serialization. - I did not look into the code how the aux part generates BibEntries. That the problem is hidden there, I am sure.

**Comment by Siedlerchr** [comment]
@koppor  Thanks for the explanation. That was indeed very helpful and let me to the root issue, that the clone method does not set the changed flag when the entry type is Misc and therefore equals the default entry type.

**Comment by Siedlerchr** [comment]
@xx256xx  This issue is now  fixed in the latest master


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
