### ISSUE TITLE
Downloaded text files are saved with extension "Text" instead of "txt"

### ISSUE THREAD

**Issue by mpatas** [JabRef/jabref#6467]
JabRef 5.0 saves downloaded text files with extension "Text", but extension "txt" would seem to be more common and thus more suitable. For example, generating an entry for RFC 1149 and downloading file from https://tools.ietf.org/rfc/rfc1149.txt results in a file named "Waitzman1990.Text", when it should probably be named "Waitzman1990.txt".

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by mpatas** [comment]
Yes, it looks like the change has been made, the development build has this improvement. Thank you.
