### ISSUE TITLE
Journal title "Nature" is not an abbreviated title

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6502]
JabRef 5.1--2020-05-19--fe5eec6
Linux 4.9.0-12-amd64 amd64 
Java 14.0.1

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

If the journal title is Nature, a warning is given in the entry editor
(same thing for Science).

1. Enter "Nature" in the field Journal of an entry Article.

==> An orange triangle appears in the lower left-hand corner of the field, indicating "Abbreviation detected".

**Comment by tobiasdiez** [comment]
The journal abbreviation list contains the line "Nature;Nature" (i.e. Nature is its own abbreviation). In some sense, this is true...not sure what's the best way to address this issue: simply forbid that the full journal name is the same as the abbreviated one? Handle this case separately in the relevant code?

@koppor I've lost track of where updates to the journal list need to be done.

**Comment by koppor** [comment]
I would suggest an integrity check for the CSV files. Thus, only valid abbreviation lists are imported into JabRef. @jlaehne Can your script help there?

I need to take some hours to think of the updates and to maybe backport changes. The current discussion is at https://github.com/JabRef/jabref/pull/5749. Think @jlaehne gave me enough hints and inputs, but I did not find the time and energy to dive into this yet. Maybe tonight or these days.

**Comment by jlaehne** [comment]
@tobiasdiez Updates to the lists should be done in the abbreviation repository abbrv.jabref.org so that they don't have to be backported.

I would favor leaving the journals where the abbreviation is the same as the journal name (Nature, Science, Nanotechnology, ...) in the repository for completeness. Then I would see two ways to handle this:
i) You adapt JabRef so that it simply ignores these journals
ii) The merge script throws out these journals when compiling the combined abbreviation list. Then, they would be in the repository, but not in the list shipped with JabRef.

The only consistency mechanism the merge script currently has is to throw out duplicates and take the last occurence. Currently, the "general" list is last and overrides the other lists.

What else were you thinking of @koppor?

These lists are so huge that a manual consistency check is only feasible by subject and will always still be error prone. I tried my best for the physics list. Another problem is that many names or preferred abbreviations of old journals have changed over time and it is sometime hard to decide what to put in the lists. One could conceive an automated check:
i) In the simplest case by making sure the abbrevation string (dots removed) is a substring of the unabbreviated string.
ii) Checking for disagreements among the lists in the repository.
iii) Using the title word abbreviation API of https://marcinwrochna.github.io/abbrevIso/. 
However, there are still exceptions ('Phys. Rev. Materials' is the official journal abbreviation according to APS, but ISO would be 'Phys. Rev. Mat.'; some of the mathematics lists use slightly different abbreviations than ISO). Basically, such a script could compile a list of suspected errors and then one would have to check them manually. It would not make sense to integrate such checks in the automated merge scripts. But it could help on the road to get more consistent abbreviation files.

**Comment by jorgman1** [comment]
If you remove these journals from the abbreviation lists, wouldn't you get a "journal not in abbreviation list" error when running the quality check?

**Comment by Siedlerchr** [comment]
The abbrev check for the journal fields in the entry editor is now removed in the latest master. No more triangle

**Comment by koobs** [comment]
Confirming resolution (see screenshot) on:

```
JabRef 5.2--2020-12-20--84c8504
Windows 10 10.0 amd64 
Java 14.0.2
```

![2020-12-22 11_40_40-_research 20201220 biblatex bib – JabRef](https://user-images.githubusercontent.com/1011612/102835393-80603c00-43ee-11eb-8d00-ba6380aaa5b7.png)
