### ISSUE TITLE
Saving the library after any change triggers "Library has been modified by another application."

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#6525]
Tested with the latest JabRef development version (master branch) on Ubuntu 16.04

Saving the library after **any** change within JabRef, triggers the message "Library has been modified by another application.", asking either to choose "Dismiss changes" or "Review changes".

I have only tested it with Ubuntu. Maybe this results due to an unfavorable race condition with the Linux file system?

Details:

- Saving library with `CTRL+S` or hitting the save button makes no difference.
- JabRef's Autosave is not enabled.
- All files are stored locally, without any external file synchronization.

Probably relevant (but old): #4877

**Comment by tobiasdiez** [comment]
Yeaaaahhh. Finally a developer gets these warning messages! Every core developer tried to replicate these issues but couldn't, which made it really hard to fix this issue.

Since you can reliable reproduce this, can you please debug it and report which changes JabRef claims to be there between the current library and the saved file. If you have the time, feel free to open a PR with a fix as well ;-) The general problem is that certain actions are applied to the library before the save, but not to the in-memory library. This leads then to a desync between the written file and whats in memory.

**Comment by systemoperator** [comment]
I have observed this issue for quite a while now, but until today, I just lived with it, but it's quite annoying. :smile: Ok, I will investigate it.

**Comment by systemoperator** [comment]
To start with it, the following changes get reported:

![image](https://user-images.githubusercontent.com/3658393/82846609-f3054980-9ee9-11ea-9c6c-f067873f5a6e.png)

![image](https://user-images.githubusercontent.com/3658393/82846616-fef10b80-9ee9-11ea-9910-4b9c77537d17.png)

**Comment by systemoperator** [comment]
Ok, what I could find out so far:
- The problem is library specific.
  - The cause depends on the existing groups.
    - Apparently, it gets triggered with creating a group of cited entries.
      - Procedure + description, see: #6420
    - When such a group has been created, then this message appears whenever the library is changed and gets saved.
    - But as stated in #6394, groups of cited entries also has issues, so this could be caused as a follow-up.

**Comment by wujastyk** [comment]
I have experienced this issue for a long time, but I've never used the "Groups" feature in JabRef.

**Comment by systemoperator** [comment]
The reason is, that this reproducible case is caused by something different.

**Comment by systemoperator** [comment]
I'm closing this, because this concrete issue is caused by #6420 and discussed there onwards.
