### ISSUE TITLE
Automaticially set extern file links

### ISSUE THREAD

**Issue by anduls** [JabRef/jabref#6533]
JabRef version  on 

- [ x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. create new bibtex lib e.g. test.bib
2. create a new Journal entry, create a bibtex key, e.g. Joe.pdf
3. put a Joe.pdf  in the same folder as the bib file
4. press F7 or Quality menu "Automatically set external file links"
5. Joe.pdf is not linked

Notes: tried several combination settings for Library properties: General file directory and user file directory set to the path of the bib and pdf file. In Options external file links: Main file directory to path of bib and pdf file, with and without "use the BIB file location as primary file directory".

Happened in v 5.0 and the 5.1 master in Ubuntu 18.04

Strange: worked in v 5.0 in Windows 10, however after I imported external settings  in Windows exported from Ubuntu  it stopped working in Windows as well. So maybe a xml or java settings issue?

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
