### ISSUE TITLE
"Manage field names & content" logic and appearance

### ISSUE THREAD

**Issue by mr-j-s** [JabRef/jabref#6536]
JabRef 5.1--2020-05-26--0d7156b
Windows 10 10.0 amd64 
Java 14.0.1

I had troubles with understanding of the logic of "Edit"-"Manage field names & content" menu today. I was trying to get rid of certain fields, but they were not disappearing, in the end I figured out that to use "Clear fields" or "Set fields" you need to tick the box "overwrite existing field values", which is quite obvious now. But "Append" and "Rename" options actually work _without_ this box (why? because old values are still there?).

I think I got confused for two reasons: 
1) hard to imagine what should be the behaviour if I clear or set field without overwriting it (?)
2) gray color of the box made me think it is inactive at first, however it seems to be a default color for all the unticked boxes.
![image](https://user-images.githubusercontent.com/18900780/83006566-ba14c400-a012-11ea-84bb-095ce4a0b8e4.png)

I think this box is simply confusing and should be removed, if you want some safety, a warning "fields will be overwritten" may be enough (with an option "do not show me this warning again"). And even that may be too much, because a person who is going to Set or Clear fields should understand that the value will change... In any case Ctrl+z will still help if something goes wrong.

Maybe also change the color of the unticked box? I don't know if I am the only one thinking that gray box is not active and cannot be ticked.

The last is a feature request: is it possible to make some real-time suggestions in the "Field name" box?
For example if I start typing "d", to drop down a list with only fields starting with "d", i.e. "date" and "doi".
This would be also useful in other places where you select one option from a list.

**Comment by mlep** [comment]
Exploring this feature, here are my observations and answer to the question.

Observations:
- For "Append to fields:", **"Overwrite existing field values" does not make sense**, because this action assumes the field is already existing, and, anyway, if the field is empty (no value) JabRef does not store it.
- For "Rename field to", **"Overwrite existing field values" does not make sense**, because you cannot rename a field that does not exist.
- For "Clear fields", **"Overwrite existing field values" does not make sense**, because if you checked it, it will clear only empty values (which are not saved by JabRef). So this option never need to be set anyway for this action.
- To me,  "Overwrite existing field values" make sense only for "Set fields", so that the field and its value can be set when the field is not existing; or, if the field already exists (and so as a content), its value be completely overwritten.

So, this call for a redesign of the items:

- Set fields
      - Overwrite existing field values
- Append to fields
- Rename field to 
- Clear fields

Moreover:
-  the OK button should be active only if the field name (and the value/new name, when required) are defined.
- "field" can be kept singular in all cases (only one field is targeted at a time). I.e. rename "Clear fields" to "Clear field", etc.

**Comment by mlep** [comment]
This issue is still relevant.

**Comment by HoussemNasri** [comment]
Hello there, I started redesigning the 'Manage field names & content' dialog and saw this issue after finishing the wireframe. The initial wireframe can be found below. Please let me know if you have any more suggestions or if you see anything that isn't obvious in the UI.

![Screenshot 2022-06-04 023327](https://user-images.githubusercontent.com/21198231/171971853-75de9f34-d14e-488c-8d1c-69e5b92db099.png)

**Comment by ThiloteE** [comment]
[This issue](https://discourse.jabref.org/t/export-only-title-and-abstract-in-html-format/3412) in the forum would make a good case for adding something like: "apply action to all fields and content, except ..."
