### ISSUE TITLE
"Cleanup entries" formatter "Clear" doesn't work?

### ISSUE THREAD

**Issue by mr-j-s** [JabRef/jabref#6538]
JabRef 5.1--2020-05-26--0d7156b
Windows 10 10.0 amd64 
Java 14.0.1

[v] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Select all entries in the database, in my case they all have DOI.
2. Open "Cleanup entries". Immediately a message appears at the bottom "Doing a cleanup for 56 entries...". (But nothing is cleaned at this step I guess?)
3. Tick only "Enable field formatters".
4. Add formatter "DOI, Clear"
5. Press OK - nothing happens, message "No entry needed a cleanup" appears.
I expected that all "DOI" fields will be removed.

P.S. The message in step2 gives information how many entries were selected, but sounds misleading. Maybe better to say "Preparing a cleanup for N entries" or "N entries selected for cleanup"?

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by mr-j-s** [comment]
Seems to work now, thank you.
