### ISSUE TITLE
Invalid Bibtex records / DOI not extracted from imported PDF files

### ISSUE THREAD

**Issue by avm19** [JabRef/jabref#6577]
Observed behaviour:
Some PDF files are imported as invalid Bibtex records of type `@Misc` with empty Bibtexkey and with _only one_ field `file`. I suppose, this is caused the failure to extract DOI from the first page of a PDF file.  ([JabRef docs ](https://docs.jabref.org/collect/findunlinkedfiles) say "In case a DOI is found on the first page, the DOI is used to generate the BibTeX information")

Expected behaviour:
JabRef extracts DOI from the PDF and retrieves the necessary information from the internet. 

Steps to reproduce the observed behavior:
1. Download the [pdf file](https://link.springer.com/content/pdf/10.1007/s10237-008-0136-z.pdf)
2. In JabRef: **Lookup** -> **Search for unlinked local files**; scan the directory with the file, select the file, proceed to **Import**.
3. Observe a new record in the database, which looks as follows:
![image](https://user-images.githubusercontent.com/52547519/83600137-e6ad6c00-a53b-11ea-8f88-f7b21bea6ffc.png)

**JabRef version**
JabRef 5.1--2020-06-02--46fd96b
Windows 10 10.0 amd64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

**Comment by Siedlerchr** [comment]
Thanks for reporting that issue. JabRef first checks for XMP metadata to be present and then tries the "magic" PDF extraction. However, the XMP parser did not correctly indicate that the entry is empty (contains no fields) and therefore the PDF extractor was not called.

This should now be fixed in the latest master (currently building, ready in ~30min)
