### ISSUE TITLE
Add right click menu for main table header

### ISSUE THREAD

**Issue by mo0ep** [JabRef/jabref#6601]
It would be nice if right-clicking on the main table header (where the column names are), provided a menu which either allowed to edit the viewed columns/fields directly or provided a link to the preferences. 

Maybe a list of the currently and most commonly used fields would show up to be activated/deactivated in the right click menu and for more detailed adjustments a reference to the settings would be displayed.

**Comment by calixtus** [comment]
Just for some inspiration: This is how it works in the windows explorer:
![image](https://user-images.githubusercontent.com/50491877/98726744-328bf900-2397-11eb-8aca-e6563d7ad068.png) 
![image](https://user-images.githubusercontent.com/50491877/98726807-459ec900-2397-11eb-9816-bd4de813f100.png)

**Comment by sj30001** [comment]
Hi, we are a group of 5 students from Adelaide University. Our software process improvement class asked us to contribute to an open-source project. We'd love to help with this issue. Is anyone currently working on this issue? If not can we take it? We are all new contributors to open-source projects. If possible could we get some guidance on which part of the code we should look into first. Thanks a lot
Zijian

**Comment by Siedlerchr** [comment]
@sj30001  Thanks for your interest in JabRef. Currently no one is working on this issue.
The TableView code is in the MainTable class under jabref.gui.maintable 
For requesting a context menu, some inspiration how this coud be achieved https://stackoverflow.com/questions/59650736/how-to-add-a-context-menu-on-unused-column-header-in-tableview 

more info on context menu:

**Comment by Qiming-Liu** [comment]
Thanks a lot. That's really helpful. Currently is there any code in JabRef about modify the order, width, show/hide of  TableColumns?

**Comment by team10-h** [comment]
Hello, we are a group of 8 students from Harbin Institute of Technology from China. Our Open Source Software Development class asked us to contribute to an open-source project. We chose this issue among the projects provided by Mr.Treude and we are interested in helping with this issue. Is anyone currently working on this issue? If not can we take it? We are all new contributors to open-source projects. If we make some mistakes, if possible would you please point it out? Thank you very much.

**Comment by calixtus** [comment]
Hi, thanks for your interest in JabRef. Your teacher already announced your team, so you are free to take it.
Please be aware that there has already been an approach to fix this back in may. So most of to rationale and a part of the solution can be found there. Please make sure you read and understand the discussion in #7729 .
If you have questions, we are happy to answer them. Happy coding!

**Comment by ShaunChang** [comment]
Hello, I am a student who comes from study team 6 at Adelaide University. Due to our course Open Source Software Development requirements, our team is focusing on contributing to an open-source project. After discussion, our team agreed that this project is a really excellent open-source project. At the same time, we are very interested in # 6601 this issue and are willing to make positive contributions. We expect to finish this issue and submit our PR before June. Can we work on this issue? If we can, we would appreciate that if you can give us some advice about how to contribute to this issue. Looking forward to your feedback sincerely.

**Comment by calixtus** [comment]
Yes you are welcome to dive into this issue. Please prepare your workspace according to our dev docs and please read the discussion at #7729 .
Remember: solution rationale is to add/ remove columns to the maintable, not to alter the visibility property of columns.

Have fun coding. Please make a draft pr as soon as possible, even when you are not finished, so we can follow your changes and help early, if there is something not understood. Feel free to use the Gitter chat to ask questions, if you got any.

**Comment by ethantr** [comment]
Is this issue still being worked on? I've noticed a few other students have looked at it and unsure if it's still taken. 
If not, I would love take a look at this for a university assignment.

**Comment by calixtus** [comment]
Seems like it's still open and I don't see anybody else working for it. Give it a shot. 👍 
Please give attention to https://github.com/JabRef/jabref/issues/6601#issuecomment-1079706114

**Comment by ethantr** [comment]
Been making progress on this issues. I have been able to access the currently used columns, but my current problem is being able to create objects of the most commonly used columns. Just wondering if there is a way to access/create these MainColumn objects so if they're not currently in the MainTabke I can still access them.

**Comment by calixtus** [comment]
Just modify or overload the constructor of the MainTableColumnFactory to make it a bit more generic, for instance instead of accessing directly the columnPreferences just provide a column type to recive a perfectly useable MainTableColumn. If you use the column objects in the Right Click Menu you can probably just add them by demand to the column list of the MainTable. But I would not advise you to use the MainTableColumn objects in the Right Click Menu, but just column types (MainTableColumnModel.Type) to avoid useless overhead.
