### ISSUE TITLE
Import automatically pdf annotations into the note field

### ISSUE THREAD

**Issue by Olifair** [JabRef/jabref#662]
This is something that is done by Mendeley internally, but I think I have seen this in one of the other programmes (don't remember if Zotero or Docear) on standard pdf annotations : 
standard pdf comments or highlighted text (as done with and compatible between Adobe, Foxit, X-Change viewer etc) is taken automatically from linked pdf and shown in the note field. With Mendeley, which uses an internal pdf reader, this is click-able, so that then the pdf will then be opened at the position of the comment /highlight.

**Comment by arurke** [comment]
+1

**Comment by koppor** [comment]
This is a modern version of [sf feature request 835](https://sourceforge.net/p/jabref/feature-requests/835/). I will close that request and point to here.

**Comment by stefan-kolb** [comment]
We wanted to have an option to show PDF comments inside JabRef (implemented by Stupro), but not in that case that it gets written to the DB?!

**Comment by oscargus** [comment]
I'm wondering if the note field is the best choice since BibTeX always adds this to the reference. I would suggest comment or review.

**Comment by Braunch** [comment]
I see some troubles using already existing fields. If the user wants to use the review function, the pdf comments will be in the way. Also the review field is editable and we don't want to have editable pdf comments, so that the user won't accidentally change the comments when he doesn't want to. The pure text field of the notes and the review field can be very confusing because you can not show the comments structured in different GUI components. My alternative suggestion would be create a special tab in the entry editor and only load the comments from the file, when the tab is opened up and not storing them into the db at all.

**Comment by tobiasdiez** [comment]
Sounds like a good solution, @Braunch. JabRef could internally store the extracted PDF comments if the extraction is time-consuming. But I also wouldn't write it into a BibTex field (because then you run into all kinds of synchronization problems).

**Comment by Olifair** [comment]
If the extracted pdf comments are stored internally, this has also the advantage that the inverse functionality could be provided : if I open up a reference, and then see a comment I'm interested in, Jabref could open the pdf at the correct page in an external viewer ? This would be great for people who work rather with books than with articles.

**Comment by lenhard** [comment]
Tracked in #2545

The option to open a PDF at a specific comment is not part of this though, since this is quite hard to support for arbitrary combinations of operating systems and pdf readers.

**Comment by lenhard** [comment]
The pull request is merged into the master branch now and the entry editor displays an additional tab with pdf annotations (if present).

Hence, I am closing this issue.
