### ISSUE TITLE
Fonts problem of JabRef 5.1

### ISSUE THREAD

**Issue by HankPPeng** [JabRef/jabref#6645]
I cannot change the **font** in Jabref's perference, but the **font size**. I want to change the default font because it looks hard...

**Comment by Siedlerchr** [comment]
Controlsfx provides a FontChooser diallog: http://fxexperience.com/2013/07/announcing-controlsfx-8-0-1/

**Comment by koppor** [comment]
Nice idea. This will be fixed when https://github.com/JabRef/jabref/pull/6036 is ready to go, since that PR covers more features than "just" the font size

To reduce the number of open issues, I'll close this out. Feel free to comment on https://github.com/JabRef/jabref/pull/6036 asking for a how-to for changing the font size.
