### ISSUE TITLE
Two versions of module org.jabref found

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#6686]
JabRef version 5.1 on Linux (latest build)

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

JabRef won't run because of the following problem:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Two versions of module org.jabref found in /opt/JabRef/lib/app/mods (JabRef-5.0.44.jar and JabRef-5.0.30386.jar)
```

1. Install JabRef from JabRef-5.1-portable_linux.tar.gz (I use the Arch package that I maintain, but that shouldn't make a difference here; it unpacks the lib directory into `/opt/JabRef/lib`)
2. Try to run JabRef

**Comment by Siedlerchr** [comment]
Do you clear the lib directory before copying over the new stuff? Seems like you have some old leftovers.
Due to the installer requirements the jabref libs are named  with an increasing minor number everytime a build is produced.
I downloaded the latest master and it contains only one version: JabRef-5.1.791.jar

**Comment by j0hannes** [comment]
OK, my bad. It seems the src directory wasn't cleaned up and so files of previous versions made it into the package. I should have wondered why this time the package had twice the size of its predecessor.
