### ISSUE TITLE
"Sentence case" and "Title case" not enforcing a capital after a period

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6759]
JabRef 5.1--2020-08-11--7ddfd9c
Linux 4.9.0-13-amd64 amd64 
Java 14.0.2

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

A title can be composed of two sentences, like "Bibliographic software. A comparison".
When applying the "sentence case" the title is converted into "Bibliographic software. a comparison".
The "sentence case" feature should enforce a capital letter at the beginning of the second part of the title.
Additionally, "Title case" produces "Bibliographic Software. a Comparison" (same defect) 

1. Create a new reference with the title "Bibliographic software. A comparison"
2. In the entry editor, right-click on this title and select Change case -> Sentence case
==> the title is converted into "Bibliographic software. a comparison".

**Comment by tmrd993** [comment]
The issue is that the sentence case formatter and the title case formatter both work on the entire paragraph instead of splitting it into individual sentences. The same problem should occur when the title has any of the following characters as terminal points: `!`, `?`, `;`, `:`, `.`

This is how the sentence case formatter formats the input:
```java
@Override
public String format(String input) {
    Title title = new Title(new LowerCaseFormatter().format(input));

    title.getWords().stream().findFirst().ifPresent(Word::toUpperFirst);

    return title.toString();
}
```

This works correctly for any **individual** sentence but goes wrong when you add in sentence terminal points like punctuation or question marks.
A quick fix would be to split the input with a regex like `"(?<=[.!;?:])\\s"`

This would split `Bibliographic Software. A Comparison` to `[Bibliographic Software., A Comparison]` which can be processed individually using the method above.

This isn't really an optimal solution though since prefixes like `Dr.` or `Mrs.` or other abbreviations with dots woult lead to incorrect formatting.

This regex works better but it's kind of ugly `"(?<=[\\.!;:\\?])(?<!mr\\.|mrs\\.|dr\\.|ms\\.|st\\.|ph\\.)\\s+"`

I guess it all depends on if you guys want the the converting to be flawless. In that case maybe it could be worth looking into third party libraries like [OpenNLP](https://opennlp.apache.org/) or [ICU4J](http://site.icu-project.org/home/why-use-icu4j) both of which can handle splitting paragrahps into sentences.

Or maybe this is all overkill and there is a much easier solution to the problem?

**Comment by tmrd993** [comment]
May I work on this? If yes, what are the requirements? Do we want 100% accurate conversion at all times?

**Comment by Siedlerchr** [comment]
I guess the proposed RegEx solution is sufficient if it fits for 90% of the cases. Let's ask the other devs @JabRef/developers

**Comment by Siedlerchr** [comment]
Thanks to @tmrd993  this issue is now fixed in the latest master version (currently building)

**Comment by mlep** [comment]
@tmrd993 It works now! Thank you for solving this issue.
