### ISSUE TITLE
Show all entries which are not in a group

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#679]
Currently, it is very hard to determine which entries are not in a group. This should be made easier as it helps to sort the remaining entries into the groups.

**Comment by Siedlerchr** [comment]
Partially solved: When you click on an entry which is in one or more groups, the group(s) are highlighted.

**Comment by lenhard** [comment]
I think this is solved as described by @Siedlerchr: If you mark all your groups (by hitting CTRL+A in the groups panel), then JabRef will highlight all entries in these groups and the ones which are in no groups are greyed out.

This should be good enough for now.

**Comment by nsheff** [comment]
@lenhard This is not the behavior I see in JabRef. If I select more than one group, it shows the `AND`, not the `OR`. Selecting all my groups highlights no entries for me, because none of my entries are in all my groups.

Ahh -- it's a setting in Preferences. For future searchers, you can change this setting in Preferences > Groups by toggling between `Intersection` and `Union`

**Comment by ThiloteE** [comment]
JabRef 5.6--2022-04-25--5c9d898
Linux 5.4.0-113-generic amd64 
Java 17.0.2 
JavaFX 18+12

While I think this feature should show in the groups pane by default, I was able to create such a group manually, using Regular Expressions (RegEx): `groups != .+`

![grafik](https://user-images.githubusercontent.com/73715071/170843737-b5a2cd00-4b1a-4731-9e0e-cd772038234a.png)

See here for info about JabRefs RegEx capabilities: https://docs.jabref.org/finding-sorting-and-cleaning-entries/search#advanced
