### ISSUE TITLE
New DOI icon is confusing and inconsistent

### ISSUE THREAD

**Issue by DominikVoigt** [JabRef/jabref#6834]
The new icon used for DOIs is confusing since the chain icon is crossed out.
Furthermore, the DOI icon in the entries is inconsistent with the DOI icon in the header.

Suggestion: Either revert the icon back or use a normal chain icon.
Furthermore, make the DOI icon used in the header and entries consistent.

![image](https://user-images.githubusercontent.com/43381984/91891570-8ee4e500-ec91-11ea-9844-52f478103f9b.png)

**Comment by koppor** [comment]
Since this is an external link, the icon should be the normal link icon - not crossed out

**Comment by fabiojavamarcos** [comment]
It seems the chain is crossed out when there is no information from the URL or the DOI. When the information is available, the chain is a regular one (not crossed out). Finally, when both are missing, no icon is shown. Is this behavior correct?

**Comment by mlep** [comment]
In JabRef 5.2:
- the chain is crossed out when there is only one link identifier.
- the chain is not crossed out when there are several link identifier.
- no symbol when there is no link identifier

To me it looks fine, except for the crossed out chain: I do not understand the rationale.

**Comment by koppor** [comment]
Crossed out is crossed out. Thus, interpretation as "one" is strange.

Can we create a custom icon?

## Alternative 1

- chain with a small one - having one entry attached
- chain with a small * - for more than one entry (or the real number of links showing)

## Alternative 2

- single chain - having one entry attached
- two chains overlapping - having multiple links attached

## Discusion

I am or alternative 2, because two same icons denote multiplicity

**Comment by fabiojavamarcos** [comment]
For Alternative 2 
- single chain: there is an icon called "link" available immediately in the library. 
- two chains: keep the "link_variant" that has two chains overlapping.

Do you agree?
