### ISSUE TITLE
Subgroups lost .....classification lost..Error occured when parsing entry "error in line 4833:EOF in Midstring' skipped entry

### ISSUE THREAD

**Issue by munissbedi** [JabRef/jabref#7024]
I am nearing the end of my thesis and the jabref has really hurt me with a sudden error and I lost the classification into groups  and subgroups .......I could not note down the error or take the screen shot .....If any body has a solution please share

**Comment by Siedlerchr** [comment]
Hi, sorry for your issues. The error indcates that you have invalid bibtex in that line. Probably some unescaped curly braces or wehatever or a curly brace too much. Try to open it in a text editor and go that line.

**Comment by munissbedi** [comment]
Thanks but another issue ....I upgraded to Jabref-5.1 ......It opened the bibliography from backup and it just opened back up with around 70 entries less....I think it was not doing back up for long but every time i opened it just showed me all the files ....now I am at loss what to do......two problems -
1. I have pdf files, any way to retrieve metadata directly into jabref 
2. It is not attaching the pdf files with the path

**Comment by Siedlerchr** [comment]
It's generally recommend to manually backup the bibtex library if you try out a new version (jiust copy the bib file). 
JabRef also creates a sav and or a bak file next to the bib file. These are just bibtex files with 
Second, I would recommend trying out the latest development version, it contains several fixes (also for the path probem) 
https://builds.jabref.org/master/

The attaching path is that JabRef in 5.1 lost the file directory setting (fixed in development version=

**Comment by munissbedi** [comment]
Although when i am trying to attach the pdf ....it is showing the message could not find the file........although the file is actually present in that location ......any way out

**Comment by munissbedi** [comment]
orange highlight of the pdf file when i attach

**Comment by Siedlerchr** [comment]
what i said above. check the main file directory setting under preferences.

**Comment by munissbedi** [comment]
thanks I changed file directory and its working... ...But any way I can recover my last week work also  or like zotero extract metadata from pdfs to rewrite the bibliography quickly
