### ISSUE TITLE
Switch from FontAwesomeFX to Ikonli

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#7058]
As FontAwesomeFX doesn't seem to be updated anymore and also doesn't include the latest 5.0 icons, we should switch to [Ikonli](https://kordamp.org/ikonli/). They have native JavaFX support as well.

I'll mark this as good-first-issue, because the code changes should be relative localized. However, there are changes required to many files, including grade build resources - so this task is perhaps a bit more complex than our average good first issues.

**Comment by IsaacRoles** [comment]
I was looking into solving this issue and was hoping you could clarify something. Are you looking to switch to the Material Design icon pack from Ikonli (https://kordamp.org/ikonli/cheat-sheet-materialdesign.html) or the Fontawesome/Fontawesome5 packs (https://kordamp.org/ikonli/cheat-sheet-fontawesome.html, https://kordamp.org/ikonli/cheat-sheet-fontawesome5.html)? 

I ask because it seems that the Material Design icon pack is more in line with the current look of the icons used in Jabref and the pack seems to offer equivalents to all the icons used in Jabref. The Fontawesome packs however have a slightly different look and are missing a few equivalents to the icons already found in Jabref.

I apologize if this is a silly question, but I want to be sure I am looking at the right options.

**Comment by tobiasdiez** [comment]
Good that you ask! I was mislead by the name of the library and thought we were currently using Fontawesome (the font). But you are right, it's Material Design. So I'd say migrate to the Material Design icon pack from Ikonli for now. Except if you strongly prefer the Fontawesome5 icons, then we can discuss to change them.

**Comment by IsaacRoles** [comment]
Thanks for getting back so quickly! I'll stick to Material Design for now. I think it would be better to maintain the current look. It should be relatively easy to switch to any other icon pack from Ikonli in the future should things change.

**Comment by Siedlerchr** [comment]
Yes, Material Design Icons are the ones we currently use. (see IconTheme.java)
Just a note, because it's confusing of the name, The MDI = Material Design Icons contain material design from google  and many more community created icons
https://kordamp.org/ikonli/#_materialdesign

**Comment by renatobellotti** [comment]
Which version are you using? I cannot use the brain icon (number 389 in https://kordamp.org/ikonli/cheat-sheet-materialdesign2.html)
