### ISSUE TITLE
EntryType not respected in File Directory Pattern

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#7070]
JabRef 5.2--2020-10-29--e08ac4e
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Define Linked File > File directory pattern = PDFs\EntryType
2. Move and drop a file to the entry
3. The file gets added to .../PDF/EntryType/citekey instead of .../PDF/article/citekey

**Comment by Siedlerchr** [comment]
Hi, it's not yet documented completely, but it's the same syntax that is also used in the Citation Key Generator:
You need to put [entrytype] in square brackets to denote it's a field marker, otherwise it's interpreted as literal.
https://docs.jabref.org/setup/citationkeypatterns#other-field-markers

**Comment by DOFfactory** [comment]
Thanks for the update, I am afraid it still does not work. I just tried changing it, and drop the file, but it does not work.

![image](https://user-images.githubusercontent.com/10846169/97987102-07276e00-1ddb-11eb-9d97-562cc921fcc8.png)

**Comment by Siedlerchr** [comment]
Try with forward slashes, that should also work on windows. I did a quick  test on mac, that worked fine.

**Comment by DOFfactory** [comment]
Thanks, this was helpful. On Windows 10 restarting JabRef was required to make this working
