### ISSUE TITLE
Changing font size makes font size field too small

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#7085]
JabRef 5.2--2020-11-04--fcbe9c5
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Changing font size makes font size field too small (see screenshot below) 

1. Go to Preferences > Appearance and tick "Override default font setting"
2. Set font size to 12
3. Save and reenter JabRef
4. The font size field show only the "1" of the "12".

Note that sometime the font size is not changed for the preference dialog and sometime the bug does not appear, but was unable to determine under which conditions this happens.

![image](https://user-images.githubusercontent.com/865866/98495306-212fd900-223f-11eb-9521-a0e56da8168a.png)

**Comment by calixtus** [comment]
JabRef is internally using pixels to define widths. A solution would be to change every width indication to 'em'.

**Comment by crystalfp** [comment]
Is this something that I can change in a custom theme?

**Comment by calixtus** [comment]
I was just taking a note for us or somebody, who wants to work on this issue. The em - indications are dependend on the font size an should automatically scale. There should be plenty of examples ion the web about this (eg https://stackoverflow.com/questions/32999605/how-can-i-change-the-base-font-size-in-javafx-8-modena-theme-that-would-cascade#33001277 )
To solve this issue a lot can be done by editing the base.css theme file, but something's are somewhat hardwired in the fxmls files and the ui Java sources in the codebase. That's one bad thing about the somewhat old codebase of JabRef, we are working on since some years, to modernize, sort and simplify everything.
If you like to give it a shot make a pull request with your changes. The PR does not have to be perfect and cover everything (although it would be very cool), but we can talk about it as soon it exists or work together on it.

**Comment by Sylvan1985** [comment]
There're other similar problems in the preferences, due to the fixed prefWidth. Like in the Entry table, the Colums will be hard to see and set.
![Size_pr](https://user-images.githubusercontent.com/52154597/99199106-0dfa9d00-275a-11eb-9488-190ffc9c62b4.png)

**Comment by aschloe** [comment]
By the way, in the latest master version this only happens if you leave the preferences window briefly and reopen it, without closing JabRef. That's because when restarting JabRef, the preferences window no longer respects the custom font size.
Is there already an issue for that separate bug?
