### ISSUE TITLE
Citation key, make it possible for an empty field to fall back to a custom field

### ISSUE THREAD

**Issue by tlannaax** [JabRef/jabref#7111]
Nowadays, most articles from online database already have their unique identifiers.
I personally prefer to use [authorsAlpha][eprint] as the default pattern for citation key. 
It expands the default [author][year] pattern (the information of [year] is already contained in [eprint]); moreover, it automatically avoid duplicate keys.
However, it is not compatible with old articles with no [eprint] field. So I hope that when [eprint] is empty, it automatically falls back to [year]. Currently JabRef has the feature to replace an empty field with a custom string, which is actually not informative at all and thus not practical. Also when [author] is empty then [editor] is automatically used. So why not make this available to all empty fields with customizable fallback field? The syntax may be simply [eprint:[year]].

**Comment by Siedlerchr** [comment]
This should be possible at least to define a fallback 
https://docs.jabref.org/setup/citationkeypatterns#citation-key-patterns

> :(x): The string between the parentheses will be inserted if the field marker preceding this modifier resolves to an empty value. The placeholder x may be any string. For instance, the marker [VOLUME:(unknown)] will return the entry's volume if set, and the string unknown if the entry's VOLUME field is not set

@k3KAW8Pnf7mkmdSMPHz27 Do you know if it's possible to define a fallback field?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> Nowadays, most articles from online database already have their unique identifiers.

You are referring to `eprint`?

> Currently JabRef has the feature to replace an empty field with a custom string,

It would be better if it supported fields/bracketed expressions as well, yup.

You might be able to workaround the issue using the [replace regular expression feature with an empty string](https://docs.jabref.org/setup/citationkeypatterns#replace-regular-expression). I am not familiar enough with regex and the `year`/`eprint` fields to come up with something good, but for the pattern `[author]|[eprint][year]` something along the lines of `(?<=|)\d\d\d\d$` (replace the last 4 digits if they are not preceded by `|`) might work (even if it doesn't give the exact results that you want)?

> So why not make this available to all empty fields with customizable fallback field?

I like the idea ``

> The syntax may be simply [eprint:[year]]

I'd recommend `[eprint:([year])]`, in that case, for consistency. I'd be happy to review/help out if you are interested in implementing this.

https://github.com/JabRef/jabref/blob/b0af521e3173e4b55673cd27563ca981ad607e8b/src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java#L549-L553

Is the (current) replacement modifier. 

> Do you know if it's possible to define a fallback field?

As far as I know, no =/

**Comment by tlannaax** [comment]
> Nowadays, most articles from online database already have their unique identifiers.
Yes, eprint or even doi. I don't like the [year] field because new articles tend to have both a preprint and a reprint with different [year]. When I update the reprint info from a preprint, the year changes, which then messes up the bibtex key and the pdf file names.  I then decided to use eprint instead of year which is unique and persistent.

I do have my personal workaround via regex.
I set the pattern [authorsAlpha]:[year]:[eprint], then replace :(.*):$|:.*:(\S) with $1$2.
So when [eprint] in not empty I get [authorsAlpha][eprint], otherwise I get [authorsAlpha][year].
Such hacking should work for customizing a fallback of any empty field.

However, I suppose that in the current version you can do regex replace **only once**. I would be already happy if it was allowed to add several regex replacement rules.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> Such hacking should work for customizing a fallback of any empty field.

Nice! Might be that others can use this meanwhile.

> However, I suppose that in the current version you can do regex replace **only once**. I would be already happy if it was allowed to add several regex replacement rules.

Agreed.

**Comment by SuXiChangZhen** [comment]
@k3KAW8Pnf7mkmdSMPHz27 Hi, I am interested in this issue. Where can I get started and What is the expected behavior of citation key generation? Thank you.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hello @SuXiChangZhen, thank you for your interest!

Pretty much all approaches start with the "alternative text modifier" as described above,
https://github.com/JabRef/jabref/blob/b0af521e3173e4b55673cd27563ca981ad607e8b/src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java#L549-L553

It is listed as the last modifier in the [JabRef documentation](https://docs.jabref.org/setup/citationkeypatterns#modifiers).

There isn't necessarily one "right" answer to this issue. The code is old and has a few violations against good coding principles making it harder to deal with it. Mostly I'd advise against trying to refactor the whole `BracketedPattern` class because it would be very time-consuming. I'd guest the best effort/utility trade-off would be to extend the method injection code found among other places in,

https://github.com/JabRef/jabref/blob/807f85e4ab418b4398408e37f023ee09209b038a/src/main/java/org/jabref/logic/citationkeypattern/CitationKeyGenerator.java#L195-L220

so that 
https://github.com/JabRef/jabref/blob/807f85e4ab418b4398408e37f023ee09209b038a/src/main/java/org/jabref/logic/citationkeypattern/BracketedPattern.java#L537

can parse and expand whatever is between the parentheses, i.e., make the same type of call as in
https://github.com/JabRef/jabref/blob/807f85e4ab418b4398408e37f023ee09209b038a/src/main/java/org/jabref/logic/citationkeypattern/CitationKeyGenerator.java#L195

Does that sort of make sense?

You are also free to solve it in some completely different way.

> expected behavior of citation key generation

I am not sure that I understand your question. The bracketed patterns were originally intended to create a citation key from bibentries by accessing its fields, (e.g., `[TITLE]` accesses `StandardField.TITLE`) with some special keywords creating shorter/easier-to-read citation keys (e.g. `[title]`). The issue here is regarding accessing a different field if `[title]` resolves into an empty string. At the moment it is only possible to use a string instead, e.g., `[TITLE:(NoTitle)]`, to generate the citation key "NoTitle" if the bibentry has no title.

**Comment by SuXiChangZhen** [comment]
Thank you for your advice. I think I understand the need. I will make a pr soon.
