### ISSUE TITLE
Name of Group Icons not properly working

### ISSUE THREAD

**Issue by AtrusRiven** [JabRef/jabref#7149]
`JabRef 5.2--2020-11-21--b0af521; Windows 10 10.0 amd64; Java 14.0.2`

In the edit menu of the groups you can set an icon for the group in the sidebar. This works when selecting a single word icon name, i.e. `book` or `eye`. It doesn't work when trying to set another name, i.e. with a dash, i.e. `eye-check`. The solution of this bug could be related to #7058.

**Comment by Siedlerchr** [comment]
Yep, it's a known problem and it's related ot that issue.

**Comment by Siedlerchr** [comment]
With the switch to the new Ikonly library, the issue is now resolved. 
You can now use any icon from these here (MaterialDesignA....Z.java)
You have to use the "keys" .e.g `EYE_CHECK`

The idea is now to add an icon picker dialog to ease the selection of icons  #6142 

https://github.com/kordamp/ikonli/tree/master/icon-packs/ikonli-materialdesign2-pack/src/main/java/org/kordamp/ikonli/materialdesign2
