### ISSUE TITLE
OSX 11.1 - Keyboard shortcut for deleting entries from table does not work

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#7233]
Current master (5.2-dev)

1. Select entries in the table
2. Press cmd + backspace or only backspace
 => Nothing happens

Deletion from menu works fine.

**Comment by tp-1000** [comment]
@Siedlerchr It doesn't look like there is a key binding for backspace to delete entries. On the latest, deletion requires the use of delete key instead of backspace key. Correct me if I am mistake in assuming 5.2-dev would be the latest version intended for the dev environment. 

I did notice some other problems related to entry editor interfering with deleting entries via the shortcut, but I do not know if we are talking about the same thing.

**Comment by Siedlerchr** [comment]
@tp-1000  Ah thanks for the hint, seems about it recognies the forward delete. fn + Backspace worked. 

>I did notice some other problems related to interference with deleting entries via the shortcut, but I do not know if we are talking about the same thing.
Could you elaborate on this?

**Comment by tp-1000** [comment]
1) Run application
2) Add new library
3) Add a couple entries
4) Select them all
5) Use Shortcut (delete key) to remove them

**It will only delete one entry.**
***
If you use the main-menu to remove them, it works fine and asks if you want to remove multiple and removes them.

It seems to be related to maybe a focus issue? Im not sure exactly what with though, possibly the entry editor? Cannot be ruled out yet, but behavior shows up even with auto-open-editor turned on for  new-entry's. If you activate the context-menu on an entry it will let the multi-delete work again. At this point you may also notice some overlapping keybindings when you try to use the shortcut. (Turn on the dialog-pop up to make it easier to see what's happening)

It's hard to say but seems like it could be related to.. issue #7392

**Comment by EricLee543** [comment]
It seems that this issue has been solved.
