### ISSUE TITLE
Option to disable automatic online version check please

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#7270]
Option to disable automatic online version check please, I do not want any automatic check of ANY kind without my setting it.

I noticed on launching that it checked for a new version automatically and I did not set that option. This was a non consentual data transfer and usage tracking.

This is a method for also tracking every time I launch the app. I do not want this tracking please.

I may have to end up blacklisting JabRef with AppArmor on network access if it continues on Linux.

**Comment by faeludire** [comment]
Just understand this issue a bit more, would you want the option to prevent all external network connectivity or just calls to check for latest version updates?

**Comment by tobiasdiez** [comment]
Although I do understand your concerns, we will not implement such an option to disable the update check. In the past, we had so many people that were using outdated versions (> 10 years old). These support requests draws to many resources from our too small team. You can already disable to be informed about a given version, this seems to be a sensible compromise.

Of course, we do not use this update check to collect telemetry data. We simply class the offical github API to see if there is a new version:
https://github.com/JabRef/jabref/blob/c8f7be89ad704065474decb61851e42416caf88d/src/main/java/org/jabref/logic/util/Version.java#L97

**Comment by retostockli** [comment]
We would have the same request, but maybe for a different reason: Our JabRef installation is managed by the IT department. Rollout of new versions are also handled by the IT department. Users cannot install anything by themselves. Therefore the version check is not making sense on the user's side. We would like to disable it for user installation but enable it for our IT staff, since they will be able to regularly check for new versions and roll them out on all clients. Would such a checkbox or even a command line argument for disabling be an option for you to implement? I understand your concerns on users never updating, but you may also see our situation. Could both be handled gracefully by having a "hidden" disable-for-updates-check feature and a default "on" for check-for-updates?

**Comment by tobiasdiez** [comment]
That's a good point and a different perspective. In a managed environment, the check indeed doesn't make much sense (although in my experience a friendly request from the user to the IT department to update software often leads to a quicker adoption of a new version). 

However, I hope you do understand that such a feature request targets a very narrow user group and I don't think anyone in the core team has currently the time to focus on this. PRs are of focus very welcome. The relevant code is in https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/help/VersionWorker.java; for the implementation I think it makes sense to follow Firefox's example and either allow configuration through group policies or via a `policies` config file next to the jabref executable.
