### ISSUE TITLE
Cannot "Move file to file directory" anymore

### ISSUE THREAD

**Issue by JClaverie** [JabRef/jabref#7281]
Hello,

I have libraries with file directory. With the previous versions, I had no problem to use the option "Move file to file directory" or "Move file to file directory and rename file". With the new 5.2 version, these options are greyed out.

I verified my paths and all is OK. I tried to add the paths in "User-specific file directory" and nothing changes.

Thanks for the support.

Best regards

**Comment by Siedlerchr** [comment]
Hi this issue has just been fixed in the latest development version.
We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by JClaverie** [comment]
Thanks very much! It works with the newest version (5.3).
