### ISSUE TITLE
"move file to file directory and rename file" is grey and can not work

### ISSUE THREAD

**Issue by soydou** [JabRef/jabref#7283]
JabRef version  on 
JabRef version 5.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In the version of 5.1, the "move file to file directory and rename file" can work, but after upgrading to 5.2, it doest not work.

My system is Fedora 33 and Centos 8.

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
