### ISSUE TITLE
Custom web address for accessing articles through DOI

### ISSUE THREAD

**Issue by jpdehollain** [JabRef/jabref#7337]
When I click on the `Open` button next to the DOI of an entry it opens a web browser to the address `https://doi.org/[DOI]`, which then redirects to the article website. In order to access articles in subscription-based journals, my institution has a shortcut that involves modifying the address to the doi site (e.g. for my institution it is `https://doi-org.ezproxy.lib.uts.edu.au/[DOI]`). It would be great if the address used to access the articles through the DOI could be modified in the preferences.

**Comment by Ali96kz** [comment]
I am a newbie to jabref, could you please provide an instruction on how to find that button

**Comment by Siedlerchr** [comment]
Add a new entry with a DOI, you can then find the button next to the DOI field.
<img width="939" alt="grafik" src="https://user-images.githubusercontent.com/320228/109426715-52e7ce00-79ef-11eb-8050-b8b58b5684ea.png">


What needs to be done:
- Add a preference for specifying a custom DOI base url in the preferences
- Use that preferences value when opening the URL of the DOI
- Maybe also use that preferences value for downloading full text?

**Comment by Ali96kz** [comment]
Started working on it

**Comment by Siedlerchr** [comment]
Thanks to @BJaroszkowski  this issue is now resolved. There is now an option in the preferences.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by jpdehollain** [comment]
@Siedlerchr @Ali96kz Thanks for getting this done. I tried it out, but I think the feature is not complete yet. Currently, it only works when I click the `Open` button from the entry editor window. However, if I click on the `Linked identifiers` button from my entry list, or if I right-click an entry and choose `Open URL or DOI` (or hit `F3`), it does not use the customised URL base.

Hope the explanation is clear, if it's not I can add some screenshots.

**Comment by Ali96kz** [comment]
@jpdehollain It's not me. That task was already in development when I wanted to start @BJaroszkowski

**Comment by BJaroszkowski** [comment]
Yes, the explanation is clear and it is something that I overlooked - opening DOI URI from `LibraryTab` and `IdentifierEditor` was handled differently. I will be shortly submitting PR to address that issue.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by jpdehollain** [comment]
Works great! Thanks for implementing this @BJaroszkowski  and @Siedlerchr
