### ISSUE TITLE
Multiple messages in the SnackBar

### ISSUE THREAD

**Issue by calixtus** [JabRef/jabref#7340]
If JabRef has do display several messages very shortly after each other, the messages are stacked and played one after each other. This is confusing, since the SnackBar is still displaying a message, which is already obsolete. E.g. if you cycle quickly through the preview styles.

A simple solution would be to stack the messages inside an already showing SnackBar, separated by a new line and to lengthen the display time of the SnackBar for the time only the last message should show.

**Comment by HoussemNasri** [comment]
Another solution would be to have multiple Snackbar views, every time we add a new Snackbar, all of the old Snackbars would move up,  and the new one would [BounceInUp](https://github.com/Typhon0/AnimateFX/wiki/Bouncing-entrances#bounceinup), Unfortunately, this  can't happen with the current Snackbar implementation (`JFXSnackbar`) because it uses only one view like shown in this code snippet : 
```java
private void show(SnackbarEvent event) {
content.getChildren().setAll(event.getContent());
```
Anyway, this is the method responsible for pushing Snackbars :
https://github.com/JabRef/jabref/blob/ae43548c16ca35b9a83a2d34864557cf503c0df4/src/main/java/org/jabref/gui/JabRefDialogService.java#L337

**Comment by EduRibeiro00** [comment]
@calixtus Since this is labelled as a good first issue, can I give it a try? If yes, and since I am new to this project, I would appreciate it if you could provide me with more information about this issue.

**Comment by calixtus** [comment]
Hi @EduRibeiro00 , yes, give it a shot. Quick
Idea would be just to add the message to a message queue, each with a closing timer and display all the messages in a distinct line, add new messages at the end, remove outtimed messages at the beginning.
Please don't forget to familiarize yourself with our developer docs and to setup your workspace according to our guide.
https://devdocs.jabref.org/

**Comment by DS-654** [comment]
Hi @calixtus, I would like to work on this issue, is it still open?

**Comment by calixtus** [comment]
Since I haven't heard anything of @EduRibeiro00 anymore, why not? Good luck and happy coding. Remember to set up your workspace according to our contributors guide at devdocs.jabref.org - especially the codestyle stuff.

**Comment by EduRibeiro00** [comment]
Hello @DS-654 and @calixtus,

I apologize for the wait and for not giving any feedback. I am currently working on this issue and will hopefully make a PR soon. :)

**Comment by EduRibeiro00** [comment]
Hey again!

Just submitted a WIP PR for this issue. Any feedback is appreciated! Once again sorry for taking so long 😅

**Comment by yogeshvar** [comment]
Hello, I would like to contribute to this. I will go through all the linked issues and PRs to understand the project base since I'm new.
