### ISSUE TITLE
Unhandled exception when searching with regular expression

### ISSUE THREAD

**Issue by KWaniova** [JabRef/jabref#7344]
JabRef version 5.2 on Windows 10, Ubuntu 20.04.1, Mac OS Catalina 10.15.7

1. Open some library with several entries.
2. Click on first article.
3. Set on regular expresion checking in the search field.
4. Paste this **10.1126/science.1188363** or **13.155//1313** or 13/ input value in search field.

![JAB-98](https://user-images.githubusercontent.com/61587204/104621514-7c8fa480-5690-11eb-9736-09c0403d0c49.jpg)

![JAB-99](https://user-images.githubusercontent.com/61587204/104621577-8d401a80-5690-11eb-8030-8eb00ea74c62.jpg)

![JAB-101](https://user-images.githubusercontent.com/61587204/104621547-85807600-5690-11eb-8ea7-a720ba9f8b37.jpg)

**Comment by Siedlerchr** [comment]
Thanks to @k3KAW8Pnf7mkmdSMPHz27  This should now be fixed in the latest development version (ready in roughly half an hour)

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by KWaniova** [comment]
Yeah, in the newest build it works.
