### ISSUE TITLE
sudden change of the sizes of the window

### ISSUE THREAD

**Issue by ChengYang03** [JabRef/jabref#7513]
JabRef version < 5.2 > on <Mac OS X 11.2.2-->

- [√] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. when I open this app, it is a maximum size window
2. when I try to create a new group, the window becomes smaller
3. when I trying to close the window which I created, the window becomes extremely  small

<img width="479" alt="Screen Shot 2021-03-10 at 1 36 01 PM" src="https://user-images.githubusercontent.com/53319002/110686927-912a7d80-81a5-11eb-9403-e96f53f1f566.png">

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by ChengYang03** [comment]
> Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.
> 
> We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

It works just fine in the new version!
