### ISSUE TITLE
Entering an Id at the Web Search should search for the id - and not throw an Exception

### ISSUE THREAD

**Issue by WolfgangFahl** [JabRef/jabref#7575]
JabRef version 5.3 on Mac OS X 10.15.7 Catalina

-  I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. select DBLP for search
2. paste DOI 10.1007/s11192-020-03391-y into the web search field
3. click search

```
org.jabref.logic.importer.FetcherException: An error occurred when parsing the query
	at org.jabref@5.3.218/org.jabref.logic.importer.SearchBasedFetcher.performSearch(Unknown Source)
	at org.jabref@5.3.218/org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$1(Unknown Source)
	at org.jabref@5.3.218/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.3.218/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.3.218/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Siedlerchr** [comment]
Thanks for your report, can reproduce this. Please note that using the WebSearch for Identifier is not the right way. If you have an Identifier like a DOI or ISBN the right workflow is to use Library -> New Entry.

However, if you have a DOI, you can also directly paste it on the maintable

<img width="493" alt="grafik" src="https://user-images.githubusercontent.com/320228/112719438-504a9c80-8ef9-11eb-9987-86ab425115c5.png">


 
Refs #7411

**Comment by WolfgangFahl** [comment]
I think the useability would much increase if the web search would automatically detect certain identifiers like ISBN and DOI

**Comment by koppor** [comment]
@WolfgangFahl We will use [Lucene Syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) in our next release. You can have a sneak look at https://builds.jabref.org/pull/7809/merge/.

In your concrete case, the query should be `doi:"10.1007/s11192-020-03391-y"`, because fields and content are separated by `:`. Moreover, `-` is a Boolean not in Lucence, thus we need to put quotes around. I know, this is not that good, maybe, we should add some pre-processing step to convert "intuitive" queries to syntactically correct ones. An "intuitive query" might be `<FIELDNAME> <FIELDCONTENT>`. @DominikVoigt

**Comment by koppor** [comment]
This report is relates to https://github.com/JabRef/jabref/issues/550 in the way that #550 asks for the "new entry" dialog and here the feature is asked for the web search.

**Comment by WolfgangFahl** [comment]
My own tool http://ptp.bitplan.com/ tries to analyze the input of the query and "guess" what the search looks for. I didn't implement a DOI mode yet but intend to do so. When I am at it i hope to share the ideas and code for the solution.

**Comment by koppor** [comment]
I think, a "relaxed" parser should be put before the actual Lucene parser. One could try to parse the input string as DOI, ISBN, ... If there is not a match, it is "just" a plain title. This `doi:"10.1007/s11192-020-03391-y"` instead of `doi:10.1007/s11192-020-03391-y` or `10.1007/s11192-020-03391-y` is Lucene-technically correct, but a very bad user experience. @DominikVoigt Maybe you could work on that?

(Adn I see, I reiterate my statement from https://github.com/JabRef/jabref/issues/7575#issuecomment-857391710)

**Comment by Siedlerchr** [comment]
Refs also https://github.com/JabRef/jabref/pull/7666

**Comment by WolfgangFahl** [comment]
http://sotsog.bitplan.com/ has the DOI mode now.

since i am using python now mostly it would be good to have RESTFul integration with JabRef but as far as i understand JabRef is not web based at this point.

**Comment by koppor** [comment]
> since i am using python now mostly it would be good to have RESTFul integration with JabRef but as far as i understand JabRef is not web based at this point.

@WolfgangFahl  Side comment: We have to active development streams ongoing: 

- JabRef Online for full online hosting mode: https://github.com/JabRef/JabRefOnline
- JabRef build in http sever: https://github.com/JabRef/jabref/pull/9748

The most important historical attempt for an online version is surely [CloudRef](https://github.com/JabRef/cloudref) with a concept of a) sharing PDF annotations among others and b) enablement of reviewing of new entries (to enable quality assurance).

**Comment by koppor** [comment]
There can be a "pre-processor" / pre-fetch using org.jabref.logic.importer.CompositeIdFetcher. This fetcher both tries to parse the Id. If the id is found, the fetcher is used.

If this is done as first step before the current parsing, it should "just" work.

**Comment by koppor** [comment]
The code is **not** in CompositeIdFetcher, but at [/src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java#L81](https://github.com/JabRef/jabref/blob/5bc359fa5f572c40ac3f05551e5eecd8126845d8/src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java#L81). Tests are in `org.jabref.gui.importer.fetcher.WebSearchPaneViewModelTest`.

**Comment by aqurilla** [comment]
Is this issue up for grabs?

**Comment by aqurilla** [comment]
Thankyou! @ThiloteE
