### ISSUE TITLE
CSL editor string placement

### ISSUE THREAD

**Issue by jspitz** [JabRef/jabref#7637]
JabRef 5.2--2020-12-24--6a2a512
Linux 5.11.12-1-default amd64 
Java 15.0.1

- I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. Select a CSL style such as "Chicago Manual of Style 16th edition (author-date)" or "Unified Stylesheet for Linguistics"
2. Select an entry with Editor field (e.g., collection)
3. The editor string "eds." is not appended, but prepended in the preview.

![grafik](https://user-images.githubusercontent.com/4538783/115107468-456cb000-9f6b-11eb-8e0a-bbf10b6c002b.png)

I have verified with several styles to exclude the possibility of a bug in the CSL style itself.

**Comment by Siedlerchr** [comment]
Thanks for your report. I could reproduce this JabRef uses https://github.com/michel-kraemer/citeproc-java to parse the CSL styles. So you should report your issue there as well

**Comment by Siedlerchr** [comment]
Thanks to the fix from @michel-kraemer  this issue is now resolved in the latest development build.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
