### ISSUE TITLE
Icons in Entry Edit Window not visible in Dark Mode 

### ISSUE THREAD

**Issue by dirkziegenbalg** [JabRef/jabref#7853]
JabRef version 5.3--2021-06-27--aa60dd6 on Windows 10

I have tested the latest development version from http://builds.jabref.org/main and the problem persists

The icons in the entry edit window are frequently too dark to be visible in dark mode. A bright color would be better suited

1. change to dark mode
2. edit an entry
3. view icons

<img width="1625" alt="Screenshot 2021-06-28 132651" src="https://user-images.githubusercontent.com/47889512/123629524-abe83700-d814-11eb-8a94-edabf7d0dc13.png">

**Comment by Joe11028** [comment]
I think we can redesign the dark-theme by adjusting the color of components then it will looks prettier. And Is there anyone work on the issue?

**Comment by Siedlerchr** [comment]
@Joe11028  Thanks for your interest! Feel free to work on this! 
'You will find the Dark Theme and the Base.css here https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/Dark.css

See also this reference guide for the javafx componnents https://openjfx.io/javadoc/16/javafx.graphics/javafx/scene/doc-files/cssref.html

**Comment by Joe11028** [comment]
@Siedlerchr Okay, thank you for providing informations. I think we should only changed the specific components' color rather than redesign the dark theme, I will try my best to work on this issue.

**Comment by Joe11028** [comment]
@Siedlerchr I'm now can sure the issue caused by the icon from the imported package(org.kordamp.ikonli.materialdesign). The icons' color can not be changed after we switch to dark theme. So we have two ways to solve this issue:
Add another set of icons that suitable for dark theme. Or don't modify icons, but let the icon-button background color be different from the main body background color, so you can find the icons(buttons) easily.
How do you think of that and which one would you prefer?
