### ISSUE TITLE
Middle-button paste in X sometimes works but more often does not

### ISSUE THREAD

**Issue by rkouznetsov** [JabRef/jabref#7905]
JabRef version 
JabRef 5.3--2021-07-05--bed9ac9
Linux 5.4.0-73-generic amd64 
Java 16.0.1 
JavaFX 16+8

Installed from snap in ubuntu 18.04

1. Open Help-about dialog
2. Select version with mouse
3. Switch to a favourite text-editor
4. Press middle mouse button in the editor's text field

In other most applications selected text would be pasted to the window. In Jabref the selection is simply ignored.

Funny enough, select - middle-cleck works between fields in "edit entry", but does not in "BibTeX source".
The same way does not work for copying strings to "web search" entry.
Clumsy "Ctrl-C -- Ctrl-V" method  works fine.

Looks like re-appearance of https://github.com/JabRef/jabref/issues/2389 

Thank you!

**Comment by marcelolaia** [comment]
Same issue here.

I would like to select a PDF text (i.e. paper's title) and paste it by middle button on the JabRef search bar. It doesn't work. Only CTRL+C/CTRL+V work.

```
JabRef 5.10--2023-09-01--779e555
Linux 6.4.0-4-amd64 amd64 
Java 21-internal 
JavaFX 20+19

```
Any workaround?

**Comment by atdushi** [comment]
Calling `ClipBoardManager.addX11Support(query)` may help. It handles middle mouse button.

**Comment by Siedlerchr** [comment]
@rkouznetsov  @marcelolaia  
/
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
