### ISSUE TITLE
Add preferences + popup for usage of GROBID

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8000]
When the PDF Import is used, the internet service GROBID is used. Default: No usage allowed. If user requests use, they have to confirm.

Preferences:

- Use GROBID
- URL of GROBID server

**Comment by tobiasdiez** [comment]
I wouldn't use the word "Grobid". This is an implementation detail, and users don't know what it is. Some generically "send pdfs to JabRef online service to analyze" is more descriptive in my opinion.

I also don't know if we really need to make the url configurable.

**Comment by btut** [comment]
> I wouldn't use the word "Grobid".
I think some credit to Grobid is due here. I would even include a link.
> Some generically "send pdfs to JabRef online service to analyze" is more descriptive in my opinion.
I would do both.

> I also don't know if we really need to make the url configurable.
I myself am not going to use the service otherwise (actually, I would just point grobid.jabref.org to localhost in my hosts file, but would much rather have a JabRef setting). Setting up a Grobid instance is quite easy. Users concerned about their data can have their own or institutions could provide one for their researchers to use.

**Comment by Siedlerchr** [comment]
Add Grobid in braces

**Comment by btut** [comment]
How about this?
![image](https://user-images.githubusercontent.com/10479048/130040814-fc584431-27dc-4ef6-8eca-d17258c58e77.png)

**Comment by calixtus** [comment]
Fixed by #8002
