### ISSUE TITLE
Move search button of web search elsewhere

### ISSUE THREAD

**Issue by liurui39660** [JabRef/jabref#8288]
**Is your suggestion for improvement related to a problem? Please describe.**

The search button in Web Search occupies a separate row. It can be put after the above combo box or text box, so as to save some space.

**Describe the solution you'd like**

Move the search button to after the combo box or text box.

**Additional context**

![image](https://user-images.githubusercontent.com/20491264/143983984-ec7b5630-ced0-4b18-b647-fccd3f9ed55b.png)

**Comment by Yancy10-1** [comment]
Hi, I want to fix it, can you give me a shot?

**Comment by ThiloteE** [comment]
Refs #6112

In general: "Search" of websearch and "Add Group" for aesthetic reasons probably should stay coherent. If "search" is moved, "add group" should probably also be moved.

Yancy10-1 you are so fast! xD

There was a reason I put this issue here on low priority instead of leaving it on normal priority. I was too lazy to write something up and now I have to pay the prize for it. :/ ok here is why I actually want to close this issue:

1. If you move it next to the search bar, in half a year or in one year, it is very likely, somebody will open an issue to remove it from next to the search bar. And then when you have removed it again, somebody else will come up with another issue moving it back again. It seems to be one of these "endless loop" issues. It's like it is never right, and it depends on user preference. Since this is the case it would probably be better to work on something that actually brings a new feature to JabRef or to fix an actual bug.

2. The "space" argument is a red hering. When using a small screen, there is no space regardless if you put it next to the search bar or if you have it below the search bar. Adding groups with long group names, searching through groups or the web may require me to increase the size of the panel, but having a look at entries in the entry table may trigger me to **de**crease the size of the panel. There is not enough space for both when operating on small screens, so moving this button because of "more space" is a kind of awkward argument. 

   As you can see, currently I operate on a very small screen:
   ![grafik](https://user-images.githubusercontent.com/73715071/168482548-db2bd647-0166-47d5-a394-97f272258928.png)

   
**What is nice with the current implementation:**
If I have a lot of groups, I don't have to resize the panel towards the bottom by using my mouse, because there will be a scroll bar. So having it at the bottom does not require me to resize the panel. Having it at the right side next to the search bar will require me to resize the panel in certain situations though. So I prefer having it at the bottom.

If you still have space problems you can use keyboard shortcuts via `view > web search (Alt + 4)` to remove the web search from view.

**Comment by ThiloteE** [comment]
Refs #8462

**Comment by koppor** [comment]
More focused screenshot:

![grafik](https://user-images.githubusercontent.com/1366654/169888142-ae928697-dbc4-4819-90aa-81f9ace828e0.png)

**Comment by koppor** [comment]
DevCall decision: We keep the current UI as is

Main reason:

- the button next to the search bar makes the search bar too small
- important functionality should be reachable with big buttons (and not small icons)
- other reasons stated above.
