### ISSUE TITLE
[isNull] Inconsistency

### ISSUE THREAD

**Issue by stoianmihail** [JabRef/jabref#8315]
**Is your suggestion for improvement related to a problem? Please describe.**
The check for `null` in [this line](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/git/SlrGitHandler.java#L122) is inconsistent to the others, e.g., [the one in this line](https://github.com/JabRef/jabref/blob/74a4edb35e67a97c5b0ceb32be5a4bb1723d8de5/src/main/java/org/jabref/logic/git/SlrGitHandler.java#L127), used throughout the file.

**Describe the solution you'd like**
Consistent use of the check for `null` case.

**Comment by Siedlerchr** [comment]
Thanks for spotting. However, as both do the same it's not really worth it.  We foremost try to fix bugs/implement features and fix code issues/refactor along the way.
If you are interested in contributing, I strongly recommend to checkout our devdocs https://devdocs.jabref.org/

**Comment by calixtus** [comment]
Thanks for your issue. We'll put that in our dev docs code guidelines.
I think this is also something nice to see in our code base: it's almost 20 years old and a lot of people already contributed to it. Every contributer had her or his own style.

**Comment by Siedlerchr** [comment]
Btw, Objects.isNull is primarily intended for the usage in lamdba expressions  etc"Objects::isNull"

**Comment by a1819644** [comment]
Hi, just wondering if this issue has been taken by someone? If not may I have look into it.

**Comment by ThiloteE** [comment]
I talked to @Siedlerchr. Since this issue does not really seem to be a real issue causing problems to users, let's close this.

@stoianmihail Thanks for spotting nevertheless! If you can show that this "[isNull] Inconsistency" leads to real issues, feel free to open again.
@a1819644 Anoop, instead of this one, I would ask you to choose other issues. The time and work you would have to spend on this could be better used on other issues that have higher priority.
