### ISSUE TITLE
Short freeze when selecting first entry after fresh start

### ISSUE THREAD

**Issue by Krzmbrzl** [JabRef/jabref#8446]
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

KDE Neon 5.23 (built on Ubuntu 20.04)

### Checked with the latest development build

- [ ] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Start JabRef
2. Select an entry

### Appendix

Note: I didn't actually test the latest development version, but I had to check the boxes in order to submit this ticket. I currently do not have the time to look into getting any development versions to work

**Comment by ThiloteE** [comment]
How long is the freeze?
Do you have data about RAM, CPU Usage etc. during the freeze?
How large is your database? ~ number of entries?

I also experience that whenever i click on an entry after starting Jabref there is a small lag. In order to open the entry editor, i have to click on an entry **twice**, not once, which could be designed intentionally, as there are features (e.g. pushing entry to external application) that do not need the entry editor.

**Comment by Krzmbrzl** [comment]
- The freeze is only about ~3-4 seconds or so. After any further selections work just fine.
- During the freeze the CPU spikes to ~40% (before selecting anything, it's about 0%). RAM jumps from ~360MB before selecting anything to ~1GB after having selected the first entry. Afterwards it stays pretty constant (also after the freeze)
- My DB is also rather small and currently has 157 entries

**Comment by ThiloteE** [comment]
This freeze is probably caused by indexing linked and attached pdf files to optimize for full-text search. The more attached pdf files you have, the longer the indexing will take. In the newest development version, a preference was added to disable full-text indexing. Would you mind giving some feedback if this would work for you and report, if it solves the freeze?

**Comment by Krzmbrzl** [comment]
I will try to find some time to try out the new version. However, I noticed that when I start JabRef it starts a background task that is about indexing files and the freeze upon the first selected item occurs, even if I wait until that task has finished before selecting any of my entries. This makes me doubt that the freeze is due to the indexing :thinking:

**Comment by HoussemNasri** [comment]
The freeze is caused by the preview panel in entry editor; the entry editor is created lazily the first time an entry is selected, which explains this behavior.
This is a flamegraph of when an entry is selected the first time.

![flamegraph](https://user-images.githubusercontent.com/21198231/160373243-49bd5541-bc0c-46df-9b7f-691d6629c581.png)
