### ISSUE TITLE
JabRef inserts incorrect keys in windows

### ISSUE THREAD

**Issue by nimra287** [JabRef/jabref#8562]
### JabRef version

5.5 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open new Writer document (no references)
2. Open JabRef
3. Connect from J to W
4. Insert a few citations
5. Press the Update Bibliography button on the left panel
6. JabRef reports "Citation key xxxx not found in your current library"
7. Look at the JabRef entries. Key is shown in the table.
8. Writer document has JR_cite_1_ in in front of the key shown in JabRef.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Duplicate of  #8541

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
