### ISSUE TITLE
Method in Author model to capitalize every first letter of the name

### ISSUE THREAD

**Issue by Neitan2001** [JabRef/jabref#8627]
Looking at the code, I see there could be a method inside the author's model to capitalize every first word of the final string.

**Comment by Siedlerchr** [comment]
Is this a question or an issue? Please specify.

**Comment by u7283219** [comment]
I think @Neitan2001 is trying to say that there should be a check in Author.java to ensure the author's name is capitalised. If this is indeed the case and appropriate for the project can I be assigned this issue? I have set up the project, read the project documentation and contribution statements.

Thanks

**Comment by ThiloteE** [comment]
Thoughts:

- I wonder if there are languages that have no capital case?
   -  users would loose the possibility to enter data with lower case
- OP seems to have lost interest and failed to clarify
- Automatically changing entry metadata always poses a risk. We have users with libraries spanning thousands of entries that they may share with multiple machines and users. If there indeed are many entries stored in lower case (for whatever reason), this change here has the potential to change the whole library and trigger sync process. (Performance for large databases is not really all that great, so this could be a one time bother for these users :/)

On the plus side:

I think making sure to capitalize only the first word in the string in the authors field would be ok as such. It would protect users from typos.

Since there are (tiny) risks associated with this change and there is not really a big lobby behind this (OP never responded), I would suggest to find another [good first issue](https://github.com/JabRef/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or project from the [projects page](https://github.com/JabRef/jabref/projects) to work on and indeed, I think @u7283219 , you have found at least one other issue, so I would suggest to work on that one first, before you start another one.

**Comment by Siedlerchr** [comment]
Isn't that already this TitleCase/SentenceCase formatter which you can use?

**Comment by mlep** [comment]
Note that in some languages, some part of names should not be always capitalized.
Examples: van, von, der, de, da, du, ben,

And in some languages, what looks like a compound first name is not a compound first name...
Example (Chinese): Chiu-wai (and not Chiu-Wai)

Of course, this is a "just" convention. But JabRef should respect such a convention.

**Comment by koppor** [comment]
Note the current implementation does not take care about the type of the field:

![grafik](https://user-images.githubusercontent.com/1366654/195952879-8edbca26-d769-47f6-81b2-3dbcee62322b.png)

When working on this, maybe following two issues can be handled, too:

- https://github.com/koppor/jabref/issues/308
- https://github.com/koppor/jabref/issues/356

**Comment by koppor** [comment]
No one else showed up for an interest; I will close this issue. If someone really wants this feature, please speak up.
