### ISSUE TITLE
Correctly understand DOI author fields on import ("[name], [first name]" vs. "[first name] [name]")

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8745]
**Is your suggestion for improvement related to a problem? Please describe.**
Follow-up from #8744. Basically, DOI import shows differences in the author field, when there actually is just a different order of the name format used.

**Describe the solution you'd like**
Treat that in the background or a different way.

**Additional context**
![grafik](https://user-images.githubusercontent.com/6171135/166164619-ad4b8201-d5c0-488c-a29f-e1ac9b163b97.png)

**Comment by claell** [comment]
Just did some research: BibTeX actually seems to support both formats: https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Authors

Still, JabRef should be able to notice, which of both formats is used and correctly import to that format.

(Especially in cases where a last name consists of more than one name, separating first and last names with a comma might be useful (or using curly brackets for that)).

**Comment by koppor** [comment]
Just a comment:

JabRef understands different name formats very well. See our [documentation on the field `author`](https://docs.jabref.org/advanced/fields#standard-bibtex-fields) and [in the code](https://github.com/JabRef/jabref/blob/0b580790d7a323ccdb445b8a8a6e8dd4d5917e69/src/main/java/org/jabref/logic/importer/AuthorListParser.java#L237).

What you bring up is a UX issue. There seem to be two different "personas" using JabRef. The first persona does not trust tooling and wants to comprehend/control everything the tool does. Thus, JabRef should not alter content automatically, but show content as is. The second persona wants JabRef to "just work" and does not care about details such as lastname, firstname ordering or some BibTeX details about field contents. -- I tend to be the first persona, because I am creating LaTeX templates and should be aware, what happens. Most users seem to tend to be close to the second persona. My thinking is: JabRef should be a tool for both personas.

We will implement to things to improve that:

- [ ] Fetched entries will have their author list normalized
- [ ] The diff dialog will have a visual indicator if the fields are semantically equal, but not syntactially.

**Comment by claell** [comment]
Thanks!
