### ISSUE TITLE
Button highlight doesn't respect rounded corners

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8806]
### JabRef version

5.6 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Use JabRef
2. Open a dialog with a button
3. Highlighted buttons (left on the screenshot) or hovered ones (right on the screenshot) show sharp corners.

### Appendix
Problem marked in yellow.
![grafik](https://user-images.githubusercontent.com/6171135/168646034-0a327526-3092-4633-9062-aaad9586f8c6.png)

**Comment by ThiloteE** [comment]
Please explain your rationale for suggesting rounded corners. E.g.: Does it fix a bug or is it more about fashion?

**Comment by claell** [comment]
The buttons are rounded normally, already. Only on highlight, that isn't respected. Default:
![grafik](https://user-images.githubusercontent.com/6171135/168651177-5e01849e-4d2e-49f5-8508-e70113435e6c.png)

**Comment by ThiloteE** [comment]
@claell are you sure you want to leave this open? Currently there are more issues than pull requests and more issues than developers can fix. Since that is so, fixing this during one of the larger reworks of the UI. For example, when replacing JavaFX with something else. I get that fixing this would make JabRef more beautiful, but there are so many other issues open that deserve working on and solving this issue does not really change anything when working with JabRef apart from that tiny little "feeling of satisfaction" you get when looking at rounded corners...
I would argue, most people will not even notice.

**Comment by claell** [comment]
Speaking for me, I got slightly annoyed by it. Since this is an issue, I suggest leaving it open, priority can be set accordingly. Possibly it is also not that hard to fix.

**Comment by claell** [comment]
Seems as this can be fixed in here:
https://github.com/JabRef/jabref/blob/6a2332f6b17c818a7f091647b102e7099d36569e/src/main/java/org/jabref/gui/Base.css#L320

Adding `-fx-background-radius: 4px;` there solves the issue, but creates some probably unwanted side effects. Also, I ideally want to set the radius to the same value as `-fx-border-radius`, but that didn't work quickly when I tried that.

**Comment by june-hong** [comment]
Hi, could I be able to work on this issue if nobody is working on it?

**Comment by claell** [comment]
@june-hong yes, that'd be appreciated!
