### ISSUE TITLE
Not possible to change or create custom fields in "{} biblatex source" tab

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8859]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 100.0.0 Linux 5.4.0-113-generic amd64  Java 18.0.1  JavaFX *unknown*

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to `{} biblatex source` tab
2. Try to add a new custom field
   e.g. `whatever = {whatevernot}`,
3. Switch to a new tab or select another entry in the maintable
4. Switch back to `{} biblatex source` tab
   
**What happens:**

New custom entry has not remained. It has vanished.

**Additional info:**

- It is possible to change whatever is WITHIN a field (withing the curly braces `{` `}`).
- Changing anything OUTSIDE of a field is not possible anymore and will be deleted upon switching. E.g. changing the field `title` by typing `date` will lead to vanishing.

**Cause:**
I tested some recent commits and found it was caused by 7257350b60427fbd6ee5b6f65641fe912ae8e78a

**What to do:**

Not sure. We have the choice between pest and cholera.

- Revert: We gain the feature back, but we also got an indexoutofbounds issue.
- Have commit: Fixes an index out of bounds issue, but we loose the feature.
   - Also it is still possible to create customized fields. Very lengthy workarounds:
      - Fields can be created under `options > customize entry types`
      - Customized Fields can be edited directly in the library file (via texteditors) and imported into JabRef

**Comment by ThiloteE** [comment]
@LIM0000

**Comment by ThiloteE** [comment]
To be honest, I think this feature is too important to let go of it because of this index out of bounds. :/ Damn. Welcome back index out of bounds.

**Comment by LIM0000** [comment]
Thank you @ThiloteE , I strongly believe it is possible to add the feature and fix the index out of bound issue at the same time.
I will create a PR for this issue soon.

**Comment by LIM0000** [comment]
Hi team, I have done some researches on this issue again and would like to share my findings here.

After digging much deeper of this issue, I have found that the cause of `UnsupportedOperationExpection` is due to inconsistency of modifying `ObservableMap` from `FXCollections`. For some reason, only the steps to reproduce issue in https://github.com/JabRef/jabref/issues/8012 trigger `ObservableMap` to be **immutable** and throw exception if any methods try to modify it.

![000](https://user-images.githubusercontent.com/49628911/171018091-abb211a1-1925-4bad-a90b-8a7c7f12a890.png)


Both `remove()` and `put()` which modifies the `ObservableMap`. If **immutable**, both the methods will throw exception.

![111](https://user-images.githubusercontent.com/49628911/171018787-e4caf468-9537-4d49-8c52-31b6bc2d34ba.png)
![222](https://user-images.githubusercontent.com/49628911/171018792-6a0cf686-f343-4f3d-8e2f-f575cd7bd658.png)

Additional information:
Apologize that I have to raise my findings from technical perspective here instead of creating a new PR as I could not find a solution for this issue just yet.

**Comment by ThiloteE** [comment]
Thank you! Don't worry, it is fine to post your findings here. Last time I might have overreacted slightly when I argued  that Issues are mainly for Issue description / enhancement and feature ideas / design and discussion about how JabRef ought to be and you might have seen that post. Since then, I have come to realize: Discussion is good, good. Posting code is good. Too much discussion can be distracting though, but no worries :), in theory, if a discussion were to become too complicated and messy, we can always close it and create a follow up issue with a nice summary for all the people that don't want to dig through 50 pages of text xD

**Comment by Siedlerchr** [comment]
Thanks for the detailed analysis! I think the problem is that you somewhere have a SortedList which is immutable.
And I suspect it's the SortedList of the mainTable which triggers somehow a listener on the selectedItems changes

**Comment by LIM0000** [comment]
@Siedlerchr Could we reopen #8012? I would suggest to revert PR #8821 to retain the ability to edit field in bibtex source tab before we found a solution for issue #8012.
I have looked into #8012 again and still could not find the main reason that causes both `UnsupportedOperationExpection` and `ArrayIndexOutOfBoundsException`
