### ISSUE TITLE
Improve performance of journal abbreviation loading

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#8928]
**Is your suggestion for improvement related to a problem? Please describe.**
As a User I have a huge list of custom abbreviations. Adding them will freeze JabRef for a couple of minutes and will produce other issues.
https://discourse.jabref.org/t/journal-abbreviations-with-dot/3400/4 

**Describe the solution you'd like**
I would like to have a better performance and continue using JabRef while the abbreviations are loaded in the background. 

**Additional context**
JabRef stores its internal abbreviations in a h2 mv database. Custom abbreviations are added to it. Refs #6304
The key problem is that all journal abbreviation stuff loading is done on the FX-Thread. This will block the user.

**Solution**: The files need to be loaded in a background task and added to JabRef's mv database. 
It must be taken care of concurrent reading/writing issues when toggling the abbreviation button in the entry editor.
It must be considered that the journal Repo is injected everywhere.

**Comment by HoussemNasri** [comment]
The real bottleneck apparently reside in the way duplicates are removed. Before an abbreviation entry gets added to the list, it will be searched and removed from the list to make sure no duplicates are kept. I run the profiler and found `99.5%` of abbreviation loading time goes to `ArrayList#remove`. This is clearly happened because Lists are not optimized for removal. One possible solution for the bottleneck is by using another data structure, maybe a `Set` or a `LinkedList`.
Nonetheless the whole thing should not run on the FX Thread. The FX Thread should never do long running tasks. This will block the UI.
## Bottleneck
https://github.com/JabRef/jabref/blob/152d41179c105790e6bceb64b468412f70c6c2cc/buildSrc/src/copied/java/org/jabref/logic/journals/JournalAbbreviationRepository.java#L92-L99
## Profiler Results
![image](https://user-images.githubusercontent.com/21198231/175698787-36e71490-d719-46f6-a226-2eaaa406295b.png)

**Comment by ThiloteE** [comment]
Metaissue:  #8906
