### ISSUE TITLE
Regressions and enhancements surrounding the new automatic field editor dialogue

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8971]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 100.0.0 Linux 5.4.0-122-generic amd64  Java 18.0.1  JavaFX 18.0.1+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Follow up issue to https://github.com/JabRef/jabref/commit/9701e35bb6c271ae64d1baebcbf79488928867ae

Some of my remarks may be nitpicks (less important), others are regressions from old "Manage field names and content".

The Automatic field editor can be opened by selecting an entry in the library and then go to `Edit > Automatic Field Editor`

**Issues:**

- [x] 1. Regression: The Field selection does not allow to write custom fields anymore. In the old version this was possible.
   Before:
   ![grafik](https://user-images.githubusercontent.com/73715071/178504508-b814823a-3ddf-4a88-8ac5-647907584502.png)
   After:
   ![grafik](https://user-images.githubusercontent.com/73715071/178508349-5d4013c4-aeb7-4c57-935c-79baba0bb5c5.png)

- [x] 2. I am not sure what `Clear field` is supposed to do.

   Example:
   ```
   @Article{testclearfield,
      whatever = {a}
      }
   ```
   Press clear field.
   Result: Nothing happens.

**Non-critical/low priority issues that are based on personal subjective opinion**

- [x] 3. Rename `Clear field` to `Delete field & content` or `Clear field content`, depending on how it behaves. See above. I don't really understand yet. Needs more testing/explanation.

- [x] 4. The tab name `two fields` is very ambiguous. It could be replaced with `Copy, move & swap` or `Copy, move & swap content`

- [x] 5. Replace all words in the `automatic field editor` dialogue that contain `value` with `content` instead.

   Why? I argue the word content can be understood more easily than value. The word "value" can be attached to many things e.g. also to field names. The word "content" on the other hand means a value is within something and therefore in this specific context would be more specific.
   
- [x] 6. Rename:
   ![grafik](https://user-images.githubusercontent.com/73715071/178518547-7eb67e15-c93c-4006-a2a7-84d224c1c9ad.png)
   Also change the colour slightly to grey. Right now it almost looks like a button that could be pressed instead of being a field that can be written into.

**Comment by HoussemNasri** [comment]
@ThiloteE Thank you for looking into it! I agree with you on most of the points.
> 1. Regression: The Field selection does not allow to write custom fields anymore. In the old version this was possible.

Absolutely, maybe another tab called "Add Field" that adds a field to all selected entries. It's also possible to include this feature in the "Edit field value" tab, but I prefer to make the UI as simple as possible.

> . I am not sure what Clear field is supposed to do.
>
> Example:
>
> @Article{testclearfield,
>   whatever = {a}
>   }
> Press clear field.
> Result: Nothing happens.

This is strange😕. Clearing a field is supposed to set its value to empty. Additionally, the field will be removed from the BibteX file because JabRef doesn't store empty fields. Did you choose "Keep Modifications" when quitting the dialog?

> 4. The tab name two fields is very ambiguous. It could be replaced with Copy, move & swap or Copy, move & swap content

I considered that option but did not select it. The reasoning behind this is that other actions may be added in the future in addition to Copy, Move, and Swap, but there will always be two fields :). I'm not very good at naming things, so I'll have to look up other applications and see what name they used.
