### ISSUE TITLE
Add libraries that were opened with File-Open library (ctrl+o) to "Recent libraries"

### ISSUE THREAD

**Issue by mode-2020** [JabRef/jabref#9042]
**Is your suggestion for improvement related to a problem? Please describe.**
When I want to open a recent .bib file, I usually want to find it in 'File-Recent libraries' at the toolbar. However, this function can only show the recent files opened from the 'File-Open library (ctrl+o)' function. If I open a .bib file directly from the _explorer_ in Windows, this file will not shown in 'Recent libraries'.

**Describe the solution you'd like**
I want recent files opened from the _Windows Explorer_ will be shown in 'Recent libraries'.

**Additional context**

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by ThiloteE** [comment]
Check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is worth having a look at. Feel free to ask if you have any questions here on GitHub or also at JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat.

Try to open a (draft) pull request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.
