### ISSUE TITLE
Add toggle to only show entries that are NOT in this group

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#9073]
- [ ] Fixes #4237 via workaround

   Would be nice:

   - How about making `Toggle intersection` slightly more sophisticated by extending to individual groups? Adding per-group negation (i.e., toggle to 'NOT') would be possible without complicated query logic. Selected groups could default to the current option (AND/OR) and toggle to NOT.

   _Originally posted by @ryan-carpenter in https://github.com/JabRef/jabref/issues/4681#issuecomment-1221145439_

**Comment by ThiloteE** [comment]
In addition to its inherent use, this would be a workaround to add "floating mode" like capabilities. Albeit less smooth looking of a solution, adding a toggle avoids adding various colours to the entry table, which would be necessary to distinguish between entries that have been found using search:
- entries with high score
- entries with low score
- entries that are part of a group
- entries that are not part of this group

Adding many colours comes at the added cost of
- maintaining compatibility with light/dark mode
- can look ugly
- Even though there are different colours, it may not be intuitive to users what all these various colours **mean**

**Comment by ryan-carpenter** [comment]
This issue is also related to #7871. I love regex solutions, but here are some ideas for mouse-driven boolean logic: (sorry, no graphics or videos)

1. Three-way `Toggle intersection` between union (OR), intersection (AND), and 
* exclusion (XOR), or possibly
* inversion (NOR)
… changing only the icon.

2. Difference tool, like Inkscape or illustrator https://inkscape-manuals.readthedocs.io/en/latest/boolean-operations.html, where the laste shape (group) selected is the one subtracted (or optionally, the first shape selected).

Possible JabRef approach:
* Click group A -> Shift+click group D -> entry table shows A–D (current situation)
* With A–D selected, click the difference tool -> entry table shows (A–C NOT D).
* Click the difference tool again-> entry table switches to (D NOT A–C)

3. More about the per-group NOT toggle (this issue, #9073)
The Citavi screenshots in #4237 show the filter menu but not the hidden, unintuitive, cumbersome, yet very useful `invert` arrows. ON-OFF sliders next to each JabRef group would be immensely simpler to use.

![image](https://user-images.githubusercontent.com/23321102/187022778-7dadc801-aff8-4769-a228-b02583e8eb15.png)

**Comment by Rupesh-Lal** [comment]
Hi @ThiloteE , I tried adding a button for negation function. The button is displayed properly and tooltip is also working fine but I am not able to add functionality properly. Can you help me like what files I need to modify to add functionality or what is the flow from where the keyword we give on search bar is doing match with the entries.

**Comment by LoayGhreeb** [comment]
> The floating mode is readded. All entries in a group have a white background, the entries not in a group a darker one.

Even in filtering mode (with search and group filter toggles enabled), the "invert groups" toggle will apply, making entries not matching the selected group appear with a white background.

This toggle also works with multiple group selections, depending on whether the view mode is set to union or intersection:
- Multiple group selection, Union mode (without invert): Shows entries that match ANY of the selected groups $`A \lor B`$.
- Multiple group selection, Intersection mode (without invert): Shows entries that match ALL of the selected groups $`A \land B`$.
- Single group selection with invert: Shows all entries EXCEPT those in the selected group $`\neg A`$.
- Multiple group selection, Union mode (with invert): Shows entries that are not in ANY of the selected groups $`\neg (A \lor B)`$ --> (NOR).
- Multiple group selection, Intersection mode (with invert): Shows entries that are not in ALL of the selected groups $`\neg (A \land B)`$ --> (NAND).
