### ISSUE TITLE
Add default hierachical context in group creation

### ISSUE THREAD

**Issue by t-fourcade-isp** [JabRef/jabref#9141]
Thanks for your hard work developing this very sefull software. 

I like all my groups to be of union type as hierarchical context and It is a bit tedious to have to change this type each time I create a new group. 

Then, in my opinion, it would be nice to be able to change the default hierarchical context for new group in the the parameters once for all.

**Comment by treebog** [comment]
Could I be assigned this issue?

**Comment by ThiloteE** [comment]
Relevant documentation: 
- https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups#hierarchical-context

![grafik](https://user-images.githubusercontent.com/73715071/198572827-2633ef70-bdf1-447d-8505-40baa7dbd80f.png)

**Comment by sayan9112** [comment]
Hey, @HoussemNasri  if this issue is still open I'm interested to contribute.

**Comment by ThiloteE** [comment]
@sayan9112 as you can see at the top right side of GitHub, this issue is already in progress and if you scroll down you can see a pull-request has already been opened by a group of students that will likely fix this. I am pretty sure it would be more efficient and lead to less confusion and organisational strain, if you were to choose another issue.

If you are new to JabRef, please have a look at our projects page with "[good first issues](https://github.com/orgs/JabRef/projects/5)". If you are a student, the "[candidates for university  projects](https://github.com/orgs/JabRef/projects/3)" page offers some issues of varying difficulty and scope and that have been estimated to be compatible with university courses as well and often bring a larger feature to JabRef. Of course, feel free to tackle one of the other "normal" issues around, if you feel you have the knowledge or the willingness to take them on, preferably from the [projects page](https://github.com/JabRef/jabref/projects?type=classic), as those have been already screened and assigned a rough measure of priority. There are many around.

Thank you!
