### ISSUE TITLE
Switch to Java 19

### ISSUE THREAD

**Issue by wamserma** [JabRef/jabref#9417]
**Is your suggestion for improvement related to a problem? Please describe.**
OpenJDK 18 is EOL and some Linux distributions have already dropped it.

**Describe the solution you'd like**
JabRef should switch to OpenJDK 19 and publish a new release, so downstream distros can pick the update.
A possible alternative would be to restore source compatibility with Java 17 LTS.

**Additional context**
Gradle has already been updated to a version supporting Java 19, so the switch should be a low effort task.

**Comment by Siedlerchr** [comment]
Thanks for the issue, we already thought about this as well. Normally JabRef ships it's own custom version of the jdk using jpackage, so it should not depend on the java version on the OS. However, we probably only would need to adjust the build pipeline.

Unfortunately our linux rpm builds are broken  since a few days due to #9419

**Comment by Siedlerchr** [comment]
As JDK19 does not yet work for generating installer packages we decided to downgrade to jdk17

**Comment by Siedlerchr** [comment]
The development version will no require jdk19
