### ISSUE TITLE
Refine right click menu

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9432]
Follow-up to https://github.com/JabRef/jabref/issues/6601

We take Windows Explorer as reference (see https://github.com/JabRef/jabref/issues/6601#issuecomment-724932377)

Current appearance:

![grafik](https://user-images.githubusercontent.com/1366654/205727896-88767045-6195-468f-982f-e27a66855279.png)

Only columns enabled in the preferences are shown:

![grafik](https://user-images.githubusercontent.com/1366654/205727817-dfbf8bf8-360f-4bc3-893b-b926e500f9ef.png)

How to enable addition of new columns (as shown at the screenshot at https://github.com/JabRef/jabref/issues/6601#issuecomment-724932377)?

We think "More..." ("Mehr..." in German) is missing:

![grafik](https://user-images.githubusercontent.com/1366654/205728242-f6758768-caee-45b8-bd99-a94041c006e2.png)

After a click, a new popup opens 

![grafik](https://user-images.githubusercontent.com/1366654/205728433-9667c683-acef-4cc2-99d3-c3353616a2de.png)

Would be nice if that was added here, too. Would that be possible?

This list should be filled with all fields known to JabRef. In case a user wants to add more fields, they must go to the preferences and add the custom field there.

**Comment by ilippert** [comment]
I like to highlight that I think it is of key importance that indeed the user interacts with an overview of the other fields already available, before/when they want to add another field.

**Comment by ThiloteE** [comment]
@dragos222 i will assign you to it, but I assume you are very new to coding, as there is very low amounts of activity in your github account. While I am happy you chose this issue, if you ever feel it is too hard for you, there is the possibility to choose another one from [good first issues](https://github.com/orgs/JabRef/projects/5). Those are usually a little easier. If it were to turn out that way, just leave a short comment here and/or unassign yourself. Otherwise, gl & hf :-)

**Comment by nikolaynikolaevn** [comment]
Hi! I am currently trying to complete this issue for a university project but I haven't asked to get assigned to it yet as I was not sure whether I could complete it soon. At this point, I think I think I am able to add a new right-click context menu item with custom logic (doing something else than enabling/disabling a table column).

My idea for the solution is to show a "More" option at the end of the current context menu that appears when right-clicking on a table column, and when the "More" option is selected, open the Preferences window at the "Entry table" tab, so that the existing functionality for managing the table columns shown can be reused. Is this solution proposal fine with you? If yes, is there some way to open the Preferences window at the "Entry table" tab from the code?

**Comment by ThiloteE** [comment]
@calixtus tagging you, because preferences related. Good idea or not?

**Comment by calixtus** [comment]
Sounds like a very good solution.
There is not yet any functionality implemented, that would need to happen in some generic way...
This would probably be the greater part: to think of some nice solution for this. Maybe we can discuss this further, how to do that?

**Comment by calixtus** [comment]
Yes, why not. A little bit guidance:
Please avoid creating cross dependencies between classes. My idea (i just had not time to implement it) would be to tell the prefs dialog constructor to show a tab of a certain `Class<?> class` (in this case something like ShowPreferencesAction(jabRefFrame, taskExecutor, TableTab.class), let the Dialog look for the right one and show/focus it.
