### ISSUE TITLE
Support OAI harvesting for Citeseer

### ISSUE THREAD

**Issue by calixtus** [JabRef/jabref#9467]
The current implementation of the Citeseerfetcher had to be deactivated, since the api for search requests seems to have changed.

`org.jabref.logic.importer.FetcherException: A network error occurred while fetching from https://citeseer.ist.psu.edu/search?sort=rlv&q=doi%3A10.1.1.115.9665&t=doc`

Issue would be to rework the current citeseer fetcher to implement the opi harvester (see https://csxstatic.ist.psu.edu/downloads/data ).

**Comment by Ravitwr** [comment]
The links mentioned on their website doesn't seem to work. Not sure if there is newer Api available.

**Comment by DanielS01ss** [comment]
Hi!
I would love to work on this task!

**Comment by premparmar11** [comment]
Do we need to change URL in CiteSeer.java File's method getURLForQuery().

From URL : "https://citeseer.ist.psu.edu/search"
To URL : ""https://citeseer.ist.psu.edu/oai2/search""

**Comment by Siedlerchr** [comment]
That's only the first step. Then you have to rework the fetcher to parse the information. If I remember correctly there is already another fetcher (Open books or similar) that also implements this

**Comment by ACeldo1** [comment]
Hi, I would like to contribute to this issue if possible. 
And if possible, would it be more appropriate to ask questions here or open a draft PR and discuss there?

**Comment by koppor** [comment]
Organization: 

- We did not hear back from @DanielS01ss since three months, so I unassign him
- @premparmar11 Did not come up with a PR since one month, so I think, he continued at another task
- I assign @ACeldo1 to this task

@ACeldo1 A draft PR is the way to move forward. Reason: When discussing code snippets here, one does not know the context and has to put the code snippets in the IDE by one self. Costs much time. A draft PR can be checked out and worked on.
