### ISSUE TITLE
External Changes resolver should show the bib entry source next to the preview

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9509]
**Is your suggestion for improvement related to a problem? Please describe.**
I am frustrated because I cannot see the  BibTeX source for the changes

**Describe the solution you'd like**
Put the Preview and the bibtex source field display (read only) in a tab so I can toggle between it

**Additional context**
See screenshpt

![grafik](https://user-images.githubusercontent.com/1366654/210183494-334e1560-9528-4382-80ed-6cd866563670.png)

**Comment by HoussemNasri** [comment]
**Some context**

The external changes resolver dialog is used to display the differences between the external version of your library *(.e.g. the version stored on the filesystem)* and the version loaded in JabRef. The differences *(or changes as referred to in the code)* can be read as the transformation done by an external program to our library. For instance, Added entry 'Dag2' implies that an external program added a new entry with a citation key 'Dag2'. In addition to displaying changes, the dialog allows you to review them by providing the option to accept or deny each change in your library.

In the code, changes are modeled in two classes, `DatabaseChange` and `DatabaseChangeDetailsView`:
- *DatabaseChange*: This class provides the code that modifies the database when the user accepts a change. Not that this is an abstract class and should have a different implementation for each type of change.
- *DatabaseChangeDetailsView*: This class creates the UI to show more information about the change. For example, when an EntryAdd change is selected, the details UI is a preview of the added entry with its title, authors, journal, etc. Note that this is an abstract class too.

The problem at hand originates from the way `EntryAdd`, `EntryDelete`, and `EntryChange` details UI is constructed. Currently, the details UI for the mentioned change types shows only a preview panel of the added/deleted or changed entry. The preview shows only a subset of the fields that the entry contains. For example, if an external program added a new entry that has a custom field I wouldn't be able to see the value of the field in the preview.

Since we can't show all fields of an entry in the preview panel without messing up the UI, the best solution here is to show the BibTeX source of the entry. 

**Code Hints**

https://github.com/JabRef/jabref/blob/e86839a85fb939920e3a3d0214aeda9a0b47ae44/src/main/java/org/jabref/gui/collab/entryadd/EntryAdd.java#L11

https://github.com/JabRef/jabref/blob/e86839a85fb939920e3a3d0214aeda9a0b47ae44/src/main/java/org/jabref/gui/collab/entryadd/EntryAddDetailsView.java#L14-L16

https://github.com/JabRef/jabref/blob/8bd1845a7a2c31ff0444e3485f716e19c28cbb7e/src/main/java/org/jabref/gui/entryeditor/SourceTab.java#L63

**Requirements**

- [ ] Show the BibTeX source along the preview panel in the details UI of the deleted/added entry for `EntryAdd` and `EntryDelete` changes.
- [ ] Show the BibTeX source of the on Disk/on JabRef versions of an entry in the details UI for `EntryAdd` changes as described in [this comment](https://github.com/JabRef/jabref/pull/9021#issuecomment-1221380451)
- [ ] The preview panel and BibTeX source UI should be in separate tabs
- [ ] The BibTeX source UI should be read-only.
- [ ] (OPTIONAL) Show a label to indicate when the BibTeX source is read-only.

**Useful Links**
- [Improve the external changes resolver dialog #9021](https://github.com/JabRef/jabref/pull/9021) — The PR where this issue was first discussed
- [Sealed Classes and Interfaces in Java](https://www.baeldung.com/java-sealed-classes-interfaces) — It is worth knowing about sealed classes since *DatabaseChange* and *DatabaseChangeDetailsView* – one of the most important classes in this issue – are sealed
