### ISSUE TITLE
Very large Bibtex-Databases: Why is Jabref 5.9 so slow and Jabref 3.8.2 so fast?

### ISSUE THREAD

**Issue by hasehas16** [JabRef/jabref#9822]
Hi, I am working with a quite large Bibtex database with about 50000 entries. I am still using Jabref 3.8.2 which works quite well, because all newer versions of Jabref 4.x and Jabref 5.x are much [!!] slower and are freezing from time to time. I would like to propose to make Jabref 5.x (x = 10) as fast as Jabref 3.8.2!

**Comment by koppor** [comment]
Spontaneously:

- Nicer UI, not looking dated (JabRef 3.8.2 was heavily critized for that)
- Using JavaFX

Switching technologies sometimes has drawbacks. If you have time, you can investigate. Dive into Java, dive into application debug. Please support us.

Since there are multiple existing issues on that, we close this one. This one is too vague for us to directly work on it. I would assume, the library has > 10.000 entries, the OS is Windows, you have linked PDFs, you have German text in it (with umlauts). You are very welcome to provide more details!

**Comment by calixtus** [comment]
Thanks for your interest in JabRef and your proposal. JabRef is a project maintained in the free time of a few java and latex enthusiasts. The project is targeted in providing a modern bibtex application and in teaching students in software engineering. We are always happy about support, technical as well as financial, so we can support more interns working and learning with jabref.

**Comment by ThiloteE** [comment]
@hasehas16, if you want to dive deeper into the topic and if you have knowledge about debugging or coding (or know somebody who could help with that), I would suggest to check and try to solve the various other open bugs with the label https://github.com/JabRef/jabref/labels/type%3A%20performance.

From past user feedback we know that some preferences have a high impact on performance.  Please have a look at https://docs.jabref.org/faq#q-i-have-a-huge-library.-what-can-i-do-to-mitigate-performance-issues and try disabling those from the list. Also, disabling full-text search should be good for performance.

I would be happy to hear, if the list was of any help to you.
