### ISSUE TITLE
Container for group item count still visible if display count is off

### ISSUE THREAD

**Issue by mschroen** [JabRef/jabref#9972]
**Cosmetic bug:**
When the display of group item counts is deactivated in the settings, the enclosing darkgrey rectangles are still visible in the group panel.

![grafik](https://github.com/JabRef/jabref/assets/7942719/8358d251-5766-4b6d-a687-b0e9cee33e12)

**Comment by BeeJay28** [comment]
Hello, can I work on this issue?

**Comment by AEgit** [comment]
@Siedlerchr See https://github.com/JabRef/jabref/pull/9980#issuecomment-1766895702 - I think the respective changes need to be reverted. Fixing this cosmetic bug actual has removed some functionality from JabRef.

**Comment by ThiloteE** [comment]
Have you tried turning "display count of groups" on with never versions of JabRef? Does it still have a large impact on performance?

**Comment by AEgit** [comment]
JabRef 5.11--2023-10-17--8ede31a
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20.0.2+3

Just tried it again. The "Display count of items in groups" performance issue is improved I think (at least from what I recall - I had disabled it for ages, since originally the performance problems it caused were atrocious), but is still clearly noticeable. When I load my database with >24k entries with the count turned off, the CPU load drops after a few sec to 0-5%. With the count of items turned on it stays on 70% for at least a minute and shoots up every time I assign an item to a new group.

**Comment by ThiloteE** [comment]
Could you create a separate issue for the performance problems with count of groups? Just so that we can track it more easily. Also, i think removing the container for group items is legit.

Maybe it is possible to have another new more beautiful way that would show that an entry is within a group, when the item count is disabled. I would create a new issue for that.

**Comment by AEgit** [comment]
The performance issue with the counts of groups is know - I created an issue 3 years ago and the workaround was, indeed, to turn of the count of items in groups:
https://github.com/JabRef/jabref/issues/6042

Funnily enough I already mentioned there, that the background box should not be removed, exactly because of the problem that we encounter now ^^:

> However, you shouldn't get rid of the background box surrounding the group item account. This box changes colour according to whether an item selected in the main table is part of a group or not, so this information should be available. In the old JabRef version this was achieved by having the name of a group underlined, which contained a selected item.

As for your suggestion - I would say yes and no. Yes, in the sense that there could be better ways to display group membership (e.g. by underlining the group like in JabRef 3.8.2 or - if you want it to be more fancy - by creating a background box for each group and colouring that according to group membership). This way also the counting of groups items would not be associated with displaying group membership - two distinct features.
No, however, as long as this alternative solution is not implemented. Currently with this implementation it is simply not possible any more to get a visual cue immediately whether an item belongs to a group or not if the item count is turned off. This is clearly a loss of functionality, and, if I say so, a rather big one for me. On the other hand, displaying the grey rectangle, is - as mentioned originally by the thread starter just a "cosmetic bug" at best. It is not even an inconvenience, it just does not look that great (to be honest, I was never really bothered). So as long, as an alternative solution is not implemented, I would heavily suggest to revert the change that was made. I don't think it is worthwhile giving up a major functionality just for beauty's sake ^^

**Comment by AEgit** [comment]
@koppor @Siedlerchr Can this change simply be reverted or should I open a new issue (see https://github.com/JabRef/jabref/issues/9972#issuecomment-1766896789; https://github.com/JabRef/jabref/pull/9980#issuecomment-1766895702)?

**Comment by Siedlerchr** [comment]
Following @AEgit  proposal we should just keep the indicator as a visual indicator

**Comment by AEgit** [comment]
Cheers!

**Comment by koppor** [comment]
Screenshot of marked containment:

![image](https://github.com/JabRef/jabref/assets/1366654/452e5e36-e920-429e-85eb-66f2013d682b)

**Comment by koppor** [comment]
We currently need this indicators. Thus, the solution is NOT to just remove them. There needs to be another solution to highlight containment. Maybe a colored background of all groups the entry is belonging to?

**Comment by AEgit** [comment]
JabRef 5.12--2023-10-22--b1abe02
Windows 10 10.0 amd64 
Java 21.0.1 
JavaFX 20.0.2+3

I can confirm that by reverting the original change the "coloured group indication" feature, which was lost with the originally implemented change (see https://github.com/JabRef/jabref/issues/9972#issuecomment-1766896789; https://github.com/JabRef/jabref/issues/9972#issuecomment-1767070516), has returned. Well done!

I notice, that for the group "All entries" the rectangle is not coloured no matter which item/article you select - I think this behaviour was different in previous development versions (and the new behaviour may be unexpected given that all items should be part of this group?), but it is not a real problem, since all items should be part of the "All entries" group anyway. So whether that is indicated by colour or not, should make no difference to the user.
